### ISSUE TITLE
Error SQLSERVER MAMP install drivers

### ISSUE THREAD

**Issue by DaniJmurcia** [microsoft/msphpsql#1007]
I have problems when installing the SQLSERVER drivers on mac

The first problem is that to install it I put: sudo pecl install sqlsrv and it appears:

MacBook-Pro-de-Dani: bin danimurcia $ sudo pecl install sqlsrv
pecl / sqlsrv requires PHP (version> = 7.1.0), installed version is 5.6.40
No valid packages found
install failed

Well, I look for other versions and he says:

MacBook-Pro-of-Dani: bin danimurcia $ pecl install sqlsrv-5.6.1preview
Failed to download pecl / sqlsrv, version "5.6.1preview", latest release is version 5.6.1, stability "stable", use "channel: //pecl.php.net/sqlsrv-5.6.1" to install
install failed

Does anyone know the version of the drivers for php 5.6.40?

Thank you

**Comment by david-puglielli** [comment]
@DaniJmurcia Unfortunately we do not support php 5.6 for macOS, only Windows. We do support PHP 7 on macOS, however. If you would prefer to install the drivers for PHP 7, you can find instructions [here](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-macos-sierra-high-sierra-and-mojave).

**Comment by david-puglielli** [comment]
@DaniJmurcia Do you have any updates or further questions for us? If not, we will close this issue in a few days.

**Comment by david-puglielli** [comment]
Closing issue. Please reopen if necessary.
