### ISSUE TITLE
Instructions missing for installing ODBC Driver 17 on Debian Buster

### ISSUE THREAD

**Issue by arunchandarQA** [microsoft/msphpsql#1009]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## Microsoft ODBC Driver version
 + msodbcsql17

 +## Problem description
 + msodbcsql17 gives file not found error with debian buster. I could not find installation instructions in the below page:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017

 +## Expected behavior and actual behavior
 + Page updated with installation instructions

**Comment by przemo-hemmersbach** [comment]
Was this issue resolved? Any workarounds?

**Comment by yitam** [comment]
@przemo-hemmersbach the upcoming release of ODBC driver will support Buster, and our documentation is being updated.

**Comment by yitam** [comment]
FYI, ODBC driver 17.4 is released with [instructions](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017) updated
