### ISSUE TITLE
unnamed field fetch_object error

### ISSUE THREAD

**Issue by szollosi** [microsoft/msphpsql#1010]
Dear Developers,

## PHP Driver version or file name
sqlsrv  5.3.0   stable
## SQL Server version
Microsoft SQL Server 2017 (RTM-CU15-GDR) (KB4505225) - 14.0.3192.2 (X64) 
## Client operating system
debian 9.9 stretch
## PHP version
7.0.33-0+deb9u3
## Microsoft ODBC Driver version
msodbcsql17 17.3.1.1-1
## Table schema
field1 int (not relevant)
## Problem description
fields without name or alias doesn's fetch object
## Expected behavior and actual behavior
actually when i fetch "select field1, count(1) from tbl group by field1" fetch_object doesn't fetch object, i think it would be better to fetch the object with "field1" property, and if possible "Expr1" property to the "count(1)" column like SSMS does or "_ColN" property to the Nth column
## Repro code or steps to reproduce
$link = sqlsrv_connect(...);
$result = sqlsrv_query($link, "select field1, count(1) from tbl group by field1");
$object = sqlsrv_fetch_object($result);
print_r($object, true);
## Why i ask this
1. i don't know the result is really empty or just fetch_object doesn't fetch object.
2. i use Stored Procedures (SP-s), what wasn't i wrote, the SP-s sometimes updating, and sometimes happening the new SP result fields unnamed. in php when i see the property is missing, i can fix my php code in a few minutes, ie. i change "count" property to "_Col2", or i can start searching for the bug in the SP.

Thanks!

Sorry for my bad english!

**Comment by yitam** [comment]
hi @szollosi, [sqlsrv_fetch_object](https://docs.microsoft.com/sql/connect/php/sqlsrv-fetch-object?view=sql-server-2017) returns *false* if something goes wrong. If there is no data you should get *null* instead. 

For example, your script can be modified as follows:

```
$link = sqlsrv_connect(...);
$result = sqlsrv_query($link, "select field1, count(1) from tbl group by field1");
$object = sqlsrv_fetch_object($result);
if (is_null($object)) {
    echo "OBJECT is NULL" . PHP_EOL;
} elseif ($object === false) {
    echo "sqlsrv_fetch_object FAILED" . PHP_EOL;
} else {
    print_r($object, true);
}
```

The documentation clearly says that `If a field with no name is returned, sqlsrv_fetch_object will discard the field value and issue a warning.` To check the error message(s), you can do the following:

```
$errors = sqlsrv_errors(SQLSRV_ERR_ALL);
var_dump($errors);
```

In your case, the warning is `An empty field name was skipped by sqlsrv_fetch_object.`

By default, [warnings are returned as errors](https://docs.microsoft.com/sql/connect/php/sqlsrv-configure?view=sql-server-2017) unless you have set `sqlsrv_configure('WarningsReturnAsErrors', 0);`

Hope this helps.

**Comment by szollosi** [comment]
hi,

this helps, i can do a workaround now :)

Thanks!
