### ISSUE TITLE
Always Encrypted Support

### ISSUE THREAD

**Issue by maddhatter** [Microsoft/msphpsql#102]
Are there plans to add support for querying Always Encrypted columns? At least using the local certificate store on Windows?

**Comment by meet-bhagdev** [comment]
@maddhatter Absolutely! It is in our future plans: https://github.com/Azure/msphpsql/tree/PHP-7.0#future-plans
Could you share some details around the specifics? Are you looking to use Always Encrypted with our PHP 7 driver? Are you using sqlsrv or pdo_sqlsrv?

**Comment by maddhatter** [comment]
Sorry, I should have checked there first (I thought I had to be honest).

I'm looking to use PHP 7 pdo_sqlsrv on IIS. My application pool is running as a domain user, and the certificate I want to use for Always Encrypted in stored in that user's certificate store.

**Comment by someone9388** [comment]
When will you support for querying  Always Encrypted columns?

**Comment by meet-bhagdev** [comment]
@maddhatter @someone9388 This is still in our plans. We plan to get to this in the coming months.

**Comment by someone9388** [comment]
@meet-bhagdev Thanks for your reply. I'm using PHP7 pdo_sqlsrv. Waiting for your new release! Thanks!

**Comment by meet-bhagdev** [comment]
@all we are running into some issues with AE. We have retrieval working. But there are some failing test cases with data types such as varchar max. The failures can result in unrecoverable crashes. We are working aggressively on tracking them down and fixing it. I will keep you guys posted.

**Comment by Hadis-Fard** [comment]
Exciting news @ ALL, we have released [5.1.0 preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.1.0-preview) drivers supporting [Always Encrypted](https://github.com/Microsoft/msphpsql/wiki/Features#using-always-encrypted-with-the-php-driver-510-preview-for-sql-server)! To use Always Encrypted you should install [MS ODBC 17 preview ](https://github.com/Microsoft/msphpsql/wiki/Install-and-configuration#odbc-17-linux-installation). You can ODBC 17 binaries from [here ](https://github.com/Microsoft/msphpsql/tree/dev/ODBC%2017%20binaries%20preview).

**Comment by Hadis-Fard** [comment]
@ALL we just released another [preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.1.1-preview) supporting Always Encrypted, would love to hear your feedback :blush:

**Comment by yitam** [comment]
Please check the latest [v5.3.0 release](https://github.com/Microsoft/msphpsql/releases/tag/v5.3.0). 

Should you have any other problem or issue with Always Encrypted, please create a new issue.
