### ISSUE TITLE
Chinese characters not being stored correctly

### ISSUE THREAD

**Issue by TonyMarston** [microsoft/msphpsql#1033]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 +5.6.1
 +## SQL Server version
 +2014 and 2017
 +## Client operating system
 +Windows 10
 +## PHP version
 +7.3.9
 +## Microsoft ODBC Driver version
 +17
 +## Table schema
 +CREATE TABLE mnu_user_alt (
  user_id nvarchar(16) NOT NULL, 
  language_id nvarchar(5) NOT NULL,
  user_name nvarchar(40) NOT NULL,  
  PRIMARY KEY (user_id, language_id)
);
 +## Problem description
 +If I enter Chinese characters such as 苏州工业园区 into a field on a web page and store it, it gets displayed as ??????.  If I look at the data in Management Studio I see ???????. However, if I run the query within Management Studio and then display it, it shows as 苏州工业园区 even in my PHP application.
 +## Expected behavior and actual behavior
 +I am using "characterSet" => "UTF-8" in my connection string, so I expect multi-byte characters to be stored correctly but this is not happening.
 +## Repro code or steps to reproduce
 Run the query through a PHP app and it stores the data incorrectly. Run the query through Management Studio and it stores the data properly.

**Comment by yitam** [comment]
hi @TonyMarston 

You didn't specify which driver, but I assume you used the sqlsrv driver.
Please use the `N` prefix, as explained in our documentation about [INSERT statements](https://docs.microsoft.com/sql/t-sql/statements/insert-transact-sql?view=sql-server-2017)

Here is the extract:

> When referencing the Unicode character data types nchar, nvarchar, and ntext, 'expression' should be prefixed with the capital letter 'N'. If 'N' is not specified, SQL Server converts the string to the code page that corresponds to the default collation of the database or column. Any characters not found in this code page are lost.

For example, your insert statement should be similar to this:

`INSERT INTO mnu_user_alt (user_name) VALUES (N'苏州工业园区');`

Alternatively, you can use input parameters, like this:

```
$params = array('苏州工业园区');
$tsql = "INSERT INTO mnu_user_alt (user_name) VALUES(?);";
$stmt = sqlsrv_query($conn, $tsql, $params);
if ($stmt === false) {
    var_dump(sqlsrv_errors());
}
```

**Comment by TonyMarston** [comment]
How can I set the default collation of the database or column to UTF-8?

**Comment by yitam** [comment]
hi @TonyMarston , please check the online documentation, beginning with [database collation](https://docs.microsoft.com/sql/relational-databases/collations/set-or-change-the-database-collation?view=sql-server-2017) and [column collation](https://docs.microsoft.com/sql/relational-databases/collations/set-or-change-the-column-collation?view=sql-server-2017).

If you need help with database design please ask in the [SQL Server forums](https://feedback.azure.com/forums/908035-sql-server). I'm going to close this issue because this is not a driver issue.

**Comment by TonyMarston** [comment]
I don't need help with database design, I just need proper instructions on how to read and write UTF-8 characters in my database. The page at https://docs.microsoft.com/en-us/sql/connect/php/how-to-send-and-retrieve-utf-8-data-using-built-in-utf-8-support?view=sql-server-2017 simply says that to send and retrieve UTF-8 data all I need do is specify "CharacterSet" => "UTF-8" in the connection data. You are now telling me that this data is incomplete. What a farce!

**Comment by yitam** [comment]
Please do note that the examples in the aforementioned page concerning how to send or retrieve UTF-8 data using sqlsrv have used parameters, as in my first reply to you. In such case, specifying `"CharacterSet" => "UTF-8"` in the connection string suffices.

It's with T-SQL insert statements that you have to do something extra. Anyway, have a good day.
