### ISSUE TITLE
Can't load the MS SQL Driver for PHP 7.3 on Debian 10

### ISSUE THREAD

**Issue by ToubieObie** [microsoft/msphpsql#1034]
+## PHP Driver version or file name
5.6 for PHP Version 7.3
 
+## SQL Server version
Not relevant
 
+## Client operating system
Debian 10
 
+## PHP version
 PHP 7.3.9-1+0 20190902.44+debian10~1.gbpf8534c
 
 +## Problem description
 PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20180731/sqlsrv.so (/usr/lib/php/20180731/sqlsrv.so: undefined symbol: tsrm_get_ls_cache), /usr/lib/php/20180731/sqlsrv.so.so (/usr/lib/php/20180731/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

 +## Expected behavior and actual behavior
 Load Driver for PHP 7.3

 +## Repro code or steps to reproduce
First I just download the .so file from Microsoft. (https://github.com/Microsoft/msphpsql/releases/tag/v5.6.0)
Placed the file "php_sqlsrv_73_ts.so" in the folder "/usr/lib/php/20180731" (extension dir) and added the line "extension=php_sqlsrv_73_ts.so" to "/etc/php/7.3/apache2/php.ini" and "/etc/php/7.3/cli/php.ini"

And now when i try to verify the module with "php -i" i get these error:
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_sqlsrv_73_ts.so' (tried: /usr/lib/php/20180731/php_sqlsrv_73_ts.so (/usr/lib/php/20180731/php_sqlsrv_73_ts.so: undefined symbol: tsrm_get_ls_cache), /usr/lib/php/20180731/php_sqlsrv_73_ts.so.so (/usr/lib/php/20180731/php_sqlsrv_73_ts.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

i removed the line in the php.ini files, deleted the .so file and tried these guide:
https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-debian-8-and-9
But this guide is for Debian 9 and I have Debian 10.

Bute the result was the same:
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20180731/sqlsrv.so (/usr/lib/php/20180731/sqlsrv.so: undefined symbol: tsrm_get_ls_cache), /usr/lib/php/20180731/sqlsrv.so.so (/usr/lib/php/20180731/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Thank you!
Best regards 
Tobias

**Comment by yitam** [comment]
Hi @ToubieObie we officially support Debian 10 starting with our [preview release v5.7.0](https://github.com/microsoft/msphpsql/releases/tag/v5.7.0-preview), and please follow the [instructions here](https://github.com/microsoft/msphpsql/blob/master/Linux-mac-install.md#installing-the-drivers-on-debian-8-9-and-10). 

You also require [ODBC Driver 17.4](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017) and above.

**Comment by yitam** [comment]
Due to inactivity, we will be closing this issue shortly, unless you have any other question for us, @ToubieObie ?

**Comment by yitam** [comment]
Please feel free to reopen this if necessary.

**Comment by jlcalderon** [comment]
Hey @yitam !

This is a new issue to me. I had the driver **php_sqlsrv_73_ts.so** working fine before. But now I am getting something like this when I run **php -m** in my linux shell 

`PHP Warning:  PHP Startup: Unable to load dynamic library 'php_sqlsrv_73_ts.so' (tried: /usr/lib/php/20180731/php_sqlsrv_73_ts.so (/usr/lib/php/20180731/php_sqlsrv_73_ts.
so: undefined symbol: tsrm_get_ls_cache), /usr/lib/php/20180731/php_sqlsrv_73_ts.so.so (/usr/lib/php/20180731/php_sqlsrv_73_ts.so.so: cannot open shared object file: No s
uch file or directory)) in Unknown on line 0`

**Comment by jlcalderon** [comment]
In the web app this the error seen when the application try to connect to the **SQL Server** and make a **SELECT query**:

`Array ( [0] => Array ( [0] => HYT00 [SQLSTATE] => HYT00 [1] => 0 [code] => 0 [2] => [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired [message] => [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired ) [1] => Array ( [0] => 08001 [SQLSTATE] => 08001 [1] => 10057 [code] => 10057 [2] => [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2749 [message] => [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2749 ) [2] => Array ( [0] => 08001 [SQLSTATE] => 08001 [1] => 10057 [code] => 10057 [2] => [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. [message] => [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. ) )`

**Comment by jlcalderon** [comment]
Is in my understanding that the DBA has the application IP address whitelisted and that the server is up and running since I can make connections thru other means. So I am narrowing posibilities here to the driver issue.

**Comment by yitam** [comment]
@jlcalderon is it Debian 10 you're running? What is the version of SQL Server? Please create a new issue and fill in the questions.
