### ISSUE TITLE
Feature request: support for ClientConnectionId / ActivityID

### ISSUE THREAD

**Issue by mathieuk** [microsoft/msphpsql#1035]
I've been looking into ways to improve our logging. I'd like to be able to link requests to, for instance, events reported by the Extended Events functionality in SQL Server. Some of this functionality is described here: https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/accessing-diagnostic-information-in-the-extended-events-log?view=sql-server-2017

From the logging I've done on the SQL Server side it seems that the PHP driver doesn't create and/or send a ClientConnectionId to the SQL Server (the extended event field `client_connection_id` remains `00000000-0000-0000-0000-000000000000` for requests done by PHP).

It would be nice to be able to either set on or retrieve the connection ID from the driver.

**Comment by yitam** [comment]
hi @mathieuk please specify which php driver (sqlsrv or pdo_sqlsrv) and elaborate some more whether you would like a new attribute or a new function, etc.

**Comment by mathieuk** [comment]
I'm targeting PDO_SQLSRV (but ideally both, I'd assume?).

For us, the ideal solution would be able to _provide_ the client connection id to the driver as this would let me (re)use a request ID generated earlier. This would have benefits about having a generated value as I would have to provide both to our logging. 

This would have to be available before connection so it would need to be an option to the PDO constructor.

`php
$requestId = generateNewUUID();

$connection = new PDO(
	'sqlsrv:Server=;Database=',
	 'username', 
	'password', 
	[
		constant('PDO::SQLSRV_ATTR_CONNECTION_ID') => $requestId
	]
);
`

If that's not possible, it would have to generated by the driver and fetchable through PDO::getAttribute() somehow.

**Comment by yitam** [comment]
@mathieuk you might have noticed that `SQL_COPT_SS_CLIENT_CONNECTION_ID` is a read only attribute, and we figure it is likely more useful for other users for general logging purposes.

**Comment by mathieuk** [comment]
I did not, but just being able to fetch it would be just fine.

**Comment by yitam** [comment]
hi @mathieuk 

>From the logging I've done on the SQL Server side it seems that the PHP driver doesn't create and/or send a ClientConnectionId to the SQL Server (the extended event field client_connection_id remains 00000000-0000-0000-0000-000000000000 for requests done by PHP).

Please shed some lights on what steps that you have followed and/or where you found the event field 00000000-0000-0000-0000-000000000000 for requests done by PHP. This helps us decide when or whether to support this feature request in the driver(s).

**Comment by mathieuk** [comment]
hi @yitam 
The 00000000-0000-0000-0000-000000000000 value for client_connection_id was found in the extended events reporting available in SQL Server.

**Comment by yitam** [comment]
Thanks @mathieuk but you have already mentioned that before. It would help us decide if you can provide the scripts and/or steps that you are using to find this client connection id in the log(s). ODBC driver did provide some identifiers to the server but the drivers did not do the logging in SQL Servers directly

**Comment by mathieuk** [comment]
@yitam seems like I jumped to conclusions regarding the zero-filled UUID. Turns out that this happens when the Extended Event `blocked_process_report` is recorded. Other events like `sp_statement_completed` do have a client connection ID.  

So, that seems to be a SQL _server/extended events_ thing and perhaps shouldn't be considered.

**Comment by yitam** [comment]
Thanks @mathieuk for the update. In this case we might leave this request in our backlog for now.

**Comment by yitam** [comment]
Closing this issue as this is not a request anymore
