### ISSUE TITLE
Extension will not load with PHP 7.4RC1 on IIS/Win2016

### ISSUE THREAD

**Issue by GenesisCraig** [microsoft/msphpsql#1036]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 + ## PHP Driver version or file name
 + php_sqlsrv-5.7.0preview-7.3-nts-vc15-x64
 + ## SQL Server version
 + 2014
 + ## Client operating system
 + Windows Server 2016
 + ## PHP version
 +  php-7.4-nts-windows-vc15-x64
 + ## Microsoft ODBC Driver version
 + 17.4.1.1
 + ## Table schema
 + N/A
 + ## Problem description
 + SQL driver extension will not load.
 + ## Expected behavior and actual behavior
 + Expected - > load the extension / no error message in log.
 + Actual: `[11-Sep-2019 17:18:46 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv' (tried: C:\Program Files\PHP\v7.4.0RC1\ext\sqlsrv (The specified module could not be found.), C:\Program Files\PHP\v7.4.0RC1\ext\php_sqlsrv.dll (The specified procedure could not be found.)) in Unknown on line 0`
 + ## Repro code or steps to reproduce
The php.ini file hasthe following lines in it pertaining to the loading #of this extension:

`extension_dir="C:\Program Files\PHP\v7.4.0RC1\ext\"`
` extension=sqlsrv`

I have also tried:

`extension=php_sqlsrv.dll`

Output of DIR command showing location of the DLL:

    PS C:\Program Files\PHP\v7.4.0RC1> dir "C:\Program Files\PHP\v7.4.0RC1\ext\php_sqlsrv.dll"
    Directory: C:\Program Files\PHP\v7.4.0RC1\ext
    
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    -a----        9/11/2019   9:46 AM         253440 php_sqlsrv.dll`

**Comment by yitam** [comment]
Hi @GenesisCraig please [download the 7.4 binaries](https://github.com/microsoft/msphpsql/releases/tag/v5.7.0-preview) instead

**Comment by yitam** [comment]
Any update, @GenesisCraig ? We will be closing this issue shortly due to inactivity.

**Comment by yitam** [comment]
Please feel free to reopen this if necessary.
