### ISSUE TITLE
Error to Install sqlsrv with pecl on MacOS

### ISSUE THREAD

**Issue by rmartin93** [microsoft/msphpsql#1040]
<p>Any help would be greatly appreciated. Sorry if I use the Markdown incorrectly. </p>

<code>sudo pecl install sqlsrv</code>
<code>
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading sqlsrv-5.6.1.tgz ...
Starting to download sqlsrv-5.6.1.tgz (183,396 bytes)
.......................................done: 183,396 bytes
34 source files, building
running: phpize
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:
building in /private/tmp/pear/install/pear-build-rootQ8Q9xG/sqlsrv-5.6.1
running: /private/tmp/pear/install/sqlsrv/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking target system type... x86_64-apple-darwin18.7.0
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable sqlsrv functions... yes, shared
checking for SQLSRV headers... /private/tmp/pear/install/sqlsrv/shared/
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by cc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking how to run the C++ preprocessor... g++ -E
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common
checking if g++ PIC flag -fno-common works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /private/tmp/pear/install/pear-build-rootQ8Q9xG/sqlsrv-5.6.1/libtool --mode=compile g++ -std=c++11 -I. -I/private/tmp/pear/install/sqlsrv -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-rootQ8Q9xG/sqlsrv-5.6.1/include -I/private/tmp/pear/install/pear-build-rootQ8Q9xG/sqlsrv-5.6.1/main -I/private/tmp/pear/install/sqlsrv -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/private/tmp/pear/install/sqlsrv/shared/  -DHAVE_CONFIG_H  -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -fstack-protector   -c /private/tmp/pear/install/sqlsrv/conn.cpp -o conn.lo
mkdir .libs
 g++ -std=c++11 -I. -I/private/tmp/pear/install/sqlsrv -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-rootQ8Q9xG/sqlsrv-5.6.1/include -I/private/tmp/pear/install/pear-build-rootQ8Q9xG/sqlsrv-5.6.1/main -I/private/tmp/pear/install/sqlsrv -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/private/tmp/pear/install/sqlsrv/shared/ -DHAVE_CONFIG_H -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -fstack-protector -c /private/tmp/pear/install/sqlsrv/conn.cpp  -fno-common -DPIC -o .libs/conn.o
In file included from /private/tmp/pear/install/sqlsrv/conn.cpp:21:
/private/tmp/pear/install/sqlsrv/php_sqlsrv.h:25:10: fatal error: 'php.h' file not found
#include "php.h"
         ^~~~~~~
1 error generated.
make: *** [conn.lo] Error 1
ERROR: `make' failed
</code>

**Comment by rmartin93** [comment]
Tried deleting this issue since I clearly didn't get the markdown right but it doesn't look like deleting issues is a thing. Sorry about that.

**Comment by yitam** [comment]
Which macOS version, @rmartin93 ? Did you follow [the documentation of installing php in macOS](https://docs.microsoft.com/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-macos-sierra-high-sierra-and-mojave) ?

**Comment by rmartin93** [comment]
MacOS Mohave 10.14.6. 

And yes, I have php on my macOS.

**Comment by yitam** [comment]
@rmartin93

Yes you have php because you could run `pecl install`, but which php version? 

Based on your error report, some php files are missing in your env. Have you checked whether you have folders / files in `/usr/include/php/`?

You should see folders like these ones:
```
TSRM
Zend
ext
main
sapi
```

So did you follow the steps in our documentation (please click the link above in my first reply)?

And what's the output of the following commands:
1. which php
1. php -v
1. pecl version

**Comment by rmartin93** [comment]
In usr I have 

```bin		lib		libexec		local		sbin		share		standalone```

Yes, I followed the instructions above. 

which php 

```/usr/bin/php```

php -v 

```
PHP 7.1.23 (cli) (built: Feb 22 2019 22:19:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

pecl version

```PEAR Version: 1.10.9
PHP Version: 7.1.23
Zend Engine Version: 3.1.0
Running on: Darwin Ryans-MBP.attlocal.net 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64```

**Comment by yitam** [comment]
@rmartin93 I wonder if you did the following step after using `brew install`? I expect `which php` to show `/usr/local/bin/php` 

`brew link --force --overwrite php@7.1`?

**Comment by rmartin93** [comment]
I'm not sure what you mean. 

I don't think I ran ```brew link --force --overwrite php@7.1``` after doing brew install. 

I tried that command and I got ```Error: No such keg: /usr/local/Cellar/php@7.1```

**Comment by yitam** [comment]
Based on your info, @rmartin93 , I assumed you had installed php 7.1 via brew install, but it looks like something went wrong. Can you try uninstalling php and repeat all the steps in the installation guide prior to `pecl install`?

**Comment by rmartin93** [comment]
I Googled uninstall php and it doesn't look like there's a very simple or straightforward way of doing that. Any suggestions for the proper way to uninstall php?

**Comment by yitam** [comment]
@rmartin93 Did you check what's in `/usr/local/Cellar`? Any php versions there?

If a `brew install php@7.1` was successful, you should be able to uninstall using `brew uninstall php@7.1` or with force `brew uninstall --force php@7.1`

After that, you might want to `brew cleanup`, `brew update` and/or `brew doctor` 

Please also check [Brew FAQ](https://docs.brew.sh/FAQ)

**Comment by rmartin93** [comment]
This is what is in ```/usr/local/Cellar```

```autoconf	automake	libtool		msodbcsql17	mssql-tools	openssl		unixodbc```

**Comment by yitam** [comment]
Please follow the [installation instructions](https://docs.microsoft.com/en-ca/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#step-1-install-php-4) to install php. 

To install PHP 7.1 / 7.2, replace php@7.3 with php@7.1 / php@7.2 respectively. Just so you know, php 7.1 is near the end of [its support cycle](https://www.php.net/supported-versions.php).

Nevertheless, I assume you want php 7.1, and Mojave comes with an older version of php 7.1. But brew would install the latest available, which is [7.1.32 as of today](https://www.php.net/archive/2019.php#2019-08-30-1). Thus, you should find `php@7.1` in `/usr/local/Cellar` after this.

Please adjust your env path as well by following the prompts during brew install, or at least you should put "/usr/local/bin" in the beginning of your path.

If php is successfully installed, `which php` should be `/usr/local/bin/php` and `php -v` should display something like this :

```
PHP 7.1.32 (cli) (built: Sep 14 2019 18:22:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.32, Copyright (c) 1999-2018, by Zend Technologies
```

If it still fails, please try following the instructions in a clean environment and troubleshoot from there.

**Comment by rmartin93** [comment]
Okay, after making sure ```which php``` returned ```/usr/local/bin/php``` I was finally able to run 

```sudo pecl install pdo_sqlsrv
sudo pecl install sqlsrv```

without any problems. 

In ```/usr/local/Cellar``` I have php but not php@7.1 just so you know. 

On the instructions on this page: https://www.microsoft.com/en-us/sql-server/developer-get-started/php/mac/step/2.html when I run ```php connect.php``` I get ```PHP Fatal error:  Uncaught Error: Call to undefined function sqlsrv_connect() in /Users/ryanmartin/Local Sites/SqlServerSample/connect.php:9```

Installing pdo_sqlsrv and sqlsrv should have fixed that, right?

**Comment by yitam** [comment]
@rmartin93 I'm not sure I understand what you did:
> after making sure which php returned /usr/local/bin/php I was finally able to run

or whether you had installed via `brew install`
> In /usr/local/Cellar I have php but not php@7.1 just so you know.

Judging from the error message, sqlsrv driver is not loaded by your php or pecl install linked the drivers to a different php.

Again, what's the output of 
1. php -v
1. pecl version

What about `php --ri sqlsrv`?

The link you provided is based on using SQL Server on your Mac, using Docker. Are you?

If not, can you please try follow the [instructions](https://docs.microsoft.com/en-ca/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#step-1-install-php-4) I gave you earlier in a **clean** environment and troubleshoot from there first.

**Comment by rmartin93** [comment]
I am running a SQL Server on my Mac using Docker. I am just having trouble connecting it with a Codeigniter PHP project. 

php -v outputs this 

```PHP 7.1.23 (cli) (built: Feb 22 2019 22:19:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies```

pecl version outputs this

```PEAR Version: 1.10.9
PHP Version: 7.3.10
Zend Engine Version: 3.3.10
Running on: Darwin Ryans-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64```

php --ri sqlsrv outputs this 

```Extension 'sqlsrv' not present.```

I've followed all the instructions. I've downloaded brew, sqlsrv, pecl, and everything else the instructions have said to. I'm sorry, I just don't understand why this isn't working.

**Comment by yitam** [comment]
@rmartin93 can you see that your pecl is linked to php 7.3.10 while your `php -v` displays php 7.1.*?

Maybe you should check with the Codeigniter PHP support as well.

**Comment by rmartin93** [comment]
Okay. Trying to figure out how to update my php so that ```php -v``` gives me PHP 7.3.10. 

I'll get back to you after I figure that out.

**Comment by rmartin93** [comment]
Got it. Now they're both PHP 7.3.8. 

I still get ```Fatal error: Uncaught Error: Call to undefined function sqlsrv_connect() in /Users/ryanmartin/Local Sites/docker_php/connect.php on line 10```

when I try to follow step 2.3 on this link: https://www.microsoft.com/en-us/sql-server/developer-get-started/php/mac/step/2.html

**Comment by yitam** [comment]
@rmartin93 if you have to use both php for some reason, then perhaps you should use absolute path or set up your env path accordingly. Your goal is to make sure you know which one you're using (or, one of them has to take precedence).

Also, did you check **all** the outputs as in my last detailed reply yesterday? As I already said before, I highly suspect `pecl` is linked to a diff php from the one you run.  

For example, assuming you have used brew to install, and `which php` gives `/usr/local/bin/php`

`ls -al /usr/local/bin/php`  should display something like:

i.e. `/usr/local/bin/php -> .../Cellar/php/7.3.10/bin/php`

Do you still have php in `/usr/bin/php`?

Try comparing the outputs of 
1. `php --ri sqlsrv` 
1. `/usr/local/bin/php --ri sqlsrv`
1. `/usr/bin/php --ri sqlsrv`

**Comment by yitam** [comment]
@rmartin93 I'm afraid your system is quite messed up. Please start from scratch or in a clean Mojave and follow the instructions from the very beginning. Running brew install should give you the latest as of today, which is php 7.3.10 as I mentioned [above](https://github.com/microsoft/msphpsql/issues/1040#issuecomment-539196743).

Good luck!

**Comment by yitam** [comment]
@rmartin93 just one more suggestion from me, try using the absolute path like this:

`/usr/local/bin/php connect.php`

If it works, you might want to set up your env path, like this:

`export PATH="/usr/local/bin:${PATH}"`

**Comment by rmartin93** [comment]
Haha, I sure hope that's what it is. 

If you have any guides as to how to clean my Mojave so I can start from scratch you recommend I'd be happy to look at those. Of course I'll try to find it on my own as well. 

I tried ```/usr/local/bin/php connect.php``` and I got 

```
-bash: cd: php: Not a directory
```

Thanks for all the help.

**Comment by yitam** [comment]
That error message about `cd` is unexpected and makes no sense :(

Anyway, try to clean up all php in your Mojave:

```
brew update
brew upgrade
brew cleanup

# Check if you have old deprecated Homebrew PHP versions and extensions installed
brew list | grep php

# Uninstall deprecated Homebrew PHP, every one of them:
brew unlink php@5.5
brew unlink php@5.6
brew unlink php@7.0
brew unlink php@7.1
brew unlink php@7.2
brew unlink php@7.3
brew unlink php
brew cleanup

brew uninstall --force php@5.5
brew uninstall --force php@5.6
brew uninstall --force php@7.0
brew uninstall --force php@7.1
brew uninstall --force php@7.2
brew uninstall --force php@7.3

# Check that no deprecated Homebrew PHP packages are left
brew cleanup
brew list | grep php

# Remove all old PHP configurations
rm -Rf /usr/local/etc/php/*
```

Then follow the instructions again, but this time make sure you get [php installed correctly](https://github.com/microsoft/msphpsql/issues/1040#issuecomment-539196743) and check all my replies above.

Once again, good luck!

**Comment by rmartin93** [comment]
Is it possible I need to have MS SQL Extension in my php.ini file? 

If so, how would I do that?

**Comment by yitam** [comment]
I assume you meant the `sqlsrv` extension, and if the entire installation is done correctly, `pecl install sqlsrv` would have taken care of that. 

Let me quote one of your replies [above](https://github.com/microsoft/msphpsql/issues/1040#issuecomment-539565317), which obviously `sqlsrv` is enabled in `/usr/local/bin/php` but not present in the other php:

> /usr/local/bin/php --ri sqlsrv 

```
sqlsrv

sqlsrv support => enabled
ExtensionVer => 5.6.1

Directive => Local Value => Master Value
sqlsrv.WarningsReturnAsErrors => On => On
sqlsrv.LogSeverity => 0 => 0
sqlsrv.LogSubsystems => 0 => 0
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240
```

**Comment by yitam** [comment]
Any luck, @rmartin93 ?

**Comment by rmartin93** [comment]
Yes and no. I've started a course on Udemy for Docker so I'm hoping through that I'll be able to figure this out. I've got some parts done but not all. You can feel free to close this issue if you like. 

Thanks again for the help! :)

**Comment by yitam** [comment]
Good luck @rmartin93 !
Please feel free to reopen this issue.
