### ISSUE TITLE
debconf not handled correctly on msodbcsql17

### ISSUE THREAD

**Issue by LiohMoeller** [microsoft/msphpsql#1048]
I am trying to predefine the ACCEPT LICENSE debconf variable for the ODBC package (msodbcsql17) like this:

echo msodbcsql17 msodbcsql/accept_eula boolean true | debconf-set-selections

But it seems to be ignored by the pre-installation script, which just checks only for the environment variable to be set. This does not work on automated installations e.g. when using puppet.

**Comment by david-puglielli** [comment]
@LiohMoeller debconf support is scheduled for a future release of the ODBC driver, please stay tuned.

**Comment by yitam** [comment]
@LiohMoeller please check the [latest ODBC documentation](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)

**Comment by LiohMoeller** [comment]
It does not say anything about debconf support.

**Comment by yitam** [comment]
@LiohMoeller please search for the keyword "debconf". I pasted the screenshot below for your reference:

![image](https://user-images.githubusercontent.com/21340756/73676798-d955a300-4669-11ea-8439-f01c2b79b362.png)

**Comment by LiohMoeller** [comment]
Ah, I was looking at the German version of the docs (browser default here) which does not contain the note yet. Thanks.

**Comment by yitam** [comment]
Resolved. Closing the issue.
