### ISSUE TITLE
ODBC17, PDO SQLSRV and IMAGE, VARBINARY, VARCHAR(MAX) field returns corrupted data

### ISSUE THREAD

**Issue by Wooya** [microsoft/msphpsql#1052]
## PHP Driver version or file name
 + 5.6.1
## SQL Server version
 + 2012
## Client operating system
 + CentOS 7.7.1908
## PHP version
 + 7.3.10
## Microsoft ODBC Driver version
 + 17.4.2.1
## ODBC.ini
```
[CONN]                                                                        
Driver = ODBC Driver 17 for SQL Server                       
Description = SRV
Server = srv.domain.com,1433                             
ServerSPN = MSSQLSvc/srv.domain.com:1433                    
Database = MyDB          
Trusted_Connection = Yes 
```
## Problem description
 + When attempting to retrieve data from field type image, data contains NULL value every 255 chars. Also data stream doesn't look like binary but like hex. I've tried to remove all NULLs from stream and then hex2bin() but after conversion stream looks corrupted also.
## Expected behavior and actual behavior
 + In old Sybase driver I've received binary PDF file
## Repro code or steps to reproduce
```
$query = $this->query("
--Data is IMAGE type field
SELECT Data FROM Table WHERE Id = :Id
");
$stmt = $this->pdo->prepare($query);
$stmt->bindValue(':Id', $Id, \PDO::PARAM_INT);
$stmt->execute();
$row = $stmt->fetch(\PDO::FETCH_ASSOC);
$bin_data = $row['Data'];
```
Expecting binary data, but receiving this (NULL every 255th char):
![image](https://user-images.githubusercontent.com/541588/68105136-e5e92480-fedd-11e9-9d31-a28158c43c68.png)

**Comment by david-puglielli** [comment]
@Wooya I believe you are using the pdo_odbc driver by accident, as I can only reproduce your output with pdo_odbc and not with pdo_sqlsrv. To use the pdo_sqlsrv driver, prepend `sqlsrv` and not `odbc` to the connection string as follows:
```
$conn = new PDO("sqlsrv:server=myserver.....", $uid, $pwd);
```
In addition, to retrieve binary data you must bind LOB and binary PDO types to the binary column, as follows:
```
$stmt = $conn->query("SELECT Data FROM Table");
$stmt->bindColumn('Data', $img, PDO::PARAM_LOB, 0, PDO::SQLSRV_ENCODING_BINARY);
$row = $stmt->fetch(PDO::FETCH_BOUND);
var_dump($img);
```
Please try this and let us know if it works.

Note also that the image type is deprecated and will be removed in a future version of SQL Server - we advise using varbinary(max) in place of image as much as possible.

**Comment by Wooya** [comment]
@david-puglielli Thank you for your response. Of course I'm using pdo_odbc not pdo_sqlsrv. I've tried with pdo_sqlsrv and it works like a charm.
