### ISSUE TITLE
PHP to SQL Server Connection issue

### ISSUE THREAD

**Issue by Shahroz09** [microsoft/msphpsql#1054]
**Error**: Connection could not be established. Array ( [0] => Array ( [0] => 08001 [SQLSTATE] => 08001 [1] => 11001 [code] => 11001 [2] => [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No such host is known. [message] => [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No such host is known. ) [1] => Array ( [0] => HYT00 [SQLSTATE] => HYT00 [1] => 0 [code] => 0 [2] => [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired [message] => [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired ) [2] => Array ( [0] => 08001 [SQLSTATE] => 08001 [1] => 11001 [code] => 11001 [2] => [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. [message] => [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. ) )

 +## PHP Driver version 7.3.11
 +
 +## SQL Server version 2014
 +
 +## Client operating system Windows 10
 +
 +## PHP version 7.3.11
 +
  +## Problem description: I am trying to connect php xampp server with sql server but unable to do. Above is the error I am getting after trying to connect. I have already added dll file in extension folder and added in php.ini
 +## My code
 <?php   
$serverName = "XXXXXXXXXXXXX,XXXX";  
$uid = "XX";     
$pwd = "XXXXXX";    
$databaseName = "XXX";  
$connectionInfo = array("UID" => $uid, "PWD" => $pwd, "Database"=>$databaseName);  
$conn = sqlsrv_connect( $serverName, $connectionInfo);  
if( $conn )  
{  
     echo "Connection established.\n";  
}  
else  
{  
     echo "Connection could not be established.\n";  
     die( print_r( sqlsrv_errors(), true));  
}  
sqlsrv_close( $conn);  
?>

**Comment by david-puglielli** [comment]
@Shahroz09 It looks like the driver can't find your server. Can you connect with `sqlcmd`? Also, which version of the ODBC driver are you using?

**Comment by Shahroz09** [comment]
Thanks @david-puglielli  I have been able to resolve the issue after giving server's ip in $serverName variable in this format $serverName = "ServerIp\InstanceName,Port";
