### ISSUE TITLE
DML statements open a cursor that needs to be closed manually

### ISSUE THREAD

**Issue by juacala** [microsoft/msphpsql#1066]
+## PHP Driver version or file name
pdo_sqlsrv version 5.6.1 (from phpinfo)
 +## SQL Server version
Microsoft SQL Server 2017 (RTM-CU15-GDR) (KB4505225) - 14.0.3192.2 (X64)
Jun 15 2019 00:45:05
Copyright (C) 2017 Microsoft Corporation
Developer Edition (64-bit) on Linux (Ubuntu 18.04.3 LTS)
 +## Client operating system
Ubuntu 18.04.3 LTS
 +## PHP version
PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
 +## Microsoft ODBC Driver version
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1
UsageCount=1
  
 +## Problem description
I have a PHP program that uses the PDO::sqlsrv driver to query against an MS SQL Server database.

This has some strange behavior. If I have MARS enabled (https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars?view=sql-server-ver15), which is the default, and try to start a transaction at some points, I get the following error:

```
["42000",3988,"[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]New transaction is not allowed because there are other threads running in the session."]
```

It appears that this is because some active result sets need to get closed down. Unfortunately, I'm not aware of how to determine what threads are running in the session. I turned off MARS to try to better determine what queries are not shutting down properly, and after any insert/update I get the following error:

```
IMSSP
-61
The connection cannot process this operation because there is a statement with pending results.  To make the connection available for other queries, either fetch all results or cancel or free the statement.  For more information, see the product documentation about the MultipleActiveResultSets connection option.
```

Apparently any insert/update is creating a result set that needs its cursor closed.

Manually closing the cursor after each DML statement fixes the issue. This is quite inconvenient, and doesn't seem like it should be the behavior of SQL Server to create a result set that is meaningless (DML statements don't return any rows).

Is this the intended behavior (that DML statements need manual closing of the associated cursor)?

Is there a way to stop this behavior (close the cursors automatically for DML statements)?

Is there a way to close all the open result sets on a connection, so I can start a transaction (that would be easy to implement at the beginning of all transactions)?

**Comment by yitam** [comment]
@juacala Since you did not provide repro steps, judging from what you have described, you may want to consider using [`SET NOCOUNT ON`](https://docs.microsoft.com/sql/t-sql/statements/set-nocount-transact-sql?view=sql-server-ver15), in which case the count indicating the number of rows affected by a Transact-SQL statement (like an INSERT / UPDATE) is not returned. 

Otherwise, the count is returned, which needs to be processed (calling `$stmt->closeCursor()`, for example). 

Yet, using `SET NOCOUNT` does have some implications. You might want to go through [this answer](https://stackoverflow.com/questions/1483732/set-nocount-on-usage) as well.

**Comment by juacala** [comment]
Thank you for your response.

It appears that rowcounts are the issue, as you guessed. "set nocount on" also resolves the issue. After looking at it a little more carefully, this behavior happens if there is an insert or update (possibly delete) that includes a sub-query. To repeat, you could do the following (this inserts if the value is not there, and does nothing if it is already there):

```
insert into "table" ("col1")
select "col2" from (select "col2" from "table2") f 
where not exists
(select 1 from "table" t
where(t.col1=f.col2)
```

Then attempt any query after this, and it will fail (without MARS turned on). This is true even if you use $result->rowCount() multiple times on the result. I suppose the subqueries produce a rowcount somehow that cannot be cleared without using closeCursor.

Is that the intended functionality?

**Comment by yitam** [comment]
@juacala it would help if you could give us a clearer picture of what you're trying to do. Please provide some concrete scripts / examples / steps / table schema, etc.

**Comment by yitam** [comment]
@juacala this article about [SET NOCOUNT ON](https://www.sqlshack.com/set-nocount-on-statement-usage-and-performance-benefits-in-sql-server/) might be helpful to you

**Comment by yitam** [comment]
Any update @juacala ? We now close this issue due to inactivity. Please feel free to reopen if necessary.
