### ISSUE TITLE
apt-get update , fails

### ISSUE THREAD

**Issue by kenny1har** [microsoft/msphpsql#1067]
```Err:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (84552 != 156065). Mirror sync in progress? [IP: 13.76.190.189 443]
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
Hit:3 http://security-cdn.debian.org/debian-security buster/updates InRelease
Hit:4 http://cdn-fastly.deb.debian.org/debian buster InRelease
Hit:5 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease
Fetched 3959 B in 1s (4869 B/s)
Reading package lists...
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease (expected bionic but got stable)
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (84552 != 156065). Mirror sync in progress? [IP: 13.76.190.189 443]
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000```


I am unable to run apt-get update

**Comment by leexin** [comment]
Facing the same issue here. Ubuntu 18.04.

`Hit:1 https://deb.nodesource.com/node_10.x bionic InRelease
Get:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [3959 B]
Get:3 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [166 kB]
Err:3 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (93512 != 165979). Mirror sync in progress? [IP: 13.76.190.189 443]
  Hashes of expected file:
   - Filesize:165979 [weak]
   - SHA512:ce0cd5497cdc9242a0e841113b3c280aa381555b20cde125fb1ded717ba89d936f004d0e64c83b3b6d5e2ef42756352975feb16ae5c7271cdcf631ffe6c3872a
   - SHA256:179eb71f2afb4a72bf5b11180b4d4c9ccf1644076dd75f5a7bbf880ecefafbba
   - SHA1:381a8321619083a4063fa8381bf3aa12a2dac5a3 [weak]
   - MD5Sum:54c730dd6a33c612b2ae3c23fe0cfcb7 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Fetched 3959 B in 2s (2621 B/s)
Reading package lists...
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease (expected bionic but got stable)
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.gz  File has unexpected size (93512 != 165979). Mirror sync in progress? [IP: 13.76.190.189 443]
   Hashes of expected file:
    - Filesize:165979 [weak]
    - SHA512:ce0cd5497cdc9242a0e841113b3c280aa381555b20cde125fb1ded717ba89d936f004d0e64c83b3b6d5e2ef42756352975feb16ae5c7271cdcf631ffe6c3872a
    - SHA256:179eb71f2afb4a72bf5b11180b4d4c9ccf1644076dd75f5a7bbf880ecefafbba
    - SHA1:381a8321619083a4063fa8381bf3aa12a2dac5a3 [weak]
    - MD5Sum:54c730dd6a33c612b2ae3c23fe0cfcb7 [weak]
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by aballi1** [comment]
Same for 16.04 repo

`Err:20 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Hashes of received file:
   - SHA512:4bbecd83f655aad0a078b711e0cb23b2d3cf8955be13263f4832c75afbc857d816da0ad3fce8f4ad04be87ff4ac7a679d98aec1dfef83c940a63b2e88e86e0e1
   - SHA256:75d820494bbcd6f7b81861efa8947c2d359baa10a3207bb1d0cd56b54a583187
   - SHA1:a67afc08346ba95d2639399c1019ca6cb5af8005 [weak]
   - MD5Sum:aa3ec1d695e6e848b9fd16bca107cfb2 [weak]
   - Filesize:110382 [weak]
  Last modification reported: Fri, 13 Dec 2019 04:32:05 +0000
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
Fetched 180 kB in 2s (67.4 kB/s)
Reading package lists... Done
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease (expected xenial but got stable)
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Hashes of received file:
    - SHA512:4bbecd83f655aad0a078b711e0cb23b2d3cf8955be13263f4832c75afbc857d816da0ad3fce8f4ad04be87ff4ac7a679d98aec1dfef83c940a63b2e88e86e0e1
    - SHA256:75d820494bbcd6f7b81861efa8947c2d359baa10a3207bb1d0cd56b54a583187
    - SHA1:a67afc08346ba95d2639399c1019ca6cb5af8005 [weak]
    - MD5Sum:aa3ec1d695e6e848b9fd16bca107cfb2 [weak]
    - Filesize:110382 [weak]
   Last modification reported: Fri, 13 Dec 2019 04:32:05 +0000
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by tekook** [comment]
Same for Debian 10 repo.

W: Conflicting distribution: https://packages.microsoft.com/debian/10/prod buster InRelease (expected buster but got stable)
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages.bz2  File has unexpected size (18556 != 156065). Mirror sync in progress? [IP: 13.74.252.37 443]
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by david-puglielli** [comment]
This should now be fixed. Please try again.

**Comment by tekook** [comment]
> This should now be fixed. Please try again.

Can confirm, build now works fine.

**Comment by david-puglielli** [comment]
Closing issue, as it's fixed.
