### ISSUE TITLE
Error install on MacOs Catalina

### ISSUE THREAD

**Issue by paneb84** [microsoft/msphpsql#1073]
+## PHP Driver version or file name
 +5.7.1-preview
 +## SQL Server version
 +
 +## Client operating system
 +
 +## PHP version
 +7.3
 +## Microsoft ODBC Driver version
 +
 +## Table schema
 +
 +## Problem description
 When I go to install with the indicated commands 

 `sudo pecl install sqlsrv-5.7.1preview`

the following error is generated

`/private/tmp/pear/install/sqlsrv/php_sqlsrv.h:25:10: fatal error: 'php.h' file not found
#include "php.h"
         ^~~~~~~
1 error generated.
make: *** [conn.lo] Error 1
ERROR: `make' failed
`
 +## Expected behavior and actual behavior
 +
 +## Repro code or steps to reproduce

**Comment by yitam** [comment]
@paneb84 have you [installed the ODBC driver](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#macos)? It would install the required header files from unixodbc

**Comment by paneb84** [comment]
I installed the ODBC driver.

php -v
`PHP 7.3.8 (cli) (built: Aug 24 2019 19:38:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans`

echo $PATH:
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands`

I don't remember if i install php with brew.
Thx

**Comment by yitam** [comment]
@paneb84 macOS Catalina comes with PHP 7.3 pre-installed. If you had installed php with brew recently, the version would have been higher, like 7.3.13 as of today.

Please follow our [instructions](https://github.com/microsoft/msphpsql/blob/master/Linux-mac-install.md#installing-the-drivers-on-macos-sierra-high-sierra-mojave-and-catalina) but replace 7.4 with 7.3

Also, make sure `/usr/local/bin` is in your path and unlink the pre-installed 7.3, so you might want to do this:
```
export PATH="/usr/local/bin:${PATH}"
brew link --force php@7.3

php -v
echo $PATH
```

**Comment by paneb84** [comment]
I install 7.3 from your instruction, but when i run `brew link --force php@7.3` this is the output:
```
Linking /usr/local/Cellar/php@7.3/7.3.13...
Error: Could not symlink bin/pear
Target /usr/local/bin/pear
already exists. You may want to remove it:
  rm '/usr/local/bin/pear'

To force the link and overwrite all conflicting files:
  brew link --overwrite php@7.3

To list all files that would be deleted:
  brew link --overwrite --dry-run php@7.3
```

i run `brew link --overwrite php@7.3` and the output:
```
Warning: php@7.3 is keg-only and must be linked with --force

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/php@7.3/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/php@7.3/sbin:$PATH"' >> ~/.zshrc
```

after `which php`
`/usr/bin/php`
and php -v returns:
```
PHP 7.3.8 (cli) (built: Aug 24 2019 19:38:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
```

how can I proceed? thank you so much for your help

**Comment by yitam** [comment]
@paneb84 probably try `brew link --force --overwrite php@7.3`?

**Comment by paneb84** [comment]
`brew link --force --overwrite php@7.3`
```
Linking /usr/local/Cellar/php@7.3/7.3.13... 25 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/php@7.3/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/php@7.3/sbin:$PATH"' >> ~/.zshrc
```

`php -v`
```
PHP 7.3.8 (cli) (built: Aug 24 2019 19:38:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by yitam** [comment]
> Also, make sure `/usr/local/bin` is in your path and unlink the pre-installed 7.3, so you might want to do this:
> 
> ```
> export PATH="/usr/local/bin:${PATH}"
> echo $PATH

have you changed your path as mentioned above?

**Comment by paneb84** [comment]
I try execute the commands
```
sudo pecl install sqlsrv-5.7.1preview
sudo pecl install pdo_sqlsrv-5.7.1preview
```
and the commands were successfully executed, but in phpinfo i see this in PDO:

```
PDO support | enabled -- | -- 
PDO drivers | mysql, pgsql, sqlite
```

but not sqlsrv

**Comment by yitam** [comment]
Hi @paneb84 
What's the output of `php --ini`? How about `php -m`?

**Comment by paneb84** [comment]
php -ini
```
Configuration File (php.ini) Path: /usr/local/etc/php/7.3
Loaded Configuration File:         /usr/local/etc/php/7.3/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.3/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.3/conf.d/ext-opcache.ini
```
php -m
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pdo_sqlsrv
pgsql
Phar
phpdbg_webhelper
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
sqlsrv
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by yitam** [comment]
Thanks @paneb84 . 
You see `pdo_sqlsrv` listed? 
Also, forgot to ask about `php --ri pdo_sqlsrv`. Does it show the right version?

**Comment by paneb84** [comment]
```
pdo_sqlsrv

pdo_sqlsrv support => enabled
ExtensionVer => 5.7.0-preview

Directive => Local Value => Master Value
pdo_sqlsrv.log_severity => 0 => 0
pdo_sqlsrv.client_buffer_max_kb_size => 10240 => 10240
```

**Comment by yitam** [comment]
Looks like you have the previous version, `5.7.0-preview`, already installed. 

If so, run `sudo pecl uninstall sqlsrv` and repeat for pdo_sqlsrv. Then reinstall version `5.7.1-preview` again.

**Comment by yitam** [comment]
Any update @paneb84 ?

**Comment by paneb84** [comment]
Hi @yitam  sorry for delay. Now the result of command is 
```
pdo_sqlsrv

pdo_sqlsrv support => enabled
ExtensionVer => 5.7.1-preview

Directive => Local Value => Master Value
pdo_sqlsrv.log_severity => 0 => 0
pdo_sqlsrv.client_buffer_max_kb_size => 10240 => 10240
```
and now my script connect correctly with DB but i have an error in date format but i don't know if depend from driver or PHP version, in another PC the script run correctly....
Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 242 [FreeTDS][SQL Server]

**Comment by yitam** [comment]
Glad that this problem has been resolved, @paneb84 . Please create a new issue for the different problem and provide more details than that. I'm closing this one now.

**Comment by yitam** [comment]
@paneb84 btw, just noticed `FreeTDS` in your error message. FYI, our php drivers only work with [Microsoft ODBC driver](https://docs.microsoft.com/sql/connect/odbc/microsoft-odbc-driver-for-sql-server?view=sql-server-ver15).
