### ISSUE TITLE
[pdo_sqlsrv] Failover_Partner doesn't seem to work on Linux

### ISSUE THREAD

**Issue by paste** [microsoft/msphpsql#1076]
Doesn't seem like "Failover_Partner" connection option has any effect on Ubuntu under PHP 7.3 using PDO. I see there is a comment in the test suite saying the same thing -- if that is true it should be documented in the connection options. 

> The Failover_Partner keyword does not work on Unix

https://github.com/microsoft/msphpsql/blob/bd06cf3e3f991298d209e84f727888fe685d94d4/test/functional/sqlsrv/sqlsrv_testConnection.phpt#L99

PHP Driver version or file name
pdo_sqlsrv 5.6.1

SQL Server version
2016

Client operating system
Ubuntu 18

PHP version
7.3.12

Microsoft ODBC Driver version
libmsodbcsql-17.4.so.2.1

**Comment by yitam** [comment]
Thanks @paste for your input. We will get back to you on this

**Comment by yitam** [comment]
Yes @paste we will update our documentation accordingly. FYI, this [odbc page listing the connection string attributes](https://docs.microsoft.com/sql/connect/odbc/dsn-connection-string-attribute?view=sql-server-ver15) might be useful

**Comment by paste** [comment]
thanks @yitam, I hadn't seen that one.

**Comment by yitam** [comment]
Hi @paste the documentation update is in the queue and will be rolled out with the next stable release. Thank you for your contribution, and we are closing this issue now. Please feel free to reopen.
