### ISSUE TITLE
sudo pecl install sqlsrv causes error on char size

### ISSUE THREAD

**Issue by sqlAllAround** [microsoft/msphpsql#1078]
Banging my head.  Is there a config that changes the unsigned integer to something that compiles?

sudo pecl install sqlsrv

errors out with:

 g++ -std=c++11 -I. -I/tmp/pear/temp/sqlsrv -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootZ76h5K/sqlsrv-5.6.1/include -I/tmp/pear/temp/pear-build-rootZ76h5K/sqlsrv-5.6.1/main -I/tmp/pear/temp/sqlsrv -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -I/tmp/pear/temp/sqlsrv/shared/ -DHAVE_CONFIG_H -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -fstack-protector -c /tmp/pear/temp/sqlsrv/shared/core_stream.cpp  -fPIC -DPIC -o shared/.libs/core_stream.o
/tmp/pear/temp/sqlsrv/shared/core_stream.cpp:209:1: error: invalid conversion from ‘size_t (*)(php_stream*, char*, size_t) {aka long unsigned int (*)(_php_stream*, char*, long unsigned int)}’ to ‘ssize_t (*)(php_stream*, char*, size_t) {aka long int (*)(_php_stream*, char*, long unsigned int)}’ [-fpermissive]
 };
 ^
Makefile:204: recipe for target 'shared/core_stream.lo' failed
make: *** [shared/core_stream.lo] Error 1
ERROR: `make' failed
yeh@linux1:/etc/php/7.4$ sudo update-alternatives --set phpize /usr/bin/phpize7.1
update-alternatives: error: alternative /usr/bin/phpize7.1 for phpize not registered; not setting
yeh@linux1:/etc/php/7.4$ ^C

php -v
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies

**Comment by yitam** [comment]
@sqlAllAround v5.6.1 do not yet support 7.4. Please do `sudo pecl install sqlsrv-5.7.1preview` or wait for the next stable release.

**Comment by yitam** [comment]
Thanks @miurabo for the confirmation

**Comment by yitam** [comment]
@sqlAllAround we are going to close this issue due to inactivity. Please feel free to reopen if necessary.
