### ISSUE TITLE
Need information for connecting to 2005 SP4

### ISSUE THREAD

**Issue by lourdas** [microsoft/msphpsql#1085]
Hi,

Apologies for opening a issue not directly related to this repository.

My development environment is Windows 10 1909 64-bit and my PHP is 7.3 64-bit NTS. I need information on how to connect to a old SQL 2005 64-bit running in a old Windows 2003 R2 64-bit operating system. The page at https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver?view=sql-server-ver15 does not quote 2005 at all, so I don't know where to look.

I **know** that both SQL 2005 and Server 2003 are EOL, but at the moment we have this old system that we need to connect and retrieve information. In the next few months we will upgrade this system to SQL 2014, so in that case I will use the driver provided here.

**Comment by david-puglielli** [comment]
@lourdas Our drivers do not support SQL Server 2005 at all, but there are earlier PHP drivers, [mssql](https://www.php.net/manual/en/book.mssql.php) and [pdo_dblib](https://www.php.net/manual/en/ref.pdo-dblib.php), that can access SQL Server databases. However, these only work for PHP 5.3 and below.

A better option is to use the [pdo_odbc](https://www.php.net/manual/en/ref.pdo-odbc.php) driver, which you can use with PHP 7.3. You need the ODBC driver - the latest is version 17, which should work but if not you can try earlier versions. Download links [here](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-2017).

Also note that you may run into issues with TLS encryption as Windows 2003 does not support TLS 1.2. See [this comment](https://github.com/microsoft/msphpsql/issues/888#issuecomment-442890386) for more info.

**Comment by lourdas** [comment]
Thank you for the information. I will try your suggestion.

Please keep this issue open in case I find a problem, so that I can post here.

Thanks.

**Comment by lourdas** [comment]
I used the ODBC driver v.11 and I successfully connected using php_odbc. The only minor thing is that I cannot seem to set the connection character set, so I have to use iconv to convert the text to UTF-8, but it works.

Thank you for the information, closing this!

**Comment by david-puglielli** [comment]
Glad it works! Incidentally, pdo_odbc only supports ASCII characters so it's no surprise that iconv is required to convert to UTF-8. pdo_sqlsrv however supports UTF-8 by default, no need for iconv.
