### ISSUE TITLE
Debian packages for 17.5 are missing

### ISSUE THREAD

**Issue by esetnik** [microsoft/msphpsql#1088]
Where is msodbcsql17_17.5.1.1-1_amd64.deb?

https://packages.microsoft.com/debian/9/prod/pool/main/m/msodbcsql17/

Index of /debian/9/prod/pool/main/m/msodbcsql17/
../
msodbcsql17_17.0.1.1-1_amd64.deb                   12-Mar-2018 19:32             3835428
msodbcsql17_17.1.0.1-1_amd64.deb                   03-Apr-2018 23:38             3861804
msodbcsql17_17.2.0.1-1_amd64.deb                   11-Jul-2018 05:45             4068616
msodbcsql17_17.3.1.1-1_amd64.deb                   26-Feb-2019 04:46              749208
msodbcsql17_17.4.1.1-1_amd64.deb                   02-Aug-2019 17:49              796686
msodbcsql17_17.4.2.1-1_amd64.deb                   04-Oct-2019 01:13              797708

**Comment by yitam** [comment]
Yes @esetnik this morning we realized the microsoft repo removed the 17.5 package, for some reason. We have informed the people in charge. Please check again later

**Comment by david-puglielli** [comment]
@esetnik The package for 17.5 is now available.
