### ISSUE TITLE
PDO with duplicated named parameter in query is not working

### ISSUE THREAD

**Issue by pierrefeelunique** [microsoft/msphpsql#1096]
## Problem description

After upgrading from `dblib` based driver, all the existing queries that uses placeholder multiple times in the query fails. It's basically asking me to duplicate the name. Is there a way to fix that without us having to go through all the existings queries and change the name ?

## PHP Driver version or file name

|pdo_sqlsrv  | |
|-- | -- |
| ExtensionVer | 5.8.0|

 ## SQL Server version
Microsoft SQL Server 2016 (SP2-CU6)
 ## Client operating system
Ubuntu 18.04
 ## PHP version
7.2.27
 ## Microsoft ODBC Driver version
ODBC Driver 17 for SQL Server

 ## Expected behavior and actual behavior
 
 Named parameter should be assigned based on the param regardless of duplication

**Comment by yitam** [comment]
Hi @pierrefeelunique , please note that it says clearly in [PDO::prepare](https://www.php.net/manual/en/pdo.prepare.php) that "You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on."

You may consider turning emulate prepares to true (which is false by default in pdo_sqlsrv), like this
`$sth = $dbh->prepare($sql, array(PDO::ATTR_EMULATE_PREPARES => true));`

**Comment by pierrefeelunique** [comment]
Ah indeed, it may have been setup like this with the old driver.

Would using the emulation mode prevent the sql server for using execution plan and instead do everything adhoc queries ?

**Comment by yitam** [comment]
@pierrefeelunique With emulation mode it means that no prepared statement is created with `$dbh->prepare()` call. This should be true for all pdo drivers, which internally replace all the placeholders with the parameter values. Thus, a generic query string with no placeholders is sent to the server. Some users like this but some don't. It really depends on the application. 

For example, unlike pdo_sqlsrv, the default value for the `PDO::ATTR_EMULATE_PREPARES` option in pdo_mysql is TRUE.

**Comment by pierrefeelunique** [comment]
@yitam Thanks a lot for all the information.

Closing the issue since it's expected behaviour.
