### ISSUE TITLE
Certain characters for APP connection string property not allowed?

### ISSUE THREAD

**Issue by gjdanis** [microsoft/msphpsql#1098]
## PHP Driver version or file name
5.8.0

## SQL Server version
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 

## Client operating system
Windows 10 Enterprise

## PHP version
PHP 7.2.9 (cli) (built: Aug 22 2018 18:31:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

## Table schema
```
CREATE DATABASE test
GO
```
## Problem description
Having certain characters for the [APP attribute](https://docs.microsoft.com/en-us/sql/connect/php/connection-options?view=sql-server-ver15) in the connection string appears to cause issues with getting a connection.

We've been setting APP to the top level PHP controller/action. For example in the URL `www.eshopper1000/basket/checkout`, we'd set APP to `basket/checkout`. However, there seem to be some issues when the route contains curly braces. For example if we were to set APP to `basket/{basketId}/view` we get this error:

```
SQLSTATE[IM002]: [unixODBC][Driver Manager]Data source name not found and no default driver specified
```

## Expected behavior and actual behavior
We should get a connection without issue.

## Repro code or steps to reproduce
```
$pdo = $pdo = new \PDO('sqlsrv:LoginTimeout=30;MultipleActiveResultSets=False;Server=localhost;Database=test;App=/{code}/status;');
```

**Comment by gjdanis** [comment]
I think this might have something to do with setting `MultipleActiveResultSets=False` in the connection string. I am able to connect if I remove it regardless of what App is set to.

**Comment by yitam** [comment]
Hi @gjdanis , when using `}` in any of the values in the connection string, you have to escape it with another `}`, because 

"The first closing brace in the value is assumed to terminate the value, so values cannot contain closing brace characters." (for details please read it [here](https://docs.microsoft.com/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-2017#odbc-driver-connection-string-keywords))

Try this:

```
$conn = new PDO( "sqlsrv:server=$server ; Database = $database; App=basket/{basketId}}/view", $uid, $pwd);

$query = "SELECT APP_NAME()";
$stmt = $conn->query($query);
while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
    echo $row[0]."\n";
}
```

The output should be `basket/{basketId}/view`

**Comment by gjdanis** [comment]
Awesome that worked! Thanks @yitam - appreciate the quick reply!

**Comment by gjdanis** [comment]
Closing the issue as it looks like this is expected behavior.
