### ISSUE TITLE
Differences between ATTR_TIMEOUT and SQLSRV_ATTR_QUERY_TIMEOUT?

### ISSUE THREAD

**Issue by gjdanis** [microsoft/msphpsql#1100]
## PHP Driver version or file name
5.8

## SQL Server version
Microsoft SQL Server 2017 (RTM-CU8) (KB4338363) - 14.0.3029.16 (X64)   Jun 13 2018 13:35:56   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)

 ## Client operating system
Windows 10 enterprise

 ## PHP version
PHP 7.2.9 (cli) (built: Aug 22 2018 18:31:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

## Table schema
`CREATE DATABASE test`

## Problem description
It looks like `ATTR_TIMEOUT` and `SQLSRV_ATTR_QUERY_TIMEOUT` don't exhibit the same behavior. Setting `SQLSRV_ATTR_QUERY_TIMEOUT` ensures your query doesn't last more than a certain number of seconds. Setting `ATTR_TIMEOUT` doesn't seem to have this effect.

## Expected behavior and actual behavior
 `ATTR_TIMEOUT` should have the same behavior as `SQLSRV_ATTR_QUERY_TIMEOUT`.

## Repro code or steps to reproduce

```
    $username = ...
    $password = ...

    $pdo = new \PDO('sqlsrv:Server=localhost; Database=test', $username, $password);
    $pdo->setAttribute(\PDO::ATTR_TIMEOUT, 1);

    $start = time_ms(true);
    try {
      $pdo->exec("WAITFOR DELAY '00:00:30'");
    } catch (\Throwable $th) {
      echo $th->getMessage() . PHP_EOL;
    } finally {
      $elapsed = time_ms(true) - $start;
      echo $elapsed . PHP_EOL;
    }

    $pdo = new \PDO('sqlsrv:Server=localhost; Database=test', $username, $password);
    $pdo->setAttribute(\PDO::SQLSRV_ATTR_QUERY_TIMEOUT, 1);

    $start = time_ms(true);
    try {
      $pdo->exec("WAITFOR DELAY '00:00:30'");
    } catch (\Throwable $th) {
      echo $th->getMessage() . PHP_EOL;
    } finally {
      $elapsed = time_ms(true) - $start;
      echo $elapsed . PHP_EOL;
    }

```

**Comment by david-puglielli** [comment]
@gjdanis Thank you for bringing this to our attention. Note that we do not support the `PDO::ATTR_TIMEOUT` attribute (it's not listed on the list of supported attributes on our [`PDO::setAttribute`](https://docs.microsoft.com/sql/connect/php/pdo-setattribute) page) - if you set `PDO::ATTR_ERRMODE` to `PDO::ERRMODE_EXCEPTION`, the script throws an exception when trying to set `PDO::ATTR_TIMEOUT`. Note also that the [PHP documentation for `PDO::ATTR_TIMEOUT`](https://www.php.net/manual/en/pdo.setattribute.php) states that `Not all drivers support this option, and its meaning may differ from driver to driver. For example, sqlite will wait for up to this time value before giving up on obtaining an writable lock, but other drivers may interpret this as a connect or a read timeout interval.` We will clarify this in the documentation (there are several other attributes that we do not support).

We did find a slightly different bug in testing. If `$pdo` is explicitly `unset()` before reconnecting, `SQLSRV_ATTR_QUERY_TMEOUT` is not set correctly - the query still takes 30 seconds to run, unless connection pooling is disabled. We will continue to investigate and keep you updated.

**Comment by gjdanis** [comment]
Thanks for investigating, @david-puglielli. I take it that there are no plans to support `PDO::ATTR_TIMEOUT` because its meaning is ambiguous for other drivers?

**Comment by david-puglielli** [comment]
That's right, we will not be supporting `PDO::ATTR_TIMEOUT`.

**Comment by yitam** [comment]
hi @gjdanis , as we have answered your questions, we will close this issue. Please feel free to reopen if necessary.
