### ISSUE TITLE
ODBC Driver 11/13/13.1/17 for SQL Server does not support connections to SQL Server 2000 or earlier versions

### ISSUE THREAD

**Issue by rowjak** [microsoft/msphpsql#1105]
+ First, i'm using Php 7.2, php_sqlsrv_71_ts_x64.dll & php_pdo_sqlsrv_71_ts_x64.dll -> i'm test in cmd using php -v and got no error, so i think it's work properly. i'm using **Laravel 7** and test connection to ms sql server remotely... but i got this error

> ODBC Driver 11/13/13.1/17 for SQL Server does not support connections to SQL Server 2000 or earlier versions
+ i'm try install & reinstall all version of odbc, 11 / 13 / 13.1 / 17 and still got this error while test connection using laravel

this is my laravel .env config
```
DB_CONNECTION=sqlsrv
DB_HOST=host
DB_PORT=port
DB_DATABASE=databasename
DB_USERNAME=username
DB_PASSWORD=password

```

+ Second, i'm using Php 5.6, **unofficial** php_sqlsrv_56_ts_x64.dll & php_pdo_sqlsrv_56_ts_x64.dll cause i'm search official phpsqlsrv for php5.6 is only available on x86 -> i'm test in cmd using php -v and got no error, so i think it's work properly. i'm using **Laravel 5.4** and test connection to ms sql server remotely... but i got this error

> ODBC Driver 11/13/13.1/17 for SQL Server does not support connections to SQL Server 2000 or earlier versions
+ i'm try install & reinstall all version of odbc, 11 / 13 / 13.1 / 17 and still got this error while test connection using laravel

this is my laravel .env config
```
DB_CONNECTION=sqlsrv
DB_HOST=host
DB_PORT=port
DB_DATABASE=databasename
DB_USERNAME=username
DB_PASSWORD=password

```
 
I test connection on laravel using `php artisan migrate` , just only to test that's laravel can connect to database or not ;D
I test connection to sql server database using navicat/datagrip and works correctly...

Thanks

**Comment by yitam** [comment]
Hi @rowjak 

Please note that SQL Server 2000 [reached its end of support](https://support.microsoft.com/en-us/lifecycle/search/1044) years ago, and neither [ODBC drivers](https://docs.microsoft.com/sql/connect/odbc/windows/system-requirements-installation-and-driver-files?view=sql-server-ver15) nor [PHP drivers](https://docs.microsoft.com/sql/connect/php/microsoft-php-drivers-for-sql-server-support-matrix?view=sql-server-ver15) support it.

Please consider upgrading your server.

**Comment by rowjak** [comment]
oke thanks for the answer... now i have a reason to recommend my boss to upgrade sql server..
