### ISSUE TITLE
Makefile:192: recipe for target 'conn.lo' failed

### ISSUE THREAD

**Issue by naman-simform** [microsoft/msphpsql#1108]
I'm trying to install sqlsrv and pro sqlsrv with apache2 php 7.0, but showing `Makefile:192: recipe for target 'conn.lo' failed` error.

 +## PHP Driver version or file name
 +sqlsrv-5.3.0. with php 7.0

 +## SQL Server version
 +sqlsrv-5.3.0

 +## Client operating system
 +Ubuntu

 +## PHP version
 +7.0

 +## Microsoft ODBC Driver version
 +[ODBC Driver 17 for SQL Server]

Command : 
pecl install sqlsrv-5.3.0

Result :
downloading sqlsrv-5.3.0.tgz ...
Starting to download sqlsrv-5.3.0.tgz (173,492 bytes)
.....done: 173,492 bytes
33 source files, building
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
building in /tmp/pear/temp/pear-build-rootq50J0K/sqlsrv-5.3.0
running: /tmp/pear/temp/sqlsrv/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20190902
checking for PHP installed headers prefix... /usr/include/php/20190902
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... gawk
checking whether to enable sqlsrv functions... yes, shared
checking for SQLSRV headers... /tmp/pear/temp/sqlsrv/shared/
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for a sed that does not truncate output... /bin/sed
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking how to run the C++ preprocessor... g++ -E
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/bash /tmp/pear/temp/pear-build-rootq50J0K/sqlsrv-5.3.0/libtool --mode=compile g++ -std=c++11 -I. -I/tmp/pear/temp/sqlsrv -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootq50J0K/sqlsrv-5.3.0/include -I/tmp/pear/temp/pear-build-rootq50J0K/sqlsrv-5.3.0/main -I/tmp/pear/temp/sqlsrv -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -I/tmp/pear/temp/sqlsrv/shared/  -DHAVE_CONFIG_H  -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -fstack-protector   -c /tmp/pear/temp/sqlsrv/conn.cpp -o conn.lo
mkdir .libs
 g++ -std=c++11 -I. -I/tmp/pear/temp/sqlsrv -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootq50J0K/sqlsrv-5.3.0/include -I/tmp/pear/temp/pear-build-rootq50J0K/sqlsrv-5.3.0/main -I/tmp/pear/temp/sqlsrv -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -I/tmp/pear/temp/sqlsrv/shared/ -DHAVE_CONFIG_H -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -fstack-protector -c /tmp/pear/temp/sqlsrv/conn.cpp  -fPIC -DPIC -o .libs/conn.o
In file included from /usr/include/php/20190902/Zend/zend.h:27:0,
                 from /usr/include/php/20190902/main/php.h:34,
                 from /tmp/pear/temp/sqlsrv/shared/core_sqlsrv.h:34,
                 from /tmp/pear/temp/sqlsrv/php_sqlsrv.h:25,
                 from /tmp/pear/temp/sqlsrv/conn.cpp:20:
/tmp/pear/temp/sqlsrv/shared/core_sqlsrv.h: In function ‘void core::sqlsrv_array_init(sqlsrv_context&, zval*)’:
/usr/include/php/20190902/Zend/zend_types.h:827:24: error: expected id-expression before ‘do’
 #define ZVAL_ARR(z, a) do {      \
                        ^
/usr/include/php/20190902/Zend/zend_API.h:381:28: note: in expansion of macro ‘ZVAL_ARR’
 #define array_init(arg)    ZVAL_ARR((arg), zend_new_array(0))
                            ^~~~~~~~
/tmp/pear/temp/sqlsrv/shared/core_sqlsrv.h:2380:20: note: in expansion of macro ‘array_init’
         int zr = ::array_init(new_array);
                    ^~~~~~~~~~
Makefile:192: recipe for target 'conn.lo' failed
make: *** [conn.lo] Error 1
ERROR: `make' failed

**Comment by yitam** [comment]
Hi @naman-simform , looks like you're actually running php 7.4 (see `php/20190902/` in your build log above). In that case, please download our [latest release 5.8.0](https://github.com/microsoft/msphpsql/releases/tag/v5.8.0). 

If you prefer the older version, please make sure you first uninstall 7.4 from your system and double check if you have other php versions installed.

**Comment by yitam** [comment]
@naman-simform please check the FAQ [here](https://github.com/Microsoft/msphpsql/wiki/FAQ#recipe-for-target-failed)

**Comment by ronak90** [comment]
This worked @yitam
 The version of phpize and  php-config were still 7.4 once we updated those it worked as it should.
Thanks for the guidance.
I think we can go ahead and close the issue. @naman-simform

**Comment by naman-simform** [comment]
Yes, This is worked. 
Thanks, @yitam  and @ronak90 
Closing the issue.
