### ISSUE TITLE
Will Ubuntu 20.04 LTS be supported?

### ISSUE THREAD

**Issue by fasterforward** [microsoft/msphpsql#1110]
With the near arrival of Ubuntu 20.04 I am wondering is this version of Ubuntu supported?

**Comment by David-Engel** [comment]
It first needs to be supported by the Microsoft ODBC Driver 17 for SQL Server. That will happen at the end of July/beginning of August when the next version of the ODBC driver comes out. At that point, the Microsoft PHP Drivers 5.8 for SQL Server can be tested for compatibility and possibly declare support for Ubuntu 20.04 using the new ODBC driver.

**Comment by fasterforward** [comment]
Thanks for your answer, helps a lot!

**Comment by bbrala** [comment]
Only then? That is kinda unfortunate... no way to build before that?

**Comment by yitam** [comment]
Yes you can @bbrala. We don't officially support it yet, but you can try [the instructions](https://docs.microsoft.com/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-ubuntu-1604-1804-and-1910). When [downloading ODBC driver](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17), please use the packages from Ubuntu 19.10

**Comment by bbrala** [comment]
Cool, i'll try that for the dev, but running this in production seems risky, will probably have to wait till end of summer right?

Sent from Nine<http://www.9folders.com/>
________________________________
Van: Jenny Tam <notifications@github.com>
verzonden: maandag 4 mei 2020 17:47
Aan: microsoft/msphpsql
Cc: Björn Brala; Mention
Onderwerp: Re: [microsoft/msphpsql] Will Ubuntu 20.04 LTS be supported? (#1110)


Yes you can @bbrala<https://github.com/bbrala>. We don't officially support it yet, but you can try the instructions<https://docs.microsoft.com/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-ubuntu-1604-1804-and-1910>. When downloading ODBC driver<https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17>, please use the packages from Ubuntu 19.10

**Comment by yitam** [comment]
Yes, probably @bbrala . If you run into any issues in the dev settings, please create a new issue for us to track.

**Comment by Jordi975** [comment]
I try to connect with sqlcmd or bcp and it's impossible in Ubuntu 20.04
[08001][unixODBC][Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746

The connect with isql or tsql is successful 
Do I have to wait for the new version?

**Comment by yitam** [comment]
@Jordi975 so far our internal testing shows nothing unusual. Is it a fresh install of Ubuntu 20.04 or an upgrade from the previous version?

**Comment by Jordi975** [comment]
It's a fresh install of Ubuntu 20.04

**Comment by yitam** [comment]
> Yes you can @bbrala. We don't officially support it yet, but you can try [the instructions](https://docs.microsoft.com/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-ubuntu-1604-1804-and-1910). When [downloading ODBC driver and tools](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17), please use the packages from Ubuntu 19.10

Did you follow my suggestion above @Jordi975 to install the ODBC driver and tools?

**Comment by bbrala** [comment]
Yes I did and haven't had any complaints from developers so it seems to work as it should:+1:

**Comment by yitam** [comment]
That's great to know, @bbrala 👍 
Please bear in mind it's not official yet.

**Comment by denisdal** [comment]
Hi, just to notify you that using Ubuntu 19.10 repo on a fresh install Ubuntu 20.04 gives this error when trying to connect to sql:
[Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746

**Comment by Jordi975** [comment]
> > Yes you can @bbrala. We don't officially support it yet, but you can try [the instructions](https://docs.microsoft.com/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-ubuntu-1604-1804-and-1910). When [downloading ODBC driver and tools](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17), please use the packages from Ubuntu 19.10
> 
> Did you follow my suggestion above @Jordi975 to install the ODBC driver and tools?

I tried it but the connection with sqlcmd didn't work
I don't have mssql-server only sqlcmd installed. Because I have a remote server with windows server and sql 2008 DB
Thanks

**Comment by yitam** [comment]
@Jordi975 not sure about your windows server version, but just so you know, we stop supporting sql server 2008

@denisdal what's your version of sql server on which operating system? 

You might need some workarounds, which can be found in related issues #1112, #1121 or #252

**Comment by Jordi975** [comment]
> @Jordi975 not sure about your windows server version, but just so you know, we stop supporting [sql server 2008](https://docs.microsoft.com/support/sql/end-support-sql-server-2008)
> 
> @denisdal what's your version of sql server on which operating system?
> 
> You might need some workarounds, which can be found in related issues #1112, #1121 or #252

Sorry @yitam , is SQL Server 2016

Microsoft SQL Server 2016 (SP1-GDR) (KB4505219) - 13.0.4259.0 (X64)
        Jun 15 2019 19:20:12
        Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: )

**Comment by yitam** [comment]
@Jordi975 for SQL Server 2016, you will need a workaround. Please check [my reply](https://github.com/microsoft/msphpsql/issues/1112#issuecomment-609972220)

**Comment by Jordi975** [comment]
Now, yes @yitam ...thank you so much for you help. I connected with sqlcmd and PHP7.4 !!

But I have an application running on in other server Ubuntu 18.04 (PHP 7.3)
And in the new one with new driver sqlsrv I have a strange error:

Example:
  ["fecha_entrada"]=>
  object(DateTime)#2 (3) {
    ["date"]=>
    string(26) "2019-08-02 10:49:26.323000"
    ["timezone_type"]=>
    int(3)
    ["timezone"]=>
    string(13) "Europe/Madrid"
  }

while( $row = sqlsrv_fetch_array( $stmt, SQLSRV_FETCH_ASSOC) ) {
var_dump($row);
$o = new ReflectionObject($row["fechabulto"]);
var_dump($o);
$p = $o->getProperty('date');

ERROR: Caught exception: Property date does not exist

**Comment by yitam** [comment]
hi @Jordi975 please check php 7.4 [deprecation](https://www.php.net/manual/en/migration74.deprecated.php) to see if ReflectionObject is one of them. If you like, please create a new issue as this is unrelated to Ubuntu 20.04 support

**Comment by denisdal** [comment]
> 
> @denisdal what's your version of sql server on which operating system?
> 
> You might need some workarounds, which can be found in related issues #1112, #1121 or #252

Microsoft SQL Server 2014 (SP2-GDR) (KB4019093) - 12.0.5207.0 (X64) 
	Jul  3 2017 02:25:44 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by yitam** [comment]
@denisdal as explained [above](https://github.com/microsoft/msphpsql/issues/1110#issuecomment-634777951), [a workaround is required](https://github.com/microsoft/msphpsql/issues/1112#issuecomment-609972220) for older SQL Server versions. There is a reason for the enhanced security and do it at your own risk.

**Comment by ryanhinton** [comment]
Hello, I have an upgraded version of 20.04 from 19.10. I have had ODBC Driver 17 for SQL Server previously installed, however, I now receive the error: Error code 0x2746 (10054) (SQLDriverConnect)
I tried the steps mentioned in your instructions for 19.10 and it shows that I already have the latest version of odbc 17 driver. I have noticed that it appears everyone has a fresh install. In my case, it is an upgrade. Is there something different that I need to do in order to make this work properly?

Thank you.

**Comment by ryanhinton** [comment]
Hello @yitam, 

Your [solution reference](https://github.com/microsoft/msphpsql/issues/1112#issuecomment-609972220) for older SQL Server versions with Ubuntu 20.04 worked.  

I did not have an issue with this in 19.10, but as soon as I upgraded to 20.04, I was getting the following error: `[Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746`

Thank you so much for your help!  :-)

**Comment by fasterforward** [comment]
With the new release of the ODBC driver 17.6 is there an ETA for the php driver for Linux?

https://techcommunity.microsoft.com/t5/sql-server/odbc-driver-17-6-for-sql-server-released/ba-p/1556980

**Comment by David-Engel** [comment]
@fasterforward Give the 5.8 release a try with ODBC 17.6 and let us know how it goes. We are going to run the same configuration through our PHP test suites and see if 5.8 can simply be certified with ODBC 17.6. I don't have an ETA to share at this time, though. Looking at schedules, we could know this week, or a couple weeks later.

Regards,
David

**Comment by yitam** [comment]
Hi @fasterforward and others, 

As @David-Engel mentioned, SQLSRV drivers 5.8 now officially support the new ODBC driver 17.6. 

That being said, Ubuntu 20.04 LTS comes with stricter security measure and if you're using older servers (prior to SQL Server 2017) you still require a workaround (as explained above and [other related issues](https://github.com/microsoft/msphpsql/issues/1110#issuecomment-634770175)). Please consider upgrading your servers as well.

If you encounter any other problem please create a new issue.

**Comment by fasterforward** [comment]
> 
> 
> Hi @fasterforward and others,
> 
> As @David-Engel mentioned, SQLSRV drivers 5.8 now officially support the new ODBC driver 17.6.
> 
> That being said, Ubuntu 20.04 LTS comes with stricter security measure and if you're using older servers (prior to SQL Server 2017) you still require a workaround (as explained above and [other related issues](https://github.com/microsoft/msphpsql/issues/1110#issuecomment-634770175)). Please consider upgrading your servers as well.
> 
> If you encounter any other problem please create a new issue.

Thanks for you reply and I am happy with your answer!

We will connect to Sql Server 2019. Can you confirm that this is fully supported by Microsoft?

**Comment by yitam** [comment]
Yes @fasterforward and also please check our [support matrix](https://docs.microsoft.com/sql/connect/php/microsoft-php-drivers-for-sql-server-support-matrix?view=sql-server-ver15) for your future reference.

**Comment by fasterforward** [comment]
> 
> 
> Yes @fasterforward and also please check our [support matrix](https://docs.microsoft.com/sql/connect/php/microsoft-php-drivers-for-sql-server-support-matrix?view=sql-server-ver15) for your future reference.

Thank you for pointing me to the matrix. Very useful information. Have a nice day!
