### ISSUE TITLE
Query fails when multiple brackets are escaped in LIKE

### ISSUE THREAD

**Issue by Beakerboy** [microsoft/msphpsql#1118]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 + sqlsrv 5.8
 +## SQL Server version
 + 2019
 +## Client operating system
 + Linux
 +## PHP version
 + 7.3
 +## Microsoft ODBC Driver version
 +
 +## Table schema
 +
 +## Problem description
 + No results when two escaped bracket are in a LIKE statement.
 +## Expected behavior and actual behavior
 + expect the same results for all three queries below
 +## Repro code or steps to reproduce
 ```php
public function testStraightPdo() {
    $prefix = 'test7472525';
    $prefixed_table = $prefix . 'test_people';
    $create_sql = "CREATE TABLE $prefixed_table (name nvarchar(max), job varchar(255))";
    $dbh = new \PDO("sqlsrv:Server=localhost;Database=mydrupalsite", "sa", "Password12!");
    $dbh->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
    $dbh->exec($create_sql);

    $insert_sql = "INSERT INTO $prefixed_table (name, job) VALUES ('Dirk', '[Rutles] - Guitar')";
    $dbh->exec($insert_sql);
    // $select = "SELECT name, job FROM $prefixed_table WHERE job LIKE 'Rutles'";
    $sql = "SELECT name, job FROM $prefixed_table WHERE job LIKE :db_condition_placeholder_0";
    $sth = $dbh->prepare($sql);

    // This Works.
    $args = [
      ':db_condition_placeholder_0' => '%Rutles%',
    ];
    $sth->execute($args);
    $row = $sth->fetch(\PDO::FETCH_ASSOC);
    $name = $row['name'];
    $this->assertEqual('Dirk', $name, "No Brackets");

    // This Works.
    $args = [
      ':db_condition_placeholder_0' => '%[[]Rutles%',
    ];
    $sth->execute($args);
    $row = $sth->fetch(\PDO::FETCH_ASSOC);
    $name = $row['name'];
    $this->assertEqual('Dirk', $name, "One Bracket");

    // This does not.
    $args = [
      ':db_condition_placeholder_0' => '%[[]Rutles[]]%',
    ];
    $sth->execute($args);
    $row = $sth->fetch(\PDO::FETCH_ASSOC);
    $name = $row['name'];
    $this->assertEqual('Dirk', $name, "Two Brackets");
  }

**Comment by yitam** [comment]
Hi @Beakerboy thanks for bringing this to our attention. We will investigate and get back to you

**Comment by yitam** [comment]
Hi @Beakerboy before I dig any further, I'd like to understand what exactly you're trying to do.

I tried running this simple query in Management Studio:
`SELECT * FROM test7472525test_people WHERE job LIKE '%[[]Rutles[]]%'`

It did not return anything, as expected.

If you want to escape the square brackets in the LIKE clause, just so you know, you only need to escape the opening `[`, not the closing `]`, as explained [here](https://stackoverflow.com/questions/439495/how-can-i-escape-square-brackets-in-a-like-clause)

**Comment by Beakerboy** [comment]
That’s probably it then. Thanks!
