### ISSUE TITLE
Failed to load ext\php_pdo_sqlsrv_74_nts_x64

### ISSUE THREAD

**Issue by ZackInMA** [microsoft/msphpsql#1119]
PHP can not seem to load these driver files. REceive the error:

PHP Warning:  PHP Startup: Failed to load ext\php_pdo_sqlsrv_74_nts_x64, The system cannot find the file specified.

PHP Warning:  PHP Startup: Failed to load ext\php_sqlsrv_74_nts_x64, The system cannot find the file specified.

PHP 7.3.x has no issues loading the applicable SQL Drivers for that version. Seems others are having the issue with 7.4 as well. 

https://stackoverflow.com/questions/60603495/php-sqlsrv-extension-not-loading

**Comment by yitam** [comment]
Hi @ZackInMA to help us to figure out the problem, please do not skip the issue template and answer the questions.

**Comment by ZackInMA** [comment]
+## PHP Driver version or file name
php_pdo_sqlsrv_74_nts_x64 and php_sqlsrv_74_nts_x64

 +## SQL Server version
Any version. MS SQL driver for PHP will not load so can't even connect to SQL

+## Client operating system
Win 10 1909

+## PHP version 
7.4.4 x64

 +## Microsoft ODBC Driver version 

+ +## Table schema 
N/A

 +## Problem description
PHP won;t load the MS SQL server drivers. See above error logged in the PHP startup log. 

 +## Expected behavior and actual behavior
PHP should load the drivers without logging issues in the error log and it should be able to connector to a SQL server

+## Repro code or steps to reproduce
Download PHP x64 NTS version
try to get the x64 NTS php_sqlsrv_74_nts_x64 and php_pdo_sqlsrv_74_nts_x64 to load. 

PHP.ini has the correct path to the extension directory. Other extensions load fine. PHPInfo.php lists the correct path to the PHP extension directory.

**Comment by yitam** [comment]
Thanks and which version of php drivers are you using?

**Comment by ZackInMA** [comment]
5.8.
This one.
https://docs.microsoft.com/en-us/sql/connect/php/download-drivers-php-sql-server?view=sql-server-ver15
 Which I believe is the only version that supports PHP 7.4.x

**Comment by yitam** [comment]
Yes you're right @ZackInMA 
I just downloaded it myself but have no problem after appending the following lines to php.ini:

```
extension_dir=ext\
extension=php_sqlsrv_74_nts_x64.dll
extension=php_pdo_sqlsrv_74_nts_x64.dll
```
![image](https://user-images.githubusercontent.com/21340756/78935789-44549900-7a62-11ea-94dc-7e586fc5fe89.png)

**Comment by ZackInMA** [comment]
I notice you have the .dll file extension on the file names for the extensions. I don't have those and will give that a try. I never had to have them in there before though and none of the other extensions that come with PHP have the file extension as well. But it's worth a try. I'll report back soon.

**Comment by ZackInMA** [comment]
As promised, I tested adding the .dll to the extension= in the PHP.ini file and IT WORKED! NEver needed to do that before but I honestly don't care. As long as I have a solution. Thank you so very much for your help yitam!!

**Comment by lahiru888** [comment]
include dll file with .dll extension.
Example:- 
extension=php_pdo_sqlsrv_74_ts_x64.dll
extension=php_sqlsrv_74_ts_x64.dll

**Comment by yitam** [comment]
@LahiruRangana it's unclear whether you have an issue or you're providing a solution to this issue. If it's the former, please create a new issue.

**Comment by Charlink3** [comment]
> Yes you're right @ZackInMA I just downloaded it myself but have no problem after appending the following lines to php.ini:
> 
> ```
> extension_dir=ext\
> extension=php_sqlsrv_74_nts_x64.dll
> extension=php_pdo_sqlsrv_74_nts_x64.dll
> ```
> 
> ![image](https://user-images.githubusercontent.com/21340756/78935789-44549900-7a62-11ea-94dc-7e586fc5fe89.png)

The files no longer available can you send me for email, I looking for the files, but don't find anywhere

**Comment by SimeonAnunciado** [comment]
can you share any external link that can download php_74_pdo sqlsrv ? i cant find low version now most of them are php8.0 thanks for this issue threads

**Comment by David-Engel** [comment]
@SimeonAnunciado For PHP 7.4 support, you have to go back to version 5.10 of the driver:

[Support Matrix](https://learn.microsoft.com/en-us/sql/connect/php/microsoft-php-drivers-for-sql-server-support-matrix?view=sql-server-ver16#php-version-support)

[5.10 Release Notes and download](https://learn.microsoft.com/en-us/sql/connect/php/release-notes-php-sql-driver?view=sql-server-ver16#510)
