### ISSUE TITLE
PHP Version 7.3.9 with sqlserver 2012 connection

### ISSUE THREAD

**Issue by Romit4309** [microsoft/msphpsql#1123]
i following this link:
https://www.youtube.com/watch?v=hxfdbnpOqSI

PHP Version 7.3.9
C:\xampp\php\ext\php_pdo_sqlsrv_73_ts.dll
C:\xampp\php\php.ini    **extension=php_pdo_sqlsrv_73_ts.dll**

http://localhost/phpinfo.php
PDO
PDO drivers  = mysql, sqlite

can you help me?

**Comment by yitam** [comment]
hi @Romit4309 I only watched the first minute of the video. It was about some old releases. 

Depending on your choice (thread safe or non-thread safe? 64 bit or 32 bit?), the latest for PHP 7.3 is 7.3.17, and you can download one of the four zip files from https://windows.php.net/download

Make sure you download the right PHP zip file and the corresponding pdo_sqlsrv driver.
 
Also, in your `C:\xampp\php\php.ini` you may need to specify the extension_dir

For example, you can do that:
```
extension_dir=ext\
extension=php_pdo_sqlsrv_73_ts.dll
```

**Comment by Romit4309** [comment]
driver downloaded this link :
https://docs.microsoft.com/en-us/sql/connect/php/download-drivers-php-sql-server?view=sql-server-ver15

PHP Version update 7.3.9 to 7.4.4

already set
extension_dir = "C:\xampp\php\ext"

>
>
>

**Comment by Romit4309** [comment]
Hii,Jenny Tam, yitam,my issues solve.
 Thanks for help.

use PHP Version 7.1.13
SQL Server driver downloaded this link :
      https://www.microsoft.com/en-us/download/details.aspx?id=55642
 following this link:
        https://www.youtube.com/watch?v=w3L3G-TMmJA&t=192s
