### ISSUE TITLE
[PECL] 5.8.1 windows build issues

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/msphpsql#1124]
The [`pdo_sqlsrv` 5.8.1 has been built](https://windows.php.net/downloads/pecl/releases/pdo_sqlsrv/5.8.1/) but not linked for download.
The [`sqlsrv` has not been built yet](https://windows.php.net/downloads/pecl/releases/sqlsrv/5.8.1/), it seems. But that may be a different problem.

I don't know, where else I could report it, please forward to appropriate people.

**Comment by yitam** [comment]
@AnrDaemon pecl packages just uploaded two hours ago, so please wait a little longer.
Meanwhile you can check the links below:
https://windows.php.net/downloads/pecl/releases/pdo_sqlsrv/5.8.1/
https://windows.php.net/downloads/pecl/releases/sqlsrv/5.8.1/

**Comment by yitam** [comment]
Closing the issue as the links are available now, @AnrDaemon

**Comment by AnrDaemon** [comment]
Yes, sorry. Was overexcited and missed the date of the post.
