### ISSUE TITLE
Always On listener connection fails

### ISSUE THREAD

**Issue by irreleph4nt** [microsoft/msphpsql#1125]
## PHP Driver version or file name
[ExtensionVer] => 5.6.1+11919

## SQL Server version
SQL Server 2016 Build 13.0.5081.1

## Client operating system
Windows 7 Enterprise

## PHP version
7.1.30

## Microsoft ODBC Driver version
[DriverDllName] => msodbcsql17.dll 
[DriverODBCVer] => 03.80 
[DriverVer] => 17.04.0001 

## Table schema
dbo

## Problem description
When using Always On, connecting to the listener of an Availability Group we observe the following error message:

`Array ( [0] => Array ( [0] => IMSSP [SQLSTATE] => IMSSP [1] => -46 [code] => -46 [2] => An error occurred translating the query string to UTF-16: No mapping for the Unicode character exists in the target multi-byte code page. . [message] => An error occurred translating the query string to UTF-16: No mapping for the Unicode character exists in the target multi-byte code page. . ) ) 1`

The webpage throwing the error has no access control (open to everyone) and is hosted on Windows Server 2016 IIS in the UK. The error is returned only for a single user in India but works for everyone else (Europe, US, India). So far we have tested only on Google Chrome as the webpage does not work on Win7's version of Internet Explorer.

We are limited to the sqlsrv driver and can not use PDO for internal reasons.

## Expected behavior and actual behavior
**Expected behavior:**
Connections - using PHP - work for every user visiting the webpage.

**Actual Behavior:**
Connecting to both servers in the AG directly works fine for **_all users_**.
When connecting via the AG listener however, for a **_single user_** the error message above is returned. 

## Repro code or steps to reproduce
```
$server = "aglistener.company.com";
$database = array
(
        "Database" => "dbs_MyDatabase",
        "UID"=> "svc_account", 
	"PWD"=> "supersecretpasswort",
	"TransparentNetworkIPResolution" => "enabled",
	"MultiSubnetFailover" => "yes",
	"CharacterSet" => "UTF-8"
);
$conn = sqlsrv_connect($server, $database);
if ($conn === false) die("<pre>".print_r(sqlsrv_errors(), true));
```

**Comment by yitam** [comment]
@irreleph4nt the message indicated that something went wrong when translating the query string to UTF-16, not the connection string. Please make sure that certain user in India did not use any invalid Unicode characters in the query string. 

If you like you may want to provide ODBC trace for us to investigate further.

**Comment by irreleph4nt** [comment]
@yitam thanks for getting back. I was out of the office so I am sorry for the delay in response time.

Please note that this is for SQL code executed by PHP directly on a webserver. The user has no control over the SQL code and the same code is executed for every user that accesses the page.

Furthermore, it **is** the connection to the database that is throwing the error. I have tested this by adding statements right after the connection code that never get executed for that one particular user. The connection code is also right at the top of my .php file, so it's the first thing to run.

I'll provide an ODBC trace if I can. Is this something a user with no administrative privileges can obtain?

**Comment by yitam** [comment]
Hi, if this happens only to one user, does this user connect with any specific login credentials different from the other users? Can this user connect to the same SQL Server using SQL Server Management Studio or [sqlcmd](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15)?

What's the typical connection string for those that work? What's the php script or SQL code that gets executed? 

Please provide ODBC trace if possible, this shows you [how to do it](https://knowledgebase.progress.com/articles/Article/3059).

**Comment by irreleph4nt** [comment]
I am closing this as a code rewrite has "solved" the problem for me.
I still don't know however why the sqlsrv connection would fail for no obvious reason for a single person. Keep in mind again that the code in question here is located in a .php file and executed by IIS with an integrated user account. Hence the code should behave the same for any person looking at the website, as who that person is has no effect on the code at all.

**Comment by yitam** [comment]
Thanks for your feedback, @irreleph4nt. Without more details or ODBC trace it's difficult for us to investigate the issue, unless you want to share how rewriting your code (assuming you meant php scripts) has solved your problem. Anyway, please feel free to get back to us if necessary.
