### ISSUE TITLE
Backslashes ( \ ) in parametized queries causes Invalid sql_display_size

### ISSUE THREAD

**Issue by savvior** [Microsoft/msphpsql#113]
Running on the preview ubuntu1604_binaries with latest PHP7 from Ubuntu repos.

When doing a parametized query, if a replacement string has a backslash ( \ ) in it, an "sql_display" size error is returned.

`
$stmt = $dbh->prepare("INSERT INTO REGISTRY (name, value) VALUES (:name, :value)");
$stmt->bindParam(':name', "path");
$stmt->bindParam(':value', 's:\test\filename.txt');
$stmt->execute();
`

**Comment by meet-bhagdev** [comment]
Hello @savvior , 
Parameterized queries is a know issue and we have listed it in our [README](https://github.com/Azure/msphpsql/tree/PHP-7.0-Linux#limitations) file. About the sql_display size error, we believe we have a fix and will be releasing it along with our next release on GitHub.

**Comment by meet-bhagdev** [comment]
@savvior what are the type(int, string etc) of columns of name and value in the insert statement?

**Comment by Hadis-Fard** [comment]
@savvior This issue is fixed, please get latest binaries [here](https://github.com/Microsoft/msphpsql/releases/tag/v4.0.5-Linux) or use PECL to install SQLSRV drivers. Feel free to open the issue, if the issue persists.
