### ISSUE TITLE
error: conflicting declaration ‘typedef windowsULong_t DWORD’

### ISSUE THREAD

**Issue by guigui69** [microsoft/msphpsql#1131]
Hello,

debian version
```
@ srv-intranet: ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU / Linux 10 (buster)
Release: 10
Codename: buster
Linux srv-intranet 4.19.0-8-686-pae # 1 SMP Debian 4.19.98-1 (2020-01-26) i686 GNU / Linux
```

```
root @ srv-intranet: ~ # odbcinst -j
unixODBC 2.3.6
DRIVERS ............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES ..: / etc / ODBCDataSources
USER DATA SOURCES ..: /root/.odbc.ini
SQLULEN Size .......: 4
SQLLEN Size ........: 4
SQLSETPOSIROW Size .: 2
```

`Php version 7.3`

I am trying to install the OBBC drivers for my debian version

I block at this step "pecl install sqlsrv" I have this error

```
d / xplat_intsafe.h: 50: 29: error: conflicting declaration ‘typedef windowsULong_t DWORD’
     typedef windowsULong_t DWORD;
                                 ^ ~~~~
 /usr/include/sqltypes.h:96:24: note: previous declaration as ‘typedef long unsigned int DWORD’
     typedef unsigned long DWORD;
                            ^ ~~~~
    make: *** [Makefile: 194: conn.lo] Error 1
    ERROR: `make 'failed
```

On the internet it indicates that it can come from a value in the file /user/include/unixodbc_conf.h but I don't have this file in this location. This is present in "/usr/include/i386-linux-gnu/unixodbc_conf.h"
(Passage of the value from 4 to 8)

```
#ifndef SIZEOF_LONG_INT
define SIZEOF_LONG_INT 8
#endif
```

But it still doesn't work.

And the apt-get install command msodbcsql mssql-tools ==> the packets are not found

What mistake is this made?

sorry I do not speak English

**Comment by yitam** [comment]
Hi @guigui69 are you using Debian 10 32 bit? 

Try run `uname -m` in a terminal. It shows if your system is running 32-bit (i686 or i386) or 64-bit(x86_64).

We do not support any Linux system running 32 bit.

**Comment by guigui69** [comment]
root@srv-intranet:/opt# uname -m
i686

OK,

**Comment by yitam** [comment]
@guigui69 if you change to Debian 10 64 bit we would be happy to help.

**Comment by yitam** [comment]
Closing the issue. Please feel free to reopen if you have any other questions
