### ISSUE TITLE
Count error with named parameters

### ISSUE THREAD

**Issue by steftahiti** [microsoft/msphpsql#1134]
## PHP Driver version or file name
5.8.1
## SQL Server version
2016
## Client operating system
Windows 2016 server
## PHP version
7.3.17
## Microsoft ODBC Driver version
13
## Table schema
`create table table1 (field1 varchar(50), field2 varchar(50));`
 ## Problem description
 With PDO MySQL I use named parameters with complex SQL, it’s useful because I can set the same parameter several times. But with PDO sqlsrv I get this error:
`SQLSTATE[07002]: [Microsoft][ODBC Driver 13 for SQL Server]COUNT field incorrect or syntax error`
## Expected behavior and actual behavior
I expect that all parameters with the same name are replaced and the SQL is executed without error.
## Repro code or steps to reproduce
```
$data = [];
$data[':value'] = 'test';
$db = new PDO('sqlsrv:server=locahost;database=db1', '', '', [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
$stm = $db->prepare('INSERT INTO table1 (field1, field2) VALUES (:value, :value)');
$stm->execute($data);
```

**Comment by yitam** [comment]
@steftahiti related to #1096 

Just so you know, emulation mode is **ON** by default for pdo_mysql. It's the opposite for pdo_sqlsrv.

In [PDO::prepare](https://www.php.net/manual/en/pdo.prepare.php) it clearly indicates that 

> You must include a unique parameter marker for each value you wish to pass in to the statement when you call PDOStatement::execute(). You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on.

**Comment by steftahiti** [comment]
Thank you for the explanations.
It works fine when I activate the emulation mode.

**Comment by yitam** [comment]
@steftahiti glad to hear that, but just so you know, emulation mode does have its [limitations](https://docs.microsoft.com/sql/connect/php/pdo-prepare?view=sql-server-ver15#limitations).
