### ISSUE TITLE
Trying to install msodbcsql in Centos 7, got segmentation fault.

### ISSUE THREAD

**Issue by gremo** [microsoft/msphpsql#1138]
I'm trying to use the binaries for PHP 7.1 on my server, Centos 7 x64.

I successfully loaded non thread-safe `.so` modules, and configured PHP 7.1 to load them:

![screen1](https://user-images.githubusercontent.com/1532616/83354542-ae4e3800-a359-11ea-81d1-0f40fa9154b3.JPG)
![screen2](https://user-images.githubusercontent.com/1532616/83354544-af7f6500-a359-11ea-84e4-67b610662844.JPG)

However as soon as PHP hit the extension, I get the following error:

>  SQLSTATE[IMSSP]: This extension requires the Microsoft ODBC Driver for SQL Server to communicate with SQL Server. Access the following URL to downl
>   oad the ODBC Driver for SQL Server for x64: https://go.microsoft.com/fwlink/?LinkId=163712

So I run `yum install msodbcsql`... which ends up with a **segmentation fault**:

```
Do you accept the license terms? (Enter YES or NO)
yes
Please enter YES or NO
Do you accept the license terms? (Enter YES or NO)
yes
Please enter YES or NO
Do you accept the license terms? (Enter YES or NO)
yes
Please enter YES or NO
Do you accept the license terms? (Enter YES or NO)
YES
/var/tmp/rpm-tmp.kRGCaB: line 4:  1775 Segmentation fault      odbcinst -q -d -n "ODBC Driver $1 for SQL Server" &>/dev/null
/var/tmp/rpm-tmp.kRGCaB: line 4:  1776 Segmentation fault      odbcinst -q -d -n "ODBC Driver $1 for SQL Server" &>/dev/null
  Installing : msodbcsql-13.1.9.2-1.x86_64                                                                                               1/1
warning: %post(msodbcsql-13.1.9.2-1.x86_64) scriptlet failed, exit status 127
Non-fatal POSTIN scriptlet failure in rpm package msodbcsql-13.1.9.2-1.x86_64
  Verifying  : msodbcsql-13.1.9.2-1.x86_64                                                                                               1/1

Installed:
  msodbcsql.x86_64 0:13.1.9.2-1

Complete!
```

Any help is much appreciated. I really need to communicate with an (external) MSSQL database.

**Comment by yitam** [comment]
Hi @gremo please install ODBC 17 for CentOS by following [the instructions for Red Hat(https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#redhat17))
Hope this helps.

**Comment by gremo** [comment]
Sorry, I was pretty sure that I answered the issue by myself.

Anyways, the segmentation fault goes away updating unixODBC (which is required by Plesk, and cannot be installed).

So, for me, the following worked:

```bash
curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/mssql-release.repo
yum update unixODBC
ACCEPT_EULA=Y yum install -y msodbcsql
```

ODBC 13 works just fine, I cant connect, update, delete rows and so on. Thanks!

**Comment by yitam** [comment]
@gremo that's good. Just so you know, ODBC 17 has new features and fixed the bugs in ODBC 13. You're encouraged to upgrade, but your decision, of course.

**Comment by gremo** [comment]
Yep, sure, but msodbcsql is still version 13 for me (official mssql repository). Don't know how to update to version 17.

**Comment by yitam** [comment]
> Hi @gremo please install ODBC 17 for CentOS by following [the instructions for Red Hat](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#redhat17))
> Hope this helps.

My initial reply included the link to install ODBC 17. Yet, these two can coexist. Thus, when using php drivers, you can [specify which ODBC driver to use](https://github.com/microsoft/msphpsql/wiki/Features#driverConnOption). 

If not specified, ODBC 17 will be the default. 

Later, if you like, you can uninstall ODBC 13.
