### ISSUE TITLE
Integer value inside varchar field

### ISSUE THREAD

**Issue by sirio3mil** [Microsoft/msphpsql#114]
I have this query:

`UPDATE pedido SET numero_pedido = ? WHERE pedido_id = ?`

numero_pedido is a varchar(20) not null

When I execute this query with first param value 4010057612 as it, sqlsrv insert instead this value -284909684, I have to send strval(param) to set right value.

PHP Version 7.0.8
x64
Thread Safety disabled
Windows NT 10.0 build 14393 (Windows 10) AMD64

Driver version 4.0.8629.3
ODBC 13

**Comment by meet-bhagdev** [comment]
@sirio3mil Can you send us a repro script and schema. This will help us further debug this

**Comment by sirio3mil** [comment]
Ok I will try to reproduce

**Comment by meet-bhagdev** [comment]
@sirio3mil our latest releases on Windows and Linux have a fix for this issue. Can you help us validate? 
Linux: https://github.com/Microsoft/msphpsql/releases/tag/4.0.4-Linux
Windows: https://github.com/Microsoft/msphpsql/releases/tag/4.1.2-Windows

**Comment by sirio3mil** [comment]
Yes @meet-bhagdev, tested on windows and works.

PHP 7.0.10 x64 NTS
ODBC 13.1
Driver version 4.1.8909.1
