### ISSUE TITLE
error on PHP 7.4

### ISSUE THREAD

**Issue by crisleiria** [microsoft/msphpsql#1142]
## PHP Driver version or file name
 + sqlsrv  version 5.8.1
 + pdo_sqlsrv version 5.8.1
 ## SQL Server version
 + SQL Server 2008 R2 (10.50.6560.0)
 ## Client operating system
 + ubuntu 16..04
 ## PHP version
 + 7.4
  ## Microsoft ODBC Driver version
 + lastest (17.5.2.1-1)
  ## Table schema
 + not applicable
 ## Problem description
 + Ubuntu Server 16.04 with Apache and PHP 7.1 loaded thru FCGI is running without any issues and can connect to SQL Server (Several Laravel applications). 
 + We want to update this stack to PHP 7.4 and latest MSSQL driver. We have updated PHP already and MSSQL driver all to latest version. All with no issues.
 + Currently we are not able to connect to SQL server with PHP 7.4 (with cli and FCGI), only with PHP 7.1. 

We receive this warning on any PHP commands thru comand line:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20190902/pdo_sqlsrv.so (/usr/lib/php/20190902/pdo_sqlsrv.so: undefined symbol: _zend_hash_index_update), /usr/lib/php/20190902/pdo_sqlsrv.so.so (/usr/lib/php/20190902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20190902/sqlsrv.so (/usr/lib/php/20190902/sqlsrv.so: undefined symbol: _object_and_properties_init), /usr/lib/php/20190902/sqlsrv.so.so (/usr/lib/php/20190902/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20190902/pdo_sqlsrv.so (/usr/lib/php/20190902/pdo_sqlsrv.so: undefined symbol: _zend_hash_index_update), /usr/lib/php/20190902/pdo_sqlsrv.so.so (/usr/lib/php/20190902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

 + When I try to make a query with PHP 7.4 on cli I get this error:
` Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("could not find driver")
      /home/extranet/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("could not find driver")
      /home/extranet/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.

   Whoops\Exception\ErrorException  : PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20190902/sqlsrv.so (/usr/lib/php/20190902/sqlsrv.so: undefined symbol: _object_and_properties_init), /usr/lib/php/20190902/sqlsrv.so.so (/usr/lib/php/20190902/sqlsrv.so.so: cannot open shared object file: No such file or directory))

  at Unknown:0
    1|

  Exception trace:

  1   Whoops\Run::handleError()
      /home/extranet/vendor/filp/whoops/src/Whoops/Run.php:408

  2   Whoops\Run::handleShutdown()
      [internal]:0
`

+ This is related with PHP driver load on cli and fcgi for PHP 7.4, I understand this.. but I am not able to fix this.. I have followed this guide:
[https://medium.com/@nahomt/using-sql-server-from-your-php-apps-on-ubuntu-16-04-c85671249c45](https://medium.com/@nahomt/using-sql-server-from-your-php-apps-on-ubuntu-16-04-c85671249c45)

 ## Repro code or steps to reproduce
+ This is an multi PHP envirement. I have PHP 7.1, 7.2 and 7.4 installed on Ubuntu Server. PHP 7.1 no problems, I am able to switch PHP versions on cli with this comand:
`sudo update-alternatives --set php /usr/bin/php7.4`
+ PHP 7.1 no errors or warnings, all works fine with latest driver.

**Comment by yitam** [comment]
Hi @crisleiria , 

This is our [instructions to install sqlsrv and pdo_sqlsrv](https://docs.microsoft.com/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-ubuntu-1604-1804-and-1910). We keep this up-to-date for each stable release.

Have you checked `/usr/lib/php/20190902/` and see if `sqlsrv.so` or `pdo_sqlsrv.so` is there?

Before you did `pecl install` have you checked your php version? This [FAQ entry](https://github.com/microsoft/msphpsql/wiki/FAQ#recipe-for-target-failed) might give you an idea.

Under php 7.4, what's the output of `php --ini`?

**Comment by crisleiria** [comment]
Hi @yitam,

I already have uninstalled and installed again pdo_sqlsrv and sqlsrv driver and the files are always placed on `/usr/lib/php/20170718/` and not on `/usr/lib/php/20190902`
I also have tried to copy manually and sqlsrv.so and pdo_sqlsrv.so files to 2019 folder. No luck, warnings are diferent, but I am not able to connect.

I have checked your FAQ entry link.. I think I am getting somewhere...
Comand `php-config --phpapi` returns `20170718` and not `20190902` as expected. How can I change this?

php --ini output:
` PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20190902/pdo_sqlsrv.so (/usr/lib/php/20190902/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/pdo_sqlsrv.so.so (/usr/lib/php/20190902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20190902/sqlsrv.so (/usr/lib/php/20190902/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/sqlsrv.so.so (/usr/lib/php/20190902/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20190902/pdo_sqlsrv.so (/usr/lib/php/20190902/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/pdo_sqlsrv.so.so (/usr/lib/php/20190902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20190902/sqlsrv.so (/usr/lib/php/20190902/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/sqlsrv.so.so (/usr/lib/php/20190902/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Configuration File (php.ini) Path: /etc/php/7.4/cli
Loaded Configuration File:         /etc/php/7.4/cli/php.ini
Scan for additional .ini files in: /etc/php/7.4/cli/conf.d
Additional .ini files parsed:      /etc/php/7.4/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.4/cli/conf.d/10-opcache.ini,
/etc/php/7.4/cli/conf.d/10-pdo.ini,
/etc/php/7.4/cli/conf.d/15-xml.ini,
/etc/php/7.4/cli/conf.d/20-calendar.ini,
/etc/php/7.4/cli/conf.d/20-ctype.ini,
/etc/php/7.4/cli/conf.d/20-curl.ini,
/etc/php/7.4/cli/conf.d/20-dom.ini,
/etc/php/7.4/cli/conf.d/20-exif.ini,
/etc/php/7.4/cli/conf.d/20-ffi.ini,
/etc/php/7.4/cli/conf.d/20-fileinfo.ini,
/etc/php/7.4/cli/conf.d/20-ftp.ini,
/etc/php/7.4/cli/conf.d/20-gettext.ini,
/etc/php/7.4/cli/conf.d/20-iconv.ini,
/etc/php/7.4/cli/conf.d/20-imagick.ini,
/etc/php/7.4/cli/conf.d/20-json.ini,
/etc/php/7.4/cli/conf.d/20-mysqli.ini,
/etc/php/7.4/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.4/cli/conf.d/20-pdo_sqlsrv.ini,
/etc/php/7.4/cli/conf.d/20-phar.ini,
/etc/php/7.4/cli/conf.d/20-posix.ini,
/etc/php/7.4/cli/conf.d/20-readline.ini,
/etc/php/7.4/cli/conf.d/20-shmop.ini,
/etc/php/7.4/cli/conf.d/20-simplexml.ini,
/etc/php/7.4/cli/conf.d/20-sockets.ini,
/etc/php/7.4/cli/conf.d/20-sqlsrv.ini,
/etc/php/7.4/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.4/cli/conf.d/20-sysvsem.ini,
/etc/php/7.4/cli/conf.d/20-sysvshm.ini,
/etc/php/7.4/cli/conf.d/20-tokenizer.ini,
/etc/php/7.4/cli/conf.d/20-xmlreader.ini,
/etc/php/7.4/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.4/cli/conf.d/20-xsl.ini,
/etc/php/7.4/cli/conf.d/30-pdo_sqlsrv.ini,
/etc/php/7.4/cli/conf.d/30-sqlsrv.ini
`

pecl version output:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20190902/pdo_sqlsrv.so (/usr/lib/php/20190902/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/pdo_sqlsrv.so.so (/usr/lib/php/20190902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20190902/sqlsrv.so (/usr/lib/php/20190902/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/sqlsrv.so.so (/usr/lib/php/20190902/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20190902/pdo_sqlsrv.so (/usr/lib/php/20190902/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/pdo_sqlsrv.so.so (/usr/lib/php/20190902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20190902/sqlsrv.so (/usr/lib/php/20190902/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/sqlsrv.so.so (/usr/lib/php/20190902/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PEAR Version: 1.10.8
PHP Version: 7.4.7
Zend Engine Version: 3.4.0
Running on: Linux DEV-SERVER03 4.4.0-179-generic #209-Ubuntu SMP Fri Apr 24 17:48:44 UTC 2020 x86_64
`
Thank you for your help.

**Comment by yitam** [comment]
Hi @crisleiria 

The key is to run `update-alternatives`, as explained in [How to switch multiple php versions](https://tecadmin.net/switch-between-multiple-php-version-on-ubuntu/)

```
sudo update-alternatives --set php /usr/bin/php7.4
sudo update-alternatives --set phar /usr/bin/phar7.4
sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.4
sudo update-alternatives --set phpize /usr/bin/phpize7.4
sudo update-alternatives --set php-config /usr/bin/php-config7.4
```

Then do a `pecl install` again. Manually copying the sqlsrv.so and pdo_sqlsrv.so files to 2019 folder won't work because they were compiled against different PHP versions.

**Comment by crisleiria** [comment]
Hi @yitam ,

Ok, I was able to fix the problem regarding cli. I am able to connect thru comand line now. Thank you for your help. I follow Microsoft instructions, I believe it was connected to an old ppa:ondrej/php repository. It fix my problem.

I am still not able to connect thru Apache CGI on Laravel, but I will check later on. i will update this post with my findings.

Again thank you for your help, your links were very helpfull.

Best regards,
Cristovao Oliveira

**Comment by yitam** [comment]
Glad to be of help, @crisleiria 
Good luck and let us know if you have other questions about the sqlsrv drivers.

**Comment by crisleiria** [comment]
Hi @yitam ,

Just to let you know, all OK on cli and cgi. I have notice some changes on the driver behavior (my previous driver version was old).
Mainly on EXEC procedures comands:

`SQLSTATE[IMSSP]: The active result for the query contains no fields. (SQL: EXEC	[dbo].`

I saw others with the same result and changed from my side (I am using Laravel framework). 

Stackoverflow references [here](https://stackoverflow.com/questions/46909253/the-active-result-for-the-query-contains-no-fields-laravel/46910858) and [here](https://stackoverflow.com/questions/16735898/the-active-result-contains-no-fields-using-pdo-with-ms-sql).

Thank you for the help, I will close this issue.

Best regards,
Cristovao Oliveira
