### ISSUE TITLE
PDO & sqlsrv_connect connections take over 15s to fail

### ISSUE THREAD

**Issue by conandrum** [microsoft/msphpsql#1148]
**PDO example:**
```
$servername = "111.111.111.111,1433";
$dbname = "dbname"; $username = "username"; $password = "password";
$dsnString="sqlsrv:Server=$servername;Database=$dbname;";
try {
	$conn = new PDO( $dsnString , $username, $password);
	$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch(Exception $e) {
	echo 'Exception -> ';
	var_dump($e->getMessage());
}

```
**sqlsrv_connect example:**
```
<?php
$servername = "111.111.111.111,1433";
$dbname = "dbname"; $username = "username"; $password = "password";
$connectionString = array( "Database"=>"$dbname", "UID"=>"$username", "PWD"=>"$password");

$conn = sqlsrv_connect( $serverName, $connectionString);
if( !$conn ) {
	echo 'Exception -> ';
	die( print_r( sqlsrv_errors(), true));
}
?>
```

``
by contrast, MySQL connections to the same address fails within a second.
Why the big difference, and is there a way to make such failures return faster?
Thanks.

**Comment by yitam** [comment]
Hi @conandrum 

Please note that the default login timeout is set to 15 seconds, and you can set a shorter timeout if necessary. Yet, a login timeout of less than 10 seconds may not be reliable and/or accurate. For example, you can specifically set it to 1s, as shown in the examples below, but sometimes it might take take 2 seconds to fail. 

In sqlsrv, 
```
$conn = sqlsrv_connect($serverName , array("LoginTimeout" => 1));
```

In pdo_sqlsrv:
```
try {
    $conn = new PDO( "sqlsrv:server=$server ; LoginTimeout = 1", $uid, $pwd, array(PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION));
} catch (PDOException $e) {
    var_dump($e->getMessage());
}
```

Note that in pdo_sqlsrv, when the connection fails the PDO error mode is irrelevant. It fails with an exception regardless.

Setting the login timeout has to be done *before* connection, and for more information please read about the attribute SQL_ATTR_LOGIN_TIMEOUT in [ODBC reference](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function?view=sql-server-ver15).

Alternatively, you can [change the settings in SQL Server directly](https://docs.microsoft.com/sql/database-engine/configure-windows/configure-the-remote-login-timeout-server-configuration-option?view=sql-server-ver15).

**Comment by conandrum** [comment]
@yitam Excellent thank you.
