### ISSUE TITLE
Why is this closed? I need to connect to a remote SQL Server and am getting the same error. I cannot change anything on the server. Downgrading openssl is not really an option. Running Ubuntu 20.4.

### ISSUE THREAD

**Issue by RadBoris** [microsoft/msphpsql#1151]
Why is this closed? I need to connect to a remote SQL Server and am getting the same error. I cannot change anything on the server. Downgrading openssl is not really an option. Running Ubuntu 20.4.

_Originally posted by @RadBoris in https://github.com/microsoft/msphpsql/issues/252#issuecomment-655840815_

**Comment by yitam** [comment]
Hi @RadBoris please check the related issues #1110 and #1112

**Comment by yitam** [comment]
Any update, @RadBoris ?

**Comment by RadBoris** [comment]
Thanks for the reference @yitam! I used the official instructions but they did not work for me on a fresh install of Ubuntu 20.04. I downgraded my openssl version and used freetds to connect to the server. Will revisit when official support for Ubuntu 20.04 is announced.

**Comment by yitam** [comment]
Hi @RadBoris, glad that it works for you now, but it's the server and openssl versions, not ODBC driver. You either upgrade your server or downgrade the [security setting as a workaround](https://github.com/microsoft/msphpsql/issues/1112#issuecomment-609972220), which is not recommended, as already explained in the related issues.
