### ISSUE TITLE
WARNING: Module pdo-sqlsrv ini file doesn't exist under /etc/php/7.3/mods-available

### ISSUE THREAD

**Issue by hoaaah** [microsoft/msphpsql#1157]
## PHP Driver version or file name
 pdo_sqsrv.ini
 ## SQL Server version
 SQL Server 2017
 ## Client operating system
 Ubuntu 16.04
 ## PHP version
 PHP 7.3
 ## Microsoft ODBC Driver version
 msodbcsql17
 ## Problem description
 I follow this step and get stucked at [this step](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#step-3-install-the-php-drivers-for-microsoft-sql-server). It install sqlsrv but not pdo_sqlsrv.
Step 3 give me this error 
```bash
sudo phpenmod -v 7.3 sqlsrv pdo-sqlsrv

WARNING: Module pdo-sqlsrv ini file doesn't exist under /etc/php/7.3/mods-available
WARNING: Module pdo-sqlsrv ini file doesn't exist under /etc/php/7.3/mods-available
WARNING: Module pdo-sqlsrv ini file doesn't exist under /etc/php/7.3/mods-available
```
 ## Expected behavior and actual behavior
It supposed to install both sqlsrv and pdo_sqlsrv. But in reality it only install sqlsrv. Here are my php.ini
```
PHP Version => 7.3.19-1+ubuntu16.04.1+deb.sury.org+1

System => Linux ubuntu-sqlserver 4.15.0-1091-azure #101~16.04.1-Ubuntu SMP Fri Jun 26 01:14:12 UTC 2020 x86_64
Build Date => Jun 12 2020 07:48:10
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc/php/7.3/cli
Loaded Configuration File => /etc/php/7.3/cli/php.ini
Scan this dir for additional .ini files => /etc/php/7.3/cli/conf.d
Additional .ini files parsed => /etc/php/7.3/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.3/cli/conf.d/10-opcache.ini,
/etc/php/7.3/cli/conf.d/10-pdo.ini,
/etc/php/7.3/cli/conf.d/15-xml.ini,
/etc/php/7.3/cli/conf.d/20-calendar.ini,
/etc/php/7.3/cli/conf.d/20-ctype.ini,
/etc/php/7.3/cli/conf.d/20-curl.ini,
/etc/php/7.3/cli/conf.d/20-dom.ini,
/etc/php/7.3/cli/conf.d/20-exif.ini,
/etc/php/7.3/cli/conf.d/20-fileinfo.ini,
/etc/php/7.3/cli/conf.d/20-ftp.ini,
/etc/php/7.3/cli/conf.d/20-gd.ini,
/etc/php/7.3/cli/conf.d/20-gettext.ini,
/etc/php/7.3/cli/conf.d/20-iconv.ini,
/etc/php/7.3/cli/conf.d/20-imagick.ini,
/etc/php/7.3/cli/conf.d/20-intl.ini,
/etc/php/7.3/cli/conf.d/20-json.ini,
/etc/php/7.3/cli/conf.d/20-mbstring.ini,
/etc/php/7.3/cli/conf.d/20-mysqli.ini,
/etc/php/7.3/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.3/cli/conf.d/20-phar.ini,
/etc/php/7.3/cli/conf.d/20-posix.ini,
/etc/php/7.3/cli/conf.d/20-readline.ini,
/etc/php/7.3/cli/conf.d/20-recode.ini,
/etc/php/7.3/cli/conf.d/20-shmop.ini,
/etc/php/7.3/cli/conf.d/20-simplexml.ini,
/etc/php/7.3/cli/conf.d/20-sockets.ini,
/etc/php/7.3/cli/conf.d/20-sqlsrv.ini,
/etc/php/7.3/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.3/cli/conf.d/20-sysvsem.ini,
/etc/php/7.3/cli/conf.d/20-sysvshm.ini,
/etc/php/7.3/cli/conf.d/20-tidy.ini,
/etc/php/7.3/cli/conf.d/20-tokenizer.ini,
/etc/php/7.3/cli/conf.d/20-wddx.ini,
/etc/php/7.3/cli/conf.d/20-xmlreader.ini,
/etc/php/7.3/cli/conf.d/20-xmlrpc.ini,
/etc/php/7.3/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.3/cli/conf.d/20-xsl.ini,
/etc/php/7.3/cli/conf.d/20-zip.ini
```

 ## Repro code or steps to reproduce
I installed SQL Server and it can run smoothly,
After install SQL server, I follow all the step and stop at [Step 3](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#step-3-install-the-php-drivers-for-microsoft-sql-server)

**Comment by yitam** [comment]
hi @hoaaah I suppose you did `sudo pecl install pdo_sqlsrv` too? Did you get any errors?

If no errors, you should be able to find both `sqlsrv.so` and `pdo_sqlsrv.so` in `/usr/lib/php/20180731/`

Make sure you do the following steps before calling `phpenmod`
```
sudo su
printf "; priority=20\nextension=sqlsrv.so\n" > /etc/php/7.3/mods-available/sqlsrv.ini
printf "; priority=30\nextension=pdo_sqlsrv.so\n" > /etc/php/7.3/mods-available/pdo_sqlsrv.ini
exit
```

**Comment by hoaaah** [comment]
Thanks @yitam .
I already follow that step, and I can find pdo_sqlsrv.ini at mods-availale directory. But I don't know why phpenmod give this error.

**Comment by yitam** [comment]
From your description, the error was `WARNING: Module pdo-sqlsrv ini file doesn't exist under /etc/php/7.3/mods-available`

Hi @hoaaah please use underscore, not hyphen, for `pdo_sqlsrv`, so please do `sudo phpenmod -v 7.3 sqlsrv pdo_sqlsrv`

**Comment by hoaaah** [comment]
My bad. Sorry to bother you @yitam

**Comment by waliullah2022** [comment]
after run this: phpenmod mbstring       
i get this error:                                                                                                    1 ⨯ 1 ⚙
WARNING: Module mbstring ini file doesn't exist under /etc/php/8.1/mods-available

**Comment by mialdi98** [comment]
@waliullah2022 
> after run this: phpenmod mbstring i get this error: 1 ⨯ 1 ⚙ WARNING: Module mbstring ini file doesn't exist under /etc/php/8.1/mods-available

you need to use a specific version when doing 

```
              #!/bin/bash
              sudo apt-get update
              sudo apt-get install -y apache2 php8.1 php8.1-dom php8.1-gd php8.1-xml php8.1-mbstring libapache2-mod-php8.1 unzip
```
