### ISSUE TITLE
php_sqlsrv and php_odbc where can be download??

### ISSUE THREAD

**Issue by shuqiangzhou** [microsoft/msphpsql#1159]
Where can I download pre-compiled php sqlsrv and php_odbc?? None of your documentation links are useful!php5.3+-php7+ v ersion

**Comment by yitam** [comment]
@shuqiangzhou did you mean sqlsrv and pdo_sqlsrv? The pre-compiled versions can be found in [download center](https://docs.microsoft.com/sql/connect/php/download-drivers-php-sql-server?view=sql-server-ver15) or the [releases](https://github.com/microsoft/msphpsql/releases) page.

**Comment by yitam** [comment]
Any update @shuqiangzhou ? Did you find what you wanted?

**Comment by shuqiangzhou** [comment]
Sorry, I forgot about this. I have found the related driver in Microsoft sql server for php. I thought the driver should be a tar, but I didn’t expect it to be packaged into an installer. Thank you very much.
