### ISSUE TITLE
Integer type confusion regarding bound in/out parameters

### ISSUE THREAD

**Issue by cmb69** [microsoft/msphpsql#1164]
## PHP Driver version or file name

pdo_sqlsrv 5.8.1

## SQL Server version

Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Express Edition

## Client operating system

Microsoft Windows [Version 10.0.18362.959]

## PHP version

PHP 7.3

## Microsoft ODBC Driver version

2017.175.01.01
 
## Table schema

no tables; just a single stored procedure:

````
CREATE PROCEDURE sp_Test
    @ErrorNumber INT = 0 OUTPUT
AS
BEGIN
    SET @ErrorNumber = -1
    SELECT 1,2,3
END
````

## Problem description

If a bound in/out parameter is assigned a negative value in a stored procedure, it has a large positive value on 64bit architectures.

## Repro code or steps to reproduce
 
* create the stored producedure as described above
* run the following PHP script (use appropriate values for the constructor parameters):
````.php
<?php
$pdo = new PDO($dsn, $user, $pass);
$stmt = $pdo->prepare('{CALL sp_Test(?)}');
$out = 0;
var_dump($stmt->bindParam(1, $out, PDO::PARAM_INT | PDO::PARAM_INPUT_OUTPUT, 255));
$stmt->execute();
$stmt->fetchAll(PDO::FETCH_NUM);
var_dump($out);
?>
````

## Expected behavior

int(-1)

## Actual behavior

int(4294967295)

## Analysis

[`default_c_type()`](https://github.com/microsoft/msphpsql/blob/5f76f838e5d44ca951a44bec6be1af05fae4bd93/source/shared/core_stmt.cpp#L2049) does not properly get the desired C type for `IS_LONG`s. These refer to `zend_long` (PHP 7) and `long` (PHP 5), respectively. `zend_long` is usually a 64bit type on 64bit architectures, and a 32bit type on 32bit architectures. The code is, however, checking for the actual value of the given `param_z`, what cannot work for out parameters.

Consider to apply the following patch (PHP 7 only, though):
````.diff
 source/shared/core_stmt.cpp | 12 +++++-------
 1 file changed, 5 insertions(+), 7 deletions(-)

diff --git a/source/shared/core_stmt.cpp b/source/shared/core_stmt.cpp
index 9cac96a..ee82a21 100644
--- a/source/shared/core_stmt.cpp
+++ b/source/shared/core_stmt.cpp
@@ -1951,13 +1951,11 @@ SQLSMALLINT default_c_type( _Inout_ sqlsrv_stmt* stmt, _In_opt_ SQLULEN paramno,
             sql_c_type = SQL_C_SLONG;
             break;
         case IS_LONG:
-            //ODBC 64-bit long and integer type are 4 byte values.
-            if ((Z_LVAL_P(param_z) < INT_MIN) || (Z_LVAL_P(param_z) > INT_MAX)) {
-                sql_c_type = SQL_C_SBIGINT;
-            }
-            else {
-                sql_c_type = SQL_C_SLONG;
-            }
+#if SIZEOF_ZEND_LONG == 8 
+            sql_c_type = SQL_C_SBIGINT;
+#else
+            sql_c_type = SQL_C_SLONG;
+#endif
             break;
         case IS_DOUBLE:
             sql_c_type = SQL_C_DOUBLE;
````

**Comment by yitam** [comment]
Thanks @cmb69 and we recently made a similar change in PR [1144](https://github.com/microsoft/msphpsql/pull/1144)
If necessary, we can change to use `SIZEOF_ZEND_LONG` instead.

**Comment by cmb69** [comment]
Ah, I didn't find that PR. Using `ZEND_ENABLE_ZVAL_LONG64` should be fine as well. :)
