### ISSUE TITLE
WITH NOWAIT query hint breaks PDO error handling/bubbling up of SQL errors

### ISSUE THREAD

**Issue by RogerRWang** [microsoft/msphpsql#1182]
## PHP Driver version or file name
pdo_sqlsrv 5.3.0

## SQL Server version
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) Aug 22 2017 17:04:49 Copyright (C) 2017 Microsoft Corporation Express Edition (64-bit) on Windows 10 Enterprise 10.0 (Build 16299: ) (Hypervisor)

## Client operating system
Windows 10 Enterprise 1709

## PHP version
PHP 7.4.3 (cli) (built: Feb 27 2020 15:30:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

## Microsoft ODBC Driver version
10.0.16299.15

## Table schema
Tables are irrelevant. But the below stored procedure is used to demonstrate the issue:
```
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Roger Wang
-- Create date: 2020/08/24
-- Description:	Simple sproc that has 2 RAISERROR messages, one of which uses WITH NOWAIT
-- =============================================
CREATE OR ALTER PROCEDURE sp_ThisBreaksPDO 
AS
BEGIN

RAISERROR('Some other message', 0, 1) WITH NOWAIT; -- Comment this out to see expected behavior

RAISERROR('A bad thing has occurred!', 11, 1);

END
GO
```
## Problem description
WITH NOWAIT query hint breaks PDO error handling/bubbling up of SQL errors. Specifically, when using RAISERROR with a severity of 11 or higher, if a preceding WITH NOWAIT hint was used, the RAISERROR is not correctly bubbled up as a PDO exception.

## Expected behavior and actual behavior
Expected: A PDOException is thrown with the message of the RAISERROR.
Actual: No exception is thrown and an empty result set is returned.

## Repro code or steps to reproduce
 Fill in the PDO constructor with the DSN/credentials needed to work with the database:
```
// Create your PDO object
$pdo = new PDO($connectionString, $username, $password, $driverOptions);    

// Prepare statement to execute stored procedure
$statement = $pdo->prepare('EXEC sp_ThisBreaksPDO;');

// When the sproc uses a WITH NOWAIT, we fail to catch the subsequent
// RAISERROR, but when it is commented out, we can catch it as expected.
try {
  $statement->execute();
} catch (\Exception $e) {
  $error = $e->getMessage();
}

echo $error ? 'Successfully caught exception' : 'Failed to catch exception';
```

**Comment by yitam** [comment]
Thanks @RogerRWang we will investigate and get back to you on this

**Comment by yitam** [comment]
Hi @RogerRWang, after some investigation, the key is to invoke `$statement->nextRowset();` after processing an informational message, so please consider modifying your script as follows;

```
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

// Prepare statement to execute stored procedure
$statement = $pdo->prepare('EXEC sp_ThisBreaksPDO;');

// When the sproc uses a WITH NOWAIT, we fail to catch the subsequent
// RAISERROR, but when it is commented out, we can catch it as expected.
$statement->execute();
var_dump($statement->errorInfo());

try {
  $statement->nextRowset();
} catch (\Exception $e) {
  $error = $e->getMessage();
}

var_dump($statement->errorInfo());
echo $error ? 'Successfully caught exception' : 'Failed to catch exception';
```

I just tested the above and got this output. Hope this helps.

```
array(3) {
  [0]=>
  string(5) "01000"
  [1]=>
  int(50000)
  [2]=>
  string(72) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Some other message"
}
array(3) {
  [0]=>
  string(5) "42000"
  [1]=>
  int(50000)
  [2]=>
  string(79) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A bad thing has occurred!"
}
Successfully caught exception
```

**Comment by RogerRWang** [comment]
Hi @yitam! Thanks for looking into it.
I just tried this myself, and it does seem to allow the PDOException to get emitted now.

However, if we make the example slightly more complex by adding something like a SELECT after the sproc execution and try to fetch the result:
```
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

// Prepare statement to execute stored procedure
$statement = $pdo->prepare(
'
EXEC sp_ThisBreaksPDO;
SELECT \'Success\'
'
);

// When the sproc uses a WITH NOWAIT, we fail to catch the subsequent
// RAISERROR, but when it is commented out, we can catch it as expected.
$statement->execute();
var_dump($statement->errorInfo());

try {
  $statement->nextRowset();
} catch (\Exception $e) {
  $error = $e->getMessage();
}

// Try to retrieve some info as if there are no errors
$result = $statement->fetchColumn();

var_dump($statement->errorInfo());
echo $error ? 'Successfully caught exception' : 'Failed to catch exception';
```
and then update the sp_ThisBreaksPDO so that it does not use RAISERROR anywhere:
```
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Roger Wang
-- Create date: 2020/08/24
-- Description:	Edited to just do nothing and return
-- =============================================
CREATE OR ALTER PROCEDURE sp_ThisBreaksPDO 
AS
BEGIN
RETURN;
END
GO
```

Now, the nextRowset makes the fetchColumn call return false, since presumably the result is incremented past with the nextRowset call.

All this is to say that it seems strange that we would need to use nextRowset() to allow for a RAISERROR of severity > 10 to get bubbled up as a PDOException. Maybe I am missing something/have a bad understanding of how RAISERROR is thought of from the driver perspective though.
(Maybe consider the case that RAISERROR is raised conditionally in the stored procedure, then how can the application code know to use nextRowset or not?)

**Comment by yitam** [comment]
Hi @RogerRWang 

I think you have misunderstood what [nextRowset](https://docs.microsoft.com/sql/connect/php/pdostatement-nextrowset?view=sql-server-ver15) does. It simply moves the cursor to the next result set.

When executing your original stored procedure, you process an informational message before the serious error. Hence, after the first message you should call `nextRowset` to move on, in which case a serious error occurred and that's why you would have caught an exception.

In your modified php script, after calling the stored procedure, you have yet another result set (SELECT 'SUCCESS'), so once again you should have invoked `nextRowset`. However, because the second error was serious, the entire statement execution fails.

For example, try adding the following block to your slightly changed PHP script right after the exception:

```
...
var_dump($statement->errorInfo());
echo $error ? 'Successfully caught exception' : 'Failed to catch exception';
echo PHP_EOL;

$return = $statement->nextRowset();
var_dump($return);

// Try to retrieve some info as if there are no errors
$result = $statement->fetchColumn();
var_dump($result);
```

Both `$return` and `$result` should be false. 

To illustrate my point, alter your original stored procedure by changing the second `RAISEERROR` to a severity below 11, turning it into another informational message. In this case, there is no exception. Thus, change your PHP script again, like this:

```
$statement->execute();
var_dump($statement->errorInfo());

$return = $statement->nextRowset();
var_dump($statement->errorInfo());

$return = $statement->nextRowset();
var_dump($return);

$result = $statement->fetchColumn();
var_dump($result);
```

The new output should be:
```
array(3) {
  [0]=>
  string(5) "01000"
  [1]=>
  int(50000)
  [2]=>
  string(72) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Some other message"
}
array(3) {
  [0]=>
  string(5) "01000"
  [1]=>
  int(50000)
  [2]=>
  string(79) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A bad thing has occurred!"
}
bool(true)
string(7) "Success"
```

**Comment by yitam** [comment]
FYI, my [reply to this issue](https://github.com/microsoft/msphpsql/issues/932#issuecomment-469500716) might help you understand how to process informational messages (calling sqlsrv's equivalent of nextRowset)

**Comment by RogerRWang** [comment]
Thanks for the explanation @yitam!

So please correct me if I'm misunderstanding.
Serious errors are actually stored per-result set, so we shouldn't expect PDOExceptions to be raised unless the statement cursor is on the correct result set.
In order to account for this, we should be iterating over all result sets (until there are no more) rather than just blindly fetching results/assuming we are on the correct result set (below is the piece in your other response you referenced that made me come to this conclusion).
```
while ($next_result = sqlsrv_next_result($stmt)) {
        print_r(sqlsrv_errors());
    }
```
?

**Comment by yitam** [comment]
Yes @RogerRWang something along this line. However, as you said, it really depends on how complex your stored procedure is and/or how much you know about the stored procedure. If you write your own stored procedures you should know what to expect and catch exceptions when necessary. Does this make sense?

**Comment by RogerRWang** [comment]
Yea I believe so! Thank you so much for explaining.

**Comment by yitam** [comment]
Sounds good. If it's alright with you, I will close this issue unless you have more questions?

**Comment by RogerRWang** [comment]
Yes that is fine. Thank you!

**Comment by yitam** [comment]
You're welcome. Please feel free to reopen this issue if you have any other question.
