### ISSUE TITLE
How to install msphpsql extension in CentOS 7

### ISSUE THREAD

**Issue by chengaopan** [microsoft/msphpsql#1188]
Where can I see the centos7 installation tutorial

**Comment by yitam** [comment]
hi @chengaopan you can follow the installation [instructions for Red Hat](https://docs.microsoft.com/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-red-hat-7-and-8)

Just omit the line that begins with `subscription-manager...`

**Comment by yitam** [comment]
Any update @chengaopan ? I'm closing this issue now please feel free to reopen if necessary.
