### ISSUE TITLE
Does this driver support calling stored procedure from a PHP Azure Web App?

### ISSUE THREAD

**Issue by Calvin-Yuhui-Liu** [microsoft/msphpsql#1202]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 + 5.8.1
 +## SQL Server version
 + Azure SQL Server
 +## Client operating system
 + Linux f4465053639e 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 GNU/Linux
 +## PHP version
 + PHP 7.3.21 (cli) (built: Aug 26 2020 04:41:39) ( NTS )
 +## Microsoft ODBC Driver version
 +
 +## Table schema
 +
 +## Problem description
 + I can use sqlsrv_query to query a simple "select" SQL, but not to "EXEC a_stored_procedure". And print_r(sqlsrv_errors()) didn't output anything.
 +## Expected behavior and actual behavior
 + Calling a stored procedure from PHP code
 +## Repro code or steps to reproduce
 N/A

**Comment by yitam** [comment]
Hi @Calvin-Yuhui-Liu , assuming you have permissions on executing this stored procedure, have you tried running another stored procedure?

If not, please try creating a simple one like this:

```
CREATE PROCEDURE mySelect
AS
SELECT * FROM aTable
GO;
```

Then run this using sqlsrv_query: `EXEC mySelect`
What's the returned value of [sqlsrv_query](https://docs.microsoft.com/sql/connect/php/sqlsrv-query?view=sql-server-ver15)?

You might want to debug your stored procedure and this [discussion](https://stackoverflow.com/questions/15412804/how-to-debug-stored-procedures-with-print-statements) might give you some ideas

**Comment by Calvin-Yuhui-Liu** [comment]
Hi Jenny,
Yes you're right. This application connects to the DB with another user so no permission to exec that stored procedure. It's solved now. Thanks.

**Comment by yitam** [comment]
Glad to be of help. Please feel free to reopen this issue if necessary.
