### ISSUE TITLE
ERROR: `phpize' failed

### ISSUE THREAD

**Issue by fernandohernandezpaz** [microsoft/msphpsql#1208]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 sqlsrv

 +## SQL Server version
Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64) 
	Sep 23 2020 16:03:08 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Linux Mint 20) <X64>
 +## Client operating system
 Linux Mint 20
 +## PHP version
 PHP 7.4.11 (cli) (built: Oct 17 2020 07:30:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

 +## Microsoft ODBC Driver version
 msodbcsql17

 +## Problem description
 pecl install sqlsrv pdo_sqlsrv  
downloading sqlsrv-5.8.1.tgz ...
Starting to download sqlsrv-5.8.1.tgz (186,879 bytes)
........................................done: 186,879 bytes
downloading pdo_sqlsrv-5.8.1.tgz ...
Starting to download pdo_sqlsrv-5.8.1.tgz (181,286 bytes)
...done: 181,286 bytes
34 source files, building
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
configure.ac:161: warning: LTOPTIONS_VERSION is m4_require'd but not m4_defun'd
build/libtool.m4:61: LT_INIT is expanded from...
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: LTSUGAR_VERSION is m4_require'd but not m4_defun'd
build/libtool.m4:61: LT_INIT is expanded from...
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: LTVERSION_VERSION is m4_require'd but not m4_defun'd
build/libtool.m4:61: LT_INIT is expanded from...
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: LTOBSOLETE_VERSION is m4_require'd but not m4_defun'd
build/libtool.m4:61: LT_INIT is expanded from...
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure:4877: error: possibly undefined macro: m4_ifval
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:8483: error: possibly undefined macro: _LT_SET_OPTIONS
configure:8483: error: possibly undefined macro: LT_INIT
ERROR: `phpize' failed

**Comment by yitam** [comment]
Thanks @fernandohernandezpaz we are aware of this and will get back to you on this.

**Comment by yitam** [comment]
@fernandohernandezpaz it seems the [issues have been resolved](https://stackoverflow.com/questions/64402604/php-7-4-install-imagick-fails-looking-for-undefined-macro) in the latest php7.4-dev package, please apt-get update and apt-get install php7.4-dev (at least). Just confirmed in our test lab as well.

**Comment by yitam** [comment]
Any update @fernandohernandezpaz ?

**Comment by fernandohernandezpaz** [comment]
I'm sorry for the delay, mmm i installed the package previously and the problema persiste. I read that issue but it not was helpfullness :(

**Comment by yitam** [comment]
Did you do `apt-get update` and `apt-get install php7.4-dev`? 

You might need to `apt-get purge php7.4-dev`

**Comment by fernandohernandezpaz** [comment]
i will try apt-get purge `php7.4-dev` and then i will comment you.
