### ISSUE TITLE
Blank localhost/testsql.php file

### ISSUE THREAD

**Issue by RickPerez10** [microsoft/msphpsql#1212]
PHP 7.4.11
pdo_sqlsrv 5.8.1
sqlsrv 5.8.1
Ubuntu 20.04.1 LTS

Issue is I'm having a constant blank php file when I look at it from the browser.
Followed and installed curl, pdo_sqlsrv, sqlsrv, php, loaded drivers at php.ini, verified with phpinfo.php, verified php works with a simple php hello world file, verified php installed with php -v, yet when i run the sample script thats at the bottom of the page, and after i input the sql info, i always come up with a blank page. 

Expected to see anything, even an error to be displayed while going to testsql.php

To reproduce error follow guide:
https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-ubuntu-1604-1804-and-2004

See also previous ticket:
https://github.com/MicrosoftDocs/sql-docs/issues/5639

Please assist thank you.

**Comment by yitam** [comment]
Assuming you're using Apache, @RickPerez10 , have you tried a simple phpinfo.php and view it under localhost? Are the drivers loaded? 
Have you tried the same test using php in command line (not with Apache)?
What is the version of your SQL Server?

**Comment by yitam** [comment]
hi @RickPerez10 , I checked your previous ticket [MicrosoftDocs/sql-docs#5639](https://github.com/MicrosoftDocs/sql-docs/issues/5639) and believed you made a typo in the following while loop. You had `4row` instead of `$row`. 

```
while ($row = sqlsrv_fetch_array($stmt, SQLSRV_FETCH_ASSOC)) {
    echo $row['SQL_VERSION'] . PHP_EOL;
}
```

If this does not solve the problem, try running your testsql.php in a terminal and add the following block right after the above while loop:

```
if (empty($row)) {
   print_r(sqlsrv_errors());
}
```

**Comment by yitam** [comment]
Hi @RickPerez10 , I could reproduce the blank screen if I made the same typo in the php script. If running in a terminal, you would have seen an error like this: `PHP Parse error:  syntax error, unexpected 'row' (T_STRING) in /home/jennyt/testsql.php on line 30`

When running from Apache, the error log can be found in `/var/log/apache2`, like this:

![image](https://user-images.githubusercontent.com/21340756/98409367-8ad59a80-2027-11eb-80a5-733d850c0631.png)

We will update the documentation to add the location of Apache log files for troubleshooting. 

I believe this issue has been resolved. Please feel free to reopen the issue if necessary.

**Comment by RickPerez10** [comment]
Hi @yitam , Thanks for catching that typo, I fixed the mentioned error but I am still having a blank page on the browser while calling that testsql.php file, and yes I am running on apache.
I've yet to try running the file from the terminal so I will give that a try and get back to you.

**Comment by yitam** [comment]
Thanks @RickPerez10 . Please restart apache after making the change to your php script. 
Feel free to reopen this if you still have issues.

**Comment by RickPerez10** [comment]
@yitam  There were several errors with the script on my end, here's what I did and for records:

Find and fixed all syntax errors line per line on script by running **php -f testsql.php** , the test ran and spat out the results without issues. Thank you for your assistance everyone.

**Comment by yitam** [comment]
Nice, @RickPerez10. FYI, to reduce the chance of typos or errors you might want to copy the sample script and only modify the credentials for quick testing. Anyway, glad to be of help!
