### ISSUE TITLE
what error?

### ISSUE THREAD

**Issue by wrskook** [microsoft/msphpsql#1214]
php.ini
----------------
extension=php_pdo_sqlsrv_74_nts_x64.dll
extension=php_pdo_sqlsrv_74_ts_x64.dll
extension=php_sqlsrv_74_nts_x64.dll
extension=php_sqlsrv_74_ts_x64.dll

xampp start ->display php7.dll lose error

**Comment by yitam** [comment]
@wrskook I don't understand what you're asking. Please fill in the blanks of the new issue template.

**Comment by yitam** [comment]
Any update @wrskook ?

**Comment by yitam** [comment]
Closing this issue due to insufficient details.
