### ISSUE TITLE
Please use "alpha" instead of "preview"

### ISSUE THREAD

**Issue by remicollet** [microsoft/msphpsql#1222]
Can you please avoid to use "**preview**" for future devel version ?

Instead, use **alpha / beta / rc** which are  the commonly used names

Pros:
*` alpha < beta < rc`  (alphabetical order)

while `preview > beta`, which create nightmare for downstream package versioning
(having to update from **5.9.0~preview1** to **5.9.0~zbeta2**)

**Comment by remicollet** [comment]
Notice, with PHP projects
Upstream: dev < alpha < beta < RC (using version_compare)
downstream: DEV < alpha <  beta < rc (using case sensitive sort)

**Comment by yitam** [comment]
HI @remicollet 

Starting with this release we will avoid using "preview" for devel version. We switched to beta this time primarily because of #1210 , but regrettably it still did not work out.

**Comment by yitam** [comment]
Do you have any other question, @remicollet ? If not I'm going to close this issue.

**Comment by yitam** [comment]
Closing this issue now, @remicollet . From now on we will use either `beta` or `RC` for our previews.
