### ISSUE TITLE
Install OK with Big Sur but "Unknown processor architecture"

### ISSUE THREAD

**Issue by docteuri** [microsoft/msphpsql#1223]
Dear team,

After a success installation on Big Sur with Apple Silicon, I've got a "Unknown processor architecture" error.

Please could you add Silicon processor, I can help if needed.
The point is here : 
https://github.com/microsoft/msphpsql/blob/e7e7a8d636aaec7bf2cb922fe990e8fcf86b6abc/source/shared/core_conn.cpp

But I do not know the value to add.

Thanks a lot

Edouard

**Comment by docteuri** [comment]
I think you should add arm64 at line 52 ?

`const char* PROCESSOR_ARCH[] = { "x86", "x64", "ia64", "arm64" };`

**Comment by yitam** [comment]
Hi @docteuri , you're probably right. We can make changes to the PHP drivers now, or you're welcome to create a PR (please merge to our `dev` branch). 

That being said, even though we get PHP drivers working, ODBC driver does not officially support this new architecture yet. The good news is that it's in our plan to support it in the near future.

**Comment by docteuri** [comment]
Thanks a lot, you can add it it will be quicker.
I will test the next beat release to see if it works or not.
I do not know how to test with our pecl.
Thanks a lot
Edouard

**Comment by yitam** [comment]
Hi @docteuri , I forgot to mention that the function `get_processor_arch()` is called mainly because the driver is going to return an error message about ODBC driver not installed.

**Comment by docteuri** [comment]
I think the driver is ready

http://www.odbcmanager.net/about.php

Thanks a lot

Edouard

**Comment by yitam** [comment]
I mean [Microsoft ODBC Driver for SQL Server](https://docs.microsoft.com/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15), @docteuri

**Comment by yitam** [comment]
Closing this issue as per [5.10.0-beta1](
https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta1)
