### ISSUE TITLE
./sites/default/settings.php file you have configured Drupal to use a sqlsrv server, however your PHP installation currently does not support this database type.

### ISSUE THREAD

**Issue by oletubogs** [microsoft/msphpsql#1234]
DATABASE SETTINGS
Resolve all issues below to continue the installation. For help configuring your database server, see the installation handbook, or contact your hosting provider.
In your ./sites/default/settings.php file you have configured Drupal to use a sqlsrv server, however your PHP installation currently does not support this database type.

**Comment by yitam** [comment]
hi @oletubogs , what are your questions? Have you contacted Drupal support?

**Comment by yitam** [comment]
Do you have any question, @oletubogs ? If not we will close this issue
