### ISSUE TITLE
msodbcsql17 unattended-upgrades possible?

### ISSUE THREAD

**Issue by conandrum** [microsoft/msphpsql#1235]
Hi 

I have msodbcsql17 on Ubuntu 18.04.
Is it possible to get msodbcsql17 to be upgraded through  unattended-upgrades?
If so, what should I enter in /etc/apt/apt.conf.d/60unattended-upgrades ?
Will the EULA be bypassed in this situation?

e.g.
Unattended-Upgrade::Allowed-Origins {
   ????
};

Thanks

**Comment by yitam** [comment]
Hi @conandrum, this should work by setting `ACCEPT_EULA=Y` using the debconf variable, as explained in [the installation instructions](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#ubuntu17) 

Hope this helps!

**Comment by conandrum** [comment]
Excellent thanks Yitam!

**Comment by yitam** [comment]
Do you have any other question, @conandrum ? If not we will close this issue.
