### ISSUE TITLE
Problem with Named Parameters

### ISSUE THREAD

**Issue by temp** [microsoft/msphpsql#1237]
+## PHP Driver version or file name
pdo_sqlsrv 5.9.0

 +## SQL Server version
12.0.557

 +## Client operating system
Alpine Linux

 +## PHP version
 7.4.15

 +## Microsoft ODBC Driver version
msodbcsql 17_17.7.1.1-1_amd64
 +## Table schema
 ?

 +## Problem description
 We experience a wild performance issue when we use named parameters. Without a named parameter, the query is executed at once (something like 100 ms over a vpn). With a named parameter, the same query takes 5000 ms (50x more).

 +## Expected behavior and actual behavior
Nearly same performance for both variants.
 +## Repro code or steps to reproduce
 
```php
$stmt = $pdo->prepare("SELECT username FROM Users WHERE username = 'foo'");
$stmt->execute();
print_r($stmt->fetchAll(\PDO::FETCH_ASSOC));
// 100 ms
```
versus
```php
$stmt = $pdo->prepare("SELECT username FROM Users WHERE username = :username");
$stmt->bindValue(':username', $username);
$stmt->execute();
print_r($stmt->fetchAll(\PDO::FETCH_ASSOC));
// 5000ms
```

**Comment by yitam** [comment]
Thanks @temp for reporting this. Can you try a quick test while we are investigating? 
Modify your second script like this:

```
$username = 'foo';
$stmt = $pdo->prepare("SELECT username FROM Users WHERE username = ?");
$stmt->bindValue(1, $username);
$stmt->execute();
print_r($stmt->fetchAll(\PDO::FETCH_ASSOC));
```

Also, how many rows are there in the Users table where username is 'foo'?

**Comment by temp** [comment]
Hi @yitam, thanks for the quick response.
Sorry, forgot to mention - I also tried the simple parameter version (what's the right term for it?), but with the same result - as slow as the named parameter version.
The Users Table has something like 13.000.000 entries. And it has an index on the username column.
(it's not really a Users-table and a username-column, this is a 1:1 example, the column is a varchar-column, I don't think that the client would like to read his table names here). But the query I tried was as simple as that, select one column with a where-clause that matches one column.

**Comment by yitam** [comment]
Hi @temp, yes it's totally fine using Users or username as examples to explain the problem. Now that you mentioned a varchar column, I remember a related issue #1018, where the user pointed out SQL may not have used the index effectively when searching because the parameter value is bound as `N'...'`

Please check [my reply] to the issue (https://github.com/microsoft/msphpsql/issues/1018#issuecomment-534765819) and try using `PDOStatement::bindParam` instead. See if that makes a difference in your use case.

**Comment by temp** [comment]
Hi @yitam,  here are my findings:
`bindParam(':id', $id)` works, is faster than `bindValue(':id', $id)`, but far slower than a query without a parameter.
`bindParam(':id', $id, \PDO::PARAM_STR)` works, `bindParam(':id', $id, \PDO::PARAM_STR), \PDO::SQLSRV_ENCODING_SYSTEM` doesn't. Error: `[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'OUTPUT'`

Timings for the more complex query:
Native MSSQL-Client: 200 ms
PDO, without Parameter: 400 ms
PDO, with bindParam: 5000 ms
PDO, with bindValue: 8000 ms

I always tried every variant multiple times, and this was the average.

**Comment by temp** [comment]
New findings: directly setting `$pdo->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_SYSTEM)` seems to solve our performance issues - but it introduces another strange problem. Which is directly related to the system encoding, the problem is gone when we remove the encoding-call. But then it's slow as hell again.

The problem: we have a varchar(60) column, when we select this and the content is 60 chars long, the last char is truncated, and instead a null-byte is appended.

Example, with symfony dump():
```
"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, s\x00"
```
versus
```
"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, se"
```

Again, this is a changed example, since the error happens on a customer-address-column...

**Comment by temp** [comment]
And, again, new insights:
The performance penalty comes from an implicit conversion, which converts the where-column (username in my example) to NVARCHAR(30) (I guess). When I remove PDO::SQLSRV_ATTR_ENCODING and do a `WHERE username=CONVERT(VARCHAR(30), ?)` it works without penalty.
But this is a rather ugly solution...
So I'd rather stick with setting PDO::SQLSRV_ATTR_ENCODING, but then I have the problem from my posting above.

**Comment by yitam** [comment]
Thank you @temp for all the details. When using `bindParam`, please set `length` to 0 for input parameters. In your case, please try to only alter the parameter encoding, not the entire pdo connection, like this:

`bindParam(':id', $id, \PDO::PARAM_STR, 0, \PDO::SQLSRV_ENCODING_SYSTEM)`

About the truncation issue, we will investigate. What's your database collation?

**Comment by temp** [comment]
@yitam The collation is Latin1_General_CI_AS (queried by `SELECT SERVERPROPERTY('collation')`, I hope this is correct).
Switching to bindParam for each parameter worked.

**Comment by yitam** [comment]
Glad to hear using bindParam at the parameter level worked for you, @temp . About collation and performance hit, this [article](https://www.sqlservercentral.com/blogs/revised-difference-between-collation-sql_latin1_general_cp1_ci_as-and-latin1_general_ci_as#:~:text=The%20Latin1_General_CI_AS%20collation%20is%20a,with%20a%20slight%20performance%20hit.) explains it well.

When setting `PDO::SQLSRV_ENCODING_SYSTEM` at the connection level, this essentially tell the php driver not to do any character conversions. In some encodings (like Windows 1252) the German umlauts take up 1 byte, but in UTF-8 they are 2, hence the truncation. If you use varchar columns a lot, you can set `PDO::SQLSRV_ENCODING_SYSTEM` at the statement level instead. For example,

```
```

If the columns are nvarchar instead, those are UTF-16, so both ASCII chars and the umlauts are 2 bytes each. FYI, SQL Server 2019 introduced [UTF-8 support](https://techcommunity.microsoft.com/t5/sql-server/introducing-utf-8-support-for-sql-server/ba-p/734928). 

Hope this answers your questions.

**Comment by yitam** [comment]
Closing this since the issue has been resolved, @temp. Please feel free to reopen if necessary.
