### ISSUE TITLE
PDO::SQLSRV_ENCODING_UTF8 as invalid attribute

### ISSUE THREAD

**Issue by drajathasan** [microsoft/msphpsql#1238]
## PHP Driver version or file name
 + 5.9.0
 ## SQL Server version
 + SQL Server 2008
 ## Client operating system
 + Ubuntu 18.04
 ## PHP version
 + 8.0.2
 ## Microsoft ODBC Driver version
 + 17.7.1.1-1
 ## Table schema
 + dbo
 ## Problem description
 + I have error "An invalid attribute was designated on the PDO object." in Ci3 with PHP 8.0.2
 ## Expected behavior and actual behavior
 + no connection created if the pdo instance setup with PDO::SQLSRV_ENCODING_UTF8 = 1
 ## Repro code or steps to reproduce
 - I just set the dsn options withou PDO::SQLSRV_ENCODING_UTF8, and it works. But its ok without charset?

**Comment by yitam** [comment]
FYI, @drajathasan , we no longer support SQL Server 2008. That being said, with pdo_sqlsrv, `PDO::SQLSRV_ENCODING_UTF8` is the default, so you do not need to specify it. Even if you want to, the correct syntax is

```
$conn = new PDO("sqlsrv:Server=$host; Database = $dbname", $userid, $pswd, array(PDO::SQLSRV_ATTR_ENCODING=>PDO::SQLSRV_ENCODING_UTF8));
```
 
 OR 
 
```
$conn = new PDO("sqlsrv:Server=$servername ; Database = $dbname", $userid, $pswd);
$conn->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_SYSTEM)
``` 

Hope this helps.

**Comment by drajathasan** [comment]
> FYI, @drajathasan , we no longer support SQL Server 2008. That being said, with pdo_sqlsrv, `PDO::SQLSRV_ENCODING_UTF8` is the default, so you do not need to specify it. Even if you want to, the correct syntax is
> 
> ```
> $conn = new PDO("sqlsrv:Server=$host; Database = $dbname", $userid, $pswd, array(PDO::SQLSRV_ATTR_ENCODING=>PDO::SQLSRV_ENCODING_UTF8));
> ```
> 
> OR
> 
> ```
> $conn = new PDO("sqlsrv:Server=$servername ; Database = $dbname", $userid, $pswd);
> $conn->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_SYSTEM)
> ```
> 
> Hope this helps.

Thanks for your help. I'll try it ASAP.

**Comment by yitam** [comment]
My second example above should be the following instead:

```
$conn = new PDO("sqlsrv:Server=$servername ; Database = $dbname", $userid, $pswd);
$conn->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_UTF8);
```

**Comment by drajathasan** [comment]
> PDO::SQLSRV_ENCODING_UTF8

It works. Thanks Jenny.

**Comment by drajathasan** [comment]
> $conn = new PDO("sqlsrv:Server=$host; Database = $dbname", $userid, $pswd);
> $conn->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_UTF8);

It works, thanks you Jenny.

**Comment by yitam** [comment]
Glad to hear that @drajathasan. Closing this issue now, and please feel free to reopen if you have other related questions.
