### ISSUE TITLE
Can't install on big sur M1

### ISSUE THREAD

**Issue by much-rebel** [microsoft/msphpsql#1246]
## PHP Driver version or file name
pecl.php.net/pdo_sqlsrv-5.9.0
## Client operating system
macos big sur 11.2.3 (20D91), M1 chip
## PHP version
PHP 7.4.16 (cli) (built: Mar  4 2021 12:36:48) ( NTS )
## Microsoft ODBC Driver version
microsoft/mssql-release/msodbcsql17: stable 17.7.2.1 
## Problem description
Can't install and get the driver working
## Expected behavior and actual behavior
**Expected:** Install would work like it is described in installation manual here - https://www.microsoft.com/en-us/sql-server/developer-get-started/php/mac
**Actual:** pecl install step for extensions pdo_sqlsrv and sqlsrv fails
## Repro code or steps to reproduce
Assume you have brew installed...
[✔︎] brew install php@7.4
[✔︎] brew link --force --overwrite php@7.4
[✔︎] brew install autoconf automake libtool
[✔︎] brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
[✔︎] brew update
[✔︎] HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql17 mssql-tools
[✘] sudo pecl install pdo_sqlsrv
```
/private/tmp/pear/install/pdo_sqlsrv/shared/xplat.h:30:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^~~~~~~
1 error generated.
make: *** [pdo_dbh.lo] Error 1
ERROR: `make' failed
```
[✘] sudo pecl install sqlsrv
```
/private/tmp/pear/install/pdo_sqlsrv/shared/xplat.h:30:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^~~~~~~
1 error generated.
make: *** [pdo_dbh.lo] Error 1
ERROR: `make' failed
```
## Additional information
I was able to install these extension by adding CXXFLAGS and LDFLAGS
[✘] sudo CXXFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.9/include" LDFLAGS="-L/opt/homebrew/lib" pecl install pdo_sqlsrv sqlsrv
```
Build process completed successfully
Installing '/opt/homebrew/Cellar/php@7.4/7.4.16/pecl/20190902/pdo_sqlsrv.so'
install ok: channel://pecl.php.net/pdo_sqlsrv-5.9.0
...
Build process completed successfully
Installing '/opt/homebrew/Cellar/php@7.4/7.4.16/pecl/20190902/sqlsrv.so'
install ok: channel://pecl.php.net/sqlsrv-5.9.0
Extension pdo_sqlsrv enabled in php.ini
Extension sqlsrv enabled in php.ini
...
~ » php -i | grep sqlsrv
Registered PHP Streams => https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip, sqlsrv
PDO drivers => dblib, mysql, odbc, pgsql, sqlite, sqlsrv
pdo_sqlsrv
pdo_sqlsrv support => enabled
pdo_sqlsrv.client_buffer_max_kb_size => 10240 => 10240
pdo_sqlsrv.log_severity => 0 => 0
pdo_sqlsrv.report_additional_errors => 1 => 1
pdo_sqlsrv.set_locale_info => 2 => 2
sqlsrv
sqlsrv support => enabled
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240
sqlsrv.LogSeverity => 0 => 0
sqlsrv.LogSubsystems => 0 => 0
sqlsrv.SetLocaleInfo => 2 => 2
sqlsrv.WarningsReturnAsErrors => On => On
```
But the driver fails miserably on first connect attempt:
```
~ » brew services restart php@7.4
...
SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib '/usr/local/lib/libmsodbcsql.17.dylib' : file not found
```
making a symlink doesn't help either:
```
/usr/local/lib/libmsodbcsql.17.dylib -> /opt/homebrew/Cellar/msodbcsql17/17.7.2.1/lib/libmsodbcsql.17.dylib
```
php's file_exists on this symlink returns true, so should be accessible by the driver too.

**Comment by yitam** [comment]
@much-rebel [Microsoft ODBC Driver for SQL Server](https://docs.microsoft.com/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15) does not yet officially support M1 chip.

**Comment by much-rebel** [comment]
@yitam sad, can I emulate it with rosseta2 somehow?

**Comment by yitam** [comment]
@much-rebel please add your questions to [this related thread](https://github.com/Microsoft/homebrew-mssql-release/issues/53)

**Comment by FlyzZx** [comment]
Hello,
Is this still in progress ? :)

**Comment by yitam** [comment]
Hi @FlyzZx please check [this related thread](https://github.com/Microsoft/homebrew-mssql-release/issues/53) for updates and/or post your question there.

**Comment by yitam** [comment]
Closing this issue as per [5.10.0-beta1](
https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta1)
