### ISSUE TITLE
Error installing mysql extension in ubuntu 18.04.2

### ISSUE THREAD

**Issue by michaelpalomado** [microsoft/msphpsql#1248]
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20170718/pdo_sqlsrv.so (/usr/lib/php/20170718/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/pdo_sqlsrv.so.so (/usr/lib/php/20170718/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20170718/sqlsrv.so (/usr/lib/php/20170718/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/sqlsrv.so.so (/usr/lib/php/20170718/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20170718/pdo_sqlsrv.so (/usr/lib/php/20170718/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/pdo_sqlsrv.so.so (/usr/lib/php/20170718/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20170718/sqlsrv.so (/usr/lib/php/20170718/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/sqlsrv.so.so (/usr/lib/php/20170718/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
pecl/sqlsrv requires PHP (version >= 7.3.0), installed version is 7.2.24-0ubuntu0.18.04.7
No valid packages found
install failed

Always get this error while installing sqlsvr in ubuntu 18.04.2
If you have any idea to solve the problem it's a big help for me thank you...

**Comment by yitam** [comment]
Hi @michaelpalomado , as you can see from the errors above (near the end of the message), you have installed PHP 7.2 but the latest php pdo_sqlsrv drivers no longer support PHP 7.2 

Please either upgrade your PHP or pecl install an older version of pdo_sqlsrv drivers.

**Comment by yitam** [comment]
Closing the issue due to inactivity, @michaelpalomado . Please feel free to reopen if necessary.
