### ISSUE TITLE
UPDATE statement does nothing at all

### ISSUE THREAD

**Issue by rvizuet** [microsoft/msphpsql#1270]
PHP Driver version or file name
 + 5.9.0

SQL Server version
 + SQL Server Standard 2019 (15.0.2080.9) running on Windows Server 2019 Standard

Client operating system
 + openSUSE Linux 15.2

PHP version
 + 7.4.6

Microsoft ODBC Driver version
 + 17

Problem description
 + I've been trying to make UPDATE statements to work, but do anything, although there is no error messages. 
 + The SELECT and INSERT statements work fine.

My code:

```PHP
    $sentenciaQueryUpdate = "UPDATE Contrato SET Estatus='?' WHERE MovID = '?' AND Cliente = '?';";
    $lecturaIni = parse_ini_file($nombreINI, true);

    $dataBase = $lecturaIni['database'];
    $usuario    = $lecturaIni['user'];
    $password = $lecturaIni['password'];

    $connectionOptions = array("Database"  => $dataBase,
                               "UID"                              => $usuario,
                               "PWD"                            => $password,
                               "ReturnDatesAsStrings" => true,
                               "Driver"                          => 'ODBC Driver 17 for SQL Server');

    $connection        = sqlsrv_connect($lecturaIni['dsn'], $connectionOptions);

    if ($connection === false) 
        {
        echo '<FONT color="black">';
        echo "<H1>Error de SQL</H1>";
        echo 'Error en la conexion SQL SERVER a ' . $dataBase;
        echo "<BR/>";
        $errors = sqlsrv_errors();

        foreach ($errors as $error) 
            {
            echo "SQLSTATE: " . $error['SQLSTATE'] . "<BR/>";
            echo "Código: "   . $error['code']     . "<BR/>";
            echo "Mensaje: "  . $error['message']  . "<BR/>";
            }

        die('</FONT>');
        }

    $parameters = [$estatusNuevo, $contratoBusqueda, $clienteBusqueda];
    $statement  = sqlsrv_prepare($connection, $sentenciaQueryUpdate, $parameters);
    
    var_dump($statement);
    echo '<BR>';
    
    if(!$statement) 
        {
        die( print_r( sqlsrv_errors(), true));
        }
    
    $ejecucion = sqlsrv_execute($statement);
        
    var_dump($ejecucion);
    
    if($ejecucion === false) 
        {
        die(print_r( sqlsrv_errors(), true));
        }

    sqlsrv_close($connection);

``` 
I'm using ```sqlsrv_prepare``` and ```sqlsrv_execute``` because I thought that ```sqlsrv_query``` was the problem in this issue.

Please, some guidance about what is going on.

Thanks in advance.

**Comment by yitam** [comment]
Hi @rvizuet 

Please try calling [sqlsrv_rows_affected()](https://docs.microsoft.com/sql/connect/php/sqlsrv-rows-affected?view=sql-server-ver15) after sqlsrv_execute()

What's the fetched result of a select statement like this and supply the same input parameters for `MovID` and `Cliente`? 
```
SELECT Estatus FROM Contrato WHERE MovID = '?' AND Cliente = '?';
```

**Comment by rvizuet** [comment]
Hi @yitam,

Thanks for your quick answer =)

The results of my execution are:

---------------------------------------------
sqlsrv_prepare results: resource(9) of type (SQL Server Statement)
sqlsrv_execute results: bool(true)
sqlsrv_rows_affected results: 0
---------------------------------------------

Now, the results of a ```SELECT Estatus FROM Contrato WHERE MovID = 'SRCB3701' AND Cliente = '0001757'``` are:

   + BAJA

Only the record I need to be updated... exactly that one.

**Comment by yitam** [comment]
Hi @rvizuet please check if the returned value of sqlsrv_rows_affected() is 0 or false, like this. If false, please check the errors.

```
$rows_affected = sqlsrv_rows_affected( $stmt);  
if( $rows_affected === false)  {
}
```

**Comment by rvizuet** [comment]
Good morning @yitam,

This is what I'm doing regarding to sqlsrv_rows_affected:

```PHP
 $rows_affected = sqlsrv_rows_affected($statement);  
    
    if($rows_affected === false)  
        {  
        echo "<BR>Error in calling sqlsrv_rows_affected.<BR>";  
        die(print_r(sqlsrv_errors(), true));  
        }  
    else if($rows_affected == -1)  
        {  
        echo "<BR>No information available.<BR>";  
        }  
    else  
        {  
        echo '<BR>sqlsrv_rows_affected result: ' . $rows_affected;  
        }  
```

But it doesn't return false, it returns zero.

**Comment by yitam** [comment]
Hi @rvizuet in this case please provide odbc trace. You can trying running the same script using command line instead of a browser

**Comment by yitam** [comment]
My bad, @rvizuet , I didn't realize that you have used single quotes for the UPDATE statement. Please try this
`$sentenciaQueryUpdate = "UPDATE Contrato SET Estatus=? WHERE MovID = ? AND Cliente = ?";`

**Comment by rvizuet** [comment]
Hi @yitam,

I just removed the single quotes but the results are the same:

 + sqlsrv_prepare: resource(9) of type (SQL Server Statement)
 + sqlsrv_execute: bool(true)
 + sqlsrv_rows_affected: 0

The column wasn't updated with the new value.

**Comment by yitam** [comment]
Did you remove all single quotes, @rvizuet? How do you check if the column is updated? Run a new select query or use Management Studio?

Anyway, please provide ODBC trace if possible.

**Comment by rvizuet** [comment]
Hi @yitam,

This is my code, the way it is now:

```
$sentenciaQueryUpdate = "UPDATE Contrato SET Estatus=? WHERE MovID=? AND Cliente=?;";
```
And after the UPDATE, I check the row in Management Studio with:
```SELECT MovID,
       Cliente,
	   Estatus
  FROM Contrato
 WHERE MovID = 'SRCB3701'
   AND Cliente = '0001757'```

The results are:
![SELECTresults](https://user-images.githubusercontent.com/84986243/122441720-749b9f80-cf63-11eb-9a69-ad0355654e79.png)

**Comment by rvizuet** [comment]
Hi @yitam,

This is my code, the way it is now:

```
$sentenciaQueryUpdate = "UPDATE Contrato SET Estatus=? WHERE MovID=? AND Cliente=?;";
```
And after the UPDATE, I check the row in Management Studio with:
```SELECT MovID,
       Cliente,
	   Estatus
  FROM Contrato
 WHERE MovID = 'SRCB3701'
   AND Cliente = '0001757'```

The results are:
MovID	  Cliente	    Estatus
SRCB3701  0001757    BAJA

**Comment by yitam** [comment]
It seems we are not going anywhere, @rvizuet, so please provide odbc trace (run your php script in command line).

Last try: what are the field types for those columns? varchar, char, nvarchar? 

Please add this block to your script before the update:

```
$contratoBusqueda = 'SRCB3701';
$clienteBusqueda = '0001757';
$parameters = [$contratoBusqueda, $clienteBusqueda];
$tsql = "SELECT Estatus FROM Contrato WHERE MovID=? AND Cliente=?";
$stmt = sqlsrv_query($conn, $tsql, $parameters);
if (sqlsrv_fetch($stmt) === false) {
    die(print_r(sqlsrv_errors(), true));
}
$value = sqlsrv_get_field($stmt, 0);
var_dump($value);
```

**Comment by rvizuet** [comment]
Sorry @yitam, I'm gonna try to get the odbc trace, using the command line and adding your code... Please be patient because I've never did it before.

In the meantime, let me give you the characteristics of the columns involved:

MovID - varchar(20)
Cliente - varchar(10)
Estatus - char(15)

Thanks

**Comment by rvizuet** [comment]
Hello again @yitam,

Finally I could get the ODBC trace! 

The results of the executions are:

SELECT results: 
+ string(15) "BAJA           "

+ sqlsrv_prepare: resource(7) of type (SQL Server Statement)

+ sqlsrv_execute: bool(true)

+ sqlsrv_rows_affected: 0

I'm attaching the odbctrace.log
[odbctrace.log](https://github.com/microsoft/msphpsql/files/6672640/odbctrace.log)

**Comment by yitam** [comment]
Thanks @rvizuet for the trace! SQLExecute does return SQL_NO_DATA. So I have several more questions:

1. What is your [database collation](https://www.sqlshack.com/sql-server-collation-introduction-with-collate-sql-casting/)?
1. What is the new value for column `Estatus` (from "BAJA" to ??)? What are the typical values in this column?
1. Please try connecting with UTF-8, as shown below, and see if there's any difference.

```
$connectionOptions = array("Database"  => $dataBase,
                               "UID"                              => $usuario,
                               "PWD"                            => $password,
                               "ReturnDatesAsStrings" => true,
                               "CharacterSet"               => "UTF-8",
                               "Driver"                          => 'ODBC Driver 17 for SQL Server');

$connection        = sqlsrv_connect($lecturaIni['dsn'], $connectionOptions);
```

I will try to reproduce this on my side too.

**Comment by rvizuet** [comment]
Hi @yitam,

My database collation is: Modern_Spanish_CI_AS.
The value for ``` Estatus ``` has never changed, no matter how many UPDATES I run. It is still "BAJA".
The Typical values for this column are: BAJA, SINAFECTAR, VIGENTE, VENCIDO and CANCELADO
I reconnected using UTF-8 but there's no difference... The ``` Estatus ``` column value didn't change.

**Comment by yitam** [comment]
Thank you @rvizuet 
We can reproduce this on our side. We will get back to you after some investigation.

**Comment by rvizuet** [comment]
Thanks a lot, @yitam. I'll be pending or you answer.

Good afternoon!

**Comment by yitam** [comment]
Sorry to disappoint you @rvizuet . There was a mistake with my repro script (see below) and once I fixed it I can no longer reproduce the UPDATE problem. 

[sqlsrv_1270.php.txt](https://github.com/microsoft/msphpsql/files/6673789/sqlsrv_1270.php.txt)

I've tried in Windows, Ubuntu 18.04 and opensuse 15:
![image](https://user-images.githubusercontent.com/21340756/122486913-d9b8ba80-cf8e-11eb-9919-a9f060b2ee52.png)

I changed the collation to the one you used:
![image](https://user-images.githubusercontent.com/21340756/122486802-a37b3b00-cf8e-11eb-95e4-096548884b0d.png)

This is my odbc trace (see line 598, SQLExecute returned SQL_SUCCESS instead of SQL_NO_DATA like yours):
[odbc.log](https://github.com/microsoft/msphpsql/files/6673811/odbc.log)

Can you try running my repro script on your side?

**Comment by rvizuet** [comment]
Good morning @yitam,

I already did the test using your script. The only thing is I'm creating this new table Contratorri, because in Contrato I have thousands of records and I cannot drop this table, so I made a new one.

Surprisingly, the UPDATE works fine over this new table Contratorri, but over my old Contrato does not.... 

![UpdateTest](https://user-images.githubusercontent.com/84986243/122579710-cce1a880-d01a-11eb-94b2-e51d3dba71e3.png)

I'm thinking that Contrato has a trigger programming, so when I make changes directly from Management Studio, I can see the multiple lines of rows affected in some other tables. Do you think this might be causing the UPDATE does not work on it?... if this is the case, what should I do?

I attach for you the new odbctrace (with Contratorri table):

[odbctrace3.log](https://github.com/microsoft/msphpsql/files/6677797/odbctrace3.log)

**Comment by yitam** [comment]
Hi @rvizuet , if [triggers](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-helptrigger-transact-sql?view=sql-server-ver15) have been created, then it's likely affecting your particular table(s) or column(s). My simple script proves that the current PHP (ODBC) drivers work with updating a regular table column.

Thus, I'm afraid this is beyond our support.  You might need to discuss with your DBA or the one who has created the trigger(s).

**Comment by rvizuet** [comment]
OK @yitam,

I appreciate your time and effort. If I can find the way to solve it, I'll let you know.

Thanks a lot.

**Comment by rvizuet** [comment]
Hi again, @yitam,

I continued doing some tests and finally could solve something I think worked for me. It's a little funny and I don't understand what is really happening. The point is as you'll see in the next two code blocks.

First (original) does not work:

```PHP
$conn = sqlsrv_connect($server, $connInfo);

$sql        = "UPDATE Contrato SET Estatus=? WHERE MovID=? AND Cliente=?";
$parameters = [$nuevoEstatus, $contratoBusqueda, $clienteBusqueda];
$stmt       = sqlsrv_query($conn, $sql, $parameters);

$nrows      = sqlsrv_rows_affected($stmt);

sqlsrv_free_stmt($stmt);
sqlsrv_close($conn);
```

This first script tries to do the UPDATE directly, but does not work.

Second (modified) does work:

```PHP
$conn = sqlsrv_connect($server, $connInfo);

$parameters = [$contratoBusqueda, $clienteBusqueda];

$sql  = "SELECT Estatus FROM Contrato WHERE MovID = ? AND Cliente = ?";
$stmt = sqlsrv_prepare($conn, $sql, $parameters);
$res  = sqlsrv_execute($stmt);

if (sqlsrv_fetch($stmt) === false) 
    {
    die(print_r(sqlsrv_errors(), true));
    }

$value = sqlsrv_get_field($stmt, 0);

$sql        = "UPDATE Contrato SET Estatus=? WHERE MovID=? AND Cliente=?";
$parameters = [$nuevoEstatus, $contratoBusqueda, $clienteBusqueda];
$stmt       = sqlsrv_query($conn, $sql, $parameters);

$nrows      = sqlsrv_rows_affected($stmt);

sqlsrv_free_stmt($stmt);
sqlsrv_close($conn);
```

In this second script I included a SELECT statement previous to do the UPDATE and it DOES work.

How is it possible?.... I don't know but it works.

Anyway, I'm gonna let it this way because it's doing fine. I have an extra SELECT I don't need, but...

I just wanted to share this with you.

Thanks!

**Comment by yitam** [comment]
Hi @rvizuet I suspect this is something to do with cursor(s) and trigger(s). The trigger(s) might be the reason behind your other problem (#1263), which explains why server-side cursors did not work for you.

I suggest you dig deeper rather than looking for workarounds, which probably work until the triggers change again. That being said, do you have any other questions specifically related to our drivers?

**Comment by rvizuet** [comment]
Thanks, @yitam, for your feedback. The only thing I would like to ask is if there's some book or site you recommend to enrich SQL Server knowledge in order to solve the issues I have.

**Comment by yitam** [comment]
Hi @rvizuet 

Please start with [DML Triggers](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/dml-triggers?view=sql-server-ver15). There are other websites too for DBAs but you might need to search around.

**Comment by rvizuet** [comment]
You're so kind, @yitam.

Thanks for your time.
