### ISSUE TITLE
Error code 0x2746

### ISSUE THREAD

**Issue by omaromp2** [microsoft/msphpsql#1278]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 + 5.9
 +## SQL Server version
 +
 +## Client operating system
 + Ubuntu 20.04
 +## PHP version
 + 7.4 

I keep getting this connection error "Error code 0x2746" , after following the installation instruccions

**Comment by yitam** [comment]
Hi @omaromp2 

What is the version of your SQL Server? It matters. Please check the [this FAQ entry about Ubuntu 20.04](https://github.com/Microsoft/msphpsql/wiki/FAQ#unable-to-connect-ubuntu20)

**Comment by omaromp2** [comment]
hi @yitam , 
Thanks for the quick reply. 
The sqlsrv version is 2012 is not hosted in my machine. This is my work machine and I have never had a problem connecting with other versions

**Comment by omaromp2** [comment]
@yitam 
Sorry If I gave too little info, I'm going to try to install the 5.6.1 version with pecl. 
This might work. 
Thanks for your support

**Comment by yitam** [comment]
Hi @omaromp2 , no it's not the drivers but Ubuntu 20.04 has raised its security bar. You won't be able to connect to any SQL Servers older than SQL Server 2017. You need a workaround, and please check aforementioned FAQ entry for details.

**Comment by omaromp2** [comment]
@yitam , thanks for the FAQ. 
I tried modifying the openssl.cnf however I keep getting the same error. 
`SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 `
Thanks in advanced.

**Comment by yitam** [comment]
@omaromp2 please provide more details, and as you can see in the FAQ entry, many people have similar issues. They have different needs or requirements (some using Docker, etc.) and provide their workarounds. Have you checked them all?

**Comment by omaromp2** [comment]
Hi @yitam, sorry for the delay. 
Due to the Error that I get: 
''SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746" 
I followed the current issue from the FAQ. 
https://github.com/microsoft/msphpsql/issues/1112
However, after I configure the openssl.cnf file, I keep getting the same error. 

I ended up downgrading to ubuntu 18.10 and the install was easy and it worked from the get go. 
It would be nice to find a workaround on ubuntu 20. 

As always, I'm very thankful for your help. 👍

**Comment by yitam** [comment]
Hi @omaromp2 

Glad to hear that you managed to install the drivers and connected successfully. However, Ubuntu 18.10 was out of support so perhaps Ubuntu 18.04 LTS is a better option?

The workarounds are not really recommended because there's a reason for Ubuntu 20.04 to raise the security bar. If possible, please consider upgrading your server to SQL Server 2017 to later.

**Comment by yitam** [comment]
Any update, @omaromp2 ?

**Comment by omaromp2** [comment]
Hi @yitam, 
Thank you for the follow-up.
At the moment we are unable to upgrade the DB due to other legacy apps. 
So I'm running my apps in Ubuntu 18.04.  
On Ubuntu 20.04 I keep getting the error: 
SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 
Thank you for your support.

**Comment by omaromp2** [comment]
Fixed it!!!! 
First of all, thanks for the FAQ links and shedding some light on what was happening to my connection. 
This is the link I followed in order to connect to sqlsrv 2012. 
https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level
@yitam  Thank you very much for your support!
