### ISSUE TITLE
Linux x86

### ISSUE THREAD

**Issue by brincas** [Microsoft/msphpsql#128]
I dont seen to find the Ubuntu16 32bits in the zips :(

trying to install in a runninng test server in 32 bits to upgrade it, i dont think the machine will handle the 64 :(,

**Comment by brincas** [comment]
This is the error we got:

php_pdo_sqlsrv_7_nts.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=e04c62a3bcc2e22805377017d47f9f14fa481590, not stripped
php_pdo_sqlsrv_7_ts.so:  ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=9575e8c75dc3d3cf34fd42dce991c7cd72cc60ee, not stripped
php_sqlsrv_7_nts.so:     ELF 64-bit LSB shared object, x86-64, version 1 
(GNU/Linux), dynamically linked,
BuildID[sha1]=c6b10d208f463fab669196825d79148ff62c450f, not stripped
php_sqlsrv_7_ts.so:      ELF 64-bit LSB shared object, x86-64, version 1 
(GNU/Linux), dynamically linked,
BuildID[sha1]=05d3be3bf8f983495791bcdfe5c6b82902fd872c, not stripped

**Comment by meet-bhagdev** [comment]
@brincas PHP Drivers for SQL Server on Linux are not available for 32-bit. The drivers have a dependency on the C++ ODBC Driver which is not available for 64-bit. Any particular reason why you can not use Ubuntu 16 64 bit?

**Comment by brincas** [comment]
our main machine is in 64bits, the one that has the public sites

this one is a old beasty, just for we test the sites before doing any upgrade on the main server, but i guess with this new it will require to update it to 64bits (he it can old the 64 xD)

**Comment by meet-bhagdev** [comment]
@brincas Sounds good. Let us know if you have any questions about the x64 variant of the Linux driver.

**Comment by meet-bhagdev** [comment]
Closing as it is not scoped for now.
