### ISSUE TITLE
installed SqlServ driver ODBC on Alpine Linux 3.12

### ISSUE THREAD

**Issue by huguijian** [microsoft/msphpsql#1283]
Hi 
I found error When I use pod_sqlsrv connect sqlserve.
  [PDOException]
  SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.2.1' : file not found

Use ldd /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.2.1  error:Error relocating /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.2.1: unsupported relocation type 1
 +## PHP Driver version or file name
 + PHP 7.4.7 (cli)

**Comment by yitam** [comment]
Hi @huguijian how did you install [ODBC driver in Alpine Linux](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#alpine17)?

This seems like [an issue with linker and glibc](https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path)

**Comment by huguijian** [comment]
Hi @yitam 
Thinks for you replay
I refer to the download address ：https://docs.microsoft.com/zh-cn/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#alpine17

**Comment by yitam** [comment]
Please type `uname -a` and show us the results

**Comment by huguijian** [comment]
uname -a 
Linux a426964f398d 5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021 aarch64 Linux
I install ODBC driver in docker on my MAC M1

**Comment by huguijian** [comment]
Hi @yitam 
Thinks for you replay
I refer to the download address ：https://docs.microsoft.com/zh-cn/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#alpine17

**Comment by yitam** [comment]
@huguijian for your information, php drivers do not support Linux non-x86 platforms nor Mac M1

**Comment by huguijian** [comment]
> @huguijian for your information, php drivers do not support Linux non-x86 platforms nor Mac M1

Will support in the future ？

**Comment by yitam** [comment]
The support for Mac M1 is in the backlog but no plan to support non-x86 Linux platforms yet.
