### ISSUE TITLE
Confused about connection encryption

### ISSUE THREAD

**Issue by WilliamDEdwards** [microsoft/msphpsql#1289]
## PHP Driver version or file name

pdo_sqlsrv 5.9.0

## SQL Server version

Unknown.

## Client operating system

Debian 10

## PHP version

7.4.22

## Microsoft ODBC Driver version

17.7.2.1-1

## Problem description

Trying to connect to an SQL Server without encryption does not work as expected with `Encrypt=0`.

## Expected behavior and actual behavior

When setting `Encrypt=0` in the DSN, I see encrypted packets in tcpdump nonetheless, and the following exception is thrown:

    PDOException: SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol]

When downgrading `MinProtocol` and `CipherString` in `/usr/lib/ssl/openssl.cnf`, the connection is successfully established with `Encrypt=0`. I acknowledge that the SQL Server should support recent TLS versions, but why is any SSL negotiation going on with `Encrypt=0`?

I only see encrypted packets at connection init time by the way, which makes me suspect that `Encrypt=0` is only used for communications after the initial communication. If that is the case, this is a request to improve documentation at best.

**Comment by yitam** [comment]
With Debian 10 it really depends on your SQL Server version. Please check [this FAQ entry](https://github.com/microsoft/msphpsql/wiki/FAQ#unable-to-connect-ubuntu20)

**Comment by yitam** [comment]
@WilliamDEdwards also, please let us know which parts of the documentation is unclear to you? [ODBC Driver connection string keywords](https://docs.microsoft.com/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-ver15#odbc-driver-connection-string-keywords)

**Comment by WilliamDEdwards** [comment]
> @WilliamDEdwards also, please let us know which parts of the documentation is unclear to you? [ODBC Driver connection string keywords](https://docs.microsoft.com/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-ver15#odbc-driver-connection-string-keywords)

`Encrypt`: "Specifies whether data should be encrypted before sending it over the network. Possible values are "yes" and "no". The default value is "no"."

However, when using `Encrypt=0`, traffic is being encrypted, and I get `routines:ssl_choose_client_version:unsupported protocol`.

**Comment by yitam** [comment]
Hi @WilliamDEdwards, as mentioned in the aforementioned FAQ entry, Debian 10 has raised the security bar. The negotiated state is the more secure of the two, so if either the server or the client requests encryption, data will be encrypted.

**Comment by WilliamDEdwards** [comment]
Hi! I am aware of the difference with the OpenSSL config that Debian 10 ships by default, but that's not what this issue is about. Are you saying that if traffic is being encrypted even though I've set `Encrypt=0`, it's possible the SQL Server is upgrading the connection?

**Comment by yitam** [comment]
FYI, @WilliamDEdwards 
[Enable encrypted connections to the Database Engine](https://docs.microsoft.com/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15)

**Comment by WilliamDEdwards** [comment]
Seems like https://docs.microsoft.com/nl-nl/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15#configure-server is indeed the explanation I'm looking for. I think this issue can be closed, because in that case this has nothing to do with the PHP drivers :)

**Comment by yitam** [comment]
Good, @WilliamDEdwards 
Closing this issue now.
