### ISSUE TITLE
Named parameterized queries

### ISSUE THREAD

**Issue by atomusr** [microsoft/msphpsql#1299]
Can you please support named parameterized queries? 

We often have several column names with application side defaults and repeating ? with the same value is tedious.

**Comment by yitam** [comment]
Please be more specific with your questions or requests, @atomusr .
You can try the pdo_sqlsrv driver, which supports named parameters in queries.

**Comment by atomusr** [comment]
Coming from a linux background, I don't like object oriented programming so I'm not going to use pdo driver. I'm using the "procedural" driver (sqlsrv_*).

I have the following query:
```
sqlsrv_begin_transaction($conn);
sqlsrv_query('INSERT INTO foo(production_date, update_date, overset_date)
VALUES(?, ?, ?)', new DateTime("now"), new DateTime("now"), new DateTime("now"));
sqlsrv_commit($conn);
```

All 3 columns are supposed to have "datetime now" that is "unique" within a transaction....which means with your driver, I have to do ? three times like above. With other DBMS like postgresql, the "datetime now" is unique within a transaction. I don't have to pass a PHP date, I can just do CURRENT_TIMESTAMP which will be unique within a transaction (that's not the problem, the problem is named parameterized queries).

**Comment by yitam** [comment]
Hi @atomusr , I think there are some misunderstandings. Using named parameters is something else. Please see the [pdo_prepare](https://www.php.net/manual/en/pdo.prepare.php) example for more details. 

In your scenario, sqlsrv driver also supports `CURRENT_TIMESTAMP`, like this:

```
$sql = "CREATE TABLE foo(DATE1 DateTime2, DATE2 DateTime2, DATE3 DateTime2)";
$stmt = sqlsrv_query($conn, $sql);

sqlsrv_begin_transaction($conn);
$sql = "INSERT INTO foo(DATE1, DATE2, DATE3) VALUES(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)";
$stmt = sqlsrv_query($conn, $sql);
sqlsrv_commit($conn);

$sql = "SELECT * FROM foo";
$options = array('ReturnDatesAsStrings' => true);
$stmt = sqlsrv_query($conn, $sql, array(), $options);
$row = sqlsrv_fetch_array($stmt, SQLSRV_FETCH_ASSOC);
var_dump($row);
```

And this is the output:

```
array(3) {
  ["DATE1"]=>
  string(27) "2021-09-13 16:30:07.2400000"
  ["DATE2"]=>
  string(27) "2021-09-13 16:30:07.2400000"
  ["DATE3"]=>
  string(27) "2021-09-13 16:30:07.2400000"
}
```

**Comment by atomusr** [comment]
No, I don't think you understand. Let me explain. 

```
sqlsrv_begin_transaction($conn);
sqlsrv_query($conn, 'INSERT INTO test(col1) VALUES(SYSUTCDATETIME())');
sleep(10);
sqlsrv_query($conn, 'INSERT INTO test(col1) VALUES(SYSUTCDATETIME())');
sqlsrv_query($conn, 'INSERT INTO test(col1) VALUES(SYSUTCDATETIME())');
sqlsrv_commit($conn);
```
For brevity, let's ignore any SQL or PHP "declaration" problems as this is a semi-pseudo real example that I ran locally.

Notice the delay of 10 seconds after the first command.
For the 3 records that are inserted WITHIN A TRANSACTION, what are the timestamps inserted??? Let's see:
2021-09-14 00:27:22.6203709
2021-09-14 00:27:32.6351712
2021-09-14 00:27:32.6359769


Disaster. Why are the timestamps different within a transaction.

**Comment by yitam** [comment]
@atomusr glad to hear you found a workaround. Do you have any more question?

**Comment by yitam** [comment]
Closing this issue @atomusr. Please feel free to ask to reopen this if you have more questions.
