### ISSUE TITLE
method_exists(PDO_sqlsrv) throws exception

### ISSUE THREAD

**Issue by GDmac** [microsoft/msphpsql#1306]
MacOS (Mojave)
PHP 7.4.x
ODBC  17.8.1.1 
pdo_sqlsrv 5.9.0

## Problem description
When trying to check if a method_exists on the PDO (sqlsrv) driver, 
it should not throw an exception.

```php
        $connSqlite = new PDO("sqlite::memory:");
        $connSqlite->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        var_dump(method_exists($connSqlite, 'exec'));
        // true
        var_dump(method_exists($connSqlite, 'executeStatement'));
        // false

        $connSqlServer = new PDO("sqlsrv:server=$server ; Database=$database", $username, $password);
        $connSqlServer->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        var_dump(method_exists($connSqlServer, 'exec'));
        // true
        var_dump(method_exists($connSqlServer, 'executeStatement'));
        // Expected: false
        // Actual: PDOException : SQLSTATE[IMSSP]: This function is not implemented by this driver.
```

**Comment by yitam** [comment]
Hi @GDmac 

I think this is related to #1258 , which is already fixed in [5.10.0-beta1](
https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta1). Please check.

**Comment by GDmac** [comment]
yes, 5.10-beta fixes this, 
when is 5.10 expected to be released?

**Comment by yitam** [comment]
Hi @GDmac PHP drivers for SQL Server, version 5.10, are targeted to be released right after the next release of Microsoft ODBC Driver in early 2022. Please stay tuned.

**Comment by yitam** [comment]
Closing this issue as it's a duplicate.
