### ISSUE TITLE
TVP for non stored procedure queries throws error

### ISSUE THREAD

**Issue by atomusr** [microsoft/msphpsql#1307]
Hello, 

Do you know if TVP feature supports non stored procedure queries? I tried the beta 5.10 driver and it fails for a non stored procedure query.

Below is the details:
CREATE TYPE id_table AS TABLE(id INT PRIMARY KEY);

CREATE TABLE test_table (id INT PRIMARY KEY);

MERGE INTO test_table t
USING ? s ON s.id = t.id
WHEN NOT MATCHED THEN
  INSERT (id) VALUES(s.id);

The 5.1 beta driver throws the following error:
Fatal error: sqlsrv_params_container::get_next_parameter - The parameter requested is missing!

Following are my parameters in PHP:

$params = [
    [['id_table' => [[1], [2], [3]]]], 
    ];

**Comment by yitam** [comment]
Hi @atomusr, we will investigate and get back to you on this.

**Comment by yitam** [comment]
Hi @atomusr , FYI, this will be fixed in the upcoming beta release.

**Comment by yitam** [comment]
[5.10.0-beta 2](https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta2) is just released. Please give it a try, @atomusr

**Comment by yitam** [comment]
Closing this now please feel free to ask us to reopen.
