### ISSUE TITLE
macOS 11.6 - M1 - "OpenSSL library could not be loaded, make sure OpenSSL 1.0 or 1.1 is installed"

### ISSUE THREAD

**Issue by LinkingYou** [Microsoft/msphpsql#1319]
## PHP Driver version or file name
 
```
pecl list
Installed packages, channel pecl.php.net:
=========================================
Package    Version     State
pdo_sqlsrv 5.10.0beta1 beta
sqlsrv     5.10.0beta1 beta
```

 ## SQL Server version
 
Microsoft SQL Server 2012

 ## Client operating system

macOS Big Sur 11.6 on a MacBook Air (M1, 2020)
 
 ## PHP version

```
php -v
PHP 8.0.12 (cli) (built: Oct 21 2021 06:07:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies
```

 ## Microsoft ODBC Driver version

```
brew info msodbcsql17
microsoft/mssql-release/msodbcsql17: stable 17.8.1.1
ODBC Driver for Microsoft(R) SQL Server(R)
```

 ## Problem description

I have installed PHP, the microsoft odbc driver and sqlsrv / pdo_sqlsrv following this tutorial https://github.com/microsoft/msphpsql/blob/master/Linux-mac-install.md#installing-the-drivers-on-macos on my new Mac.

The pecl-install-commands I have changed to the latest beta version:

```
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install sqlsrv-5.10.0beta1
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install pdo_sqlsrv-5.10.0beta1
```

At first everything looked fine. But if i want to connect to the database server, i always get this errors:

`Uncaught Exception: SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [OpenSSL library could not be loaded, make sure OpenSSL 1.0 or 1.1 is installed]`

I also tested using the test scripts in the manual above with the same error messages.

Here are some more informations about my openssl installation:

```
openssl version 
OpenSSL 1.1.1l  24 Aug 2021
```

```
which openssl
/opt/homebrew/opt/openssl@1.1/bin/openssl
```

```
echo $PATH
/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/openssl@1.1/lib:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
```

Does anyone have any idea how to fix the problem or further debug it?

**Comment by artisanclouddev** [comment]
> Thanks for your confirmation, @LinkingYou
> 
> In Apple M1, make sure there's no OpenSSL@3 and then try the following steps:
> 
> `ln -s /opt/homebrew/Cellar/openssl@1.1/1.1.1l_1 /opt/homebrew/opt/openssl`
> 
> If this already exists please `rm /opt/homebrew/opt/openssl` first
> 
> Then try `ls /opt/homebrew/opt/openssl` and see if it indeed points to the right directory

pretty cool answer for solveing my M1 to connect the sql server.
