### ISSUE TITLE
Feature Request: Support explicitly disabling PDO::ATTR_EMULATE_PREPARES at the connection level

### ISSUE THREAD

**Issue by IMSoP** [microsoft/msphpsql#1320]
Hi,

Some libraries which wrap PDO try to ensure emulated prepares are *off* on newly created connections, e.g. [EasyDB](https://github.com/paragonie/easydb/blob/master/src/EasyDB.php#L48). 

> this->pdo->setAttribute(\PDO::ATTR_EMULATE_PREPARES, false);

However, this driver [defines that variable as "statement-level only"](https://github.com/microsoft/msphpsql/blob/f2c340892abe34c19f36dfe203ddcb76d9e011b4/source/pdo_sqlsrv/pdo_dbh.cpp#L1291) so gives an error:

> PDOException: SQLSTATE[IMSSP]: The given attribute is only supported on the PDOStatement object. in /srv/app-service-auth/vendor/paragonie/easydb/src/EasyDB.php:50

As I understand it, the setting is off by default anyway, so this line would be a no-op if accepted. Would it be possible to accept the attribute, but only accept a value of false? That way, libraries wouldn't need driver-specific workarounds.

**Comment by yitam** [comment]
[5.10.0-beta 2](https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta2) is just released. Please give it a try, @IMSoP

**Comment by yitam** [comment]
Closing this now please feel free to ask us to reopen.
