### ISSUE TITLE
Named prepared statement parameters cannot be used more than once in a statement

### ISSUE THREAD

**Issue by morozov** [microsoft/msphpsql#1322]
## PHP Driver version or file name
`pdo_sqlsrv`

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU10) (KB5001090) - 15.0.4123.1 (X64) 
	Mar 22 2021 18:10:24 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 20.04.2 LTS) <X64>

## Client operating system
macOS

## PHP version
8.0.12

## Microsoft ODBC Driver version
17

## Table schema
N/A

## Problem description
One of the advantages of using named prepared statement parameters is being able to reuse them multiple times in the same statement without having to bind them multiple times. It works with some PDO-based drivers but not with `pdo_sqlsrv`.

## Expected behavior
Named prepared statement parameters can be used more than once.

## Repro code or steps to reproduce
```php
$connection = new PDO('sqlsrv:server=127.0.0.1', 'sa', 'Passw0rd');
$sql = 'SELECT :name, :name';
$stmt = $connection->prepare($sql);
$stmt->bindValue("name", 'test');
$stmt->execute();
var_dump($stmt->fetch(PDO::FETCH_NUM));

// PDOException: SQLSTATE[07002]: [Microsoft][ODBC Driver 17 for SQL Server]COUNT field incorrect or syntax error
```
The same works with `pdo_mysql`:
```php
$connection = new PDO('mysql:host=127.0.0.1', 'root', '');

// array(2) {
//   [0] =>
//   string(4) "test"
//   [1] =>
//   string(4) "test"
// }
```
And `pdo_sqlite`:
```php
$connection = new PDO('sqlite::memory:');

// array(2) {
//   [0] =>
//   string(4) "test"
//   [1] =>
//   string(4) "test"
// }
```

**Comment by yitam** [comment]
Hi @morozov 
It's by design. For your information this is duplicate issue of #1096

**Comment by morozov** [comment]
@yitam, I wasn't aware that it's by design. Thanks for pointing it out. Closing the issue.
