### ISSUE TITLE
Unable to install on Big Sur with M1 chip: ld: library not found for -lodbc

### ISSUE THREAD

**Issue by jotso** [microsoft/msphpsql#1323]
PHP Driver version or file name:  5.10.0-beta1.
Client operating system: Big Sur
PHP version: 8.0.12
Microsoft ODBC Driver version: 2.3.9_1
Problem description:

My company bought a new macbook pro with M1 chip and I am trying to install the sqlsrv extensions for php for a week now, and still I didn't manage to do so. The ODBC driver is installed correctly as I can see in the phpconfig() output. Since I am dealing with a M1 chip, I am trying to install specifically version 5.10.0-beta1 of sqlsrv. The install stops with the following:
 
ld: library not found for -lodbc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sqlsrv.la] Error 1
ERROR: `make' failed
 
Another thing I tried is installing this specific version of the driver on another mac (with i9 chip however) and copy sqlsrv.so and pdo_sqlsrv.so to the new macbook and into the extension_dir. 
This results in php complaining: 
 
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /opt/homebrew/Cellar/php/8.0.12/lib/php/20200930/sqlsrv.so (dlopen(/opt/homebrew/Cellar/php/8.0.12/lib/php/20200930/sqlsrv.so, 9): no suitable image found.  Did find:
	/opt/homebrew/Cellar/php/8.0.12/lib/php/20200930/sqlsrv.so: mach-o, but wrong architecture
	/opt/homebrew/Cellar/php/8.0.12/lib/php/20200930/sqlsrv.so: stat() failed with errno=22), /opt/homebrew/Cellar/php/8.0.12/lib/php/20200930/sqlsrv.so.so (dlopen(/opt/homebrew/Cellar/php/8.0.12/lib/php/20200930/sqlsrv.so.so, 9): image not found)) in Unknown on line 0
 
﻿By now I am out of ideas of what to do..

**Comment by yitam** [comment]
Hi @jotso have you followed [the installation instruction](https://docs.microsoft.com/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-on-macos)? 

What's the output when you type `odbcinst -j`?

**Comment by jotso** [comment]
Hi @yitam,

Thanks a ton! There was a magic line in the instructions which I missed out on: 
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install sqlsrv
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install pdo_sqlsrv

Now that's installed, I am getting the following when running a test script:
SQLSTATE: 08001<br/>Code: -1<br/>Message: [Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [OpenSSL library could not be loaded, make sure OpenSSL 1.0 or 1.1 is installed]

in my phpconfig() it shows openssl is installed (version 1.1). I also installed unixodbc version 1.7.8.1

And to come back to your question, the output of `odbcinst -j` is: 
unixODBC 2.3.9
DRIVERS............: /opt/homebrew/etc/odbcinst.ini
SYSTEM DATA SOURCES: /opt/homebrew/etc/odbc.ini
FILE DATA SOURCES..: /opt/homebrew/etc/ODBCDataSources
USER DATA SOURCES..: /Users/bobvandoorn/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

Any ideas would be great!

**Comment by yitam** [comment]
hi @jotso the ODBC team is working to fix this known issue with OpenSSL. Please use the workaround I suggested in #1319

**Comment by jotso** [comment]
Hi @yitam thanks again, I think we have it up and running now!

**Comment by yitam** [comment]
Great, @jotso ! Closing this issue now.
