### ISSUE TITLE
[unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1' : file not found

### ISSUE THREAD

**Issue by huguijian** [microsoft/msphpsql#1328]
Hi,
Does Apline arm64 have unixODBC support ？
when I am using Apline amd unixODBC prompt [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1' : file not found.

**Comment by yitam** [comment]
Hi @huguijian 

For your information, if you have questions about unixodbc, please go to http://www.unixodbc.org/

About Microsoft ODBC driver and PHP drivers, we do not support Alpine arm64.

**Comment by achretien** [comment]
Hi @yitam as mentionned here https://github.com/microsoft/msphpsql/issues/1292, php sql driver on arm seems not to be a priority (like alpine wasn't few years ago).

How can we (php developers) push the ticket up in the stack for a future support ?

Our dev team works on mac computer with a docker dev stack (ubuntu or alpine images) so the mac lib is not an option.

Microsoft already released the azure sql server image with arm support which is great. The only missing piece for us to upgrade our dev mac to ARM is the php driver.

**Comment by yitam** [comment]
Closing this @huguijian as this is more or less a duplicate issue to #1292
