### ISSUE TITLE
PHP 8.1 compile problem

### ISSUE THREAD

**Issue by aimeos** [microsoft/msphpsql#1335]
## PHP Driver version or file name
 
5.9.0

## Client operating system

Ubuntu 20.04

## PHP version

8.1.0

## Problem description
 
libtool: compile:  g++ -I. -I/tmp/pear/temp/sqlsrv -I/tmp/pear/temp/pear-build-rootu1YWCO/sqlsrv-5.9.0/include -I/tmp/pear/temp/pear-build-rootu1YWCO/sqlsrv-5.9.0/main -I/tmp/pear/temp/sqlsrv -I/usr/include/php/20210902 -I/usr/include/php/20210902/main -I/usr/include/php/20210902/TSRM -I/usr/include/php/20210902/Zend -I/usr/include/php/20210902/ext -I/usr/include/php/20210902/ext/date/lib -I/tmp/pear/temp/sqlsrv/shared/ -DHAVE_CONFIG_H -std=c++11 -D_FORTIFY_SOURCE=2 -O2 -fstack-protector -std=c++11 -c /tmp/pear/temp/sqlsrv/shared/core_stmt.cpp -MMD -MF shared/core_stmt.dep -MT shared/core_stmt.lo  -fPIC -DPIC -o shared/.libs/core_stmt.o
/tmp/pear/temp/sqlsrv/shared/core_stmt.cpp: In constructor ‘sqlsrv_stmt::sqlsrv_stmt(sqlsrv_conn*, SQLHANDLE, error_callback, void*)’:
/tmp/pear/temp/sqlsrv/shared/core_stmt.cpp:165:5: error: ‘ZVAL_NEW_ARR’ was not declared in this scope; did you mean ‘ZVAL_NEW_STR’?
  165 |     ZVAL_NEW_ARR( &param_streams );
      |     ^~~~~~~~~~~~
      |     ZVAL_NEW_STR
make: *** [Makefile:226: shared/core_stmt.lo] Error 1
ERROR: `make' failed
The command '/bin/bash -exo pipefail -c sudo pecl install sqlsrv' returned a non-zero code: 1

**Comment by sigmacraig** [comment]
I'm also receiving the above when attempting to install using the described cmd for MacOS on M1 ARM.
```
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install sqlsrv
sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install pdo_sqlsrv
```

**Comment by yitam** [comment]
HI @aimeos and @sigmacraig 
We do not support PHP 8.1 and ARM Mac until [5.10 beta1](https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta1)
For ARM Mac please check the [instructions here](https://github.com/microsoft/msphpsql/blob/master/Linux-mac-install.md)

**Comment by aimeos** [comment]
@yitam The error occurs on x86/x64 platforms when compiling the driver for PHP 8.1

**Comment by yitam** [comment]
Yes, because 5.9.0 do not support PHP 8.1. Please try beta 1, wait for beta 2 or the release next year to use PHP 8.1 in any platforms

**Comment by yitam** [comment]
Closing this as PHP 8.1 is not supported by 5.9.0. [5.10.0-beta 2](https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta2) is just released.
