### ISSUE TITLE
Missing PHP 8.1 x64 DLLs on 5.10.0-beta2 release

### ISSUE THREAD

**Issue by kyleweishaupt** [microsoft/msphpsql#1339]
I saw the new release (5.10.0-beta2) today, and wanted to test it with PHP 8.1, but I noticed the x64 directory is missing from the release (Windows-8.1.zip). 

Is this an error or something I'm missing? Thank you!

## PHP Driver version or file name
 5.10.0-beta2
## SQL Server version
 Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19044: ) (Hypervisor) 
## Client operating system
 Windows 10 Professional 21H2 Build 19044.1387
## PHP version
 8.1.0
## Microsoft ODBC Driver version
 2017.177.02.01

**Comment by yitam** [comment]
@kyleweishaupt thanks for bringing this to our attention.
Updated now. Please check.

**Comment by kyleweishaupt** [comment]
I just downloaded the release again and see it in there now. Thank you very much @yitam!
