### ISSUE TITLE
Missing info on how to get libmsodbcsql sources

### ISSUE THREAD

**Issue by NiKiZe** [microsoft/msphpsql#1341]
## Client operating system
Linux (Gentoo)

## PHP version
7.3

## Microsoft ODBC Driver version
Missing!

## Problem description
No info on what is needed after `pecl install sqlsrv`
Searching all over the place we can find documentation on installing a ODBC driver for SUSE, RH, Ubuntu and so on, but there is no links to source tarballs and how to install it for other generic Linuxes.
### _so how do I get sources to build `libmsodbcsql-17.8.so.1.1`?_

Also why should I need a ODBC driver to use sqlsrv driver, If I still need the ODBC driver then why shouldn't I just use the ODBC driver directly?

So current state is `This extension requires the Microsoft ODBC Driver for SQL Server. Access the following URL to download the ODBC Driver for SQL Server for x64: https://go.microsoft.com/fwlink/?LinkId=163712` and that link is not helpful in any since it actually mostly seem to talk about how to install the PHP driver which is already installed?

## Expected behavior and actual behavior
`pecl install sqlsrv` should be all that is needed, no extra binary blobs, not even ODBC should be needed!

**Comment by yitam** [comment]
@NiKiZe FYI, ODBC driver is not open-sourced, as indicated in our [documentation here](https://docs.microsoft.com/sql/connect/odbc/linux-mac/frequently-asked-questions-faq-for-odbc-linux)

**Comment by NiKiZe** [comment]
So you want users to trust a binary blob?

**Comment by yitam** [comment]
If you're planning to use sqlsrv driver to connect to Microsoft SQL Server, sqlsrv requires the Microsoft ODBC Driver. It's really up to the users to trust it or not.
