### ISSUE TITLE
sqlcmd, Named instances with dynamic ports: Can not connect to MS SQL from Debian Error code 0x2AF9

### ISSUE THREAD

**Issue by Adi-18** [microsoft/msphpsql#1343]
### Problem description
Connection from Windows works but not from Linux:
sqlcmd -S x.x.100.102\TESTINST -U sa -P 'mypassword'

```
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2AF9.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. er is configured to allow remote connections. For more information see SQL Server Books Online..
```
I saw any call with double back slash, but this gives me other error
sqlcmd -S x.x.100.102\\\TESTINST -U sa -P 'mypassword'
```
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.
```

As described [here](https://github.com/microsoft/msphpsql/issues/927#issuecomment-519209651),  The latest release of the ODBC driver (V 17.4) should fix any issues with named instances and dynamic port on Linux

### SQL Server version
Microsoft SQL Server 2014 (SP1-CU13) (KB4019099) - 12.0.4522.0 (X64)
        Jun 28 2017 17:36:31
        Copyright (c) Microsoft Corporation
        Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

### Client operating system
Debian GNU/Linux 10 (buster)

### Microsoft ODBC Driver version
$ cat /etc/odbcinst.ini
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1
UsageCount=1

###Setup
As Instruction [here](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017).

**Comment by v-chojas** [comment]
Backslash needs to be escaped or the shell will interpret it, so either double it or enclose the server name in single quotes.
0x2746 = 10054 "connection reset by peer", check that firewall is not preventing the connection.

Also, are you using PHP driver at all? I don't see any mention of that here.

**Comment by Adi-18** [comment]
Thank you for response.

I installed php as descried [here](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15)

I don't have any firewall rules on Linux.also not on windows server. Access from windows client works.

**Comment by Adi-18** [comment]
Thank you. This helped me. Because of old version of sql server, I had to downgrade to MinProtocol = TLSv1 on linux and we use fix port now.
