### ISSUE TITLE
Problem upgrading from v13 to v17

### ISSUE THREAD

**Issue by rvyhmeister** [microsoft/msphpsql#1344]
Just tried to install today on a functioning system... Running RHEL 8.5 and PHP 7.4. Had the sqlsrv.so and pdo_sqlsrv.so, reported to be version 13 by Moodle, which requires a newer version of sqlsrv.so. So I installed 5.9.0 using these commands.

sudo pecl install sqlsrv-5.9.0
sudo pecl install pdo_sqlsrv-5.9.0

No problems with the build. Have MS ODBC 17 also installed...

Why does PHP still pick up the old driver? Or did the new build not build version 17?

Thanks in advance.

**Comment by rvyhmeister** [comment]
The issue is not the sqlsrv.so... it's the age of the SQL Server... sorry for the bother...

**Comment by v-mabarw** [comment]
Hi @rvyhmeister does this mean you have resolved your issue and it may be closed?

**Comment by rvyhmeister** [comment]
Yes, it can be closed...
