### ISSUE TITLE
Can't install msodbcsql17; libodbc1 and odbcinst1debian2 have unmet dependencies

### ISSUE THREAD

**Issue by d0niek** [microsoft/msphpsql#1346]
Hi,

I follow this guide https://docs.microsoft.com/pl-pl/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17 and I've created the simple **Dockerfile**

```Dockerfile
FROM php:7.4-fpm

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        gnupg \
    ; \
    \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -; \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list; \
    \
    apt-get update; \
    ACCEPT_EULA=Y apt-get install -y \
        msodbcsql17
```

When I want to build it I got an error:

```
+ apt-get install -y --no-install-recommends msodbcsql17
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libodbc1 : PreDepends: multiarch-support but it is not installable
odbcinst1debian2 : PreDepends: multiarch-support but it is not installable
E: Unable to correct problems, you have held broken packages.
```

When I remove **https://packages.microsoft.com/config/debian/10/prod.list** from **/etc/apt/sources.list.d/mssql-release.list** the packages `libodbc1` and `odbcinst1debian2` are available.

I sow some docker images here https://github.com/microsoft/msphpsql/issues/168 but I can't find why the simply **Dockerfile** fail.

Can I ask you for a help to correct my **Dockerfile** or MS guide?

**Comment by yitam** [comment]
Hi @d0niek , the guide you followed does not use `--no-install-recommends` , and you will need `ACCEPT_EULA=Y` as well. Installing ODBC driver would also install unixodbc (if not exists) for you. You might want to install `unixodbc-dev` *after* installing the ODBC driver, also as shown in the guide.

**Comment by d0niek** [comment]
Hi @yitam , thank you for your time.

`--no-install-recommends` just not install recommends packages. `libodbc1` and `odbcinst1debian2` are in `additional packages` section.

Yes, I forgot `ACCEPT_EULA=Y` in my code example (fixed above). With it there is the same error.

Now I see that I wrote my issue wrong. I can install `unixodbc(-dev)`, `libodbc1` and `odbcinst1debian2` before adding yours packages repository. When I `RUN` `curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list` then I got error I mention above.

**Comment by d0niek** [comment]
I sow yours **Dockerfile** examples https://github.com/microsoft/mssql-docker/tree/master/oss-drivers but they are so old. Is it possible to update it and use `php:*` images as base?

**Comment by yitam** [comment]
Hi @d0niek , I'm not sure if anyone maintains that mssql-docker repo.

That being said, if you want an example, you can check [my reply to the Alpine users](https://github.com/microsoft/msphpsql/issues/300#issuecomment-673143369)

I briefly tested the equivalent for Debian 10. The php script is the same as in my aforementioned reply. 

This is my install_drivers.sh:
```
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/source
s.list.d/mssql-release.list
apt-get update
ACCEPT_EULA=Y apt-get install -y msodbcsql17
apt-get install -y unixodbc-dev
```

My very basic Dockerfile:
```
FROM php:7.4.27-fpm-buster
ADD install_drivers.sh /tmp
ADD pdo_client_info.php /tmp
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
RUN apt-get update && apt-get install -y gnupg2 && \
    chmod +x /tmp/install_drivers.sh && \
    /tmp/install_drivers.sh && \
    install-php-extensions sqlsrv pdo_sqlsrv
```

These are my steps:
```
docker build -t myimage -f Dockerfile .
docker run --rm -tid --name mytest myimage
docker exec -it mytest bash
```

This is the output when running it interactively:
![image](https://user-images.githubusercontent.com/21340756/147161751-0c01e99c-a7e4-42b5-bd3f-387966a25678.png)

**Comment by d0niek** [comment]
Hi @yitam , ones more thank you for your time :-)

I have change php tag to `*-buster` and it's working. So it looks like you don't support `bullseye` yet? I will follow you :-)

Here is full **Dockerfile** to install `(pdo_)sqlsrv`

```Dockerfile
ARG PHP_VERSION=7.4


FROM php:${PHP_VERSION}-buster


RUN set -eux; \
	\
	ln -srf $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini


RUN set -eux; \
	\
	apt-get update; \
	apt-get install -y --no-install-recommends \
		gnupg \
		locales \
	; \
	curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -; \
	curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list; \
	\
	rm -rf /var/lib/apt/lists/*


RUN set -eux; \
	\
	sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen; \
	locale-gen


ARG SQLSRV_VERSION=5.9.0
RUN set -eux; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	\
	apt-get update; \
	ACCEPT_EULA=Y apt-get install -y --no-install-recommends \
		msodbcsql17 \
		unixodbc-dev \
	; \
	pecl install \
		pdo_sqlsrv-${SQLSRV_VERSION} \
		sqlsrv-${SQLSRV_VERSION} \
	; \
	pecl clear-cache; \
	docker-php-ext-enable \
		pdo_sqlsrv \
		sqlsrv \
	; \
	# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
	apt-mark auto '.*' > /dev/null; \
	apt-mark manual $savedAptMark; \
	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
		| awk '/=>/ { print $3 }' \
		| sort -u \
		| xargs -r dpkg-query -S \
		| cut -d: -f1 \
		| sort -u \
		| xargs -rt apt-mark manual \
	; \
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	rm -rf /var/lib/apt/lists/*
```

**Comment by yitam** [comment]
Great, @d0niek , I hope this works out for you! It also works in bullseye with ODBC using `https://packages.microsoft.com/config/debian/10/prod.list` but it's not officially supported yet. ;)

**Comment by yitam** [comment]
@d0niek since I have not heard from you since, I'm closing this issue. Please feel free to ask us to reopen.

**Comment by simonhammes** [comment]
@yitam Sorry for bothering you, but what do you mean by 

> It also works in bullseye with ODBC using `https://packages.microsoft.com/config/debian/10/prod.list` but it's not officially supported yet. ;)

The following Dockerfile does not work for me:

```Dockerfile
FROM php:7.4-apache-bullseye

ENV ACCEPT_EULA="Y"

RUN apt-get update && \
    apt-get install -y gnupg && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update -y && \
    apt-get install -y msodbcsql17 unixodbc-dev && \
    pecl install sqlsrv-5.9.0 && \
    docker-php-ext-enable sqlsrv
```

Error message:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libodbc1 : PreDepends: multiarch-support but it is not installable
 odbcinst1debian2 : PreDepends: multiarch-support but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by yitam** [comment]
Then in that case please wait for the next official ODBC release, @simonhammes
