### ISSUE TITLE
Using phpize

### ISSUE THREAD

**Issue by szepeviktor** [Microsoft/msphpsql#135]
Good afternoon!

Is it possible to compile pdo_sqlsrv with phpize on Linux?

**Comment by meet-bhagdev** [comment]
@szepeviktor Not yet but we are open to looking into this. Can you share why would you like to do this?

**Comment by szepeviktor** [comment]
AFAIK all open-source PHP extensions are compiled with phpize.
Maybe I am stuck in open-source and Debian...

**Comment by szepeviktor** [comment]
> The phpize command is used to prepare the build environment for a PHP extension.

http://php.net/manual/en/install.pecl.phpize.php

**Comment by Catscrash** [comment]
yes, that would be very important (is there an easier and less spammy way to do a +1?)

**Comment by szepeviktor** [comment]
> is there an easier and less spammy way to do a +1?

The upper right corner of comments contains a +smiley, `+1` is there.

**Comment by meet-bhagdev** [comment]
@szepeviktor @Catscrash We accepted @xalopp's PR which lets you compile the drivers with phpize. Can you take a look and help us validate?
