### ISSUE TITLE
Module incompatibility with PHP 8.1

### ISSUE THREAD

**Issue by neurogroups** [microsoft/msphpsql#1356]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 +5.10.0beta2
 +## Client operating system
 +Windows
 +## PHP version
 +8.1
 +## Problem description
 +I have an IIS server with PHP 8.1. Tried the 5.10.0beta2. Copied php_sqlsrv.dll to ext directory, and edited php.ini file to point to this. Restarted IIS and restarted computer. However, sqlsrv does not load in info.php. Running PHP in command prompt gives the following error:
PHP Warning:  PHP Startup: sqlsrv: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match

I read this error as that the PHP version is 8.1 (API=20210902), but sqlsrv.dll version is 8.0 (20200930).
I removed the previous .dll file and restarted IIS again, but the problem persists. 

Edit:
I downloaded the dll file from https://pecl.php.net/package/sqlsrv/5.10.0beta2/windows
Specifically https://windows.php.net/downloads/pecl/releases/sqlsrv/5.10.0beta2/php_sqlsrv-5.10.0beta2-8.0-nts-vs16-x64.zip
Filename says 8.0 Non Thread Safe (NTS) x64. I'm wondering if I got the wrong version. Is there a way to get a windows dll for php 8.1?

**Comment by yitam** [comment]
@neurogroups , make sure you download the right binaries from [5.10 beta2](https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta2)

![image](https://user-images.githubusercontent.com/21340756/150030512-49fac2a1-7d2a-4c5f-9bfe-a1d781fd2fbb.png)

**Comment by yitam** [comment]
If you prefer the one in pecl, please download the one for 8.1 nts as well
https://windows.php.net/downloads/pecl/releases/sqlsrv/5.10.0beta2/

**Comment by neurogroups** [comment]
This should work- sorry I missed that link. I'll use this and update.

**Comment by neurogroups** [comment]
This worked for me. Thanks for pointing me in the right direction!

**Comment by yitam** [comment]
Great! I'll close this issue then.

**Comment by FatimaDianfou** [comment]
Hello
can you help me to solve this problem please

Warning: PHP Startup: curl: Unable to initialize module
Module compiled with module API=20210902
PHP    compiled with module API=20230831
These options need to match
 in Unknown on line 0

   INFO  Running migrations.  

  2024_12_02_171812_create_locations_table ............................................... 63.60ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'tracked_at' (Connection: mysql, SQL: create table `locations` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `tracteur_id` bigint unsigned not null, `latitude` 
decimal(10, 8) not null, `longitude` decimal(11, 8) not null, `altitude` decimal(8, 2) null, `tracked_at` timestamp not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

  1   vendor\laravel\framework\src\Illuminate\Database\Connection.php:571
      PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'tracked_at'")

  2   vendor\laravel\framework\src\Illuminate\Database\Connection.php:571
      PDOStatement::execute()
