### ISSUE TITLE
PHP 7.1 - Unable to load extension, PHP 7.0.x is fine

### ISSUE THREAD

**Issue by brainfoolong** [Microsoft/msphpsql#137]
On Windows 10 64bit with PHP 7.1 beta2, i am unable to load php_sqlsrv_ts.dll, newest release from 4.1.0 Windows. https://github.com/Azure/msphpsql/releases/download/4.1.0/php_sqlsrv_4.1.0_x64.zip

I have installed Microsoft ODBC Driver 11, 12, 13.1 but nothing worked, i still cannot get the extension to load. If i switch back newest PHP 7.0.x (simply overwriting the files) and restart apache, all work fine with the 4.1.0 release from sqlsrv.

So, i have no idea how to fix this. Is it a bug in the sqlsrv driver or in PHP 7.1?

The exact and only error message i get is: ` in Unknown on line 0
[19-Aug-2016 05:55:14 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/srv/php7/ext\php_sqlsrv_7_ts.dll' - Die angegebene Prozedur wurde nicht gefunden.
 in Unknown on line 0`

With PHP 7.0.x there is no such error and all work as expected.

**Comment by jlucasvt** [comment]
I am having the same issue.  I am running PHP 7.1.10 TS with Apache2.4 on windows.

**Comment by sirio3mil** [comment]
I think isn't compatible yet, it is build for php 7.0 not for php 7.1. Read this [comment](https://github.com/Microsoft/msphpsql/issues/58#issuecomment-225601897).

**Comment by meet-bhagdev** [comment]
@all the drivers are not compatible with PHP 7.1 yet. We are looking into this and will keep you posted.

**Comment by brainfoolong** [comment]
@meet-bhagdev Is there any possibility to get the working driver now a timely manner for the release? Maybe in the RC state of PHP 7.1? Here we always want to use newest features but we mostly bound to this driver to use it in production. Nice work anyway, just ping you to get this faster done as with PHP 7 release.

**Comment by meet-bhagdev** [comment]
@brainfoolong Are you looking to use the driver with PHP 7.1? We are working on this actively and you will soon have a preview release that will work with PHP 7.1.

**Comment by brainfoolong** [comment]
@meet-bhagdev Exactly what i've meant. Thx for information.

**Comment by Hadis-Fard** [comment]
@brainfoolong the [4.1.3 release](https://github.com/Microsoft/msphpsql/releases/tag/v4.1.3-Windows) contains pre-compiled binaries for PHP 7.1.

**Comment by brainfoolong** [comment]
Thank you. Works great with newest RC candiate of PHP 7.1 - This is all what i've expected, a release of that driver before PHP 7.1 stable release. Great support, thanks.

**Comment by stevebauman** [comment]
Downloaded the RC drivers and works great for 7.1! Thanks for your guys hard work @meet-bhagdev :)

**Comment by masnuril** [comment]
I have downloaded [https://github.com/Microsoft/msphpsql/releases/tag/v4.1.3-Windows](4.1.3) release, and it's work like a charm

**Comment by nessroman** [comment]
I have the same problem. I have PHP 7.1.4 with XAMPP in Windows... and the driver does not work. I downloaded the 4.2.0 and 4.3.0 RC and does not work... anybody can help me?

**Comment by stevebauman** [comment]
@nessroman, you need to download the latest RC shown above:

https://github.com/Microsoft/msphpsql/releases/tag/v4.1.3-Windows

**Comment by nessroman** [comment]
@stevebauman I'm download the files from your link and using the _ts.dll  x64 and does not work  for me :(  ....

**Comment by stevebauman** [comment]
@nessroman Is your PHP installation 64 bit?

**Comment by nessroman** [comment]
Ohh Sorry @stevebauman My PHP is x86 and mi PC x64 ... this is the reason for the x64 dll does'nt work ... Thank you very much for your help. Now, my Windows XAMPP is configured, but I need the same in Ubuntu 16.04. Need enable the sqlserver driver for php 7.1 in Ubuntu, is my next adventure. Thanks !

**Comment by stevebauman** [comment]
Awesome @nessroman, glad you got it working! No problem :)

**Comment by saifulmujahid** [comment]
I'm using PHP 7.0.10 with Wamp in Windows 64 bit and downloaded drivers 4.0, 
php_pdo_sqlsrv_7_ts_x64.dll
php_sqlsrv_7_ts_x64.dll
Loaded them into the php extension file, and copied the file names into php.ini, but I still get this error; 'undefined function sqlsrv_connect()' 
I've gone through numbers of threads looking for solution. Can anyone help me?

**Comment by sirio3mil** [comment]
Hi @saifulmujahid it's usually cuz some missing pre requisites. Is wamp x64? Have you downloaded Microsoft ODBC Driver 13.1 for SQL Server?

**Comment by saifulmujahid** [comment]
Hi @sirio3mil yeah I'm using wamp x64, the driver is also x64, and yup, Microsoft ODBC Driver 13.1 SQL Server installation done. Where else could go wrong? I noticed the installed drivers didn't come out in the PHP extensions list though, does that bring a hint?

**Comment by sirio3mil** [comment]
Try to check wamp error log, if there are problems loading drivers should appear, if not, problems are before PHP try to load it.

**Comment by saifulmujahid** [comment]
This is the latest error I got when trying to run connection.php file. 

Uncaught Error: Call to undefined function sqlsrv_connect() in C:\wamp64\www\project2\connection.php:6
Stack trace:
#0 {main}
  thrown in C:\wamp64\www\project2\connection.php on line 6

**Comment by Hadis-Fard** [comment]
@saifulmujahid this error means that sqlsrv driver has not been loaded, could you post the result of `php -m` and the snippet of your ini file where you have enabled extensions. Also check `extension_dir` in the ini file and make sure it is pointing to the dll location

**Comment by saifulmujahid** [comment]
![extdir](https://user-images.githubusercontent.com/22440557/29443505-1cbbc288-840b-11e7-91ae-e78ccf4a0da7.png)
extension_dir
![iniphp](https://user-images.githubusercontent.com/22440557/29443507-22784c1e-840b-11e7-8f44-9fb5a7d336eb.png)
extensions in php.ini

Should I include the path along with each extension in php.ini? The php.ini edited is also the one located in 

> C:\wamp64\bin\apache\apache2.4.23\bin

I tried not including and including it and both still displayed the undefined error. Seriously, don't know what else to do. Sorry, how to get the result of `php -m`?

**Comment by sirio3mil** [comment]
It is not necessary to include the complete path with the library name.

Go to command line, navigate to your php folder and then write php -m command

**Comment by saifulmujahid** [comment]
![image](https://user-images.githubusercontent.com/22440557/29486551-51b8102a-851b-11e7-906e-49546a36ba3e.png)
Ran the php -m command. @sirio3mil , @Hadis-Fard  Hope this could provide useful info.

**Comment by saifulmujahid** [comment]
@Hadis-Fard what are you trying to look for?

**Comment by msufyanr** [comment]
![capture](https://user-images.githubusercontent.com/30657434/30847580-7912b8c0-a2b5-11e7-8d15-692f6a19ab3e.PNG)

help me out please.. dont know what to do ??

**Comment by kockica1234** [comment]
So i read everything on this page, and i still dont resolve this error. I have win 10 64bit and wamp server. I install newest ODBC driver from microsoft site and error still pop up. PhP work perfectly on my pc win 7, but on lap top it want. I m new at this and maybe i miss some step.I would be eternally grateful to anyone who help me out with this
![bez naslova](https://user-images.githubusercontent.com/37119796/37051090-dbd0828c-2175-11e8-9d59-6bfc9f08761e.png)
.

**Comment by yitam** [comment]
Hi @kockica1234 

Based on the error message the problem you see is not really related to this particular issue, nor is it related to our drivers.

Nonetheless, looks like `php_intl.dll` is missing in your env. [This](https://stackoverflow.com/questions/16372888/intl-extension-php-intl-dll-with-wamp) might be helpful to you.

If you have problems related to our drivers, please create a new issue, and we will be happy to assist you.

**Comment by shivamg42** [comment]
I am trying to run sqlsrv_71_nts_64, and i keep getting this message.
![image](https://user-images.githubusercontent.com/14073900/38224353-a06ba098-36bd-11e8-99af-b26e2ee69de9.png)

This is what my extension_dir looks like 
![image](https://user-images.githubusercontent.com/14073900/38224398-d5887dbe-36bd-11e8-8211-4acb9ab3c90b.png)
and these are the extensions I am looking at
![image](https://user-images.githubusercontent.com/14073900/38224416-ee1ff3d4-36bd-11e8-8ef1-b55ac48e9243.png)
Is anyone else getting this?

**Comment by yitam** [comment]
Hi @shivamg42 , please create a new issue and reference this instead. 

Looks like the sqlsrv dlls do not exist in your extension path. Can you double check that?
Also, what's the output of `php -v`?

**Comment by mokhosh** [comment]
I just installed mssql tools for php on a Debian 8 image with php 7.1 and have this issue.
It should be fixed with the latest version, right? 

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/pdo_sqlsrv.so' - /usr/lib/php/20160303/pdo_sqlsrv.so: undefined symbol: php_pdo_register_driver in Unknown on line 0
```

**Comment by yitam** [comment]
Hi @mokhosh 

Did you follow the installation [instructions](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-debian-8-and-9) and its dependencies like ODBC driver?

Also, have you checked our [FAQ](https://github.com/Microsoft/msphpsql/wiki/FAQ#what-is-this-error-php-startup-unable-to-load-dynamic-library-pdo_sqlsrvso) 

If you still need help, please create a new issue.

**Comment by ganyu** [comment]
@nessroman I have the same problem，according to your method, I have solved it. Thank you so much.

**Comment by ReneAG** [comment]
PHP version with php_sqlsrv version


https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver?view=sql-server-2017

**Comment by suchitarai** [comment]
Hi 
 have installed PHP 7.2.13,  Apache 2.4.37 (Win64) & MySQL 8.0.13 and wants to connect sqlsrv_connect but I got error  Uncaught Error: Call to undefined function sqlsrv_connect() in

**Comment by sincerodel** [comment]
Hello 

I have also installed sqlsrv on my Linux Ubuntu 16.04, I have read the thread above and downloaded the RC .zip. But how do I install or where to put that file when I am using Linux 16.04 .
Thank you very much.

**Comment by yitam** [comment]
@sincerodel please follow the [instructions here](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-ubuntu-1604-1804-and-1810) to get the latest release.

**Comment by sincerodel** [comment]
@yitam Thank you very much.

**Comment by yitam** [comment]
You're welcome @sincerodel 

Please create a new issue if you run into any problem but can't find an answer in our [FAQ](https://github.com/Microsoft/msphpsql/wiki/FAQ) or in other existing issues.

**Comment by shoaib0906** [comment]
![sqlsrv](https://user-images.githubusercontent.com/14304400/64709123-8d963780-d4d7-11e9-9c5a-310433303141.PNG)

![windows_specification](https://user-images.githubusercontent.com/14304400/64709220-bae2e580-d4d7-11e9-83a7-0e18a0e2875c.PNG)


Instead of being windows 64-bit operating system i never get any error message after coping thr x64-bit supported dll.I dont know why so that i tried for 4 days with different x64 bit dll of SQLSRV greater than 4.1 where as my php version is 7.1.9 and sql server 2008.

After all those tried i want to check from cmd using php --ini command then i found the error i attached and just replace a dll of x32 bit and its done :).

I am really happy now.so please test using cmd for better output.

**Comment by yitam** [comment]
hi @shoaib0906, please [download the PHP drivers](https://docs.microsoft.com/sql/connect/php/download-drivers-php-sql-server?view=sql-server-2017) to match the PHP version (7.1 or above), arch (x64 or x86) and thread (nts or ts) and read [how to load the drivers](https://docs.microsoft.com/sql/connect/php/loading-the-php-sql-driver?view=sql-server-2017)

**Comment by shoaib0906** [comment]
@yitam  thanks for comments and i solved already from previous comments.It was fantastic after few days to came into success.

**Comment by mnunesvsc** [comment]
SOLVED all my issues, just setting 

PHPInidir=<phppath> ( i.e. C:\PHP7 )
