### ISSUE TITLE
Difference in Size between ZIP and PECL

### ISSUE THREAD

**Issue by jansor** [microsoft/msphpsql#1370]
Hi this is more a question than an issue,

I noticed when i download the DLL file via PECL:
https://windows.php.net/downloads/pecl/releases/sqlsrv/5.10.0/php_sqlsrv-5.10.0-8.1-nts-vs16-x64.zip

And when i download it via the ZIP file under the tags release:
https://github.com/microsoft/msphpsql/releases/download/v5.10.0/Windows-8.1.zip

The size of the DLL is different?
In the PECL file the size of the DLL is only 206kb
While the DLL size from the Zip file is 334kb

Maybe u missing something here? Should the both dlls not be the same size? If not, whats the difference between those two sources then?

Thanks for the great work.

Kind regards Jan,

**Comment by yitam** [comment]
Hello @jansor 

If you extract the zip files you can see that the one from pecl contains the 64-bit dll and pdb for php 8.1, nts.

On the other hand, the zip we uploaded to the release contains the signed dlls (64-bit and 32-bit, no pdb) for php 8.1, both nts and ts.

Hope this clarifies things. :)

**Comment by jansor** [comment]
Hi, sorry no i mean the DLL file itself, after i extract them.
![image](https://user-images.githubusercontent.com/1769830/152386425-e72e4d63-b755-4d4f-8a28-8ed43f4b8320.png)

**Comment by yitam** [comment]
I see, @jansor. FYI, you can check the [build scripts](https://github.com/microsoft/msphpsql/blob/master/buildscripts/buildtools.py) that we use. For an example, you can take a look at [appveyor.yml](https://github.com/microsoft/msphpsql/blob/master/appveyor.yml) 

Maybe we could have made the binaries smaller, so please let us know if you find anything.

**Comment by jansor** [comment]
I have tested both version on different implementation on our side, and they both seems to be performing the same. 
Still strange that they have different file size. i would assume they have to be the same.

Anyhow both are working fine, only difference is file size. We can close this ticket.
