### ISSUE TITLE
[Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired 

### ISSUE THREAD

**Issue by ataur2** [microsoft/msphpsql#1373]
HI, 
Trying to create HANA remote source connection using SDA(Smart data access. ODBC MSSQL server connection created using remote source and connected successfully.

while doing test connection we are getting error SAP DBTech JDBC: [403] error.
 
Error message: SAP DBTech JDBC: [403]: internal error: Cannot get remote source objects: [Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired

[SDA Error.docx](https://github.com/microsoft/msphpsql/files/8088504/SDA.Error.docx)
)
![Error SDA](https://user-images.githubusercontent.com/99881298/154479291-f571ea79-e4eb-46fc-9e92-96c1f6c342b9.JPG)

Please suggest to resolve the issue.

Regards,

**Comment by absci** [comment]
Hi, this looks like a connectivity issue. It is sometimes caused by firewall blocking access to the port you're connecting to. Try to connect outside of this application use sqlcmd and ODBC driver, see if it's possible to make the connection.

**Comment by satyaarek** [comment]
Hi @ataur2  I am getting the same error, do you mind sharing how you resolved this issue?
