### ISSUE TITLE
pdo_sqlsrv issue: TCP Provider: Error code 0x68 (with more detailed info)

### ISSUE THREAD

**Issue by deniscsz** [microsoft/msphpsql#1375]
## **PHP version**  
PHP 8.0 (tested with PHP 8.1 also)

## **PHP SQLSRV or PDO_SQLSRV version**  
pdo_sqlsrv 5.10.0
sqlsrv 5.10.0

## **SQL Server version**  
Microsoft SQL Server 2012 (SP3-CU4) (KB3165264) - 11.0.6540.0 (X64)

## **Microsoft ODBC Driver version**
ODBC Driver 17 for SQL Server

## **Client operating system**  
Ubuntu 20.04

## **Problem description**  
I'm facing the error `SQLSTATE[08S01]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x68 (SQL: select [NOME] from [PAISES])`.

It is exact the same problem from here: https://github.com/microsoft/msphpsql/issues/809
But I was able to discover more details about it: It just happens after the request get more than a specific quantity of data.

I'm testing with a very simple table:

    SELECT p.HANDLE, p.NOME, p.CODE FROM PAISES p WHERE p.HANDLE < 10;

it works.

Trying with `p.HANDLE < 20` works but after `p.HANDLE < 30` I face the 0x68 error.

I'm also able to get all the rows just with:

    SELECT p.HANDLE FROM PAISES p WHERE p.HANDLE;

The table has aprox 300 records. When I add more columns to the select I face the error again.

These facts make me think about: it looks related with the size of the "data" or the "package" fetched. 

So  I tried change the `sqlsrv.ClientBUfferMaxKBSize` to a bigger number (very big) but it didn't work. I also tried the same for `pdo_sqlsrv.client_buffer_max_kb_size` but didn't work.

Is there some other kind of configuration to the size of data transferred or to be fetched?

**Comment by absci** [comment]
This is usually a network environment issue, and the server closed the connection. I don't think changing client buffer to a big number would help. If possible, try to use a packet analyzer and see if there's any network connection problem.

**Comment by deniscsz** [comment]
The problem was caused by an issue between the ISP and our corporate VPN.
