### ISSUE TITLE
Trying to connect Microsoftsql server 2016 with PHP also used Xampp 

### ISSUE THREAD

**Issue by alanamdhari** [microsoft/msphpsql#1376]
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
**Client operating system**  

**Table schema**  

**Problem description**  

**Expected behavior and actual behavior**  

**Repro code or steps to reproduce**

**Comment by absci** [comment]
Hi, please check if `TCP/IP` enabled in SQL Server Configuration Manager. Make sure the user has the right permissions to login, and the port not blocked by firewalls etc.

**Comment by alanamdhari** [comment]
Please explain how to check for the permission and login yes TCP\IP is enabled but i am facing a lot of issues in connection the page

**Comment by absci** [comment]
> Please explain how to check for the permission and login yes TCP\IP is enabled but i am facing a lot of issues in connection the page

For example, is port 1433 accessible by the client?

**Comment by absci** [comment]
Close due to inactivity, feel free to reopen if there's any updates.
