### ISSUE TITLE
Different handling when retrieving results on different platforms

### ISSUE THREAD

**Issue by pculka** [microsoft/msphpsql#1384]
Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following (skipping questions might delay our responses):

**PHP version**  
7.4
**PHP SQLSRV or PDO_SQLSRV version**  
5.10

**Microsoft ODBC Driver version**  
18

**SQL Server version**  
2017

**Client operating system**  
AlpineLinux, Ubuntu via WSL2 and Windows

**Table schema**

**Problem description**  
So we stumbled upon a problem with our Symfony (v4) application using Doctrine. We have everything correctly set up, but one user filed an error report, which led us to debug and find the following.
If a table schema has a varchar column with special characters (encoded with 2+ bytes), retrieval fails on Ubuntu/Alpine, but works on Windows.
In our case we had a length 30 column of varchar populated fully with 1 special character "Š" (https://www.fileformat.info/info/unicode/char/0160/index.htm) The byte length exceeded 30 bytes (as Š is multibyte). This resulted in an empty result being sent over into linux client without any errors. Windows client got the result fully populated and correctly displayed.

**Expected behavior and actual behavior**  
The result sets should be same across different operating systems.

**Repro code or steps to reproduce**
1. Set up a simple symfony project with doctrine entity manager
2. Create a simple entity of string (which should map to varchar) of a specific length, don't forget the ID
3. Insert some data, mind that for some rows fully populate the varchar string column with simple characters and for other rows with multibyte characters.
4. retrieve them via CLI, or Controller by using the ID
5. Compare on PHP on Linux vs PHP on Windows

**Comment by absci** [comment]
Thanks for the report, it's under investigation. Could you specify which driver you're using `pdo_sqlsrv` or `sqlsrv`?

**Comment by absci** [comment]
If you're using sqlsrv, try adding `'characterset' => 'utf-8'` to your connection string see if that fix the problem. When I store Š to varchar and retrieve it without characterset in connection string it won't print anything because an error occurred. You could use `sqlsrv_errors(SQLSRV_ERR_ERRORS);` to get the error message.

**Comment by absci** [comment]
Close due to inactivity, feel free to reopen if there's any updates.
