### ISSUE TITLE
reusing prepared statement PDSQLSRV510 

### ISSUE THREAD

**Issue by HerveAN** [microsoft/msphpsql#1393]
**PHP version**  8.1.6

**PHP SQLSRV or PDO_SQLSRV version**  5.10

**Microsoft ODBC Driver version**  17

**SQL Server version**  14

**Client operating system**  windows 11

**Table schema**  CREATE TABLE [dbo].[cache](
	[cac_id] [int] IDENTITY(1,1) NOT NULL,
	[cac_key] [nvarchar 255] NULL,
	[cac_is_object] [smallint] NULL,
	[cac_end_time] [datetime] NULL,
	[cac_value] [nvarchar max] NULL,
 CONSTRAINT [PK_cache] PRIMARY KEY CLUSTERED 
(
	[cac_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

**Problem description**  when reusing prepared statement updating nvarchar(max) field i sometimes get this error : 
 [Microsoft][ODBC Driver 17 for SQL Server]Troncation à droite de la chaîne de données
It works fine with php8.0 bugs with php 8.1

**Repro code or steps to reproduce**
connection string :
$dbh= new PDO('sqlsrv:Server='.MPI_HOST.";Database=".MPI_NAME.";MultipleActiveResultSets=true;", MPI_USER, MPI_PASSWORD,
				array(PDO::ATTR_EMULATE_PREPARES => false,
                                         PDO::ATTR_ERRMODE => PDO::ERRMODE_SILENT,
                                         PDO::SQLSRV_ATTR_FORMAT_DECIMALS => true));

$sql="update cache set cac_value=? where cac_key='test'";
$stmt=$dbh->prepare($sql);
$stmt->execute(array($stringOfDataLengthLowerThan1000));
ok
$stmt->execute(array($stringOfDataLengthGreaterThan10000));
error with truncation message

If i do the first execute with the bigger string parameter it works fine.
If the first parameter is greater than  a limit (let's say datalength>5000) then the second will execute ok even if it's much bigger.

**Comment by absci** [comment]
I think this is related to #1391, it's under investigation. Thanks for providing the details.

**Comment by absci** [comment]
The fix has been merged, so close this now.
