### ISSUE TITLE
No mechanism to assign language during login.

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#14]
Hi.  

Having called sqlsrv_connect(), sqlsrv_errors() reports 2 entries.  

The first relates to the "Changed database context", which is appropriate for
my call (I'm setting the 'Database' option).  

The second is SQLSTATE 01000, code 5703, message "[Microsoft][SQL Server
Native Client 10.0][SQL Server]Changed language setting to us_english.".  

Being a British English speaker, I'd like the option of setting the language
as part of the configuration in some way.  

But I can't see if this is possible in any way.  

Regards,  

Richard Quadling.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 16935](http://sqlsrvphp.codeplex.com/workitem/16935)
**Status:** Closed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Mar 23, 2010 at 4:28 PM
**Reported by:**    RQuadling
**Updated on:** Jul 17, 2010 at 8:33 PM
**Updated by:** AshayC
**Closed on:**  Jul 17, 2010 at 8:33 PM

**Comment by vrobert78** [comment]
Hi,

we have the same need.
At this time we use a  `sqlsrv_query($this->bdd, 'SET LANGUAGE us_english');` as a workaround.

Regards,

Vincent
