### ISSUE TITLE
PHP 8.1.0 and 8.1.8 NTS SQLsrv

### ISSUE THREAD

**Issue by NBGTX** [microsoft/msphpsql#1401]
Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following (skipping questions might delay our responses): Yes. Checked that and issues. Didn't see anything.

**PHP version**  8.1 and 8.1.8 NTS 64bit

**PHP SQLSRV or PDO_SQLSRV version**  php_pdo_sqlsrv_81_nts & php_sqlsrv_81_nts

**Microsoft ODBC Driver version**  ODBC Driver 17 for SQL Server (2017.177.02.01) and ODBC Driver 18 for SQL Server (2018.180.01.01)

**SQL Server version**  2019 (15.0.2095.3 x64)

**Client operating system**  Windows 10

**Table schema**  ??

**Problem description**  
Getting these errors when running PHP version 8.1.0 and 8.1.8

PHP Warning:  PHP Startup: Unable to load dynamic library 'php_pdo_sqlsrv_81_nts' (tried: C:\php\ext\php_pdo_sqlsrv_81_nts (The specified module could not be found), C:\php\ext\php_php_pdo_sqlsrv_81_nts.dll (The specified module could not be found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_sqlsrv_81_nts' (tried: C:\php\ext\php_sqlsrv_81_nts (The specified module could not be found), C:\php\ext\php_php_sqlsrv_81_nts.dll (The specified module could not be found)) in Unknown on line 0
PHP 8.1.0 (cli) (built: Nov 23 2021 21:46:10) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies

**Expected behavior and actual behavior**  
Expected (will return different version though)
PHP 8.0.21 (cli) (built: Jul  6 2022 11:18:53) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.21, Copyright (c) Zend Technologies

Expected (will return different version though)
PHP 7.3.33 (cli) (built: Jul  6 2022 11:18:53) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.21, Copyright (c) Zend Technologies

**Repro code or steps to reproduce**
Installed per instructions. Works fine on 8.0.21 and 7.3 on same machine.

**Comment by NBGTX** [comment]
From 8.1.8 but same in 8.1.0

![PHP2](https://user-images.githubusercontent.com/101874775/178990981-3ef3a4e1-4780-431b-9ee6-638248e6c818.png)
![PHP1](https://user-images.githubusercontent.com/101874775/178990984-7d1bc803-2fcb-4d2a-b4e3-68a5d80a1485.png)

**Comment by NBGTX** [comment]
Actually, same response for 8.0 I had forgot to save the config file. So I cannot get it to work for PHP 8.0, 8.1, or 8.1.8. Also using IIS on Windows if that helps.

**Comment by NBGTX** [comment]
@absci 

Sigh. Sorry for everybody's time. I did not. Thought I had, but looking through it, had not........sorry

**Comment by absci** [comment]
No worries, I'll close this issue now.
