### ISSUE TITLE
PHP FPM exit with signal 8 (SIGFPE - core dumped)

### ISSUE THREAD

**Issue by oxycoder** [Microsoft/msphpsql#141]
OS: Ubuntu 16.04 with Nginx
Driver: 4.0.3
Tested on PHP-FPM 7.0.8 and 7.0.10 give same result

```
unixODBC 2.3.1
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/frost/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

/var/log/php7.0-fpm.log
```
[26-Aug-2016 00:55:17] WARNING: [pool www] child 72407 exited on signal 8 (SIGFPE - core dumped) after 1064.849232 seconds from start
[26-Aug-2016 00:55:17] NOTICE: [pool www] child 72657 started
```

/var/log/syslog
`Aug 26 00:55:13 api kernel: [ 5691.115511] traps: php-fpm7.0[72407] trap divide error ip:7f2fb56b6cec sp:7ffeaa469b10 error:0 in php_pdo_sqlsrv_7_nts.so[7f2fb565a000+8d000]`

This error will return 502 Bad Gateway on nginx because PHP process crash. It happen with Update query.

**Comment by savvior** [comment]
Similar issue with Apache2 on Ubuntu 16.04 using the 4.0.3 drivers.  Definitely broken with parameterized update queries.

[Fri Aug 26 11:10:27.531094 2016] [core:notice] [pid 21449] AH00051: child pid 23078 exit signal Floating point exception (8), possible coredump in /etc/apache2
[Fri Aug 26 11:10:56.557670 2016] [core:notice] [pid 21449] AH00051: child pid 21615 exit signal Segmentation fault (11), possible coredump in /etc/apache2

**Comment by meet-bhagdev** [comment]
@oxycoder @savvior We will look into this.

**Comment by meet-bhagdev** [comment]
@oxycoder @savvior Can you share a repro script and a schema that we can use to reproduce this in our test lab?

**Comment by oxycoder** [comment]
I just start wrote a small script and test on my vmware, I realize that I have a mistake on my code (As driver 4.0.2 and before, the code still work)
```php
<?php
$user = 'sa';
$pass = '123';
$out1 = '';
$out2 = '';
try {
	$db = new PDO("sqlsrv:Server=10.0.1.50,1433;Database=TestDB", $user, $pass);
	$sth = $db->prepare("EXEC [dbo].Create_Account ?, ?, ?");
	$sth->bindValue(1, 'tester00001');
	$sth->bindValue(2, '123456');
	$sth->bindValue(3, 'abc@cde.com');
	$sth->bindValue(4, $out1);
	$sth->bindValue(5, $out2);
	$sth->execute();
	echo $out1 . '\n';
	echo $out2 . '\n';
} catch(Exception $e) {
	var_dump($e);
}
?>
```
```sql
ALTER PROC [dbo].[Create_Account]
	@username	nvarchar(50),
	@password nvarchar(50),
	@email nvarchar(255),
	@order_idx		int	OUTPUT,
	@v_error		tinyint	OUTPUT
AS
SET NOCOUNT ON
BEGIN TRAN
	INSERT users (username, password, email) VALUES (@username, @password, @email)
	SET @order_idx = 1
	SET @v_error = 1
COMMIT TRAN
```
From the stored procedure above, the output return has type int, but in my php code, I define it as ''.
After change the value to int, the error gone away.
```php
$out1 = 0;
$out2 = 0;
```

**Comment by oxycoder** [comment]
Another problem about empty can make php-fpm process crash too, the log from system also about "trap divide error"

```sql
ALTER PROC [dbo].[Update_Account]
	@username	nvarchar(50),
	@password nvarchar(50),
	@email nvarchar(255),
	@last_login datetime,
	@order_idx		int	output,
	@v_error		tinyint	OUTPUT
AS
SET NOCOUNT ON
BEGIN TRAN
UPDATE users SET password = @password, email = @email, last_login = @last_login WHERE username = @username
SET @order_idx = 1
SET @v_error = 1
COMMIT TRAN
```

PHP code
```php
<?php
$user = 'sa';
$pass = '123';
$out1 = 0;
$out2 = 0;
try {

	$db = new PDO("sqlsrv:Server=10.0.1.50,1433;Database=TestDB", $user, $pass);
	$sth = $db->prepare("EXEC [dbo].Update_Account ?, ?, ?");
	$sth->bindValue(1, 'tester00001');
	$sth->bindValue(2, ''); // PHP-FPM crash
	$sth->bindValue(3, 'abcupdated@cde.com');
	$sth->bindValue(4, '2022-01-01 00:00:00.000');
	$sth->bindValue(5, $out1);
	$sth->bindValue(6, $out2);
	$sth->execute();
	echo $out1 . '\n';
	echo $out2 . '\n';

} catch(Exception $e) {
	var_dump($e);
}
?>
```
Workaround this problem:
```php
$sth->bindValue(2, "''"); // wrap single quote with double quote
```

**Comment by meet-bhagdev** [comment]
@oxycoder both the issues referenced above are fixed by our latest release: https://github.com/Microsoft/msphpsql/releases/tag/4.0.4-Linux. Can you help us verify?
