### ISSUE TITLE
When is the next patch release date? PHP 8.1 Doctrine compatibility.

### ISSUE THREAD

**Issue by talkinnl** [microsoft/msphpsql#1414]
Multiple fixes have landed since the last release in may, and especially changeset https://github.com/microsoft/msphpsql/pull/1408 fixed multiple issues.

If I'm honest (maybe it's my Dutch directness, sorry for that) : 
Without that fix, I'd consider SqlServer to be incompatible with PHP8.1 + Doctrine.

We've got a pretty big application, but this is our only blocker still left to upgrade to PHP 8.1

May I ask if and when a new patch release is to be expected?

**Comment by v-makouz** [comment]
There is no ETA for a fix in 5.10. However the fix will definitely be in the 5.11 release. Beta 5.11 is targeting early Dec with GA at the end of January.

**Comment by deancsmith** [comment]
This is also the only blocker for us to go to PHP 8.1, also with a moderate application using Doctrine.

**Comment by thsmrtone1** [comment]
+1 especially considering the README claiming to support PHP 8.1

**Comment by absci** [comment]
As of now, 8.1 is supported. Close this old issue.
