### ISSUE TITLE
Question: where is /tmp/pear/temp/sqlsrv/configure from in the source code

### ISSUE THREAD

**Issue by ningji** [microsoft/msphpsql#1416]
1st of all this is not a bug, but a question on the source code.
We need this driver for M1 on Alpine docker desperately, so i'm trying to see if i can cross compile it from Ubuntu 1st.

`#sudo pecl install sqlsrv`
has the following outputs, somehow it has more files than the code from "git clone".

Anyone knows how to get these files pls ?

```
Starting to download sqlsrv-5.10.1.tgz (193,661 bytes)
.........................................done: 193,661 bytes
34 source files, building
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
building in /tmp/pear/temp/pear-build-rootmePJ4e/sqlsrv-5.10.1
running: /tmp/pear/temp/sqlsrv/configure --with-php-config=/usr/bin/php-config
```

**Comment by MichaelSun90** [comment]
Hi @ningji , there is a [doc ](https://github.com/microsoft/msphpsql/blob/master/buildscripts/README.md)for compiling PHP manually. see if these steps helps.

**Comment by ningji** [comment]
@MichaelSun90 Thx for the link, that looks like for windows. i'm more looking for the source for the Linux build, then try to see if i can cross compile it for M1 chip.

**Comment by v-makouz** [comment]
Currently ODBC driver (that PHP driver uses) does not support Alpine on ARM64, so this setup (Alpine on M1) might not be possible at the moment.

**Comment by absci** [comment]
Alpine and ARM64 supported added with ODBC version 18.3.1. 
https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/release-notes-odbc-sql-server-linux-mac?view=sql-server-ver16#1831-july-2023
