### ISSUE TITLE
Where to put certificates in Linux?

### ISSUE THREAD

**Issue by amcsi** [microsoft/msphpsql#1417]
I'm using Ubuntu 22.04, PHP 8.1, this extension's 5.10.1 version.

I'm getting this error: `[Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:0A000086:SSL routines::certificate verify failed:unable to get local issuer certificate]`

But I have a certificate I would like to use for this connection (namely, AWS's). How do I tell the SQL Server PDO extension about my certificate so it would use it and it would not complain about this local issuer certificate thing?

**Comment by talkinnl** [comment]
Not related to your question, but please be warned about https://github.com/microsoft/msphpsql/issues/1414 
The 5.10 releases needed for PHP 8.1 are buggy if you (or your ORM) reuses a Statement inside a loop.

**Comment by v-makouz** [comment]
On Ubuntu, certificates go into `/etc/ssl/certs`, this doc describes it in more detail:
https://learn.microsoft.com/en-US/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-ver16

**Comment by amcsi** [comment]
Thanks, this was a great hint that I wasn't able to find in the docs.

Unfortunately it wasn't enough to put AWS's `global-bundle.pem` file in `/etc/ssl/certs` to make it work. I'm still getting the same error.
I followed all the advice on this [AskUbuntu](https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line) question:
* I was able to get `sudo dpkg-reconfigure ca-certificates` to pick up on my cert (after converting it from pem to crt)
* I confirmed the right chmod permissions
* I tried moving the pem directly in `/etc/ssl/certs` too
* I restarted nginx and the php-fpm servers

...all to no avail. Is someone really able to connect to an AWS Sql Server database in Ubuntu 22.04? Though maybe this ought to be a StackOverflow/AskUbuntu question.

**Comment by v-makouz** [comment]
The nameof the .pem file has to be set to a specific number based on the certificate hash. The easiest way to find out I know of to find out what the name should be is to `strace` the command.
i.e. `strace isql -v -k "DRIVER={ODBC Driver 18 for SQL Server};SERVER=...;UID=...;PWD=..."` 

In the output there should be something like `newfstatat(AT_FDCWD, "/usr/lib/ssl/certs/<FILENAME>", 0xXXXXXXXXXXX, 0) = -1 ENOENT (No such file or directory)`.   Note: `/usr/lib/ssl/certs` is just a symlink to `/etc/ssl/certs`

That filename is what it's looking for, so if you rename or symlink the .pem file that in `/etc/ssl/certs` to that, it should work.

**Comment by amcsi** [comment]
@v-makouz wow that actually worked! Thanks, I didn't find any info like what you wrote anywhere.

I'm closing this ticket, because I consider it resolved.

**Comment by amcsi** [comment]
For future reference the cert filename that the PHP extension looks at is `/etc/ssl/certs/df65e9bd.0`.

So this is what you need to run to make sure that ODBC 18 can connect to RDS instances:

```sh
certFilename=/usr/local/share/ca-certificates/global-bundle.crt
sudo wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -O $certFilename
sudo ln -snf $certFilename /etc/ssl/certs/df65e9bd.0
```
