### ISSUE TITLE
A band aid for Physical connection is not usable or similar errors

### ISSUE THREAD

**Issue by keskinonur** [microsoft/msphpsql#1418]
👋🏻

### Problem definition
In Linux, with PHP 8.1.x, I got error like;

`
SQLSTATE[08S01]: [Microsoft][ODBC Driver 18 for SQL Server]Session Provider: Physical connection is not usable [xFFFFFFFF].
`

And throw exception. After searching mainly in this repo, I try some classical solutions;

- Update/upgrade unixodbc, sqlsrv, pdo_sqlsrv and even PHP 🥲
- Set SQLSRV_ATTR_QUERY_TIMEOUT and SQLSRV_ATTR_CLIENT_BUFFER_MAX_KB_SIZE

But nothing works for me.

### Problem solution / quick fix
After reading more details from [Microsoft Drivers for PHP for SQL Server](https://learn.microsoft.com/en-us/sql/connect/php/microsoft-php-driver-for-sql-server) documentation, I come up with this solution;

Disable SQL preparation!  Just set SQLSRV_ATTR_DIRECT_QUERY to true and you are good to go 👍🏻

`$conn->setAttribute(PDO::SQLSRV_ATTR_DIRECT_QUERY, true);`

I hope this will help.

**Comment by v-makouz** [comment]
Thank you for the workaround. Can you give repro steps for the original issue?

**Comment by andremartinez** [comment]
Just tested this "band aid" and it works

I'll test this further, if the problem show up again I'll  comment on what I found

**Comment by absci** [comment]
Close due to inactivity
