### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by fezfez** [microsoft/msphpsql#1420]
Hello,

We are unable to install sqlsrv for php 8.2

```
downloading sqlsrv-5.10.1.tgz ...
Starting to download sqlsrv-5.10.1.tgz (193,661 bytes)
.........................................done: 193,661 bytes
34 source files, building
running: phpize
Configuring for:
PHP Api Version:         20220829
Zend Module Api No:      20220829
Zend Extension Api No:   420220829
configure.ac:165: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:165: You should run autoupdate.
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:165: the top level
building in /tmp/pear/temp/pear-build-defaultusereAj3I6/sqlsrv-5.10.1
running: /tmp/pear/temp/sqlsrv/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20220829 -I/usr/include/php/20220829/main -I/usr/include/php/20220829/TSRM -I/usr/include/php/20220829/Zend -I/usr/include/php/20220829/ext -I/usr/include/php/20220829/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20220829
checking for PHP installed headers prefix... /usr/include/php/20220829
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable sqlsrv functions... yes, shared
checking for SQLSRV headers... /tmp/pear/temp/sqlsrv/shared/
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking for clang++... no
checking whether the compiler supports GNU C++... no
checking whether g++ accepts -g... no
checking for g++ option to enable C++11 features... none needed
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/tmp/pear/temp/pear-build-defaultusereAj3I6/sqlsrv-5.10.1':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
ERROR: `/tmp/pear/temp/sqlsrv/configure --with-php-config=/usr/bin/php-config' failed
```

Can you add support for php 8.2 ?

Thanks in advance !

**Comment by v-makouz** [comment]
Support for PHP 8.2 is planned. I was able to build the PHP Driver from source using the PHP 8.2 alpha and it appears to work, so if you want to have it before official release that may be an option.

**Comment by fezfez** [comment]
> Support for PHP 8.2 is planned. I was able to build the PHP Driver from source using the PHP 8.2 alpha and it appears to work, so if you want to have it before official release that may be an option.

we are unable to compile for php 8.2 (see logs above) :neckbeard:

**Comment by fezfez** [comment]
> > Support for PHP 8.2 is planned. I was able to build the PHP Driver from source using the PHP 8.2 alpha and it appears to work, so if you want to have it before official release that may be an option.
> 
> we are unable to compile for php 8.2 (see logs above) :neckbeard:

My bad, it's working :muscle:

**Comment by cedx** [comment]
PHP 8.2 was released today!

**Comment by piotrekz5** [comment]
Can you provide a release for the latest PHP version?

**Comment by przemo-hemmersbach** [comment]
Got one of our apps running on php8.2 alpine fpm official image, with drivers installed like for 8.1.
All tests pass and app. But have no opportunity to release to PROD for now.
@v-makouz  is there anything in particular that is planned for 8.2 ? Is there a chance that current series will get point release with official 8.2 support? Thank you!

**Comment by v-makouz** [comment]
@przemo-hemmersbach There likely will be a release in January with the PHP 8.2 support.

**Comment by utqinadhif** [comment]
> @przemo-hemmersbach There likely will be a release in January with the PHP 8.2 support.

My linux can connect with freetds and php-sybase, but my windows need the lib, i always wait the moment

**Comment by utqinadhif** [comment]
> @przemo-hemmersbach There likely will be a release in January with the PHP 8.2 support.

can you tell me about the date?

**Comment by piotrekz5** [comment]
Release in January? - are you aiming for 31 January? ;)

**Comment by v-makouz** [comment]
Beta version of the driver with PHP 8.2 support is available now

**Comment by angelyovanny** [comment]
I download the drivers and it still tells me that it is in version 8.1.

**Comment by cedx** [comment]
@angelyovanny Have you tried https://github.com/microsoft/msphpsql/releases/tag/v5.11.0-beta1 ?
