### ISSUE TITLE
Hi im getting this error

### ISSUE THREAD

**Issue by Mesut1979** [microsoft/msphpsql#1421]
could somebody help me whit this issue or error i dont know what to do.
PDO error when working with database: SQLSTATE[42S22]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'originalPassword'.

**Comment by Mesut1979** [comment]
[](url)

**Comment by Mesut1979** [comment]
i find out it was the vote table and query script USE [Auction]
GO

/****** Object:  Table [dbo].[vote]    Script Date: 2022-11-12 09:06:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[vote](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [char](50) NULL,
	[prize] [int] NULL,
	[link] [text] NULL,
	[image] [text] NULL,
 CONSTRAINT [PK_vote] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


sorry im new here, but i solve the problem there is no issue on this script now.

**Comment by Mesut1979** [comment]
here is the new issue i have im trying to edit item mall item on my webpage but it says.
PDO error when working with database: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 's'.
 here is the script for sql query 
USE [Auction]
GO

/****** Object:  Table [dbo].[ItemMall]    Script Date: 2022-11-12 09:00:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ItemMall](
	[ItemName] [char](50) NOT NULL,
	[ItemPrice] [int] NOT NULL,
	[ItemDesc] [text] NOT NULL,
	[Quota] [int] NOT NULL,
	[Icon] [char](10) NOT NULL,
	[cType] [char](10) NOT NULL,
	[ItemID] [int] NOT NULL,
	[quantity] [int] NOT NULL,
	[category] [char](15) NOT NULL,
	[MallID] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

**Comment by v-makouz** [comment]
I see the create table queries, but what is the PHP application trying to do when you get these errors? Is it executing the create table queries, or is it trying to insert/select from said tables?

**Comment by absci** [comment]
Close due to inactivity
