### ISSUE TITLE
Missing DLL Files on PECL

### ISSUE THREAD

**Issue by jrose323** [microsoft/msphpsql#1431]
Both SQLSRV and PDO_SQLSRV are missing the windows DLL files for version 5.10.1 and 5.11.0 Beta1

**Comment by absci** [comment]
Hi, DLLs can be found on Github release -> Assets section (https://github.com/microsoft/msphpsql/releases).

**Comment by v-mabarw** [comment]
To add to this, the Windows PECL build machine is currently unavailable so until that is resolved you can find the DLLs in the releases.  For more details and updates, please refer to https://windows.php.net/
