### ISSUE TITLE
 PHP Startup: Unable to load dynamic library Unable to initialize module

### ISSUE THREAD

**Issue by minemint** [microsoft/msphpsql#1437]
Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following (skipping questions might delay our responses):

**PHP version**  
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_sqlsrv_81_nts_x64' (tried: c:/wamp64/bin/php/php8.2.0/ext/php_sqlsrv_81_nts_x64 (The specified module could not be found), c:/wamp64/bin/php/php8.2.0/ext/php_php_sqlsrv_81_nts_x64.dll (The specified module could not be found)) in Unknown on line 0

PHP Warning:  PHP Startup: Unable to load dynamic library 'php_pdo_sqlsrv_81_nts_x64' (tried: c:/wamp64/bin/php/php8.2.0/ext/php_pdo_sqlsrv_81_nts_x64 (The specified module could not be found), c:/wamp64/bin/php/php8.2.0/ext/php_php_pdo_sqlsrv_81_nts_x64.dll (The specified module could not be found)) in Unknown on line 0

PHP Warning:  PHP Startup: sqlsrv: Unable to initialize module

Warning: PHP Startup: pdo_sqlsrv: Unable to initialize module

**Comment by minemint** [comment]
this help
![image](https://user-images.githubusercontent.com/106004714/219736337-1559f108-51bc-4590-925a-dd2f5da2d8a5.png)

**Comment by v-makouz** [comment]
It looks like there is a mismatch, php_php_sqlsrv_81_nts_x64.dll implies that it is linked with 8.1 version of the PHP, while PHP itself is 8.2.0. Can you try using 8.2 versions of the .dlls?

**Comment by macintoshplus** [comment]
I am pleased to announce that this extension is now compiled for Windows by the PHP Extension Repository site.

You can download the DLLs on the extension page: https://phpext.phptools.online/extension/database/pdo_sqlsrv-96

If you have any questions, I am available to discuss them.

**Comment by v-makouz** [comment]
Closed due to inactivity
