### ISSUE TITLE
PHP-7.0-Linux sqlsrv_query produces floating point exception when bind parameter is a empty string

### ISSUE THREAD

**Issue by xalopp** [Microsoft/msphpsql#144]
While this query worked fine with version `4.0.2` of `sqlsrv`
```php
sqlsrv_query($conn, 'SELECT ?', ['']);
```
version `4.0.3` will produce a floating point exception for the same query.
```
Core was generated by `/usr/bin/php7.0 -n -c /vagrant/msphpsql/source/sqlsrv/tmp-php.ini -d output_han'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007f4d923dd0c6 in (anonymous namespace)::default_sql_size_and_scale (param_z=0x7f4d9265cf68, param_z=0x7f4d9265cf68, 
    decimal_digits=<synthetic pointer>, column_size=<synthetic pointer>, encoding=SQLSRV_ENCODING_CHAR, paramno=3, stmt=0x7f4d9266e000)
    at /vagrant/msphpsql/source/sqlsrv/core_stmt.cpp:1963
1963					column_size = SQL_SERVER_MAX_FIELD_SIZE / char_size;
````

`char_size` is defined in [line 1957](https://github.com/Microsoft/msphpsql/blob/PHP-7.0-Linux/source/sqlsrv/core_stmt.cpp#L1957), an will be `0` if ` Z_STRLEN_P( param_z )` is zero, which happens for an empty string.

My Environment:
`Ubuntu 16.04 LTSUbuntu 16.04 LTS`
`PHP 7.0.10-1+deb.sury.org~xenial+1 (cli) ( NTS )PHP 7.0.10-1+deb.sury.org~xenial+1 (cli) ( NTS )`

This issue is similar to #141 where `pdo_sqlsrv` is affected.

PR is in Progress.

**Comment by sirio3mil** [comment]
Same for me.

CentOS Linux release 7.2.1511 (Core)
PHP 7.0.10 (cli) (built: Sep  1 2016 10:36:29) ( NTS )
SQLSRV driver 4.0.3.0

Regards

**Comment by meet-bhagdev** [comment]
@sirio3mil, @xalopp : We believe we have a fix for this and are validating it in our test labs. Stay tuned :)

**Comment by xalopp** [comment]
@meet-bhagdev could you add some (regression) tests to each fixes, like in PR #145? This will make the fixes more transparent and prevent regressions.

**Comment by meet-bhagdev** [comment]
@xalopp Sure thing! Will get it added to our test lab.

**Comment by xalopp** [comment]
4ccffbbe077e87288bf00cc6327142579da46775 fixes this issues 👍
