### ISSUE TITLE
New release still reports version as 'beta1'

### ISSUE THREAD

**Issue by amoyns** [microsoft/msphpsql#1447]
PHP version 8.2.3, PDO_SQLSRV version 5.11.0 (php_pdo_sqlsrv_82_nts.dll)
Windows Server 2019

New 5.11.0 release : pdo_sqlsrv reports version to PHP (in phpinfo() ) as 5.11.0-beta1+16628
Previous beta release showed 5.11.0-beta1+16527

Expected behaviour: Don't include 'beta1' in version, so as to not cause confusion!

Thx, 
AM

**Comment by absci** [comment]
Hi, there may be a delay in publishing files to the Microsoft Download Center. Try redownload the file [here](https://learn.microsoft.com/en-us/sql/connect/php/download-drivers-php-sql-server?view=sql-server-ver16).

**Comment by amoyns** [comment]
No different today, identical .dll found.

Could this be the problem in 
source\shared\version.h ?

`// For previews, set this constant to 1, 2 and so on. Otherwise, set it to 0`
`#define PREVIEW 1`

**Comment by jrose323** [comment]
Im seeing the same issue on my end and I downloaded the DLL files from Assets here on github

**Comment by jrose323** [comment]
It looks like the SEMVER_PRERELEASE was not set to empty prior to release as it still shows beta in version.h

**Comment by absci** [comment]
I see, I'll make sure to fix this issue in the next release.
