### ISSUE TITLE
Supported in GitHub Codespace?

### ISSUE THREAD

**Issue by Offbeatmammal** [microsoft/msphpsql#1454]
I have a GitHub Codespace for a PHP 8.2 project (default container).

if I start php to serve the content `php -S 0.0.0.0:8000` the .php code works, but, when it encounters a `sqlsrv_` commend it throws an error, eg `Call to undefined function sqlsrv_connect()`

In /etc/ there is an odbc.ini, but it's empty. There is a mysql directory, but not an mssql one.

Are these drivers supported in codespace by default, or can they be optionally added (the regular Ubuntu instructions don't seem to work).

For context, we normally dev using Windows, migrating to Azure WebApp/GitHub/Codespace
Just FYI in the Azure WebApp deployment (Linux, PHP 8.2) this works fine.

**Comment by v-makouz** [comment]
It looks like by default neither ODBC nor PHP driver is installed in GitHub Codespace. To install ODBC driver use the following:
https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16

For PHP Driver, instructions are here:
https://learn.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver16

But you will need to replace 8.1s with 8.2, and when installing the diver itself use the following: 
`sudo pecl -d php_suffix=8.2 install sqlsrv`

And use PHP 8.2 to run the script: `php8.2 file.php`

**Comment by Offbeatmammal** [comment]
sadly no luck. interestingly the sqlsrv.so file never seems to be installed, so I might be missing something. Would be nice to see MS preinstall their own toys ;)

**Comment by v-makouz** [comment]
What's the error output? I did get it to work, so I know it is possible to install the driver(s)

**Comment by Offbeatmammal** [comment]
error when I run PHP is
```PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20220829/sqlsrv.so (/usr/lib/php/20220829/sqlsrv.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
[Mon May 29 03:10:10 2023] PHP 8.2.6 Development Server (http://0.0.0.0:8000) started
```

no errors I could see following the install steps. Is there a 'one click' install option that will work in the default codespace?

**Comment by v-makouz** [comment]
In the php.ini can you check the following values (see if they're set to 'On'):
`display_errors = On`
`display_startup_errors = On`
`log_errors = On`

Usually it would print useful errors with those turned on.

**Comment by Offbeatmammal** [comment]
just realised the snipped I'd pasted hadn't shown properly, edited to show the whole thing. looks like sqlsrv.so isn't installing

**Comment by absci** [comment]
> just realised the snipped I'd pasted hadn't shown properly, edited to show the whole thing. looks like sqlsrv.so isn't installing

Try uninstall and reinstall. Sometimes if there're multiple php versions in one system, it confuses pecl. 

```
sudo pecl uninstall sqlsrv

sudo pecl -d php_suffix=8.2 install sqlsrv
```

**Comment by Offbeatmammal** [comment]
that worked, thanks (now just gotta get all that to run on a container rebuild, but at least the manual steps are working fine!)
