### ISSUE TITLE
SQL Server 2008; PHP version 8.2.8

### ISSUE THREAD

**Issue by keithyeohh** [microsoft/msphpsql#1461]
**PHP version**  
8.2.8

**PHP SQLSRV or PDO_SQLSRV version**  
5.11.0

**Microsoft ODBC Driver version**  
ODBC Driver 13 for SQL Server

**SQL Server version**  
2008

**Problem description**  
Attempted to connect to the SQL server from my Laravel php application. I am getting the following error.
```
SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib '/opt/homebrew/lib/libmsodbcsql.13.dylib' : file not found
```

When I following the trail to locate the file, it somewhat exists in the directory.
<img width="1205" alt="Screenshot 2023-07-11 at 4 34 46 PM" src="https://github.com/microsoft/msphpsql/assets/4651260/196ed2f3-8fe6-4dc8-a64f-fad8cb8a0dd5">

<img width="1012" alt="Screenshot 2023-07-11 at 4 35 47 PM" src="https://github.com/microsoft/msphpsql/assets/4651260/11ac8050-79fd-4b21-aa89-dd6a31226db5">

---

Tried to symlink it, but no luck still
```
sudo ln -s /opt/homebrew/etc/odbcinst.ini /etc/odbcinst.ini
sudo ln -s /opt/homebrew/etc/odbc.ini /etc/odbc.ini
```

**Comment by v-makouz** [comment]
It sounds like the ODBC driver might be missing a dependency. However ODBC driver 13 is quite old, I would recommend trying a newer one, such as 18 or 17 (18 has some security features on by default), in particular because the newer drivers have a reduced number of dependencies.

**Comment by v-makouz** [comment]
Closed due to inactivity
