### ISSUE TITLE
SQLSTATE[08001]: [Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:0A000102:SSL routines::unsupported protocol]

### ISSUE THREAD

**Issue by Xanyone** [microsoft/msphpsql#1462]
Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following (skipping questions might delay our responses):

**PHP version**  
8.2.8
**PHP SQLSRV or PDO_SQLSRV version**  
5.11.0
**Microsoft ODBC Driver version**  
2.3.11
**SQL Server version**  
sqlserver2014
**Client operating system**  
macOs  ventura 13.4.1
**Table schema**  

**Problem description**  
Using Brew to install the latest PHP has been causing this issue all the time. I don't know if it is related to the PHP version, but after looking at many solutions, it has not been successful. I would like to ask for advice on how to end this issue
**Expected behavior and actual behavior**  

**Repro code or steps to reproduce**

**Comment by v-makouz** [comment]
What's the version of OpenSSL on the machine (`openssl version`)?

**Comment by Xanyone** [comment]
> What's the version of OpenSSL on the machine (`openssl version`)?

<img width="637" alt="image" src="https://github.com/microsoft/msphpsql/assets/48007465/cfd93ed4-5369-4fa4-854b-ceb369eab866">

**Comment by Xanyone** [comment]
> What's the version of OpenSSL on the machine (`openssl version`)?

openssl version is 3.1.1

**Comment by v-makouz** [comment]
"unsupported protocol" sounds like it's trying to use TLS 1.0 or 1.1, which newer OpenSSL doesn't allow by default. I believe basic SQL Server 14 doesn't support TLS 1.2, so potential solutions would be to allow lower security in OpenSSL config on the client or patch the server with a service pack that has TLS 1.2 support.

Also, you can try connecting to a newer SQL Server if you have one available to verify my theory.

**Comment by Xanyone** [comment]
> "unsupported protocol" sounds like it's trying to use TLS 1.0 or 1.1, which newer OpenSSL doesn't allow by default. I believe basic SQL Server 14 doesn't support TLS 1.2, so potential solutions would be to allow lower security in OpenSSL config on the client or patch the server with a service pack that has TLS 1.2 support.
> 
> Also, you can try connecting to a newer SQL Server if you have one available to verify my theory.

Hello makouz, thank you very much. My database is an educational version. Based on your suggestion, I downloaded the patch SQLServer2014SP3-KB4022619-x64, restarted the server, and now I can connect normally

**Comment by safwanAzman** [comment]
i have the same issue , so the soluiton would be downgrade the openssl version ?

**Comment by v-makouz** [comment]
@safwanAzman If updating the server isn't an option, you can configure OpenSSL to use old TLS:

For example: at the top of `openssl.cnf` add:
```
openssl_conf = default_conf
```

And at the bottom:
```
[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.1
CipherString = DEFAULT@SECLEVEL=0

[openssl_init]
providers = provider_sect
```

On Linux `openssl.cnf` is usually in `/etc/ssl` but on Mac it depends, if you installed it via Brew it would be somewhere in the Brew folder.

**Comment by M4ST3RBYT3** [comment]
@v-makouz I tried to configure the `openssl.cnf` with the specifications, the file looks like this and the error persist 
```cnf
openssl_conf = default_conf

[ req ]
#default_bits		= 2048
#default_md		= sha256
#default_keyfile 	= privkey.pem
distinguished_name	= req_distinguished_name
attributes		= req_attributes

[ req_distinguished_name ]
countryName			= Country Name (2 letter code)
countryName_min			= 2
countryName_max			= 2
stateOrProvinceName		= State or Province Name (full name)
localityName			= Locality Name (eg, city)
0.organizationName		= Organization Name (eg, company)
organizationalUnitName		= Organizational Unit Name (eg, section)
commonName			= Common Name (eg, fully qualified host name)
commonName_max			= 64
emailAddress			= Email Address
emailAddress_max		= 64

[ req_attributes ]
challengePassword		= A challenge password
challengePassword_min		= 4
challengePassword_max		= 20

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.1
CipherString = DEFAULT@SECLEVEL=0

[openssl_init]
providers = provider_sect
```
The version of my OpenSSL is `OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)`

So do I need to downgrade my OpenSSL as well?
Do you know some helpful information, for troubleshooting?

**Comment by v-makouz** [comment]
I've seen sometimes there were several `openssl.cnf` on a system, so if that's the case maybe it's using the other one. Otherwise downgrading OpenSSL might work.

**Comment by tw2066** [comment]
You can refer to it
```
#
# OpenSSL example configuration file.
# This is mostly being used for generation of certificate requests.
#

# Note that you can include other files from the main configuration
# file using the .include directive.
#.include filename

# This definition stops the following lines choking if HOME isn't
# defined.
openssl_conf = default_conf
HOME			= .

# Extra OBJECT IDENTIFIER info:
#oid_file		= $ENV::HOME/.oid
oid_section		= new_oids

# To use this configuration file with the "-extfile" option of the
# "openssl x509" utility, name here the section containing the
# X.509v3 extensions to use:
# extensions		=
# (Alternatively, use a configuration file that has only
# X.509v3 extensions in its main [= default] section.)

[ new_oids ]

# We can add new OIDs in here for use by 'ca', 'req' and 'ts'.
# Add a simple OID like this:
# testoid1=1.2.3.4
# Or use config file substitution like this:
# testoid2=${testoid1}.5.6

# Policies used by the TSA examples.
tsa_policy1 = 1.2.3.4.1
tsa_policy2 = 1.2.3.4.5.6
tsa_policy3 = 1.2.3.4.5.7

####################################################################
[ ca ]
default_ca	= CA_default		# The default ca section

####################################################################
[ CA_default ]

dir		= ./demoCA		# Where everything is kept
certs		= $dir/certs		# Where the issued certs are kept
crl_dir		= $dir/crl		# Where the issued crl are kept
database	= $dir/index.txt	# database index file.
#unique_subject	= no			# Set to 'no' to allow creation of
					# several certs with same subject.
new_certs_dir	= $dir/newcerts		# default place for new certs.

certificate	= $dir/cacert.pem 	# The CA certificate
serial		= $dir/serial 		# The current serial number
crlnumber	= $dir/crlnumber	# the current crl number
					# must be commented out to leave a V1 CRL
crl		= $dir/crl.pem 		# The current CRL
private_key	= $dir/private/cakey.pem# The private key

x509_extensions	= usr_cert		# The extensions to add to the cert

# Comment out the following two lines for the "traditional"
# (and highly broken) format.
name_opt 	= ca_default		# Subject Name options
cert_opt 	= ca_default		# Certificate field options

# Extension copying option: use with caution.
# copy_extensions = copy

# Extensions to add to a CRL. Note: Netscape communicator chokes on V2 CRLs
# so this is commented out by default to leave a V1 CRL.
# crlnumber must also be commented out to leave a V1 CRL.
# crl_extensions	= crl_ext

default_days	= 365			# how long to certify for
default_crl_days= 30			# how long before next CRL
default_md	= default		# use public key default MD
preserve	= no			# keep passed DN ordering

# A few difference way of specifying how similar the request should look
# For type CA, the listed attributes must be the same, and the optional
# and supplied fields are just that :-)
policy		= policy_match

# For the CA policy
[ policy_match ]
countryName		= match
stateOrProvinceName	= match
organizationName	= match
organizationalUnitName	= optional
commonName		= supplied
emailAddress		= optional

# For the 'anything' policy
# At this point in time, you must list all acceptable 'object'
# types.
[ policy_anything ]
countryName		= optional
stateOrProvinceName	= optional
localityName		= optional
organizationName	= optional
organizationalUnitName	= optional
commonName		= supplied
emailAddress		= optional

####################################################################
[ req ]
default_bits		= 2048
default_keyfile 	= privkey.pem
distinguished_name	= req_distinguished_name
attributes		= req_attributes
x509_extensions	= v3_ca	# The extensions to add to the self signed cert

# Passwords for private keys if not present they will be prompted for
# input_password = secret
# output_password = secret

# This sets a mask for permitted string types. There are several options.
# default: PrintableString, T61String, BMPString.
# pkix	 : PrintableString, BMPString (PKIX recommendation before 2004)
# utf8only: only UTF8Strings (PKIX recommendation after 2004).
# nombstr : PrintableString, T61String (no BMPStrings or UTF8Strings).
# MASK:XXXX a literal mask value.
# WARNING: ancient versions of Netscape crash on BMPStrings or UTF8Strings.
string_mask = utf8only

# req_extensions = v3_req # The extensions to add to a certificate request

[ req_distinguished_name ]
countryName			= Country Name (2 letter code)
countryName_default		= AU
countryName_min			= 2
countryName_max			= 2

stateOrProvinceName		= State or Province Name (full name)
stateOrProvinceName_default	= Some-State

localityName			= Locality Name (eg, city)

0.organizationName		= Organization Name (eg, company)
0.organizationName_default	= Internet Widgits Pty Ltd

# we can do this but it is not needed normally :-)
#1.organizationName		= Second Organization Name (eg, company)
#1.organizationName_default	= World Wide Web Pty Ltd

organizationalUnitName		= Organizational Unit Name (eg, section)
#organizationalUnitName_default	=

commonName			= Common Name (e.g. server FQDN or YOUR name)
commonName_max			= 64

emailAddress			= Email Address
emailAddress_max		= 64

# SET-ex3			= SET extension number 3

[ req_attributes ]
challengePassword		= A challenge password
challengePassword_min		= 4
challengePassword_max		= 20

unstructuredName		= An optional company name

[ usr_cert ]

# These extensions are added when 'ca' signs a request.

# This goes against PKIX guidelines but some CAs do it and some software
# requires this to avoid interpreting an end user certificate as a CA.

basicConstraints=CA:FALSE

# Here are some examples of the usage of nsCertType. If it is omitted
# the certificate can be used for anything *except* object signing.

# This is OK for an SSL server.
# nsCertType			= server

# For an object signing certificate this would be used.
# nsCertType = objsign

# For normal client use this is typical
# nsCertType = client, email

# and for everything including object signing:
# nsCertType = client, email, objsign

# This is typical in keyUsage for a client certificate.
# keyUsage = nonRepudiation, digitalSignature, keyEncipherment

# This will be displayed in Netscape's comment listbox.
nsComment			= "OpenSSL Generated Certificate"

# PKIX recommendations harmless if included in all certificates.
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer

# This stuff is for subjectAltName and issuerAltname.
# Import the email address.
# subjectAltName=email:copy
# An alternative to produce certificates that aren't
# deprecated according to PKIX.
# subjectAltName=email:move

# Copy subject details
# issuerAltName=issuer:copy

#nsCaRevocationUrl		= http://www.domain.dom/ca-crl.pem
#nsBaseUrl
#nsRevocationUrl
#nsRenewalUrl
#nsCaPolicyUrl
#nsSslServerName

# This is required for TSA certificates.
# extendedKeyUsage = critical,timeStamping

[ v3_req ]

# Extensions to add to a certificate request

basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment

[ v3_ca ]


# Extensions for a typical CA


# PKIX recommendation.

subjectKeyIdentifier=hash

authorityKeyIdentifier=keyid:always,issuer

basicConstraints = critical,CA:true

# Key usage: this is typical for a CA certificate. However since it will
# prevent it being used as an test self-signed certificate it is best
# left out by default.
# keyUsage = cRLSign, keyCertSign

# Some might want this also
# nsCertType = sslCA, emailCA

# Include email address in subject alt name: another PKIX recommendation
# subjectAltName=email:copy
# Copy issuer details
# issuerAltName=issuer:copy

# DER hex encoding of an extension: beware experts only!
# obj=DER:02:03
# Where 'obj' is a standard or added object
# You can even override a supported extension:
# basicConstraints= critical, DER:30:03:01:01:FF

[ crl_ext ]

# CRL extensions.
# Only issuerAltName and authorityKeyIdentifier make any sense in a CRL.

# issuerAltName=issuer:copy
authorityKeyIdentifier=keyid:always

[ proxy_cert_ext ]
# These extensions should be added when creating a proxy certificate

# This goes against PKIX guidelines but some CAs do it and some software
# requires this to avoid interpreting an end user certificate as a CA.

basicConstraints=CA:FALSE

# Here are some examples of the usage of nsCertType. If it is omitted
# the certificate can be used for anything *except* object signing.

# This is OK for an SSL server.
# nsCertType			= server

# For an object signing certificate this would be used.
# nsCertType = objsign

# For normal client use this is typical
# nsCertType = client, email

# and for everything including object signing:
# nsCertType = client, email, objsign

# This is typical in keyUsage for a client certificate.
# keyUsage = nonRepudiation, digitalSignature, keyEncipherment

# This will be displayed in Netscape's comment listbox.
nsComment			= "OpenSSL Generated Certificate"

# PKIX recommendations harmless if included in all certificates.
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer

# This stuff is for subjectAltName and issuerAltname.
# Import the email address.
# subjectAltName=email:copy
# An alternative to produce certificates that aren't
# deprecated according to PKIX.
# subjectAltName=email:move

# Copy subject details
# issuerAltName=issuer:copy

#nsCaRevocationUrl		= http://www.domain.dom/ca-crl.pem
#nsBaseUrl
#nsRevocationUrl
#nsRenewalUrl
#nsCaPolicyUrl
#nsSslServerName

# This really needs to be in place for it to be a proxy certificate.
proxyCertInfo=critical,language:id-ppl-anyLanguage,pathlen:3,policy:foo

####################################################################
[ tsa ]

default_tsa = tsa_config1	# the default TSA section

[ tsa_config1 ]

# These are used by the TSA reply generation only.
dir		= ./demoCA		# TSA root directory
serial		= $dir/tsaserial	# The current serial number (mandatory)
crypto_device	= builtin		# OpenSSL engine to use for signing
signer_cert	= $dir/tsacert.pem 	# The TSA signing certificate
					# (optional)
certs		= $dir/cacert.pem	# Certificate chain to include in reply
					# (optional)
signer_key	= $dir/private/tsakey.pem # The TSA private key (optional)
signer_digest  = sha256			# Signing digest to use. (Optional)
default_policy	= tsa_policy1		# Policy if request did not specify it
					# (optional)
other_policies	= tsa_policy2, tsa_policy3	# acceptable policies (optional)
digests     = sha1, sha256, sha384, sha512  # Acceptable message digests (mandatory)
accuracy	= secs:1, millisecs:500, microsecs:100	# (optional)
clock_precision_digits  = 0	# number of digits after dot. (optional)
ordering		= yes	# Is ordering defined for timestamps?
				# (optional, default: no)
tsa_name		= yes	# Must the TSA name be included in the reply?
				# (optional, default: no)
ess_cert_id_chain	= no	# Must the ESS cert id chain be included?
				# (optional, default: no)
ess_cert_id_alg		= sha1	# algorithm to compute certificate
				# identifier (optional, default: sha1)

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1
CipherString = DEFAULT@SECLEVEL=0

```

**Comment by CaledoniaProject** [comment]
It doesn't really work. I have PHP 8.3 on MacOS, and from php -i I confirm the path of openssl.cnf. 
I added these lines to the top and bottom of openssl.cnf, and restarted php-fpm, but still the same error.

**Comment by tw2066** [comment]
@CaledoniaProject  Try directly overwriting the file

**Comment by CaledoniaProject** [comment]
@tw2066 It won't work. For people who stuck on this, just update your SQLServer to a newer SP, TLSv1.2 will be automatically supported.

**Comment by limit81995** [comment]
Does anyone have an answer？

**Comment by v-makouz** [comment]
This is not a PHP driver issue, but rather compatibility between OpenSSL and SQL Server. Starting with OpenSSL 3.0 TLSv1.0 and TLSv1.1 were deprecated and are not allowed by default, requiring at least TLSv1.2. Many older servers don't have TLSv1.2, thus the connection fails. The ideal solution is to patch or upgrade the server. If that's not possible, one can configure OpenSSL to still allow use of older protocols, but it's best to consult OpenSSL documentation or support for the most up to date instructions for how to do so.

**Comment by limit81995** [comment]
> [@safwanAzman](https://github.com/safwanAzman)如果无法更新服务器，您可以配置 OpenSSL 以使用旧的 TLS：
> 
> 例如：在顶部`openssl.cnf`添加：
> 
> ```
> openssl_conf = default_conf
> ```
> 
> 底部：
> 
> ```
> [default_conf]
> ssl_conf = ssl_sect
> 
> [ssl_sect]
> system_default = system_default_sect
> 
> [system_default_sect]
> MinProtocol = TLSv1.1
> CipherString = DEFAULT@SECLEVEL=0
> 
> [openssl_init]
> providers = provider_sect
> ```
> 
> 在 Linux 上`openssl.cnf`通常是，`/etc/ssl`但在 Mac 上则视情况而定，如果您通过 Brew 安装它，它将位于 Brew 文件夹中的某个位置。



> [@safwanAzman](https://github.com/safwanAzman) If updating the server isn't an option, you can configure OpenSSL to use old TLS:
> 
> For example: at the top of `openssl.cnf` add:
> 
> ```
> openssl_conf = default_conf
> ```
> 
> And at the bottom:
> 
> ```
> [default_conf]
> ssl_conf = ssl_sect
> 
> [ssl_sect]
> system_default = system_default_sect
> 
> [system_default_sect]
> MinProtocol = TLSv1.1
> CipherString = DEFAULT@SECLEVEL=0
> 
> [openssl_init]
> providers = provider_sect
> ```
> 
> On Linux `openssl.cnf` is usually in `/etc/ssl` but on Mac it depends, if you installed it via Brew it would be somewhere in the Brew folder.

thx your solution.
if you install php by brew.please check your php --ri openssl,and vim the openssl.cnf.

**Comment by flavio-back-end** [comment]
im using laradock and i have  the some  pobleme can give the  siluto=ion to fix it

**Comment by samuel201014** [comment]
> You can refer to it
> 
> ```
> #
> # OpenSSL example configuration file.
> # This is mostly being used for generation of certificate requests.
> #
> 
> # Note that you can include other files from the main configuration
> # file using the .include directive.
> #.include filename
> 
> # This definition stops the following lines choking if HOME isn't
> # defined.
> openssl_conf = default_conf
> HOME			= .
> 
> # Extra OBJECT IDENTIFIER info:
> #oid_file		= $ENV::HOME/.oid
> oid_section		= new_oids
> 
> # To use this configuration file with the "-extfile" option of the
> # "openssl x509" utility, name here the section containing the
> # X.509v3 extensions to use:
> # extensions		=
> # (Alternatively, use a configuration file that has only
> # X.509v3 extensions in its main [= default] section.)
> 
> [ new_oids ]
> 
> # We can add new OIDs in here for use by 'ca', 'req' and 'ts'.
> # Add a simple OID like this:
> # testoid1=1.2.3.4
> # Or use config file substitution like this:
> # testoid2=${testoid1}.5.6
> 
> # Policies used by the TSA examples.
> tsa_policy1 = 1.2.3.4.1
> tsa_policy2 = 1.2.3.4.5.6
> tsa_policy3 = 1.2.3.4.5.7
> 
> ####################################################################
> [ ca ]
> default_ca	= CA_default		# The default ca section
> 
> ####################################################################
> [ CA_default ]
> 
> dir		= ./demoCA		# Where everything is kept
> certs		= $dir/certs		# Where the issued certs are kept
> crl_dir		= $dir/crl		# Where the issued crl are kept
> database	= $dir/index.txt	# database index file.
> #unique_subject	= no			# Set to 'no' to allow creation of
> 					# several certs with same subject.
> new_certs_dir	= $dir/newcerts		# default place for new certs.
> 
> certificate	= $dir/cacert.pem 	# The CA certificate
> serial		= $dir/serial 		# The current serial number
> crlnumber	= $dir/crlnumber	# the current crl number
> 					# must be commented out to leave a V1 CRL
> crl		= $dir/crl.pem 		# The current CRL
> private_key	= $dir/private/cakey.pem# The private key
> 
> x509_extensions	= usr_cert		# The extensions to add to the cert
> 
> # Comment out the following two lines for the "traditional"
> # (and highly broken) format.
> name_opt 	= ca_default		# Subject Name options
> cert_opt 	= ca_default		# Certificate field options
> 
> # Extension copying option: use with caution.
> # copy_extensions = copy
> 
> # Extensions to add to a CRL. Note: Netscape communicator chokes on V2 CRLs
> # so this is commented out by default to leave a V1 CRL.
> # crlnumber must also be commented out to leave a V1 CRL.
> # crl_extensions	= crl_ext
> 
> default_days	= 365			# how long to certify for
> default_crl_days= 30			# how long before next CRL
> default_md	= default		# use public key default MD
> preserve	= no			# keep passed DN ordering
> 
> # A few difference way of specifying how similar the request should look
> # For type CA, the listed attributes must be the same, and the optional
> # and supplied fields are just that :-)
> policy		= policy_match
> 
> # For the CA policy
> [ policy_match ]
> countryName		= match
> stateOrProvinceName	= match
> organizationName	= match
> organizationalUnitName	= optional
> commonName		= supplied
> emailAddress		= optional
> 
> # For the 'anything' policy
> # At this point in time, you must list all acceptable 'object'
> # types.
> [ policy_anything ]
> countryName		= optional
> stateOrProvinceName	= optional
> localityName		= optional
> organizationName	= optional
> organizationalUnitName	= optional
> commonName		= supplied
> emailAddress		= optional
> 
> ####################################################################
> [ req ]
> default_bits		= 2048
> default_keyfile 	= privkey.pem
> distinguished_name	= req_distinguished_name
> attributes		= req_attributes
> x509_extensions	= v3_ca	# The extensions to add to the self signed cert
> 
> # Passwords for private keys if not present they will be prompted for
> # input_password = secret
> # output_password = secret
> 
> # This sets a mask for permitted string types. There are several options.
> # default: PrintableString, T61String, BMPString.
> # pkix	 : PrintableString, BMPString (PKIX recommendation before 2004)
> # utf8only: only UTF8Strings (PKIX recommendation after 2004).
> # nombstr : PrintableString, T61String (no BMPStrings or UTF8Strings).
> # MASK:XXXX a literal mask value.
> # WARNING: ancient versions of Netscape crash on BMPStrings or UTF8Strings.
> string_mask = utf8only
> 
> # req_extensions = v3_req # The extensions to add to a certificate request
> 
> [ req_distinguished_name ]
> countryName			= Country Name (2 letter code)
> countryName_default		= AU
> countryName_min			= 2
> countryName_max			= 2
> 
> stateOrProvinceName		= State or Province Name (full name)
> stateOrProvinceName_default	= Some-State
> 
> localityName			= Locality Name (eg, city)
> 
> 0.organizationName		= Organization Name (eg, company)
> 0.organizationName_default	= Internet Widgits Pty Ltd
> 
> # we can do this but it is not needed normally :-)
> #1.organizationName		= Second Organization Name (eg, company)
> #1.organizationName_default	= World Wide Web Pty Ltd
> 
> organizationalUnitName		= Organizational Unit Name (eg, section)
> #organizationalUnitName_default	=
> 
> commonName			= Common Name (e.g. server FQDN or YOUR name)
> commonName_max			= 64
> 
> emailAddress			= Email Address
> emailAddress_max		= 64
> 
> # SET-ex3			= SET extension number 3
> 
> [ req_attributes ]
> challengePassword		= A challenge password
> challengePassword_min		= 4
> challengePassword_max		= 20
> 
> unstructuredName		= An optional company name
> 
> [ usr_cert ]
> 
> # These extensions are added when 'ca' signs a request.
> 
> # This goes against PKIX guidelines but some CAs do it and some software
> # requires this to avoid interpreting an end user certificate as a CA.
> 
> basicConstraints=CA:FALSE
> 
> # Here are some examples of the usage of nsCertType. If it is omitted
> # the certificate can be used for anything *except* object signing.
> 
> # This is OK for an SSL server.
> # nsCertType			= server
> 
> # For an object signing certificate this would be used.
> # nsCertType = objsign
> 
> # For normal client use this is typical
> # nsCertType = client, email
> 
> # and for everything including object signing:
> # nsCertType = client, email, objsign
> 
> # This is typical in keyUsage for a client certificate.
> # keyUsage = nonRepudiation, digitalSignature, keyEncipherment
> 
> # This will be displayed in Netscape's comment listbox.
> nsComment			= "OpenSSL Generated Certificate"
> 
> # PKIX recommendations harmless if included in all certificates.
> subjectKeyIdentifier=hash
> authorityKeyIdentifier=keyid,issuer
> 
> # This stuff is for subjectAltName and issuerAltname.
> # Import the email address.
> # subjectAltName=email:copy
> # An alternative to produce certificates that aren't
> # deprecated according to PKIX.
> # subjectAltName=email:move
> 
> # Copy subject details
> # issuerAltName=issuer:copy
> 
> #nsCaRevocationUrl		= http://www.domain.dom/ca-crl.pem
> #nsBaseUrl
> #nsRevocationUrl
> #nsRenewalUrl
> #nsCaPolicyUrl
> #nsSslServerName
> 
> # This is required for TSA certificates.
> # extendedKeyUsage = critical,timeStamping
> 
> [ v3_req ]
> 
> # Extensions to add to a certificate request
> 
> basicConstraints = CA:FALSE
> keyUsage = nonRepudiation, digitalSignature, keyEncipherment
> 
> [ v3_ca ]
> 
> 
> # Extensions for a typical CA
> 
> 
> # PKIX recommendation.
> 
> subjectKeyIdentifier=hash
> 
> authorityKeyIdentifier=keyid:always,issuer
> 
> basicConstraints = critical,CA:true
> 
> # Key usage: this is typical for a CA certificate. However since it will
> # prevent it being used as an test self-signed certificate it is best
> # left out by default.
> # keyUsage = cRLSign, keyCertSign
> 
> # Some might want this also
> # nsCertType = sslCA, emailCA
> 
> # Include email address in subject alt name: another PKIX recommendation
> # subjectAltName=email:copy
> # Copy issuer details
> # issuerAltName=issuer:copy
> 
> # DER hex encoding of an extension: beware experts only!
> # obj=DER:02:03
> # Where 'obj' is a standard or added object
> # You can even override a supported extension:
> # basicConstraints= critical, DER:30:03:01:01:FF
> 
> [ crl_ext ]
> 
> # CRL extensions.
> # Only issuerAltName and authorityKeyIdentifier make any sense in a CRL.
> 
> # issuerAltName=issuer:copy
> authorityKeyIdentifier=keyid:always
> 
> [ proxy_cert_ext ]
> # These extensions should be added when creating a proxy certificate
> 
> # This goes against PKIX guidelines but some CAs do it and some software
> # requires this to avoid interpreting an end user certificate as a CA.
> 
> basicConstraints=CA:FALSE
> 
> # Here are some examples of the usage of nsCertType. If it is omitted
> # the certificate can be used for anything *except* object signing.
> 
> # This is OK for an SSL server.
> # nsCertType			= server
> 
> # For an object signing certificate this would be used.
> # nsCertType = objsign
> 
> # For normal client use this is typical
> # nsCertType = client, email
> 
> # and for everything including object signing:
> # nsCertType = client, email, objsign
> 
> # This is typical in keyUsage for a client certificate.
> # keyUsage = nonRepudiation, digitalSignature, keyEncipherment
> 
> # This will be displayed in Netscape's comment listbox.
> nsComment			= "OpenSSL Generated Certificate"
> 
> # PKIX recommendations harmless if included in all certificates.
> subjectKeyIdentifier=hash
> authorityKeyIdentifier=keyid,issuer
> 
> # This stuff is for subjectAltName and issuerAltname.
> # Import the email address.
> # subjectAltName=email:copy
> # An alternative to produce certificates that aren't
> # deprecated according to PKIX.
> # subjectAltName=email:move
> 
> # Copy subject details
> # issuerAltName=issuer:copy
> 
> #nsCaRevocationUrl		= http://www.domain.dom/ca-crl.pem
> #nsBaseUrl
> #nsRevocationUrl
> #nsRenewalUrl
> #nsCaPolicyUrl
> #nsSslServerName
> 
> # This really needs to be in place for it to be a proxy certificate.
> proxyCertInfo=critical,language:id-ppl-anyLanguage,pathlen:3,policy:foo
> 
> ####################################################################
> [ tsa ]
> 
> default_tsa = tsa_config1	# the default TSA section
> 
> [ tsa_config1 ]
> 
> # These are used by the TSA reply generation only.
> dir		= ./demoCA		# TSA root directory
> serial		= $dir/tsaserial	# The current serial number (mandatory)
> crypto_device	= builtin		# OpenSSL engine to use for signing
> signer_cert	= $dir/tsacert.pem 	# The TSA signing certificate
> 					# (optional)
> certs		= $dir/cacert.pem	# Certificate chain to include in reply
> 					# (optional)
> signer_key	= $dir/private/tsakey.pem # The TSA private key (optional)
> signer_digest  = sha256			# Signing digest to use. (Optional)
> default_policy	= tsa_policy1		# Policy if request did not specify it
> 					# (optional)
> other_policies	= tsa_policy2, tsa_policy3	# acceptable policies (optional)
> digests     = sha1, sha256, sha384, sha512  # Acceptable message digests (mandatory)
> accuracy	= secs:1, millisecs:500, microsecs:100	# (optional)
> clock_precision_digits  = 0	# number of digits after dot. (optional)
> ordering		= yes	# Is ordering defined for timestamps?
> 				# (optional, default: no)
> tsa_name		= yes	# Must the TSA name be included in the reply?
> 				# (optional, default: no)
> ess_cert_id_chain	= no	# Must the ESS cert id chain be included?
> 				# (optional, default: no)
> ess_cert_id_alg		= sha1	# algorithm to compute certificate
> 				# identifier (optional, default: sha1)
> 
> [default_conf]
> ssl_conf = ssl_sect
> 
> [ssl_sect]
> system_default = system_default_sect
> 
> [system_default_sect]
> MinProtocol = TLSv1
> CipherString = DEFAULT@SECLEVEL=0
> ```

if  I change this  there will be issues 
and I copyed this code and past in openssl.cnf then its connected . it will affect my application

**Comment by puzzle9** [comment]
```
openssl_conf = default_conf
HOME			= .

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1
CipherString = DEFAULT@SECLEVEL=0
```

`OPENSSL_CONF=./openssl.cnf ...`

**Comment by tanmyid** [comment]
Tested on

- Ubuntu 24.04
- PHP 8.3
- Microsoft SQL Server 2014 - 12.0.2000.8 (X64)

edit `/etc/ssl/openssl.cnf` at the bottom add

```
[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT:@SECLEVEL=0
```
