### ISSUE TITLE
SSL routines::unsupported protocol

### ISSUE THREAD

**Issue by safwanAzman** [microsoft/msphpsql#1463]
Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following (skipping questions might delay our responses):

**PHP version**  
PHP 8.1.21
**PHP SQLSRV or PDO_SQLSRV version**  
5.11.0 
**Microsoft ODBC Driver version**  
17.10
**SQL Server version**  
Microsoft SQL Server 2012 - 11.0.2100.60 (X64) 
Feb 10 2012 19:39:15 
Copyright (c) Microsoft Corporation
Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

**Client operating system**  
Mac Os Ventura 13.4.1

**Table schema**  

**Problem description**  
Trying to connect through laravel orm . Get an error 
SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [error:0A000102:SSL routines::unsupported protocol]

We try to lower the open ssl by using 1.1 . Somehow still stuck on this error 

**Expected behavior and actual behavior**  
Successfull connection  , somehow it throw an error related to unsupported protocol 
**Repro code or steps to reproduce**
Install odbc mac version 17 
Install php version 8
pecl install sqlsrv , pdo_sqlsrv

**Comment by v-makouz** [comment]
When lowering TLS to 1.1, did you set `CipherString = DEFAULT@SECLEVEL=0`? In OpenSSL 3+ they moved TLS 1.0 and 1.1 from security level 1 to 0.

**Comment by safwanAzman** [comment]
ah , i see, i miss out that part to add the setting into the config :) Thanks !

**Comment by waraikobuot** [comment]
> When lowering TLS to 1.1, did you set `CipherString = DEFAULT@SECLEVEL=0`? In OpenSSL 3+ they moved TLS 1.0 and 1.1 from security level 1 to 0.

hello sir it is safe lowering this configuration?
