### ISSUE TITLE
XAMPP on Debian 12 Cant Load Module

### ISSUE THREAD

**Issue by davcheong** [microsoft/msphpsql#1469]
Its seem like it doesnt work in Xampp on Debian 12. Doesnt seem to load the modules no matter where it is placed.

I am currently manually downloaded sqlsrv using debian11-8.2.tar, extracted the files and placed under lib/php/extensions and also i have nano php.ini added extension=/path of php_sqlsrv_8.2.so after reboot or restarted moving around the driver and change in php.ini, and whenever i check on phpinfo, sqlsrv module was never loaded. In which i cant use sqlsrv_query on my php.

Kindly help and guide is there anyway?
Using Xampp 8.2.4
Debian 12

Is it Debian11-8.2 not yet compatible for Debian 12?

**Comment by absci** [comment]
Usually .so files are not compatible with different systems. Since pecl compile packages, you could try `pecl install sqlsrv` on Debian 12.

**Comment by davcheong** [comment]
> Usually .so files are not compatible with different systems. Since pecl compile packages, you could try `pecl install sqlsrv` on Debian 12.

Hi absci, thanks for the reply. I also did tried pecl install sqlsrv on apache2, but fail as well. I even tried after pecl install sqlsrv then try to use the Xampp setting php.ini extenson=location of pecl install/sqlsrv.so was failed also. 

I have reinstalled Debian 12 several times to test all possible chance to make sqlsrv.so to work, but none were successful. Following exact steps guide by Microsoft.

**Comment by absci** [comment]
There's no official support for Debian 12 yet. If you are having trouble with it, I recommend using Debian 11.

**Comment by davcheong** [comment]
> There's no official support for Debian 12 yet. If you are having trouble with it, I recommend using Debian 11.

Is there any other ways beside downgrading? And how will it need to make Xampp work with the Sqlsrv driver in Debian 11?

**Comment by absci** [comment]
Currently the PHP driver doesn't support Debian 12. Sorry, I don't have experience with Xampp. If you follow instructions [here](https://learn.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver16#installing-on-debian), you should be able to get the PHP driver working with Debian 11.

**Comment by davcheong** [comment]
> Currently the PHP driver doesn't support Debian 12. Sorry, I don't have experience with Xampp. If you follow instructions [here](https://learn.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver16#installing-on-debian), you should be able to get the PHP driver working with Debian 11.

Yes. I have no problem using Xampp and apache2 php on Debian 11 installing sqldrv.so. only debian 12.
