### ISSUE TITLE
PECL is missing DLLs for 5.11

### ISSUE THREAD

**Issue by Hackwar** [microsoft/msphpsql#1473]
The PECL entry does not contain DLLs for 5.10.1 and 5.11, even though those releases are 6 months old. 
https://pecl.php.net/package/sqlsrv

We are using the download of the DLL in our appveyor setup and thus can currently not run our tests against PHP 8.2. Can you please upload the DLL to PECL?

**PHP version**  
8.2

**PHP SQLSRV or PDO_SQLSRV version**  
5.11.0

**Client operating system**  
Windows

**Comment by absci** [comment]
Hi, Windows PECL build machine is not functioning at the moment, more details [here](https://windows.php.net/). You can download the DLLs from [Github assets](https://github.com/microsoft/msphpsql/releases/tag/v5.11.0) and [Microsoft download center](https://learn.microsoft.com/en-us/sql/connect/php/download-drivers-php-sql-server?view=sql-server-ver16).
