### ISSUE TITLE
Release beta with support for PHP 8.3 RC 1

### ISSUE THREAD

**Issue by theodorejb** [microsoft/msphpsql#1477]
[PHP 8.3 RC 1 has been made available](https://www.php.net/archive/2023.php#2023-08-31-1) and I'd like to test my apps with it, but to do so I need the PHP Driver for SQL Server to support it.

### Describe the solution you'd like
Ideally a beta release of the SQLSRV driver with PHP 8.3 RC 1 support can be published within the next couple of weeks so developers can help find/fix issues before PHP 8.3 is finalized.

### Describe alternatives you've considered
Maybe it's somehow possible to compile the extension myself for PHP 8.3, but I don't have time to figure out how to do this, and I doubt most other developers do either.

### Additional context
There is precedent for beta versions of the PHP Driver for SQL Server supporting new PHP release candidates. For example, the [5.10.0-beta1 release which supported PHP 8.1 RC 1](https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta1).

**Comment by v-makouz** [comment]
I believe that PHP driver beta version with 8.3 support is scheduled for early December or so.

**Comment by theodorejb** [comment]
Why wait so long? The GA release of PHP 8.3 is [scheduled for November 23](https://wiki.php.net/todo/php83), so waiting until December would prevent testing with any of the release candidates before PHP 8.3 is finalized.

**Comment by przemo-hemmersbach** [comment]
PHP 8.2 support availability was discussed here: https://github.com/microsoft/msphpsql/issues/1420

Looks like msphpsql do not follow PHP release cadence by default but lags varied amount of time.

(I'm not affiliated with msphpsql in any way)

**Comment by SharkMachine** [comment]
I'm with @theodorejb. I could have targeted 8.3 at work but I can't :(

**Comment by SharkMachine** [comment]
The license for SQL Server is not cheap and the company I work at is paying for it. We need this as well, please make it happen.

**Comment by SharkMachine** [comment]
@v-makouz @yitam Are we paying for nothing?

**Comment by v-makouz** [comment]
We are expecting the beta release within this month

**Comment by Nirator78** [comment]
> Lets hope that early December is not 31 December ;) I can't wait!

Yes me too i need it soon for production.

**Comment by SharkMachine** [comment]
> We are expecting the beta release within this month

Thank you :)

----

I'm not criticizing individual developers with the following statement. The PHP release schedule has been the same since 7.0 (2015). There is no other excuse for being late than not being bothered being on time. It is possible to plan for 8.4 right now, the first alpha will most likely be released in June and GA in November or December.

**Comment by absci** [comment]
> > We are expecting the beta release within this month
> 
> Thank you :)
> 
> I'm not criticizing individual developers with the following statement. The PHP release schedule has been the same since 7.0 (2015). There is no other excuse for being late than not being bothered being on time. It is possible to plan for 8.4 right now, the first alpha will most likely be released in June and GA in November or December.

We have discussed this and possibly release on October for the next version.

**Comment by SharkMachine** [comment]
The beta works like charm, thank you :heart: .

Is there a schedule for a GA release? If it's in January or February, I'm happy.

**Comment by MichaelSun90** [comment]
Hi @SharkMachine, Thanks for the feed back. Will let people know when we actually got GA release date finalized.

**Comment by felipito2023** [comment]
Is there an update to get sqlsrv extension for PHP 8.3 at this moment?

**Comment by CaledoniaProject** [comment]
Just tell me how to build this myself. I tried to use phpize but sql.h is missing.

**Comment by SharkMachine** [comment]
https://wiki.php.net/todo/php84

**Comment by theodorejb** [comment]
Closing now that a stable release supporting PHP 8.3 is available.

**Comment by lionslair** [comment]
Didn't know it was released

**Comment by SharkMachine** [comment]
Thank you. We will be using PHP 8.3 support :)
