### ISSUE TITLE
Linux .so file is executable

### ISSUE THREAD

**Issue by szepeviktor** [Microsoft/msphpsql#148]
E.g. `pdo_sqlsrv.so` has 0755 perms.

Please consider setting 0644.

Thank you.

**Comment by Hadis-Fard** [comment]
@szepeviktor are you downloading the [released binaries](https://github.com/Microsoft/msphpsql/releases/tag/4.0.4-Linux) or building the driver from source?

**Comment by szepeviktor** [comment]
I was building it.

BTW I have Windows-feeling when downloading linux software in a ZIP.


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by meet-bhagdev** [comment]
@szepeviktor we will ship the packages via tar.gz in the next release.

**Comment by szepeviktor** [comment]
I failed to implement it.

#### Results

There is an m4 macro: `PHP_SET_LIBTOOL_VARIABLE()`

libtool has a config variable `install_override_mode` which could be set to 0644

**Comment by szepeviktor** [comment]
I've found out that the linker produces the .so file with permissions 0755, fixed, not variable.

`make "INSTALL=$(pwd)/build/shtool install -c --mode=0644" install` instead of make install will do the job.

It is not nice.

**Comment by szepeviktor** [comment]
One more thing the `PHP_SUBST(varname)` macro does:

> Adds variable with it's value into Makefile, e.g.:
> CC = gcc

Maybe I don't get the syntax right. This is foreign territory for me. 
```
INSTALL='$(top_srcdir)/build/shtool install -c --mode=0644'
PHP_SUBST(INSTALL)
```

**Comment by Hadis-Fard** [comment]
@szepeviktor in the Makefile the mode is set to 644,  `INSTALL = $(top_srcdir)/build/shtool install -c
INSTALL_DATA = $(INSTALL) -m 644`. The permissions also depends on the permission of the user type (root and local user) and the ownership of the directories, also you can change the permission using `chmod` as well.
