### ISSUE TITLE
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server

### ISSUE THREAD

**Issue by LouiPet8t** [microsoft/msphpsql#1487]
Bonjour, je souhaite actuellement tester une solution sur ma machine Ubuntu, pour ce faire je dois me connecter à ma bdd obligatoirement avec ODBC 17.

Lorsque je me connecte avec sqlcmd via ma machine sous windows, je me connecte bien à ma bdd, cependant lorsque je retourne sur une machine ubuntu, j'ai ces messages d'erreurs :

Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.

Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.

Du côté des logs de mon serveur SQL j'ai ceci :

Message Une alerte irrécupérable a été générée et envoyée au point de terminaison distant. Ceci peut entraîner l’arrêt de la connexion. Le code d’erreur irrécupérable défini par le protocole TLS est 40. L’état d’erreur de Windows SChannel est 1205.

Message Une alerte irrécupérable a été générée et envoyée au point de terminaison distant. Ceci peut entraîner l’arrêt de la connexion. Le code d’erreur irrécupérable défini par le protocole TLS est 40. L’état d’erreur de Windows SChannel est 1205.

**Comment by v-makouz** [comment]
Closed due to inactivity
