### ISSUE TITLE
HY104 Invalid precision value when reusing prepared statement

### ISSUE THREAD

**Issue by Leiothrix1** [microsoft/msphpsql#1491]
Versions:
PHP: 8.2.13
sqlsrv: 5.11.1
ODBC driver: 18.3.2.1
SQL Server: 14.0.3038.14
Server OS: Windows Server 2016

Test table:
CREATE TABLE dbo.TestTable (
	TestColumn VARCHAR (8000) NULL
)

Test code: attached
[TestCase.txt](https://github.com/microsoft/msphpsql/files/13550867/TestCase.txt)

Expected output: two identical rows inserted into the database.

Actual output:
The first row is inserted in the database, and the second fails with error:
HY104 [Microsoft][ODBC Driver 18 for SQL Server]Invalid precision value

This code works fine if SQLSRV_SQLTYPE_VARCHAR() is set <= 4000 or to MAX.  If it is between 4001->8000 it produces the error above on the second insert.  This also works if the SQL type is not specified in the prepared statement.  Note that there is nothing changing between the inserts, it is just sqlsrv_execute being executed twice.

**Comment by v-makouz** [comment]
I can't seem to reproduce this one. Can you provide an ODBC trace?

**Comment by Leiothrix1** [comment]
Sorry I didn't know that option even existed or I would have included that originally.

Trace is attached.

[trace.txt](https://github.com/microsoft/msphpsql/files/13574089/trace.txt)

Thanks!

**Comment by v-makouz** [comment]
Strangely, in my tests, I could reproduce this error with 5.10 version of the PHP driver, but not 5.11. But you're already using 5.11, so I will investigate this further

**Comment by v-makouz** [comment]
I was able to reproduce this, we are now looking into it.
