### ISSUE TITLE
SQLSTATE[01002] Adaptive Server connection failed (xxx.xx.xx.xxx)

### ISSUE THREAD

**Issue by 0neCigarettes** [microsoft/msphpsql#1494]
ODBC 2017
can't connect to sqlserver, user php 7.3 laravel nginx macOs

**Comment by MichaelSun90** [comment]
Hi @0neCigarettes , searched the error, and find this [link](https://stackoverflow.com/questions/37205752/sqlstate01002-adaptive-server-connection-failed-severity-9). Seems to be a similar error. Maybe try this say if this helps.

**Comment by v-makouz** [comment]
Closed due to inactivity
