### ISSUE TITLE
Post Commit Review for Version PHP-7.0-Linux version 4.0.4

### ISSUE THREAD

**Issue by xalopp** [Microsoft/msphpsql#150]
Please have a look a my comments for
https://github.com/Microsoft/msphpsql/commit/4ccffbbe077e87288bf00cc6327142579da46775
- ~~I think there a new issue in phpize for pdo_sqlsrv, I'll open a dedicated issue for that.~~ (solved by #157 )
- The Version in version.h is 4.0.0 and not as expected 4.0.4
- There are some minor coding style issues.

**Comment by meet-bhagdev** [comment]
@xalopp definitely! Will take a look at this. Thanks for reporting them. Formatting issues and version issue looks valid. Will keep you posted.
