### ISSUE TITLE
Package cannot be installed via apt. Appears to be similar to issue 1505

### ISSUE THREAD

**Issue by kshillingstad** [Microsoft/msphpsql#1522]
8.692   Could not handshake: A TLS fatal alert has been received. [IP:xxxx]
8.789 debconf: delaying package configuration, since apt-utils is not installed
8.801 Fetched 1441 kB in 1s (1768 kB/s)
(Reading database ... 21614 files and directories currently installed.)
8.820 Preparing to unpack .../0-odbcinst_2.3.11-1_arm64.deb ...
8.823 Unpacking odbcinst (2.3.11-1) over (2.3.6-0.1+b1) ...
8.834 Preparing to unpack .../1-unixodbc-dev_2.3.11-1_arm64.deb ...
8.836 Unpacking unixodbc-dev (2.3.11-1) over (2.3.6-0.1+b1) ...
8.857 Preparing to unpack .../2-odbcinst1debian2_2.3.11-1_arm64.deb ...
8.860 Unpacking odbcinst1debian2:arm64 (2.3.11-1) over (2.3.6-0.1+b1) ...
8.879 Preparing to unpack .../3-libodbc1_2.3.11-1_arm64.deb ...
8.881 Unpacking libodbc1:arm64 (2.3.11-1) over (2.3.6-0.1+b1) ...
8.925 Selecting previously unselected package unixodbc.
8.926 Preparing to unpack .../4-unixodbc_2.3.11-1_arm64.deb ...
8.927 Unpacking unixodbc (2.3.11-1) ...
8.939 Selecting previously unselected package msodbcsql18.
8.940 Preparing to unpack .../5-msodbcsql18_18.4.1.1-1_arm64.deb ...
8.968 Unpacking msodbcsql18 (18.4.1.1-1) ...
9.019 Setting up libodbc1:arm64 (2.3.11-1) ...
9.024 Setting up odbcinst (2.3.11-1) ...
9.028 Setting up odbcinst1debian2:arm64 (2.3.11-1) ...
9.033 Setting up unixodbc (2.3.11-1) ...
9.036 Setting up msodbcsql18 (18.4.1.1-1) ...
9.039 odbcinst: Driver installed. Usage count increased to 1.
9.039     Target directory is /etc
9.040 Setting up unixodbc-dev (2.3.11-1) ...
9.044 Processing triggers for libc-bin (2.31-13+deb11u11) ...
9.054 E: Failed to fetch https://pmc-geofence.trafficmanager.net/debian/11/prod/pool/main/m/mssql-tools18/mssql-tools18_18.4.1.1-1_arm64.deb?geofence=true  Could not handshake: A TLS fatal alert has been received. [IP:xxxx]
------
Dockerfile:13
--------------------
  12 |     # Add SQL Server ODBC Driver 18
  13 | >>> RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  14 | >>>   && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
  15 | >>>   && apt-get update \
  16 | >>>   && apt-get upgrade -y\
  17 | >>>   && ACCEPT_EULA=Y apt-get install -y --fix-missing --no-install-recommends --allow-unauthenticated msodbcsql18 mssql-tools18 \
  18 | >>>   && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile \
  19 | >>>   && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc\
  20 | >>>   && apt-get -y clean

Checking cert returns following. 

`$ openssl s_client -connect pmc-geofence.trafficmanager.net:443`

Connecting to 4.155.111.140
CONNECTED(00000005)
40CF41FC01000000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:ssl/record/rec_layer_s3.c:907:SSL alert number 112
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 339 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

**Comment by ethanlilly** [comment]
Having the same issue here:
```
bash-3.2$ curl -v https://pmc-geofence.trafficmanager.net/
* Host pmc-geofence.trafficmanager.net:443 was resolved.
* IPv6: (none)
* IPv4: 4.155.111.140
*   Trying 4.155.111.140:443...
* Connected to pmc-geofence.trafficmanager.net (4.155.111.140) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* LibreSSL/3.3.6: error:1404B458:SSL routines:ST_CONNECT:tlsv1 unrecognized name
* Closing connection
curl: (35) LibreSSL/3.3.6: error:1404B458:SSL routines:ST_CONNECT:tlsv1 unrecognized name

**Comment by huliang-microsoft** [comment]
We came across the same issue
10.73 E: Failed to fetch https://pmc-geofence.trafficmanager.net/ubuntu/18.04/prod/pool/main/m/mssql-tools/mssql-tools_17.10.1.1-1_amd64.deb?geofence=true  Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
10.73 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

It started about 3 hours ago

**Comment by doza62** [comment]
same here, trying to install mssql-server

```
Err:2 https://packages.microsoft.com/ubuntu/22.04/mssql-server-2022 jammy/main amd64 mssql-server amd64 16.0.4140.3-1
  Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
Fetched 307 kB in 10s (31.8 kB/s)
E: Failed to fetch https://pmc-geofence.trafficmanager.net/ubuntu/22.04/mssql-server-2022/pool/main/m/mssql-server/mssql-server_16.0.4140.3-1_amd64.deb?geofence=true  Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by zach-cohen-milliman** [comment]
Similar issue:

```
4.490 Ign:3 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 mssql-tools18 amd64 18.4.1.1-1
5.580 Ign:3 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 mssql-tools18 amd64 18.4.1.1-1
7.672 Ign:3 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 mssql-tools18 amd64 18.4.1.1-1
11.77 Err:3 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 mssql-tools18 amd64 18.4.1.1-1
11.77   Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
11.78 E: Fetched 1629 kB in 8s (215 kB/s)
11.78 Failed to fetch https://pmc-geofence.trafficmanager.net/ubuntu/20.04/prod/pool/main/m/mssql-tools18/mssql-tools18_18.4.1.1-1_amd64.deb?geofence=true  Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
11.78 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by philnoakes** [comment]
Same issue. Updates appreciated.
update: works now.

**Comment by kshillingstad** [comment]
It looks like this has been restored. Thanks!
