### ISSUE TITLE
Unable to load extension binaries 

### ISSUE THREAD

**Issue by nahueloyha** [Microsoft/msphpsql#158]
Cant' get PHP to load the .so binaries, tried with both SQLSRV (NTS) and PDO_SQLSRV (NTS).

Already installed unixODBC driver manager (2.3.1 x64) and Microsoft ODBC Driver 13 for Linux using the provided script (both seems OK). 

The error is the same with PDO and non-PDO extension:
```
php -v 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/php_sqlsrv_7_nts.so' - /usr/lib64/php/modules/php_sqlsrv_7_nts.so: undefined symbol: SQLGetDiagField in Unknown on line 0
```

```
php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/php_pdo_sqlsrv_7_nts.so' - /usr/lib64/php/modules/php_pdo_sqlsrv_7_nts.so: undefined symbol: SQLGetDiagField in Unknown on line 0
```
PHP 7.0 NTS
CentOS 7.2 x64

Any clue? Thanks!

**Comment by meet-bhagdev** [comment]
Hi @nahueloyha are you able to connect via sqlcmd?

**Comment by nahueloyha** [comment]
Hi @meet-bhagdev ! Yes, I can connect using sqlcmd.

**Comment by nahueloyha** [comment]
UPDATE: just tried with the [preview 4.0.4 release version](https://github.com/Microsoft/msphpsql/releases/tag/4.0.4-Linux) of the binaries and the "undefined symbol" error is gone, both extensions (NTS PDO and NTS non-PDO) are loading OK now!

Thanks @meet-bhagdev !
