### ISSUE TITLE
Objects and resources (streams) cause web server crash after sqlsrv_prepare()

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#16]
/\*  
This sample code will crash your web server.  
It won't crash when $myDate is initialised to a DateTime object _ before _
calling sqlsrv_prepare().  
*/   

$conn = sqlsrv_connect(........);  
sqlsrv_free_stmt(sqlsrv_query($conn, "create table #myDateTable(id int null,
myDate datetime null)"));  
/ _ $myDate = new DateTime() _ / // Uncomment this line to avoid the crash  
$params = array(&$id, &$myDate);  
$tsql = "insert into #myDateTable(id, mydate) values(?,?)";  
$stmt = sqlsrv_prepare($conn, $tsql, $params);  
$datedata = array( 'Wed, 21 Apr 2010', 'Thu, 22 Apr 2010');  
foreach($datedata as $k=>$v)  
{  

```
$id = $k+1;
$myDate = new DateTime($v);
if ( !sqlsrv_execute($stmt) )
{
    print_r(sqlsrv_errors($conn));
    echo '<br />';
}
else
{
    echo 'Row Inserted<br />';
}
```

}  
sqlsrv_free_stmt(sqlsrv_query($conn, "drop table #myDateTable"));  
## Work Item Details

**Original CodePlex Issue:**    [Issue 17336](http://sqlsrvphp.codeplex.com/workitem/17336)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Apr 21, 2010 at 3:03 PM
**Reported by:**    robertjohnson
**Updated on:** Jul 13, 2010 at 9:04 PM
**Updated by:** icosahedron

**Comment by yitam** [comment]
Can no longer reproduce the crash. Closing this issue.
