### ISSUE TITLE
CharacterSet SQLSRV_ENC_CHAR ignored in linux

### ISSUE THREAD

**Issue by sirio3mil** [Microsoft/msphpsql#162]
Hi all,

I don't know wich is the problem source but when I run this code

`$conn = sqlsrv_connect(HOST, [
        "UID" => USER,
        "PWD" => PASW,
        "Database" => DATABASE,
        "CharacterSet" => SQLSRV_ENC_CHAR
]);

if($conn){
    $query = "SELECT TOP 1 nombre FROM cliente WHERE codigo_cliente = ?";
    $stmt = sqlsrv_query($conn, $query, [
            'TVE'
    ]);
    while($row = sqlsrv_fetch_array($stmt, SQLSRV_FETCH_ASSOC)){
        echo $row['nombre'];
        echo PHP_EOL;
        var_dump(mb_detect_encoding($row['nombre'], 'UTF-8', true));
        echo PHP_EOL;
    }
    sqlsrv_free_stmt($stmt);
    sqlsrv_close($conn);
}
else{
    echo "Connection could not be established.";
    die(print_r(sqlsrv_errors(), true));
}`

I get different answer in windows and linux.

My app and db store data in iso 8859-1 (I know bad choice) and I get in windows properly answer

> Corporacion Radio Television Española, S.A.
> 
> C:\tests\sqlsrv.php:32:boolean false

But in linux get

> CorporacionÂ RadioÂ TelevisionÂ EspaÃ±ola,Â S.A.
> 
> string(5) "UTF-8" 

Why? If I check content type I get on both iso 8859-1 and php on both is configured to serve iso 8859-1.

Regards

**Comment by sirio3mil** [comment]
Hi @meet-bhagdev any solution about this? regards

**Comment by meet-bhagdev** [comment]
@sirio3mil We are looking into this! Stay tuned.

**Comment by sirio3mil** [comment]
@meet-bhagdev if you put any invalid value in "CharacterSet" like SQLSRV_ENC_BINARY, 
unlike windows where error reports in linux still working

**Comment by meet-bhagdev** [comment]
@sirio3mil Any particular reason why you have to use "CharacterSet" => SQLSRV_ENC_CHAR? We are looking at this issue and seems like that might be the problem.

**Comment by sirio3mil** [comment]
Hi @meet-bhagdev cuz our project initially wasn't in UTF-8 so this is a default value in Windows driver an work fine in non utf8 projects. Now we are in UTF-8 and do not use it but UTF-8 differ between windows and linux version, same query produce in linux unexpected characters at the end.

**Comment by meet-bhagdev** [comment]
Understood. So for "CharacterSet" you are using UTF-8. Is that right?

**Comment by sirio3mil** [comment]
Now yes @meet-bhagdev, but as I told you, in linux, and some queries, it fail.

**Query**

 SELECT xxx.xxx_id
 FROM xxx
 INNER JOIN yyy_xxx ON yyy_xxx.xxx = xxx.xxx_id
 INNER JOIN yyy_zzz ON yyy_zzz.yyy_xxx = yyy_xxx.yyy_xxx_id
 INNER JOIN dbo.FN_SPLIT(?, ',') spl2 ON spl2.campo = xxx.field1
 INNER JOIN dbo.FN_SPLIT(?, ',') spl ON spl.campo = xxx.field2
 WHERE (xxx.date BETWEEN ? AND ?)
  AND (xxx.stat <> ?)
  AND (xxx.another = ?)
  AND (xxx.flag = 0)
  AND (xxx.other = 0)

**Params**

•	723363,723364,723365,723366,723367,723368,723369,723370,723371,723730,723731,723732,723733,723734,723735,723736,723737,723738,787301,787329,795424,796145,796146,796169,796171,798319,798320,798321,801068,801069,801072,801345,801375,801376,801386,801392,801581,801582,801583,801584,801585,801586,801587,801589,801594,801595,801597,801599,801600,801604,801606,801607,801608,801609,801610,801611,801612,801613,801614,801832,801833,803826,803827,803828,803829,803830,803831
•	17,21,6,15,3,30,5,16,22,9
•	2016-10-10 00:00
•	2016-10-18 23:55
•	7
•	0

**Error**

MSSQL Server
State: 22018
Code: 245
Message: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value '803831㭆 
..㭇 
..㭈 
..㭉 
..㭊 
..㭋 
..㭌 
..㭍 
..㭎 
..㰨 
..㰩 
..䏲 
..䏳 
..䏴 
..䏵 
..䏶 
..䏷

**Comment by sirio3mil** [comment]
I get this issue in two different queries, with long parameters as above an in sp with xml parameters that I send a null value.

I'm using last driver version for centos, using Remi Repo and PHP 7.1 RC6.

Regards.

**Comment by sirio3mil** [comment]
Both errors are present when I define CharacterSet as UTF-8, but if I remove CharacterSet from options everything is ok. In windows we still need set CharacterSet to work with UTF-8 but in linux look like if you put this configuration something go wrong.

**Comment by meet-bhagdev** [comment]
With Characted set UTF-8, the trailing Chinese character bug should be fixed 👍 

You can upgrade using PECL: https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux#install

If you need the binaries, we will be releasing them soon on GitHub
