### ISSUE TITLE
Inserted text occassionally trailed by random characters after insert for strings of length 385 or greater

### ISSUE THREAD

**Issue by ethan-tr** [Microsoft/msphpsql#163]
After updating to 4.0.4 (from 4.0.2) I started experiencing an issue where data serialized with the json_encode or serialize function is randomly trailed by what look like random Chinese characters. The fields are nvarchar(max). I didn't change the character set in PHP or collation in the DB. Unfortunately this issue seems to happen randomly. I cannot reproduce it.

This is happening with PHP 7 on Ubuntu 16.04. The SQL Server version is 12.0.2000.8.

Update: This seems to only be an issue when the data is over roughly 1000 characters.

**Comment by ianguerit** [comment]
I'm seeing same issue, potentially related to #169 with string length and UTF-8 but for a text field type

**Comment by meet-bhagdev** [comment]
@ethan-tr We are working actively on a fix for this. Can you send us a repro that we can use to validate?

**Comment by ethan-tr** [comment]
@meet-bhagdev I was able to reproduce the issue with a simple script. I'll clean it up and share it.

**Comment by ethan-tr** [comment]
This string is the minimum length (385) that triggers the issue.

```php
$message = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
```

**Comment by jan-kratochvil** [comment]
Hi I have similar issue, but on selects. Could this be related? I checked the length and it seems strings size 385 and greater are affected with this problem. The server returns extra characters at the end on select. The fieldtype is text. Do you need any more info?

**Comment by meet-bhagdev** [comment]
@jan-kratochvil @ethan-tr @ianguerit This should be fixed with our latest release. You can upgrade using PECL: https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux#install

If you need the binaries, we will be releasing them soon on GitHub
