### ISSUE TITLE
Linux Version 4.0.5 and PECL

### ISSUE THREAD

**Issue by remicollet** [Microsoft/msphpsql#164]
I notice version 4.0.5 of sqlsrv and pdo_sqlsrv have been released on PECL ?

I don't see any commit here in the PHP-7.0-Linux branch ?

Diffing 4.0.4 and 4.0.5, it seems most of the change are present (mine), but some are missing, especially the version number.

Also missing: the package.xml used to generate the pecl archive.

Can you please add the missing files / changes, and tag 4.0.5 here ?

**Comment by remicollet** [comment]
I also think the version macros are a bit confusing

       #define PHP_SQLSRV_VERSION "4.0.5"

Unused, but check during package upload on PECL

      #define VER_FILEVERSION_STR "4.0.5.0"

Used in MINFO and zend_module_entry

So "pecl list" reports 4.0.5, while phpinfo and reflection report 4.0.5.0

Would it be simpler to only use PHP_SQLSRV_VERSION everywhere ?

(of course, same comment about PHP_PDO_SQLSRV_VERSION)

**Comment by meet-bhagdev** [comment]
@remicollet should be fixed with our latest release - https://github.com/Microsoft/msphpsql/releases/tag/4.0.6-Linux. Let us know what you think.
