### ISSUE TITLE
Reported version number in phpinfo()

### ISSUE THREAD

**Issue by david-garcia-garcia** [Microsoft/msphpsql#166]
Build versions reported in phpinfo() on - at least - the Windows driver are confusing.

![image](https://cloud.githubusercontent.com/assets/9599352/19105795/38c28122-8ae4-11e6-8040-fc61fbc55a1f.png)

![image](https://cloud.githubusercontent.com/assets/9599352/19105798/3b513334-8ae4-11e6-8efc-60e8e2bb22ae.png)

Last image is supposed to be from 4.1.3 release and the previous one from 4.1.2

**Comment by Hadis-Fard** [comment]
@david-garcia-garcia Thanks for feedback, we redesigned the versioning in the latest release, please download the binaries from [here](https://github.com/Microsoft/msphpsql/releases/tag/4.1.4-Windows).
