### ISSUE TITLE
Using reflection on the extension or the functions in the extension result in invalid parameter names.

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#17]
The parameter names to all the functions in the extension (V1.1.428.1) are
quoted ...  

[2010/04/30 12:17:20] [C:] [] >c:\php5\php.exe -n -d extension_dir=c:\php5\ext
-d extension="php_sqlsrv_53_nts_vc9.dll" --rf sqlsrv_connect  
Function [ internal:sqlsrv function sqlsrv_connect ] {  
- Parameters [2] {  
  Parameter #0 [ <required> $"server" ]  
  Parameter #1 [ <optional> array $"options" ]  
  }  
  }  

Patch supplied to fix this.  

Regards,  

Richard Quadling.  

P.S. Re-attached patch and to [
http://sqlsrvphp.codeplex.com/SourceControl/PatchList.aspx
](http://sqlsrvphp.codeplex.com/SourceControl/PatchList.aspx)  
## Work Item Details

**Original CodePlex Issue:**    [Issue 17486](http://sqlsrvphp.codeplex.com/workitem/17486)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Apr 30, 2010 at 11:21 AM
**Reported by:**    RQuadling
**Updated on:** Jul 17, 2010 at 8:44 PM
**Updated by:** AshayC
#### Plaintext Attachments

[CodePlex Issue #17486 Plain Text Attachments](https://gist.github.com/8138d2b8fd3b34b7cd2b)

**Comment by yitam** [comment]
Already incorporated. Closing the issue
