### ISSUE TITLE
Windows Authentication not working anymore

### ISSUE THREAD

**Issue by gubler** [Microsoft/msphpsql#171]
I am trying to upgrade an existing application from PHP 5.5 / SQL Server Driver 3.2 to PHP 7 / SQL Server Driver 4.0. This is on servers (both web and database) using Kerberos for authentication to handle the double hop problem.

When I do a PDO connection with a username/password, I can connect fine

~~~php
$conn = new PDO(
    "sqlsrv:server=$serverName; Database = $database;ConnectionPooling=0",
    $username,
    $password
);
~~~
But when I omit the username and password to use Windows authentication I get an error

    Connection failed: SQLSTATE[28000]: [Microsoft][ODBC Driver 11 for SQL Server]
    [SQL Server]Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.

This is the PHP:

~~~php
$conn = new PDO(
    "sqlsrv:server=$serverName; Database = $database;ConnectionPooling=0"
);
~~~
This same code works fine under PHP 5.6 with SQL Server driver 3.2 on the same server, so Kerberos is configured correctly for handling the double hop.

Is there a new, different way to handle Windows Authentication with the PHP 7 and SQL Server?

**Comment by meet-bhagdev** [comment]
@gubler Very interesting. We will look into this and get back to you asap.

**Comment by gubler** [comment]
Never mind - some one applied some patches to the server - its not the SQL server driver. Whatever the updates did to the server, now this is only occurring with Windows clients (though not Mac clients). 

Since it at least works properly with Mac clients, I am sure it is a configuration change that happened to the server and not a problem with the SQL Server driver.

Thank you for the quick reply, though :)
