### ISSUE TITLE
Manually binding a column type breaks SQLSRV_ATTR_FETCHES_NUMERIC_TYPE behaviour

### ISSUE THREAD

**Issue by david-garcia-garcia** [Microsoft/msphpsql#173]
SQLSRV_ATTR_FETCHES_NUMERIC_TYPE allows types that can be represented by PHP's int and float be returned as so (int, smallint, tinyint, float, real...).

Buf if you manually bind a column's return type in a statement, this behaviour is completely broken for the rest of the columns.

Sample script here: http://pastebin.com/at3TcXRa

Current output:

> id:string
> myinteger:string
> mybiginteger:string
> myfloat:string
> mysmallint:string
> mybit:string
> myreal:string
> mynvarchar:string
> 
> id:integer
> myinteger:integer
> mybiginteger:string
> myfloat:double
> mysmallint:integer
> mybit:integer
> myreal:double
> mynvarchar:string

Expected output:

> id:integer
> myinteger:integer
> mybiginteger:string
> myfloat:double
> mysmallint:integer
> mybit:integer
> myreal:double
> mynvarchar:string
> 
> id:integer
> myinteger:integer
> mybiginteger:string
> myfloat:double
> mysmallint:integer
> mybit:integer
> myreal:double
> mynvarchar:string

**Comment by david-garcia-garcia** [comment]
BTW, if SQLSRV_ATTR_FETCHES_NUMERIC_TYPE also took care of assuming that varbinary columns store binary data, that would be awesome.

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia we are actively working a fix for this. Stay tuned! 👍

**Comment by david-garcia-garcia** [comment]
Confirmed this is fixed in the 4.1.5 release.
