### ISSUE TITLE
Compile error in centos 6.8

### ISSUE THREAD

**Issue by epoxa** [Microsoft/msphpsql#174]
Trying to compile under centos 6.8 I always get an error
`[root@centosdev php-7.0.12]# make
/bin/sh /root/php-7.0.12/libtool --silent --preserve-dup-deps --mode=compile c++ -I/root/php-7.0.12/ext -std=c++11 -Iext/pdo_sqlsrv/ -I/root/php-7.0.12/ext/pdo_sqlsrv/ -DPHP_ATOM_INC -I/root/php-7.0.12/include -I/root/php-7.0.12/main -I/root/php-7.0.12 -I/root/php-7.0.12/ext/date/lib -I/usr/include/libxml2 -I/root/php-7.0.12/ext/sqlite3/libsqlite -I/root/php-7.0.12/TSRM -I/root/php-7.0.12/Zend    -std=c++11   -c /root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp -o ext/pdo_sqlsrv/core_conn.lo 
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp: In function ‘sqlsrv_conn* core_sqlsrv_connect(sqlsrv_context&, sqlsrv_context&, driver_conn_factory, const char*, const char*, const char*, HashTable*, error_callback, const connection_option*, void*, const char*)’:
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:205:12: error: expected type-specifier
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:205:30: error: expected unqualified-id before ‘const’
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:205:30: error: expected ‘)’ before ‘const’
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:205:30: error: expected ‘{’ before ‘const’
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:205:40: error: expected initializer before ‘)’ token
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:212:5: error: expected primary-expression before ‘catch’
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:212:5: error: expected ‘;’ before ‘catch’
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:219:5: error: expected primary-expression before ‘catch’
/root/php-7.0.12/ext/pdo_sqlsrv/core_conn.cpp:219:5: error: expected ‘;’ before ‘catch’
make: *** [ext/pdo_sqlsrv/core_conn.lo] Error 1
`
I believe gcc is used. My gcc version is:
gcc version 4.7.2 20121015 (Red Hat 4.7.2-5) (GCC)
Configured with: ../configure --prefix=/opt/centos/devtoolset-1.1/root/usr --mandir=/opt/centos/devtoolset-1.1/root/usr/share/man --infodir=/opt/centos/devtoolset-1.1/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --disable-build-with-cxx --disable-build-poststage1-with-cxx --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-ppl --with-cloog --with-mpc=/home/centos/rpm/BUILD/gcc-4.7.2-20121015/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix

What can be the issue there? Thanks

**Comment by v-kigos** [comment]
I am able to build sqlsrv / pdo_sqlsqrv on CentOS 6.8.

Can you confirm:
$ cat /etc/redhat-release 
CentOS release 6.8 (Final)

$ gcc -v
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 

$ odbcinst -j
unixODBC 2.3.1
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/user/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

**Comment by epoxa** [comment]
Seems I have older gcc:
`gcc version 4.7.2 20121015 (Red Hat 4.7.2-5) (GCC)`
and 
`USER DATA SOURCES..: /root/.odbc.ini`
Should I upgrade my gcc? What repository version 4.8.2 is available in?

**Comment by v-kigos** [comment]
sudo yum update
sudo yum groupinstall "Development Tools"

These two commands should update your CentOS 6.8

**Comment by epoxa** [comment]
After updating yum it offers me to install gcc version 4.4.7-17.el6
I believe it requires some specific repo.

**Comment by v-kigos** [comment]
Can you confirm:
$ cat /etc/redhat-release

**Comment by epoxa** [comment]
CentOS release 6.8 (Final)

**Comment by meet-bhagdev** [comment]
@epoxa: Might have a solution for you. Centos 6.8 has gcc 4.4 as a default compiler.
 
We require GNU GCC 4.8 with is not available in the default yum repository yet, this it should be manually added.
 
Steps to add it
 
```
sudo wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo 
sudo yum install devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++ 
```

Give this a shot and let us know what you think

**Comment by epoxa** [comment]
I have installed it already. Seems gcc 4.8 solves the problem. So I can successfully compile sqlsrv but not pdo_sqlsqv (there was another compile error - do not remember now exact message).
For now I switched from centos 6.8 to centos 7 and installed binary package.
Thanks
