### ISSUE TITLE
Can not connect named instance

### ISSUE THREAD

**Issue by epoxa** [Microsoft/msphpsql#175]
I use precompiled version of sqlsrv driver from Remi's repository under Centos 7.2 (core). (Actually inside docker image).
Successfully connecting to ordinal sql server but somehow can not connect to named instance like that:
`$pdo = new PDO("sqlsrv:Server=servername\\H;Database=dbname", "testuser", "testpass");`
The same issue with sqlsrv_connect() without PDO.
Can anybody confirm successful connection to named sql server instance?

**Comment by epoxa** [comment]
If named instance is on known static port there is workaround:
`$pdo = new PDO("sqlsrv:Server=servername,56789;Database=dbname", "testuser", "testpass")`
where 56789 is port number.
This works well for me.

**Comment by meet-bhagdev** [comment]
Awesome! 👍 I will go ahead and close this issue for now.

**Comment by epoxa** [comment]
Thanks )
