### ISSUE TITLE
Calling stored procedures

### ISSUE THREAD

**Issue by ritey** [Microsoft/msphpsql#176]
System: Linux ubuntu 4.4.0-45-generic
PHP Version 7.0.8
PDO SQLSRV version 4.0.5.0 

I'm trying out the latest PHP available with the latest Linux SQL driver calling a stored procedure on Azure and have an issue retrieving a value from the Input Output parameter which is defined as an NVarChar(Max).

The existing MSSQL database I'm wanting to run PHP against is using extensive views and SP's and table value functions and I'd really like to leverage the latest PHP library's to make an API to the database.

The SP in the example doc provided is extremely simple, are stored procedures going to get a decent implementation in the latest version of the driver?

Thanks

**Comment by meet-bhagdev** [comment]
@ritey we will take a look at this. Can you send us a repro script?

**Comment by ritey** [comment]
This is a massively cut down stored procedure, but you get the gist with this, if you want the full existing procedure let me know who I can email it too. 

As far as I can tell, this should work.

```
USE [sample_db]
GO
/****** Object:  StoredProcedure [dbo].[getPersonId]    Script Date: 31/10/2016 11:31:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[getPersonId]
	@JSONPersonIDs NVarChar(Max) OUTPUT,
	@number integer
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @arrPersonID nvarchar(32);
	SET @arrPersonID = N'123456789';
	SET @JSONPersonIDs = CONCAT(N'[', SUBSTRING(@arrPersonID, CAST(2.0 AS int), CAST(999.0 AS int)), N']');
	SELECT @JSONPersonIDs;
END
```

The PHP

```

$number = '987654321';

$sql = 'CALL getPersonId(?,?)';
$sth = $dbh->prepare($sql);
$sth->bindParam(1, $return, PDO::PARAM_STR|PDO::PARAM_INPUT_OUTPUT,12);
$sth->bindParam(2, $number, PDO::PARAM_INT);
$sth->execute();

echo $return;
exit();

```

**Comment by ritey** [comment]
The error reported is: Uncaught PDOException: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near '@P1'

**Comment by ritey** [comment]
Also, as previous versions have not allowed NVarCharMax as an output param, even changing it to a VarChar(32) or anything for this test, still doesn't work.

**Comment by Hadis-Fard** [comment]
@ritey You should use reference parameter to retrieve output or bidirectional parameters, so you should add `&` to `$return` variable: `$sth->bindParam(1, &$return, PDO::PARAM_STR|PDO::PARAM_INPUT_OUTPUT,12);`.

**Comment by ritey** [comment]
@Hadis-Fard Interestingly, and looking at other examples you'd be right, but with this if you do you get:

Parse error: syntax error, unexpected '&' with or without the variable already initialised.

Having done some more testing and re-working based on even older SP examples I've found, changing the statement to the following does work:
```
$sql = 'EXEC getPersonId ?,?';
```

**Comment by Xavierus** [comment]
@Hadis-Fard Call-time pass-by-reference has been removed since PHP 5.4

**Comment by dixonnixon** [comment]
Hello. And  what should I do if i have no output parametres of my SP. only this code at the end of sp.:

"Select  ID , convert(char(10), MAX_DATE_REG, 104) as  DATE_REG, COUNT_ID_LOCATEWP, ID_LOCATEWP, KOD, VIDDIL from  #rez_tbl"  


And 3 input param-s 
"ALTER     procedure [dbo].[USP_VIEWKWP] (@id int, @checkreg bit = 1, @roolback bit = 1) AS ..."

I tried this code : 
"$dbDB = new PDO("sqlsrv:Server=$server;Database=$db_name", $username, $password);
        $number = 0;
	$sql = 'EXEC USP_VIEWKWP ?, ?, ?';
	$stmt = $dbDB->prepare($sql);
	$stmt->bindParam(1, $number, PDO::PARAM_INT);
	$stmt->bindParam(2, $number, PDO::PARAM_INT);
	$stmt->bindParam(3, $number, PDO::PARAM_INT);
	$stmt->execute();
	
	$result = $stmt->fetch(PDO::FETCH_ASSOC);"
and result is nothing....

**Comment by ritey** [comment]
@dixonnixon Do you have 

```
SET NOCOUNT ON;
``` 

at the beginning of the SP?

**Comment by dixonnixon** [comment]
@ritey, actually no. Only SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

**Comment by ritey** [comment]
@dixonnixon Try adding it after SET QUOTED_IDENTIFIER ON....

**Comment by dixonnixon** [comment]
I'd add this after DECLARE, in my sp and there no effect in output... 
this is sp look:
`USE [tech]
GO
/****** Object:  StoredProcedure [dbo].[USP_VIEWKWP]    Script Date: 11/08/2016 14:02:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER       procedure [dbo].[USP_VIEWKWP] (@id_udk int, @checkreg bit = 1, @roolback bit = 1) AS
declare @max_date_REG datetime, @count_id_locatewp smallint, @count_noreg smallint,
        @id_locatewp smallint , @id int,
        @kod char(4), @viddil varchar(128), @nwp smallint 

-- @roolback параметр отвечате  за фильтрацию выводимых данных 1 - только  те  карточки, которые  можно перевести  режим правки, 0 - только просмотр

SET NOCOUNT ON;
create table #rez_tbl (ID int, MAX_DATE_REG datetime, COUNT_ID_LOCATEWP smallint, ID_LOCATEWP smallint, KOD char(4), VIDDIL varchar(128), NWP smallint   )

if (@id_udk = 0 ) 
begin

 if ( @roolback = 1 )
  declare kwp_CURSOR  CURSOR FOR
  select max(date_REG), count(id_locatewp),  ID_LOCATEWP  from  kwp k  where state=1 and roolback = 1   group by ID_UDK, id_locatewp 
 else 
  declare kwp_CURSOR  CURSOR FOR
  select max(date_REG), count(id_locatewp),  ID_LOCATEWP  from  kwp k  where state=1   group by ID_UDK, id_locatewp

end
else 
begin

 if ( @roolback = 1 )
  declare kwp_CURSOR  CURSOR FOR
  select max(date_REG), count(id_locatewp), ID_LOCATEWP  from  kwp k  where id_udk = @id_udk and state=1 and roolback = 1   group by  id_locatewp
 else  
  declare kwp_CURSOR  CURSOR FOR
  select max(date_REG), count(id_locatewp), ID_LOCATEWP  from  kwp k  where id_udk = @id_udk and state=1   group by  id_locatewp

end

open kwp_CURSOR 
FETCH NEXT FROM  kwp_CURSOR into  @max_date_REG, @count_id_locatewp,  @id_locatewp

WHILE @@FETCH_STATUS = 0 
begin
 if (@checkreg = 1)
 begin
  select @count_noreg = count(*) from kwp where   id_locatewp = @id_locatewp and state = 0 
 end 
 else  
 begin
   select @count_noreg = 0 
 end
 if ( @count_noreg = 0 )
 begin
  select @id=max(id)  from  kwp  where date_REG = @max_date_REG and id_locatewp = @id_locatewp and state = 1 
   select @kod = KOD, @viddil = VIDDIL, @nwp = NWP from  vkwp  where id = @id
  insert into #rez_tbl (id, max_date_REG, count_id_locatewp, id_locatewp, kod, viddil, nwp ) values ( @id, @max_date_REG, @count_id_locatewp, @id_locatewp,  @kod, @viddil, @nwp)
 end
 FETCH NEXT FROM  kwp_CURSOR into  @max_date_REG, @count_id_locatewp,  @id_locatewp

end 

CLOSE kwp_CURSOR
DEALLOCATE kwp_CURSOR
Select  ID , convert(char(10), MAX_DATE_REG, 104) as  DATE_REG, COUNT_ID_LOCATEWP, ID_LOCATEWP, KOD, VIDDIL, NWP from  #rez_tbl
drop table  #rez_tbl

`
there is no output parametres in sp. May be i should rewrite sp somehow.
And also I use $stmt->execute(); while( $rows = $stmt->fetchAll(PDO::FETCH_NUM)) {
		   print_r($rows);
	   }

may be this wrong way

**Comment by ritey** [comment]
Ok. I'd leave the SET NO COUNT ON; as you have. In your PHP if you fire 

```
$stmt->nextRowset();
```
straight after execute and then fetch do you get anything?

**Comment by dixonnixon** [comment]
I 'Ve found this would work if declaring procedure line without brackets in SQL-code:
`ALTER procedure dbo.USP_VIEWKWP @id_udk int, @checkreg bit = 1, @roolback bit = 1 ` 
work correctly with this PHP code: 
`$dbDB = new PDO("sqlsrv:Server=$server;Database=$db_name", $username, $password);

	$sql = 'EXEC USP_VIEWKWP 0,0,0';
	
	$stmt = $dbDB->prepare($sql);

	$stmt->execute();
	// print_r($stmt);
	echo "<pre>";
	while( $rows = $stmt->fetchAll(PDO::FETCH_NUM)) {
		   print_r($rows);
	   }`

Thanx/ to/ /All/

**Comment by meet-bhagdev** [comment]
Awesome 👍  Closing it for now.
