### ISSUE TITLE
PDO_SQLSRV for HHVM?

### ISSUE THREAD

**Issue by beatrohrer** [Microsoft/msphpsql#177]
Are there any plans to port PDO_SQLSRV to HHVM?

**Comment by meet-bhagdev** [comment]
@beatrohrer Not as of now. Any particualr reasons you would prefer to use the driver with HHVM vs PHP given the recent PHP 7 enhancements

**Comment by beatrohrer** [comment]
Hack is the reason, especially async, generics, and the better type system. E.g. it would be really great to be able to make concurrent calls to the DB for non-dependent queries.

**Comment by meet-bhagdev** [comment]
Closing issue as we don't plan to support this for now. Happy to help you achieve your goals around async and generics using the PHP binaries.
