### ISSUE TITLE
php-7.0-linux pro_sqlsrv  can not find sql.h

### ISSUE THREAD

**Issue by purebin** [Microsoft/msphpsql#179]
/usr/local/php/include/php/mssql/pdo_sqlsrv/xplat.h:36:17: fatal error: sql.h: No such file or directory
compilation terminated.

**Comment by purebin** [comment]
configure : successed

but make && make install error

error info:
/usr/local/php/include/php/mssql/pdo_sqlsrv/xplat.h:36:17: fatal error: sql.h: No such file or directory
compilation terminated.

**Comment by purebin** [comment]
need to install odbc
centos --  yum install unixODBC unixODBC-devel libtool-ltdl libtool-ltdl-devel

**Comment by Hadis-Fard** [comment]
@purebin `sql.h: No such file or directory` means that unixODBC is not installed properly, please clean up any previous installed ODBC and unixODBC and follow the instructions [here](https://github.com/meet-bhagdev/phptekdemo/blob/master/proposedreadme.md#step-1-install--php-unless-already-installed). To make sure installation has been successful, please try connecting using `sqlcmd`.

**Comment by meet-bhagdev** [comment]
@purebin: @Hadis-Fard is correct. Can you follow the installation guide here: https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux#install
