### ISSUE TITLE
wget command in installodbc_ubuntu.sh fails

### ISSUE THREAD

**Issue by jsamuel** [Microsoft/msphpsql#181]
One of the wget commands in the `installodbc_ubuntu.sh` script uses both `-O` and `-P` which appears to not work as intended. With the script as it currently is, the file `msodbcsql-13.0.0.0.tar.gz` is getting downloaded inside the `/tmp/msodbcubuntu/unixODBC-2.3.1` because the `-P` is essentially ignored and that location isn't where the rest of the script is expecting it.

This can be fixed by changing:

    -O msodbcsql-13.0.0.0.tar.gz -P /tmp/msodbcubuntu

to

    -O /tmp/msodbcubuntu/msodbcsql-13.0.0.0.tar.gz

such as with this patch:

```
--- installodbc_ubuntu.sh.orig  2016-11-16 11:46:31.399941218 -0500
+++ installodbc_ubuntu.sh       2016-11-16 11:55:59.976171461 -0500
@@ -15,7 +15,7 @@
 
 
 echo "Downloading the Microsoft ODBC Driver 13 for SQL Server- Ubuntu"
-wget "https://meetsstorenew.blob.core.windows.net/contianerhd/Ubuntu%2013.0%20Tar/msodbcsql-13.0.0.0.tar.gz?st=2016-10-18T17%3A29%3A00Z&se=2022-10-19T17%3A29%3A00Z&sp=rl&sv=2015-04-05&sr=b&sig=cDwPfrouVeIQf0vi%2BnKt%2BzX8Z8caIYvRCmicDL5oknY%3D" -O msodbcsql-13.0.0.0.tar.gz -P /tmp/msodbcubuntu
+wget "https://meetsstorenew.blob.core.windows.net/contianerhd/Ubuntu%2013.0%20Tar/msodbcsql-13.0.0.0.tar.gz?st=2016-10-18T17%3A29%3A00Z&se=2022-10-19T17%3A29%3A00Z&sp=rl&sv=2015-04-05&sr=b&sig=cDwPfrouVeIQf0vi%2BnKt%2BzX8Z8caIYvRCmicDL5oknY%3D" -O /tmp/msodbcubuntu/msodbcsql-13.0.0.0.tar.gz
 cd /tmp/msodbcubuntu/
 tar xvfz /tmp/msodbcubuntu/msodbcsql-13.0.0.0.tar.gz
 cd /tmp/msodbcubuntu/msodbcsql-13.0.0.0/
```

**Comment by meet-bhagdev** [comment]
Good catch. We will look into this and fix it :)

**Comment by meet-bhagdev** [comment]
@jsamuel We no longer need the the installodbc.sh scripts. The ODBC Driver is available for install via apt-get and yum. 
Check out the instructions here: https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux#step-2-install--pre-requisites 
And let us know if you have questions
