### ISSUE TITLE
Mistake in help: Data protocol in PHP expects urlencoded data.

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#19]
PHP has a feature to open the stream from string passed through RFC 2397 data:
protocol.  
The SQLSRV help describes this feature to send the data as a stream to the MS-
SQL server.  

However, data passed in „data:text/plain,…“ string should be either urlencoded
or base64 encoded. Otherwise serious damage of the data occurs, because when
data are not passed as base64, PHP urldecodes them (+ becomes space, %20
entities get decoded, etc.)  

PROBLEM:  
In the SQLSRV help, all source code lines opening stream from string should be
modified according the correct syntax.  
Incorrect syntax: fopen( "data://text/plain,[ Insert lengthy comment here.]",
"r");  
Correct syntax, option #1: fopen("data:text/plain,".urlencode('[ Insert
lengthy comment here.]')."", "r");  
Correct syntax, option #2: fopen("data:text/plain;base64,".base64_encode('[
Insert lengthy comment here.]')."", "r");  

TEST CASE:  
Just run this code in PHP:  
<?php  
$data = 'Günther says: 1+1 is 2, 10%40 is 20.'; // testing data  

// current code  
$fp = fopen('data:text/plain,'.$data, 'rb');  
echo stream_get_contents($fp); // Günther says: 1 1 is 2, 10@ is 20. // Stream
contains invalid data!  

// Correct option 1: urlencoded data  
$fp = fopen('data:text/plain,'.urlencode($data), 'rb');  
echo stream_get_contents($fp); // Günther says: 1+1 is 2, 10%40 is 20. // OK  

// Correct option 2: base64 encoded data  
$fp = fopen('data:text/plain;base64,'.base64_encode($data), 'rb');  
echo stream_get_contents($fp); // Günther says: 1+1 is 2, 10%40 is 20. // OK  
?>  

Links:  
PHP Data stream: [ http://php.net/manual/en/wrappers.data.php
](http://php.net/manual/en/wrappers.data.php)  
RFC 2397: [ http://www.faqs.org/rfcs/rfc2397.html
](http://www.faqs.org/rfcs/rfc2397.html)  
## Work Item Details

**Original CodePlex Issue:**    [Issue 19139](http://sqlsrvphp.codeplex.com/workitem/19139)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Nov 18, 2010 at 11:44 AM
**Reported by:**    michalkocarek
**Updated on:** Nov 18, 2010 at 11:45 AM
**Updated by:** michalkocarek

**Comment by yitam** [comment]
No links to the SQLSRV documentation were specified in the original description. The potential ones are listed below. Please confirm.

http://php.net/manual/en/function.sqlsrv-send-stream-data.php

https://msdn.microsoft.com/en-us/library/cc296180(v=sql.105).aspx
https://msdn.microsoft.com/en-us/library/cc296191(v=sql.105).aspx

**Comment by yitam** [comment]
Closing issue. The aforementioned doc pages have been updated.
