### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\v7.1\ext\php_pdo_sqlsrv_7_nts_x86.dll' - The specified procedure could not be found.  in Unknown on line 0

### ISSUE THREAD

**Issue by klapsius** [Microsoft/msphpsql#191]
After upgrade to PHP 7.1 i have a problem with loading these two files:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\v7.1\ext\php_sqlsrv_7_nts_x86.dll' - The specified procedure could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\v7.1\ext\php_pdo_sqlsrv_7_nts_x86.dll' - The specified procedure could not be found.
 in Unknown on line 0
```
PHP 7.0.7 running on a same server and its fine. My PHP 7.1 is x86 drivers is also x86. IIS Server. I believe if something wrong with IIS then should be wrong with PHP 7.0.7 as well? Could be drivers?

**Comment by meet-bhagdev** [comment]
Can you confirm if you are using x86 IIS or x64 IIS?

**Comment by mlhkr** [comment]
@klapsius did you try php_sqlsrv_71_nts* ones?
https://github.com/Microsoft/msphpsql/releases/download/4.1.4-Windows/7.1.zip

**Comment by klapsius** [comment]
@meet-bhagdev  Windows Server 2012 x64

**Comment by klapsius** [comment]
@mlhkr It works!!!! Thank you. 
But now i have an error: 
```
PHP Warning:  A non-numeric value encountered in  on line 2
$k = hash( 'sha256', $salt+$id, false );
```

**Comment by yitam** [comment]
As indicated in http://php.net/manual/en/migration71.php PHP 7.1 and PHP 7.0 are not compatible. Thus new 7.1 drivers are required. Please let us know if this answers your question. Thank you.

**Comment by klapsius** [comment]
Yes. Thank you

**Comment by tobya** [comment]
@yitam  Does this mean that the mssql pdo drivers only work with PHP 7.0  but not with 7.1?

**Comment by yitam** [comment]
@tobya we provide different sets of drivers for PHP 7.0 and PHP 7.1 as they are incompatible. Please download the right ones for your needs (see the link above). Hope this helps.

**Comment by tobya** [comment]
If I go here

https://www.microsoft.com/en-ie/download/details.aspx?id=20098

I only get the option to download 4.0 drivers which I think are php 7 ones.  

On the releases page https://github.com/Microsoft/msphpsql/releases I can't see any mention of 7.1

I see your link above links to the drivers for 7.1 I'm just wondering how someone searching might find the drivers for 7.1

Thank you.

**Comment by yitam** [comment]
Hi @tobya , this is the [4.1.4 Windows Preview](https://github.com/Microsoft/msphpsql/releases/tag/4.1.4-Windows)

Stay tuned on our releases page that you already know for future releases (for Windows / Linux). 
Hope I have answered your questions.

**Comment by danchohfi** [comment]
Thank you mlhkr, for me this solution work on.

https://github.com/Microsoft/msphpsql/releases/download/4.1.4-Windows/7.1.zip

**Comment by marnylopez** [comment]
Solution from @danchohfi  still works.

**Comment by nathanaelkwangue** [comment]
ujokfdmsk!flksd;

**Comment by mmamoonkhan** [comment]
these warnings can not solved i tried to many solutions but still have an error and due to this i can not run my project
Warning: PHP Startup: Unable to load dynamic library 'pdo_sqlite' (tried: \xampp\php\ext\pdo_sqlite (The specified module could not be found.), \xampp\php\ext\php_pdo_sqlite.dll (The specified procedure could not be found.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_openssl.dll' (tried: \xampp\php\ext\php_openssl.dll (The specified procedure could not be found.), \xampp\php\ext\php_php_openssl.dll.dll (The specified module could not be found.)) in Unknown on line 0
![error](https://user-images.githubusercontent.com/27205456/51605343-a34af280-1f30-11e9-9306-e9d22d6d8d05.PNG)

**Comment by yitam** [comment]
@mmamoonkhan none of those dlls is ours and it looks like you should fix your php ini setting.

**Comment by mihai-marius** [comment]
![image](https://user-images.githubusercontent.com/63041918/81177715-cc6d8600-8faf-11ea-9225-54968070461d.png)
 
No matter what driver I use for php 7.3 is giving me this message

**Comment by yitam** [comment]
@mihai-marius are you using PHP 7.3 thread safe 64 bit?

**Comment by mlhkr** [comment]
As I can see you're using xampp which installs apache but it depends on it's used as CGI mode or not so you better try the non-thread-safe version too. *_nts_*.
Hope it solves your problem.
