### ISSUE TITLE
when using cursor ["Scrollable" => "buffered"] in query the result won't follow "CharacterSet" => "UTF-8" in connection string

### ISSUE THREAD

**Issue by thReality** [Microsoft/msphpsql#192]
I was working with sql server 2012 until now but when I'm trying to use the same code to query sql server 2014 it appear that the column which are stored in varchar and char column won't return with UTF-8 charset 

If I remove ["Scrollable" => "buffered"] it seem to work correctly.

**Comment by yitam** [comment]
We need more info, such as a simple repro script and whether you're using Windows/Linux drivers. Thank you.

**Comment by thReality** [comment]
```
$connectionInfo = ["Database" => "xxx", "UID" => "xxx", "PWD" => "xxx", "CharacterSet" => "UTF-8", 'ReturnDatesAsStrings'=>true];
$link  = sqlsrv_connect("some_srv", $connectionInfo);
sqlsrv_query($link, 'select th_name from dbo.user', [], ["Scrollable" => "buffered"]); // <-- this return ?????
sqlsrv_query($link, 'select th_name from dbo.user'); // <-- this return 'ชื่อ'
```
I'm using windows drivers v4.1
If I run these code on local pc which is windows 10 both statement give correct result
but if I run it on remote dev server which is windows server 2012 r2 it return ?????
not sure if this is related with region and language setting of the os

**Comment by yitam** [comment]
Thanks for the reply. Based on your input, I assume "th_name" is a unicode column (like nvarchar for example). 

We will do some investigation. Meanwhile, because you said it worked perfectly in Windows 10, do you mind to check if it's some settings in your Windows Server 2012 r2?

Thank you.

**Comment by thReality** [comment]
th_name is varchar column.
When I use "CharacterSet" => "UTF-8" the driver seem to automatically convert data between sql collation(Thai_CI_AS) and utf-8.
I do some additional test and found that if I set os language for non-unicode to Thai it will give correct result even if I use ["Scrollable" => "buffered"].
but if the language is set to others which doesn't Thai I need to remove ["Scrollable" => "buffered"] in order to get correct result otherwise it will return ????.

**Comment by yitam** [comment]
@thReality thanks for your detailed response. This is a known issue with varchar/char columns when the encoding is different from the code page. We are actively working on it. Please stay tuned.

**Comment by meet-bhagdev** [comment]
@thReality this issue is now fixed with our latest release. You can get the release on PECL. 
https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux#install
