### ISSUE TITLE
latest version dont work on php 7.1.0

### ISSUE THREAD

**Issue by jagDanJu** [Microsoft/msphpsql#193]
Hey Guys,

the latest version dont work with the latest php release 7.1.0
Whats wrong here?

Thanks a lot
Daniel

**Comment by meet-bhagdev** [comment]
@jagDanJu What version of the release are you using? Are you on Windows or Linux? We will look into this ASAP.

**Comment by jagDanJu** [comment]
Oh sorry..
Version 4.0 - https://www.microsoft.com/en-us/download/details.aspx?id=20098

pdo_mssql
NTS on x64

Thanks Guy

**Comment by jagDanJu** [comment]
Windows.

**Comment by meet-bhagdev** [comment]
Can you try the 7.1 binaries from here: https://github.com/Microsoft/msphpsql/releases/tag/4.1.4-Windows

**Comment by jagDanJu** [comment]
This binaries works! Next time i should at the releases...
I thought that the download center binaries are up to date.

Sorry Guy.
Many Thanks!

**Comment by meet-bhagdev** [comment]
We release every 3-6 weeks on GitHub: https://github.com/Microsoft/msphpsql/releases/. This will have the latest changes and bug fixes. We will be uploading Download Center with the 7.1 binaries in the coming days.
