### ISSUE TITLE
Drupal driver for SQL Server and SQL Azure Active?

### ISSUE THREAD

**Issue by riky93** [Microsoft/msphpsql#195]
I downloaded the SQL Server and SQL Azure driver 8.x-1.0-rc4 for Drupal 8. I Installed the sqlsrv and the driver within the Drupal folder. The issue with the remaining file is that when I click install on Drupal (SQL checked as well), a white screen with an error displays. The error reads the following 

**# Fatal error: Invalid handle returned. in C:\inetpub\wwwroot\drupal-8.2.2\drivers\lib\Drupal\Driver\Database\sqlsrv\Connection.php on line 156**

Why would a default file contain an error as default? Sure you may ask whether my pdo or php version has been installed (in which it is, matching as well).

**Comment by meet-bhagdev** [comment]
@riky93 I will look into this. @david-garcia-garcia might have some input as well.

**Comment by meet-bhagdev** [comment]
@riky93 What version of PHP and ODBC drivers are you using? I am assuming this is on Windows?

**Comment by riky93** [comment]
I am using **PHP 7 x64** and **Microsoft SQL**. THe PDO Driver I am using is **php_pdo_sqlsrv_7_nts_x64.dll**

**Comment by meet-bhagdev** [comment]
@riky93 Have you installed the ODBC Driver as well? If yes, what version of the ODBC Driver are you using?

**Comment by riky93** [comment]
I just found out what ODBC is. I have not installed it. Thank you for letting me know about this. I will install this. I really hope this can solve it. Thank you once again!

**Comment by riky93** [comment]
I just installed Microsoft **ODBC Driver version amd64**. Unfortunately, the site has the same error. Sometimes when I dont enter any information to the installation set up, the error would say "Call to undefined function" within the Connection.php file.

**Comment by david-garcia-garcia** [comment]
@meet-bhagdev "Invalid handle returned" message when no ODBC is available seems like a little bit confusing. Maybe this could be improved...

BTW, is there any way to retrieve the current ODBC version (and settings if any) from within the PDO driver?

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia Agreed! To get the current version of ODBC using use getAttribute function with desired attribute https://msdn.microsoft.com/en-us/library/ff628181(v=sql.105).aspx
@riky93 We are still looking into this.

**Comment by Hadis-Fard** [comment]
@riky93 Can you follow the [install instructions](https://github.com/Microsoft/msphpsql/blob/master/README.md#install)? also make sure the php.ini is set to load the SQLSRV extension by setting `extension_dir` to the dll path, and set the "extension" to the name of SQLSRV dll that you are using for example `extension=php_pdo_sqlsrv_7_nts.dll`. For PDO_SQLSRV driver PDO extension must be loaded too, can you confirm it is loaded by running `php -m`?

**Comment by riky93** [comment]
@Hadis-Fard. Thank you, however I have the PDO installed, and it is showned within the php description file. The php.ini is coded with

 **extension=php_sqlsrv_pdo.dll
extension=php_pdo_mysql.dll**

**Comment by riky93** [comment]
Thank you guys helping! I am a step closer. I decided to re do everything (I have a backup file as well from previous). Good news is that I am not receiving a white screen anymore. The issue is more specific. When clicking "save and continue", towards installation, I receive an error saying, 

**Database mydrupal not found. The server reports the following message when attempting to create the database: SQLSTATE[28000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Login failed for user 'sa'..**

If anyone knows what this means please feel free to let me know. I ensure that everything was running in sql management and restarted the database as well.

**Comment by riky93** [comment]
**UPDATE:**

I added the name of the server/Host name for the installation of Drupal, this time the error changes saying 

**Failed to connect to your database server. The server reports the following message: .

    Is the database server running?
    Does the database exist, and have you entered the correct database name?
    Have you entered the correct username and password?
    Have you entered the correct database hostname?**

I have installed Drupal before with MYSQL multiple times before. However, MSSQL is not letting me connect.

**Comment by meet-bhagdev** [comment]
@riky93 Seems like the SQL Server service is not running. Can you try connecting using SQL Server Management Studio and/or a sample PHP script?

**Comment by riky93** [comment]
I created a php file within the wwwroot folder. In the file, I entered the code 


**<h1>hi world</h1> 
<?php


$serverName = "(local)\MSSQLNEW";

$conn = new PDO("sqlsrv:server=$serverName;Database=thedrupal","sa","academy");
 
if($conn){
	echo "Connection established.</br></br>";
	echo $conn;
} else{
	echo "Connection could not be established. </br>";
	die(print_r(sqlsrv_errors(), true));
}


?>**

When testing the file in the browser, the site said "Hi world  Connection established"

When you said connecting SQL server to studio management, does that mean I have to use code to connect it? it does not connect by installation? Because I have a SQL studio management, thats where I made my database and user sign in.

**Comment by riky93** [comment]
The way I did this process is through a read along tutorial based on Drupal on Windows. Here is the link to it

http://www.drupalonwindows.com/en/blog/installing-drupal-8-windows 

I followed everything exactly (documenting my work as I go ensuring I do not miss anything) except installing PDO driver through composer. I did that manually. I just cant proceed to the final installation. uhhhhh.

**Comment by david-garcia-garcia** [comment]
@riky93 Setup a development environment with a debugger and dig your way through the code to find out what is going on.

There are many paid courses online on how to do that, also for free:

https://code.tutsplus.com/tutorials/xdebug-professional-php-debugging--net-34396
https://jtreminio.com/2012/07/xdebug-and-you-why-you-should-be-using-a-real-debugger/
https://www.sitepoint.com/debugging-and-profiling-php-with-xdebug/

I recommend PHP Tools for Visual Studio as an IDE:

https://www.devsense.com/

@meet-bhagdev  Nice hint about how to get the ODCB version and other attributes throug getAttribute() on the PDO. Thanks!

**Comment by riky93** [comment]
Thanks David! I have it installed Visual studio and xdebug, as well as the p for visual studios. Currently I am combating an error on Micrsoft Visual Studio saying 

Listen on port 9000 failed. Ensure no other application is using this port number.

Currently I am researching about this error. Kinda scares me because this error can be anything. It occures when I debud (F5) the code.

**Comment by meet-bhagdev** [comment]
@riky93 Listed on port 9000 seems like a networking error. Can you shed some more light on how you are using port 9000? To verify that the driver is working, can you execute a simple PHP script on your machine?

**Comment by riky93** [comment]
@meet-bhagdev Thank you, I have a testing php document within the wwwroot folder (drupal folder is store there too). In the testing php document I entered the following code:

`
<h1>hi world</h1> 
<?php


$serverName = "(local)\MSSQLNEW";

$conn = new PDO("sqlsrv:server=$serverName;Database=thedrupal","sa","academy");
 
if($conn){
	echo "Connection established.</br></br>";
	echo $conn;
} else{
	echo "Connection could not be established. </br>";
	die(print_r(sqlsrv_errors(), true));
}

?>`

I tested the code within the browser, and it stated that the **connection has been established**. 


The only time I entered a code using 9000 is in the php.ini file. I entered the following:

`zend_extension= C:\php\xdebug.dll
xdebug.remote_enable = on
xdebug.remote_handler = dbgp
xdebug.remote_host = 127.0.0.1
xdebug.remote_port = 9000
xdebug.remote_mode = req
xdebug.idekey="php-vs"`

If you can please let me know what the error is, I would definitely appreciate it.

**Comment by riky93** [comment]
So I ran the program as administrator and did not receive any issues. When clicking debug, it shows a list within the exception setting, and then a browser opens saying, 

`The requested resource /?XDEBUG_SESSION_START=77FEB13B was not found on this server.`

I am still researching to find out why this is occurring. Is the browser suppose to show something when debugging?

**Comment by riky93** [comment]
Good news everyone! I was able to install Drupal 8. All I had to do was change the port number. I went to Server Manager/AllServers and used the IPv4 Address 10.10.30.50 as the port number for config set up. It loaded to a page saying "Drupal already installed"

@meet-bhagdev  @david-garcia-garcia  Bad news is that it skipped the Password set up for Drupal admin. Since it skipped admin configuration, it lead me to the log in page for administrator. It states "no active batch". Do you guys know if I need to view some sort of back end code in order to log in as administrator?

(I apologize for the abundance amount for questions. I thank you all for helping me with this process.)

**Comment by meet-bhagdev** [comment]
@riky93 I am not sure how Drupal and the admin interface works. We are going to close this issue as it does not seem to be related to the PHP Driver for SQL Server. Feel free to re-open it if you think otherwise. 

@david-garcia-garcia would you know why it is skipping the password setup for Drupal admin. Anything we can do in the driver to avoid this?
