### ISSUE TITLE
How to SQLSRV Driver on Mac OS X

### ISSUE THREAD

**Issue by nohnaimer** [Microsoft/msphpsql#198]
Hello,
Are there manual how to run sqlsrv driver on Mac OS X with brew installed php 7?
Any help?
Thank you!

**Comment by meet-bhagdev** [comment]
@nohnaimer Check out sqlshim: https://github.com/radsectors/sqlshim.

**Comment by ulvii** [comment]
Hi @nohnaimer,
The installation instructions can be found in the Readme file too: https://github.com/Microsoft/msphpsql/tree/dev#install-unix

**Comment by dalovar** [comment]
When I try to install sqlsrv and sqlsrv pdo in Mac (MAMP), I receive the errors:
`Cannot install pecl/pdo_sqlsrv on darwin operating system, can only install on linux`

Best bet is probably using sqlshim for local testint

**Comment by ulvii** [comment]
Hi @dalovar ,

Drivers are Mac-compatible starting from 4.1.7preview release. For the latest version you would run:

`sudo pecl install pdo_sqlsrv-4.2.0preview`

**Comment by nohnaimer** [comment]
I installed here like this - https://github.com/Microsoft/msphpsql/tree/dev#install-unix

$ brew tap microsoft/mssql-preview https://github.com/Microsoft/homebrew-mssql-preview
$ brew update
$ brew install unixodbc
$ brew install msodbcsql
$ brew install mssql-tools
$ brew install llvm --with-clang --with-clang-extra-tools
$ brew install autoconf

$ sudo pear config-set php_ini `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` system
$ sudo pecl install sqlsrv-4.1.7preview
$ sudo pecl install pdo_sqlsrv-4.1.7preview

Now I'm like this:
![2017-06-14 14 31 07](https://user-images.githubusercontent.com/8865830/27130246-2e45c376-510e-11e7-9efa-573dca8e11c4.png)

But better put the latest version of 4.2.0preview
$ sudo pecl install sqlsrv-4.2.0preview
$ sudo pecl install pdo_sqlsrv-4.2.0preview

**Comment by ulvii** [comment]
Hi @nohnaimer ,

`sudo pecl install pdo_sqlsrv-4.2.0preview` will overwrite the older version.

**Comment by dalovar** [comment]
Installing `sqlsrv-4.2.0preview` and `pdo_sqlsrv-4.2.0preview` using `pecl` give me these errors:

`sudo /Applications/MAMP/bin/php/php7.0.15/bin/pecl install sqlsrv-4.2.0preview`
Error:
```
In file included from /private/tmp/pear/temp/sqlsrv/conn.cpp:20:
In file included from /private/tmp/pear/temp/sqlsrv/php_sqlsrv.h:25:
In file included from /private/tmp/pear/temp/sqlsrv/shared/core_sqlsrv.h:34:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/main/php.h:35:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend.h:35:
/Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend_string.h:326:2: warning: 'register' storage class specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
        register zend_ulong hash = Z_UL(5381);
        ^~~~~~~~~
In file included from /private/tmp/pear/temp/sqlsrv/conn.cpp:20:
In file included from /private/tmp/pear/temp/sqlsrv/php_sqlsrv.h:25:
In file included from /private/tmp/pear/temp/sqlsrv/shared/core_sqlsrv.h:34:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/main/php.h:35:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend.h:36:
/Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend_hash.h:251:2: warning: 'register' storage class specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
        register const char *tmp = key;
        ^~~~~~~~~
In file included from /private/tmp/pear/temp/sqlsrv/conn.cpp:20:
In file included from /private/tmp/pear/temp/sqlsrv/php_sqlsrv.h:25:
In file included from /private/tmp/pear/temp/sqlsrv/shared/core_sqlsrv.h:34:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/main/php.h:35:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend.h:341:
/Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend_operators.h:188:2: warning: 'register' storage class specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
        register const unsigned char *e;
        ^~~~~~~~~
In file included from /private/tmp/pear/temp/sqlsrv/conn.cpp:20:
In file included from /private/tmp/pear/temp/sqlsrv/php_sqlsrv.h:25:
In file included from /private/tmp/pear/temp/sqlsrv/shared/core_sqlsrv.h:41:
In file included from /private/tmp/pear/temp/sqlsrv/shared/FormattedPrint.h:24:
In file included from /private/tmp/pear/temp/sqlsrv/shared/xplat_winnls.h:24:
In file included from /private/tmp/pear/temp/sqlsrv/shared/typedefs_for_linux.h:23:
/private/tmp/pear/temp/sqlsrv/shared/xplat.h:30:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^
3 warnings and 1 error generated.
make: *** [conn.lo] Error 1
ERROR: `make' failed
```

`sudo /Applications/MAMP/bin/php/php7.0.15/bin/pecl install pdo_sqlsrv-4.2.0preview`
Error:

```
/Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend_string.h:326:2: warning: 'register' storage class specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
        register zend_ulong hash = Z_UL(5381);
        ^~~~~~~~~
In file included from /private/tmp/pear/temp/pdo_sqlsrv/pdo_dbh.cpp:20:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/php_pdo_sqlsrv.h:23:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/shared/core_sqlsrv.h:34:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/main/php.h:35:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend.h:36:
/Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend_hash.h:251:2: warning: 'register' storage class specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
        register const char *tmp = key;
        ^~~~~~~~~
In file included from /private/tmp/pear/temp/pdo_sqlsrv/pdo_dbh.cpp:20:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/php_pdo_sqlsrv.h:23:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/shared/core_sqlsrv.h:34:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/main/php.h:35:
In file included from /Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend.h:341:
/Applications/MAMP/bin/php/php7.0.15/include/php/Zend/zend_operators.h:188:2: warning: 'register' storage class specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
        register const unsigned char *e;
        ^~~~~~~~~
In file included from /private/tmp/pear/temp/pdo_sqlsrv/pdo_dbh.cpp:20:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/php_pdo_sqlsrv.h:23:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/shared/core_sqlsrv.h:41:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/shared/FormattedPrint.h:24:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/shared/xplat_winnls.h:24:
In file included from /private/tmp/pear/temp/pdo_sqlsrv/shared/typedefs_for_linux.h:23:
/private/tmp/pear/temp/pdo_sqlsrv/shared/xplat.h:30:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^
3 warnings and 1 error generated.
make: *** [pdo_dbh.lo] Error 1
ERROR: `make' failed
```

Any idea on what's going on? Using MAMP Version 4.1.1 (492) with PHP 7.0.15 on MacOS 10.12.5 and trying to install sqlsrv on this PHP version to run tests locally as well as in my azure server.

**Comment by ulvii** [comment]
@dalovar , 

Please post the output of the following commands:

```
1. odbcinst -j
2. odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
3. find /usr 2>/dev/null -name "libodbc*"
4. php -i | grep "Configure Command"
```

**Comment by dalovar** [comment]
1. odbcinst -j
```
unixODBC 2.3.4
DRIVERS............: /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/Cellar/unixodbc/2.3.4/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/Cellar/unixodbc/2.3.4/etc/ODBCDataSources
USER DATA SOURCES..: /Users/dalovar/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```
2. odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
```
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.13.dylib
UsageCount=1
```
3. find /usr 2>/dev/null -name "libodbc*"
```
/usr/local/Cellar/unixodbc/2.3.2_1/lib/libodbc.2.dylib
/usr/local/Cellar/unixodbc/2.3.2_1/lib/libodbc.dylib
/usr/local/Cellar/unixodbc/2.3.2_1/lib/libodbccr.2.dylib
/usr/local/Cellar/unixodbc/2.3.2_1/lib/libodbccr.dylib
/usr/local/Cellar/unixodbc/2.3.2_1/lib/libodbcinst.2.dylib
/usr/local/Cellar/unixodbc/2.3.2_1/lib/libodbcinst.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbc.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbc.a
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbc.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbccr.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbccr.a
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbccr.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbcinst.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbcinst.a
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbcinst.dylib
/usr/local/lib/libodbc.2.dylib
/usr/local/lib/libodbc.a
/usr/local/lib/libodbc.dylib
/usr/local/lib/libodbccr.2.dylib
/usr/local/lib/libodbccr.a
/usr/local/lib/libodbccr.dylib
/usr/local/lib/libodbcinst.2.dylib
/usr/local/lib/libodbcinst.a
/usr/local/lib/libodbcinst.dylib
```
4. php -i | grep "Configure Command"
The output is one big line:
```
Configure Command =>  '/Library/Caches/com.apple.xbs/Binaries/apache_mod_php/apache_mod_php-117.2~3/TempContent/Objects/php/configure'  '--prefix=/usr' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-dependency-tracking' '--sysconfdir=/private/etc' '--with-libdir=lib' '--enable-cli' '--with-iconv=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--with-config-file-path=/etc' '--with-libxml-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--with-openssl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/local/libressl' '--with-kerberos=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--with-zlib=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-bcmath' '--with-bz2=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-calendar' '--disable-cgi' '--with-curl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-dba' '--with-ndbm=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-exif' '--enable-fpm' '--enable-ftp' '--with-gd' '--with-png-dir=/Library/Caches/com.apple.xbs/Binaries/apache_mod_php/apache_mod_php-117.2~3/Root/usr/local' '--with-jpeg-dir=/Library/Caches/com.apple.xbs/Binaries/apache_mod_php/apache_mod_php-117.2~3/Root/usr/local' '--enable-gd-native-ttf' '--with-icu-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--with-ldap=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--with-ldap-sasl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--with-libedit=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-mbstring' '--enable-mbregex' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-pgsql=/usr/local/bin/pg_config' '--with-pgsql=/usr/local/bin/pg_config' '--without-pear' '--with-pear=no' '--with-pdo-mysql=mysqlnd' '--with-mysql-sock=/var/mysql/mysql.sock' '--with-readline=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-shmop' '--with-snmp=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--with-tidy=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-wddx' '--with-xmlrpc' '--with-iconv-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--with-xsl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' '--enable-zend-multibyte' '--with-apxs2=/usr/sbin/apxs' '--enable-zip' '--with-pcre-regex=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr' 'CC=/Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/bin/cc' 'CFLAGS=-arch '-pipe' '-Os' '-g' '-isysroot' '-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/include' '-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/include/apache2'' 'LDFLAGS=-arch '-pipe' '-Os' '-g' '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/lib'' 'YACC=/usr/local/bin/bison-1.28' 'CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/bin/c++' 'CXXFLAGS=-arch '-g' '-Os' '-pipe'
```
5. php -v
```
PHP 5.6.30 (cli) (built: Feb  7 2017 16:18:37)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
This is the problem php is linked to the system's PHP version which isn't php 7.0. I am now redoing everything using php 7.0 this time. This will install the sqlsrv on the system's php 7.0, but how could I install sqlsrv on the PHP that MAMP uses (stored in /Applications/MAMP/bin/php/php7.0.15)?

**Comment by dalovar** [comment]
Yup. It works now. Sorry for the mess. I'm uninstalling MAMP and using Apache and PHP directly with the terminal

**Comment by ulvii** [comment]
Hi @dalovar ,

Glad you could get the driver working. Feel free to open a new issue if you have any other questions.

**Comment by techsavvyashish** [comment]
I have also updated the php version, but still I am unable to install sqlsrv driver.
php -v
`PHP 7.0.18 (cli) (built: May  6 2017 09:49:26) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans`

**Comment by nohnaimer** [comment]
@techsavvyashish everything is fine on php 7.1.8 and I update for 4.3.0 sqlsrv release. You are clearly doing something wrong!

Proof:
![2017-08-10 8 57 31](https://user-images.githubusercontent.com/8865830/29156346-16255f04-7daa-11e7-9f7d-570f2d916460.png)
![2017-08-10 8 57 53](https://user-images.githubusercontent.com/8865830/29156348-17fdff5c-7daa-11e7-8700-24d793826c99.png)
![2017-08-10 9 01 59](https://user-images.githubusercontent.com/8865830/29156436-a09ed28c-7daa-11e7-8a9c-185133fc44ab.png)

**Comment by vivlachaga** [comment]
Hope this help:
i add the CXXFLAGS & LDFLAGS to point to unixodbc headers files and unixodbc lib path, this helps to compile the modules with pecl 

sudo CXXFLAGS="-I/usr/local/opt/unixodbc/include" LDFLAGS="-L/usr/local/lib" pecl install pdo_sqlsrv
sudo CXXFLAGS="-I/usr/local/opt/unixodbc/include" LDFLAGS="-L/usr/local/lib" pecl install sqlsrv

added the .so libraries as result inside /etc/php.ini

![image](https://user-images.githubusercontent.com/29557581/29898263-ace991f4-8d99-11e7-89da-f848076e9933.png)
![image](https://user-images.githubusercontent.com/29557581/29898278-c7d069c0-8d99-11e7-86f0-01b781e97ba9.png)

**Comment by borzale** [comment]
@vivlachaga Thank you SO much. This was the missing step I needed to get it working on OSX Sierra 10.12.4.

It worked perfectly with MAMP 4 running php 7.0.20, I just had to add that version of php to my $PATH and it automatically picked that up while running the install commands.

If this step could be added to the UNIX instruction page (https://github.com/Microsoft/msphpsql/tree/dev#install-unix) that would be awesome. It's not that common for web developers to pick up header files for compiling stuff! (from my experience anyway :) )

**Comment by tartesso26** [comment]
when installing sqlsrv on mac high sierra with sudo pecl install pdo_sqlsrv

it´s appear to go well but in the end i get 

Build process completed successfully
Installing '/usr/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so'
ERROR: failed to write /usr/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so (copy(/usr/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so): failed to open stream: Operation not permitted)

and the sqlsrv.so is not available and not appear in phpinfo()

somebody could help me?

**Comment by vivlachaga** [comment]
You need to reboot your mac and press ⌘+R when booting up. Then go into Utilities > Terminal and type the following commands:

csrutil disable
reboot 
This is a result of System Integrity Protection. 

https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html

**Comment by joao-s-neves** [comment]
Hi guys, I need some help installing PDO SQL Server drivers for Mac OS X.
Followed this (https://github.com/Microsoft/msphpsql/tree/dev#install-unix) tutorial and everything went well. Except for the fact that the PDO drivers don't show up in phpinfo(); despite the command "php -m | grep sqlsrv" showing me the drivers.

Also, phpinfo() is showing me the path to a php.ini that's completely empty, and when I do php --ini it points me out to a php.ini that has zero extensions on it.

Can someone help me out?

**Comment by vivlachaga** [comment]
Put the php.ini content in the php.ini loaded by php

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kieuquangloc147** [comment]
I just created a video to install sqlsrv for MAMP on mac:
https://youtu.be/PRH04PxZpUk

**Comment by ijpatricio** [comment]
awesome guys!! don't need a VM any more, justfor the sole purpose because of sqlserver!

https://www.microsoft.com/en-us/sql-server/developer-get-started/php/mac/

**Comment by heberfomin** [comment]
hi @nohnaimer:
I followed your steps:
$ brew tap microsoft/mssql-preview https://github.com/Microsoft/homebrew-mssql-preview
$ brew update
$ brew install unixodbc
$ brew install msodbcsql
$ brew install mssql-tools
$ brew install llvm --with-clang --with-clang-extra-tools
$ brew install autoconf

$ sudo pear config-set php_ini php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||" system

Everything runs ok, but, when I tried to make:
$ sudo pecl install sqlsrv-4.2.0preview
I got the following errors:
...
In file included from /private/tmp/pear/install/sqlsrv/conn.cpp:20:
In file included from /private/tmp/pear/install/sqlsrv/php_sqlsrv.h:25:
/private/tmp/pear/install/sqlsrv/shared/core_sqlsrv.h:34:10: fatal error: 'php.h' file not found
#include "php.h"
         ^~~~~~~
1 error generated.
make: *** [conn.lo] Error 1
ERROR: `make' failed

Do you know how can I fix it?

**Comment by yitam** [comment]
Hi @heberfomin 
Just wondering why you wanted an old preview when we already have 5.2.0 stable version released?
For instructions on installing the drivers, please click our [tutorial](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac). If you still have issues, please create a new issue, and if you like, you can reference this old issue.

**Comment by nohnaimer** [comment]
Hi @heberfomin 
Try this:
$ sudo pecl install sqlsrv pdo_sqlsrv

**Comment by heberfomin** [comment]
@nohnaimer 
Same error. It seems that I don't have any php.h. I tried to find it but there only one in
./Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/php/main/php.h
but I don't know if is the correct.
Thanks for you help anyway.

**Comment by nohnaimer** [comment]
@heberfomin 
What version of php?
Try first, maybe you forgot something ...
1. php installed and work
brew install llvm --with-clang --with-clang-extra-tools
brew install autoconf
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=y brew install --no-sandbox msodbcsql mssql-tools
sudo pecl install sqlsrv pdo_sqlsrv
sudo echo "extension= pdo_sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
sudo echo "extension= sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

**Comment by heberfomin** [comment]
I tried like you suggest. In the last command I got this error:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20160303/sqlsrv.so' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20160303/sqlsrv.so, 0x0009): closured error in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so, 0x0009): closured error in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so, 0x0009): closured error in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20160303/sqlsrv.so' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20160303/sqlsrv.so, 0x0009): closured error in Unknown on line 0

**Comment by nohnaimer** [comment]
@heberfomin 
But - Build process completed successfully, that is, the compilation was successful! On  **/private/tmp/pear/install/pear-build-rootdOF37r/install-sqlsrv-5.2.0/usr/lib/php/extensions/no-debug-non-zts-20160303/** there must be files **sqlsrv.so** and **pdo_sqlsrv.so**

**ERROR: failed to write /usr/lib/php/extensions/no-debug-non-zts-20160303/sqlsrv.so** 
You need **sudo** on compile:
$ **sudo** pecl install sqlsrv pdo_sqlsrv
And after check whether there are lines in the file **php.ini**

**Comment by heberfomin** [comment]
@nohnaimer and @yitam:
Thanks a lot for your help.
Finally I figure out what the problem was: Sistems Integrity Protection of mac.
Once I disabled it, runs ok.
Again, 
Thank you guys !

**Comment by yitam** [comment]
hi @heberfomin, glad to hear you have figured out the root cause of the problems, [System Integrity Protection on your Mac](https://support.apple.com/en-ca/HT204899).

**Comment by danielflippance** [comment]
I've noticed that not only does System Integrity Protection need to be turned off in order to install the sqlsvr driver on Mac, it also needs to be turned off in order to use that driver.

System Integrity Protection is an important security measure to prevent the root account being abused, so is there any way to use the driver with SIP turned back back on after the driver is installed?

**Comment by david-puglielli** [comment]
@danielflippance Could you provide some more info? Which version of macOS are you using? What errors do you get if you try to install and use the driver with SIP enabled?

**Comment by danielflippance** [comment]
@david-puglielli I'm running Mac OS Mohave 10.14.3 (18D109)
I didn't see any errors when installing the SQL driver. The problem happens when trying to connect to SQL Server after the driver is installed.

The connection code is:

```
if (function_exists('\sqlsrv_connect')) {
	$connection = \sqlsrv_connect($serverName, $connectionInfo);
} else {
	error_log('DEBUG sqlsrv_connect not found.');
}
```

With SIP turned off it calls the function `sqlsrv_connect` and connects.
With SIP turned on, that function is not found:
```
[29-Mar-2019 17:39:13 UTC] DEBUG sqlsrv_connect not found.
```

**Comment by david-puglielli** [comment]
That is quite strange. Is PHP loading the drivers correctly? Try `php -m` and `php --ri sqlsrv` to verify that the drivers are loaded. Also, do `sqlcmd` and `isql` work when SIP is enabled?

**Comment by david-puglielli** [comment]
@danielflippance Do you have any updates about your SIP issue for us?

**Comment by david-puglielli** [comment]
@danielflippance How did you install PHP 7.3? Also, could you provide a PHP script showing how you use namespaces with our driver?

**Comment by DaniJmurcia** [comment]
> Hi @dalovar ,
> 
> Glad you could get the driver working. Feel free to open a new issue if you have any other questions.


Can you install sql server for php version 5.6.40?
