### ISSUE TITLE
PHP 5.6 + ODBC 13?

### ISSUE THREAD

**Issue by tekniker** [Microsoft/msphpsql#204]
Prior I had no problems with PHP 5.6 + ODBC 11 + MS PHP sql driver ver 3.2 against a SQL server Express 2014. Now Im trying to get things to work with SQL server 2016 which requires ODBC 13.
I would like to keep PHP 5.6 if possible. But I got this error:
PDOException: SQLSTATE[IMSSP]: This extension requires the Microsoft ODBC Driver 11 for SQL Server to communicate with SQL Server.

The download page at https://www.microsoft.com/en-us/download/details.aspx?id=20098 says that 
"Versions 3.2 and 3.1 of the driver require Microsoft ODBC Driver 11 (or higher). You can download the Microsoft ODBC Driver 11 here."
Doesn't that mean that version 3.2 of the ms php sql driver is compatible with the ODBC Driver 13 (which is higher than 11)?

**Comment by Hadis-Fard** [comment]
@tekniker SQLSRV 3.1 and 3.2 drivers don't support ODBC 13, is there any reason you don't want to upgrade to PHP 7 drivers?

**Comment by tekniker** [comment]
@Hadis-Fard We have some issues with third-party modules for Drupal not being PHP7 compatible without further troubleshooting.

**Comment by yitam** [comment]
Regrettably the download page gives wrong information @tekniker. As @Hadis-Fard said, Versions 3.2 and 3.1 of the drivers don't work with Microsoft ODBC 13.

**Comment by meet-bhagdev** [comment]
@tekniker Sorry about that. We have corrected the download center page. Version 3.1 and 3.2 do not support ODBC 13 and PHP 7. Happy to help you with issues around Drupal and PHP 7 configuration. Other than that, I would like to understand why do you need to to use the ODBC 13 driver with Version 3.1 and 3.2? ODBC 11 should work with SQL Server 2016.

**Comment by tekniker** [comment]
@meet-bhagdev Im really surprised. The ODBC 11 driver download page doesn't mention compatibilty with SQL Server 2016!
https://www.microsoft.com/en-us/download/details.aspx?id=36434
