### ISSUE TITLE
DLL dependencies

### ISSUE THREAD

**Issue by pierre1451** [Microsoft/msphpsql#208]
Hello, the TS-64 bit drivers install and work fine with PHP 7 on a number of Windows instances. I have a clean Windows 10 install with Visual Studio v2017-RC, Apache 2.4.23, PHP 7.1, ODBC13,. With this configuration php_sqlsrv_7_ts_x64 and php_pdo_sqlsrv_7_ts_x64 do not load. Any known dependency issue that I can fix or workaround?

**Comment by meet-bhagdev** [comment]
@pierre1451 What is the error message?

**Comment by pierre1451** [comment]
PHP Startup: Unable to load dynamic library 'C:\ATDI\SpectrumE\PHP\ext\php_sqlsrv_7_ts_x64.dll' - The specified procedure could not be found. Path is good, did the usual: back/forward slash, absolute and relative path. When I point to the 32 bit dll instead (for sanity check), I get the '%1 is not a valid Win32 application' message. PHP paths are in the environment variables. I guess that covers most location / path issues. I have a number of other DLLs that I use: xdebug, mongo, ldap. They load fine and show-up in phpinfo().

**Comment by pierre1451** [comment]
I think I found something: replaced PHP 7.1.0 with PHP 7.0.10. (x64-TS). Now works! I used the github binaries and the ones from the MS download page, all good. It's kind of a big deal, because 7.1 fixes some bugs that are really annoying. Is it a known issue?

**Comment by Hadis-Fard** [comment]
@pierre1451 Are you using 7.1 binaries in [release 4.1.4](https://github.com/Microsoft/msphpsql/releases/tag/4.1.4-Windows)?

**Comment by pierre1451** [comment]
Yep, that was it. Thanks for the help!
