### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by MatasElectronics** [Microsoft/msphpsql#211]
I'm trying to build a Linux machine on which I can connect to our SQL server.
I've done it before using Ubuntu 14.04, but now we need an updated server with Ubuntu 16.04, and I just can't get it to work.

I've followed the install guide: https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux
And everything seems to be successful, but connecting isn't possible.

I've tried a variety of credential options:

- `sqlcmd -S matas-ie45\isahmssql -d TestProduktieDB -U testuser-P testpassword`
- `sqlcmd -S matas-ie45\\isahmssql -d TestProduktieDB -U testuser-P testpassword`
- `sqlcmd -S matas-ie45/isahmssql -d TestProduktieDB -U testuser-P testpassword`
- `sqlcmd -S matas-ie45\isahmssql,1433 -d TestProduktieDB -U testuser-P testpassword`
- `sqlcmd -S matas-ie45\\isahmssql,1433 -d TestProduktieDB -U testuser-P testpassword`
- `sqlcmd -S matas-ie45/isahmssql,1433 -d TestProduktieDB -U testuser-P testpassword`
- `sqlcmd -S matas-ie45,1433 -d TestProduktieDB -U testuser-P testpassword`
- `sqlcmd -S matas-ie45 -d TestProduktieDB -U testuser-P testpassword`

But none seem to work. The first three I can understand because I've read that you need to specify the port when connecting to a named instance, but that also didn't work. everytime I'm seeing an error similar to:

```
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2AFA.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
```

To verify that the connection can actually be made, I've tried it using nodejs, this package: https://www.npmjs.com/package/mssql

For this I used this connection string, and everything works as expected:
`sql.connect("mssql://`testuser:testpassword@matas-ie45/isahmssql/TestProduktieDB")`

I've got no idea what I'm doing wrong. So really hoping someone can help me debug this problem and fix it :)

**Comment by Hadis-Fard** [comment]
@MatasElectronics How did you install ODBC driver on Ubuntu 14? the install instruction is on  Ubuntu 15 and 16.  I am guessing nodejs application is using Native Client Driver, can you confirm you are using the `Microsoft ODBC Driver 13 for SQL Server` Driver in nodejs application?

**Comment by yitam** [comment]
@MatasElectronics just curious, have you tried the followings:
1. ping the server, or
2. using IP address instead, or
3. sqlcmd in a Windows command prompt

How did you prove that it used to work with Ubuntu 14.04? Does that same script still work in your Ubuntu 16?

Also, this page might be helpful:
https://blogs.msdn.microsoft.com/sql_protocols/2008/04/30/steps-to-troubleshoot-sql-connectivity-issues/

**Comment by MatasElectronics** [comment]
@Hadis-Fard It was a while back that it was installed, but I believe it where simply instructions from a readme or something on this very Gitlab repo. 
I'm not that familiar with node, so how would I confirm which driver nodejs is using?

**Comment by MatasElectronics** [comment]
@yitam 

1: `ping matas-ie45` no problems
2: Same kind of error when I try to use the IP address
3: Connecting using sqlcmd on my windows machine gives me no problem

Well, the server is still running the app, so guess that proves that it works. Also we use a Ubuntu 14.04 docker image for our CI testing, which is also still working.

**Comment by yitam** [comment]
Hi @MatasElectronics 

To clarify, you can successfully connect to your Ubuntu 16.04 server using sqlcmd in Windows, but you have troubles connecting to the server using the same credentials via sqlcmd from Linux. Correct?

Just to make sure, what ODBC driver do you have in Linux? For your information, please check https://blogs.technet.microsoft.com/dataplatforminsider/2016/10/25/odbc-driver-13-0-for-sql-server-linux-is-now-released/

**Comment by meet-bhagdev** [comment]
@MatasElectronics Also can you also share what version of SQL Server are you using?

**Comment by MatasElectronics** [comment]
@meet-bhagdev `select @@version` gives me: 

```
Microsoft SQL Server 2012 (SP3-GDR) (KB3194721) - 11.0.6248.0 (X64) 
Sep 23 2016 15:49:43 
Copyright (c) Microsoft Corporation
Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

```

**Comment by MatasElectronics** [comment]
@yitam Yes, `matas-ie45` is the hostname of the SQL Server, where `matas-ie45/isahmssql` is the instance. When I use sqlcmd from any Windows pc I can connect without a problem. But when I follow the installation guide on here and try to connect on a Ubuntu 16.04 virtual machine, I can't connect to it.

**Comment by yitam** [comment]
@MatasElectronics, after some investigation I believe the reason is that named instance resolution on Linux is not yet supported. See this [thread](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c3dc09bb-7ac6-47d8-a188-564b57b192c6/connection-problems-linux-to-sql-server?forum=sqldataaccess) for more details. 

You may consider configuring a static port for the instance as described in https://support.microsoft.com/en-us/kb/823938

Also, you might be interested in yet another [related issue](https://github.com/Microsoft/msphpsql/issues/175)

Hope this helps.

**Comment by MatasElectronics** [comment]
@yitam Looking at that the only thing I see is you have to specify the port when you try to connect to a named instance. But didn't I try that already with: 

- `sqlcmd -S matas-ie45\isahmssql,1433 -d TestProduktieDB -U testuser -P testpassword`
- `sqlcmd -S matas-ie45\\isahmssql,1433 -d TestProduktieDB -U testuser -P testpassword`
- `sqlcmd -S matas-ie45/isahmssql,1433 -d TestProduktieDB -U testuser -P testpassword`
- `sqlcmd -S matas-ie45,1433 -d TestProduktieDB -U testuser -P testpassword`

And that all doesn't work. So I'm still unable to make any sort of connection.

**Comment by yitam** [comment]
Hi @MatasElectronics, note that "it's not recommended to have a named instance listening on port 1433" as explained in this [support article](https://support.microsoft.com/en-ca/kb/823938)

Therefore, as suggested above, consider configuring a static port for the instance.

For testing purposes, you can try connecting to a default instance (not [a named instance](https://technet.microsoft.com/en-us/library/ms165614(v=sql.90).aspx)) of another SQL Server using sqlcmd in Linux, which should work.

**Comment by MatasElectronics** [comment]
@yitam I've read the article, but again it seems like omitting the name, and adding the port should work, but it isn't, so the problem persists.

Sadly I don't think I will be able to change the port. It's a database that is part of another software package which we don't manage ourselves. So we can't just change the configuration on the database server.

I'll try to connect to a not named instance, and see how that goes.

**Comment by yitam** [comment]
Yes @MatasElectronics sqlcmd in Linux should work with the default instance. If not, please let us know.

**Comment by MatasElectronics** [comment]
@yitam Okay.... so, I got it to work!
I went through all the configuration on the server again, and somewhere I found another port number being listed, so I decided to try that, and it worked.

So I'll close this issue, but I would like to know if we can expect named instances to work on Linux in the foreseeable future. Does anyone know?

Thanks for the help!
