### ISSUE TITLE
./configure for Linux

### ISSUE THREAD

**Issue by szepeviktor** [Microsoft/msphpsql#212]
This can be found in the Dockerfile

> ./configure LDFLAGS="-lgcov" CXXFLAGS="-O0 --coverage"

Previously was `./configure CXXFLAGS=-std=c++11`

Which is the suggested one?

**Comment by yitam** [comment]
Hi @szepeviktor , either way is fine. The gcov option is to enable test coverage as explained in
https://gcc.gnu.org/onlinedocs/gcc/Gcov.html

Hope this helps.

**Comment by szepeviktor** [comment]
Thank you.
