### ISSUE TITLE
The specified procedure could not be found

### ISSUE THREAD

**Issue by schrodinger-kater** [Microsoft/msphpsql#214]
Hi,
can me somebody explain why, use the standard bundle LoadLibrary/GetProcAddress on ready compiled binary files, returns ERROR_PROC_NOT_FOND?
The module (php_sqlsrv_7_nts.dll, php_pdo_sqlsrv_7_nts.dll) is loaded successfully, in export table I find procedure with name get_module, but an attempt to obtain its address returns error 0x7F (The specified procedure could not be found).
This issue occurs only with the 4th version of the extensions, that is, for PHP 7. All the previous versions (for example 3.2 for PHP 5.4-5.6) are loaded successfully.
Platform: Windows Server 2012 R2, PHP 7.1.0 x64, MS SQL 2012.

**Comment by yitam** [comment]
@schrodinger-kater Is it possible that you're using the PHP7.0.x binaries for PHP 7.1.0? For your information they are incompatible, and please download PHP7.1 binaries (https://github.com/Microsoft/msphpsql/releases)

**Comment by schrodinger-kater** [comment]
I am grateful for another source binaries (though already then I see the problem - too many officially resources with different versions of the modules), but this is not exactly (they also do not work). I will try to explain in more detail: at Windows Server 2012 R2 with IIS 8.5 (x64, respectively), through FastCGI I run php 7.1.0 nts x64. I try to use extension (x64 files version 4.1.4.9021) for connection to MS SQL Server 2012. And accordingly, these extensions are not visible in phpinfo. The easiest and most reliable way to test the extension modules - is to write a small program that will read the table of exports dll, load dll via LoadLibrary API function, and then will try to get the address of the selected procedures with the API function GetProcAddress. To work correctly, I call self program from the directory where the php7.dll. And here comes the fun part: all extension modules are stored in the directory have successfully loaded and I can each get the addresses stored procedures, but in the case of the SQLSRV program returns error 127 (ERROR_PROC_NOT_FOUND). The problem is that I have been programming in Pascal and can`t assemble modules from source. But I suspect that these binaries compiled under the C and not under C++. A feeling that only I was faced with this problem...

**Comment by schrodinger-kater** [comment]
I'm sorry, but it seems the latest version SQLSRV x64 (4.1.4.9021) is working. Errors were not, I checked several times, two days ago, my method return the same error. But now everything is working. Thank you, the topic is closed.

**Comment by yitam** [comment]
Sounds great @schrodinger-kater! I planned to get back to you today, and I was going to tell you there's a quick way to test if an extension is loaded by writing a simple php script like this:	
```
if (extension_loaded("sqlsrv"))
{
	echo ("sqlsrv driver is loaded.\n");
}
```
Please read http://php.net/manual/en/function.extension-loaded.php for details. I'll close this issue then. Thank you and have a nice day!
