### ISSUE TITLE
Security concern, Inserted/updated data is being corrupted with seemingly random data from same or other requests

### ISSUE THREAD

**Issue by sean256** [Microsoft/msphpsql#219]
OS: CentOS 7.1, 7.2, 7.3, RH7.1
PHP: PHP 7.0.14
Apache: 2.4.6
sqlsrv: latest

Summary: Inserted data is being corrupted with seemingly random data from the same request or other requests. I can replicate this through Apache and not CLI

This is a really odd one and it's got us a bit worried. We have a table with a varchar(max) and are inserting/updating a somewhat long JSON string into it. Almost every time the insert or update happens there is either corrupted data (?, nulls, etc) at the end of the string or pieces of strings from DIFFERENT sql statements (so pieces of the sql string itself) or string results from a DIFFERENT query. The included script reliably replicates the issue we are experiencing after a few runs on a vagrant box running CentOS 7.3.

I created a simple example script that I got to duplicate the issue.

It does:

1. Connects using PDO and sqlsrv
2. prepares a statement using FOR XML (this replicates what our real servers are doing)
3. executes query
4. returns data using nextRowset and fetch
5. prepare a DIFFERENT insert statement
6. executes insert using a JSON string as a parameter

Using an SQL client this is what I found in the DB for that column

```
{"demo":{},"imageBucketShowSmall":true,"darkMode":false,"showHelpMenuSearch":true,"demoCity":"Megaton","test":"temp","testMany":{"test":"hello"},"showProjects":false,"photography":{"showADTools":false,"thumbSize":"medium-thumbs","doubleSideBar":false},"project":{"showADTools":false},"imageSearch":{"showItems":true,"shotProjectInfo":false,"showADMarkups":false},"items":{"showLoadHistory":false},"projectCreationStudio":{"subLocationToggle":"shootingMerch"},"vendorImages":{"category":false},"colorOverlayRequests":{"show":{"rgb":true,"sample":true,"stock":true,"image":true,"fabric":true}}}it will corrupt the next
	insert statement.

		So here is some dummy comments

		Duo Reges: constructio interrete. Bona autem corporis huic sunt, quod posterius posui, similiora. Non minor, inquit, voluptas percipitur ex vilissimis rebus quam ex pretiosiss
```

Everything AFTER true}}} is junk data from the query in step 2

The REALLY SCARY part, in our dev environment for our real app stack, it looked like it was mixing data from DIFFERENT apache requests. We found potentially sensitive user data returning in non secure endpoints! We also don't like the idea that chunks of our SQL statements are popping back out as it reveals our data structure. 

Here is another example with a different run (after restarting the VM). Note how it's different.

```
{"demo":{},"imageBucketShowSmall":true,"darkMode":false,"showHelpMenuSearch":true,"demoCity":"Megaton","test":"temp","testMany":{"test":"hello"},"showProjects":false,"photography":{"showADTools":false,"thumbSize":"medium-thumbs","doubleSideBar":false},"project":{"showADTools":false},"imageSearch":{"showItems":true,"shotProjectInfo":false,"showADMarkups":false},"items":{"showLoadHistory":false},"projectCreationStudio":{"subLocationToggle":"shootingMerch"},"vendorImages":{"category":false},"colorOverlayRequests":{"show":{"rgb":true,"sample":true,"stock":true,"image":true,"fabric":true}}}ges.imagesID AS id,
					--versions in images
		¦??
						SELECT
							versions.versionsID AS 'id',
							storageServers.stor???
```

Test Scripts:

[datadestroyer.zip](https://github.com/Microsoft/msphpsql/files/695018/datadestroyer.zip)

datadestroyer.php
Hit this through apache to duplicate issue

run.php
This will execute curl and compare the data in the DB 20 times and log the output to data.txt. Run this via CLI, php run.php

header.php
variables to set up the above 2

sql_setup.sql
setup some tables to use for the test

Note: This does not occur when we use odbc instead of sqlsrv

**Comment by Hadis-Fard** [comment]
@sean256  Please try 4.0.8 drivers, we had similar issue in the past and is fixed in the latest release.

**Comment by sean256** [comment]
Yup, that seems to have done it.
