### ISSUE TITLE
Warning in ReflectionExtension::export('sqlsrv')

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#22]
PHP 5.3.5 - windows 7 - VC6 ts  
<code>  
ReflectionExtension::export('sqlsrv');  
</code>  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_PHPTYPE_STREAM in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_PHPTYPE_STRING in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_SQLTYPE_BINARY in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_SQLTYPE_CHAR in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_SQLTYPE_DECIMAL in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_SQLTYPE_NCHAR in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_SQLTYPE_NUMERIC in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_SQLTYPE_NVARCHAR in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_SQLTYPE_VARBINARY in global function table in
C:\www\test\index.php on line 4  

Warning: ReflectionExtension::__toString(): Internal error: Cannot find
extension function SQLSRV_SQLTYPE_VARCHAR in global function table in
C:\www\test\index.php on line 4  
Extension [ extension #57 sqlsrv version 2.0.1307.0 ] {  
- INI {  
  Entry [ sqlsrv.LogSeverity ]  
  Current = '0'  
  }  
  Entry [ sqlsrv.LogSubsystems ]  
  Current = '0'  
  }  
  Entry [ sqlsrv.WarningsReturnAsErrors ]  
  Current = '1'  
  }  
  }  
- Constants [65] {  
  Constant [ integer SQLSRV_ERR_ERRORS ] { 0 }  
  Constant [ integer SQLSRV_ERR_WARNINGS ] { 1 }  
  Constant [ integer SQLSRV_ERR_ALL ] { 2 }  
  Constant [ integer SQLSRV_LOG_SYSTEM_OFF ] { 0 }  
  Constant [ integer SQLSRV_LOG_SYSTEM_INIT ] { 1 }  
  Constant [ integer SQLSRV_LOG_SYSTEM_CONN ] { 2 }  
  Constant [ integer SQLSRV_LOG_SYSTEM_STMT ] { 4 }  
  Constant [ integer SQLSRV_LOG_SYSTEM_UTIL ] { 8 }  
  Constant [ integer SQLSRV_LOG_SYSTEM_ALL ] { -1 }  
  Constant [ integer SQLSRV_LOG_SEVERITY_ERROR ] { 1 }  
  Constant [ integer SQLSRV_LOG_SEVERITY_WARNING ] { 2 }  
  Constant [ integer SQLSRV_LOG_SEVERITY_NOTICE ] { 4 }  
  Constant [ integer SQLSRV_LOG_SEVERITY_ALL ] { -1 }  
  Constant [ integer SQLSRV_FETCH_NUMERIC ] { 1 }  
  Constant [ integer SQLSRV_FETCH_ASSOC ] { 2 }  
  Constant [ integer SQLSRV_FETCH_BOTH ] { 3 }  
  Constant [ integer SQLSRV_PHPTYPE_NULL ] { 1 }  
  Constant [ integer SQLSRV_PHPTYPE_INT ] { 2 }  
  Constant [ integer SQLSRV_PHPTYPE_FLOAT ] { 3 }  
  Constant [ integer SQLSRV_PHPTYPE_DATETIME ] { 5 }  
  Constant [ string SQLSRV_ENC_BINARY ] { binary }  
  Constant [ string SQLSRV_ENC_CHAR ] { char }  
  Constant [ integer SQLSRV_NULLABLE_YES ] { 0 }  
  Constant [ integer SQLSRV_NULLABLE_NO ] { 1 }  
  Constant [ integer SQLSRV_NULLABLE_UNKNOWN ] { 2 }  
  Constant [ integer SQLSRV_SQLTYPE_BIGINT ] { -5 }  
  Constant [ integer SQLSRV_SQLTYPE_BIT ] { -7 }  
  Constant [ integer SQLSRV_SQLTYPE_DATETIME ] { 25177693 }  
  Constant [ integer SQLSRV_SQLTYPE_FLOAT ] { 6 }  
  Constant [ integer SQLSRV_SQLTYPE_IMAGE ] { -4 }  
  Constant [ integer SQLSRV_SQLTYPE_INT ] { 4 }  
  Constant [ integer SQLSRV_SQLTYPE_MONEY ] { 33564163 }  
  Constant [ integer SQLSRV_SQLTYPE_NTEXT ] { -10 }  
  Constant [ integer SQLSRV_SQLTYPE_TEXT ] { -1 }  
  Constant [ integer SQLSRV_SQLTYPE_REAL ] { 7 }  
  Constant [ integer SQLSRV_SQLTYPE_SMALLDATETIME ] { 8285 }  
  Constant [ integer SQLSRV_SQLTYPE_SMALLINT ] { 5 }  
  Constant [ integer SQLSRV_SQLTYPE_SMALLMONEY ] { 33559555 }  
  Constant [ integer SQLSRV_SQLTYPE_TIMESTAMP ] { 4606 }  
  Constant [ integer SQLSRV_SQLTYPE_TINYINT ] { -6 }  
  Constant [ integer SQLSRV_SQLTYPE_UDT ] { -151 }  
  Constant [ integer SQLSRV_SQLTYPE_UNIQUEIDENTIFIER ] { -11 }  
  Constant [ integer SQLSRV_SQLTYPE_XML ] { -152 }  
  Constant [ integer SQLSRV_SQLTYPE_DATE ] { 5211 }  
  Constant [ integer SQLSRV_SQLTYPE_TIME ] { 58728806 }  
  Constant [ integer SQLSRV_SQLTYPE_DATETIMEOFFSET ] { 58738021 }  
  Constant [ integer SQLSRV_SQLTYPE_DATETIME2 ] { 58734173 }  
  Constant [ integer SQLSRV_PARAM_IN ] { 1 }  
  Constant [ integer SQLSRV_PARAM_OUT ] { 4 }  
  Constant [ integer SQLSRV_PARAM_INOUT ] { 2 }  
  Constant [ integer SQLSRV_TXN_READ_UNCOMMITTED ] { 1 }  
  Constant [ integer SQLSRV_TXN_READ_COMMITTED ] { 2 }  
  Constant [ integer SQLSRV_TXN_REPEATABLE_READ ] { 4 }  
  Constant [ integer SQLSRV_TXN_SERIALIZABLE ] { 8 }  
  Constant [ integer SQLSRV_TXN_SNAPSHOT ] { 32 }  
  Constant [ integer SQLSRV_SCROLL_NEXT ] { 1 }  
  Constant [ integer SQLSRV_SCROLL_PRIOR ] { 4 }  
  Constant [ integer SQLSRV_SCROLL_FIRST ] { 2 }  
  Constant [ integer SQLSRV_SCROLL_LAST ] { 3 }  
  Constant [ integer SQLSRV_SCROLL_ABSOLUTE ] { 5 }  
  Constant [ integer SQLSRV_SCROLL_RELATIVE ] { 6 }  
  Constant [ string SQLSRV_CURSOR_FORWARD ] { forward }  
  Constant [ string SQLSRV_CURSOR_STATIC ] { static }  
  Constant [ string SQLSRV_CURSOR_DYNAMIC ] { dynamic }  
  Constant [ string SQLSRV_CURSOR_KEYSET ] { keyset }  
  }  
- Functions {  
  Function [ function sqlsrv_connect ] {  
  - Parameters [2] {  
    Parameter #0 [ $"server" ]  
    Parameter #1 [ array $"options" ]  
    }  
    }  
    Function [ function sqlsrv_close ] {  
  - Parameters [1] {  
    Parameter #0 [ $"connection resource" ]  
    }  
    }  
    Function [ function sqlsrv_commit ] {  
  - Parameters [1] {  
    Parameter #0 [ $"connection resource" ]  
    }  
    }  
    Function [ function sqlsrv_begin_transaction ] {  
  - Parameters [1] {  
    Parameter #0 [ $"connection resource" ]  
    }  
    }  
    Function [ function sqlsrv_rollback ] {  
  - Parameters [1] {  
    Parameter #0 [ $"connection resource" ]  
    }  
    }  
    Function [ function &sqlsrv_errors ] {  
  - Parameters [1] {  
    Parameter #0 [ $"flags (errors, warnings, or all)" ]  
    }  
    }  
    Function [ function sqlsrv_configure ] {  
  - Parameters [2] {  
    Parameter #0 [ $"option name" ]  
    Parameter #1 [ $"value" ]  
    }  
    }  
    Function [ function sqlsrv_get_config ] {  
  - Parameters [1] {  
    Parameter #0 [ $"option name" ]  
    }  
    }  
    Function [ function &sqlsrv_prepare ] {  
  - Parameters [4] {  
    Parameter #0 [ $"connection resource" ]  
    Parameter #1 [ $"sql command" ]  
    Parameter #2 [ $"parameters" ]  
    Parameter #3 [ array $"options" ]  
    }  
    }  
    Function [ function sqlsrv_execute ] {  
  - Parameters [2] {  
    Parameter #0 [ $"statement resource" ]  
    Parameter #1 [ $"parameters" ]  
    }  
    }  
    Function [ function &sqlsrv_query ] {  
  - Parameters [4] {  
    Parameter #0 [ $"connection resource" ]  
    Parameter #1 [ $"sql command" ]  
    Parameter #2 [ $"parameters" ]  
    Parameter #3 [ array $"options" ]  
    }  
    }  
    Function [ function sqlsrv_fetch ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function &sqlsrv_get_field ] {  
  - Parameters [3] {  
    Parameter #0 [ $"statement resource" ]  
    Parameter #1 [ $"field index" ]  
    Parameter #2 [ $"type" ]  
    }  
    }  
    Function [ function &sqlsrv_fetch_array ] {  
  - Parameters [2] {  
    Parameter #0 [ $"statement resource" ]  
    Parameter #1 [ $"array type" ]  
    }  
    }  
    Function [ function &sqlsrv_fetch_object ] {  
  - Parameters [3] {  
    Parameter #0 [ $"statement resource" ]  
    Parameter #1 [ $"class name" ]  
    Parameter #2 [ $"ctor params" ]  
    }  
    }  
    Function [ function sqlsrv_has_rows ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function sqlsrv_num_fields ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function sqlsrv_next_result ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function sqlsrv_num_rows ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function sqlsrv_rows_affected ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function sqlsrv_client_info ] {  
  - Parameters [1] {  
    Parameter #0 [ $"connection resource" ]  
    }  
    }  
    Function [ function sqlsrv_server_info ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function sqlsrv_cancel ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function sqlsrv_free_stmt ] {  
  - Parameters [1] {  
    Parameter #0 [ $"connection resource" ]  
    }  
    }  
    Function [ function &sqlsrv_field_metadata ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    Function [ function sqlsrv_send_stream_data ] {  
  - Parameters [1] {  
    Parameter #0 [ $"statement resource" ]  
    }  
    }  
    }  
    }  
## Work Item Details

**Original CodePlex Issue:**    [Issue 20138](http://sqlsrvphp.codeplex.com/workitem/20138)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Mar 4, 2011 at 12:13 PM
**Reported by:**    stealth35
**Updated on:** Mar 4, 2011 at 2:54 PM
**Updated by:** stealth35

**Comment by yitam** [comment]
Already fixed. Closing the issue.
