### ISSUE TITLE
New Windows Release

### ISSUE THREAD

**Issue by david-garcia-garcia** [Microsoft/msphpsql#222]
There has not been a Windows release for a while, it would be great to get the latest fixes (that are already available in the Linux version) released.

BTW deep thanks to the team for their ongoing effort on this driver.

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia Thanks for the kind workds. We are working on this as I type. Should be out soon :)

**Comment by meet-bhagdev** [comment]
Done! :) https://github.com/Microsoft/msphpsql/releases/tag/4.1.5-Windows
