### ISSUE TITLE
Needed extra steps to get everything working on Ubuntu 16.04

### ISSUE THREAD

**Issue by koennys** [Microsoft/msphpsql#233]
I started off with a clean Ubuntu 16.04 install and I tried to follow the steps for PHP 7. I didn't run into any issues during these steps but at the end of them I still couldn't open a test php file that tried to make a connection. I had to do the following additional steps:

sudo a2enmod php7.0
sudo a2dismod mpm_event
sudo a2enmod mpm_prefork
sudo apache2ctl restart

I'm not sure if anyone else had these issues but if so maybe these additional steps can be added to the guide?

**Comment by Hadis-Fard** [comment]
Can you follow [install instructions](https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux#install) on README? What is the error message you are receiving? also what is the driver you are using?

**Comment by koennys** [comment]
I followed the install instructions in this readme https://github.com/Microsoft/msphpsql/blob/PHP-7.0-Linux/README.md
The steps I followed were for ubuntu 16.04 and php 7.0 these are also the versions I'm using.
The first 6 steps went fine without any problems. At step 7, testing a php script my source code was just shown on screen rather then parsed. this is when I did:

sudo a2enmod php7.0
sudo apache2ctl restart

I tried again and I got the following error:

Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP

I solved this by doing:

sudo a2dismod mpm_event
sudo a2enmod mpm_prefork
sudo apache2ctl restart

In my test script I was using the PDO sqlsrv driver /usr/lib/php/20151012/pdo_sqlsrv.so

I have to say that I've never before had the problem of installing apache and php and not having the module activated automatically. But usually I install them all together and not as spread out as I did following the steps in the readme.

**Comment by Hadis-Fard** [comment]
@koennys you're receiving "Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe. You need to recompile PHP", because you are using non-thread safe PHP on thread safe apache, and you had to disable the thread safety. Note that  PHP installed using package manager is non-thread safe (NTS) and you must use NTS apache and NTS PDO_SQLSRV. Do you still have any problem getting your script working?

**Comment by koennys** [comment]
Yes I was able to get everything working with the extra steps I listed.

**Comment by meet-bhagdev** [comment]
@koennys How did you install apache? Did you use apt-get or build it from source?

**Comment by koennys** [comment]
@meet-bhagdev I used apt-get to install it. this is the list of steps I took for the configuration

sudo su
apt-get -y install php7.0 mcrypt php7.0-mcrypt php-mbstring php-pear php7.0-dev php7.0-xml
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
apt-get update
ACCEPT_EULA=Y apt-get install msodbcsql mssql-tools
apt-get install unixodbc-dev
apt-get install libapache2-mod-php7.0
apt-get install apache2
pecl install sqlsrv
pecl install pdo_sqlsrv
echo "extension=/usr/lib/php/20151012/sqlsrv.so" >> /etc/php/apache2/php.ini
echo "extension=/usr/lib/php/20151012/sqlsrv.so" >> /etc/php/7.0/apache2/php.ini
echo "extension=/usr/lib/php/20151012/pdo_sqlsrv.so" >> /etc/php/7.0/apache2/php.ini
echo "extension=/usr/lib/php/20151012/sqlsrv.so" >> /etc/php/7.0/cli/php.ini
echo "extension=/usr/lib/php/20151012/pdo_sqlsrv.so" >> /etc/php/7.0/cli/php.ini
service apache2 restart

--extra steps start here--
a2enmod php7.0
service apache2 restart
a2dismod mpm_event
a2enmod mpm_prefork
service apache2 restart

I needed the extra steps because php wasn't active in apache following the exact steps from the tutorial, I've never had this problem before I usually install php and apache in the same apt-get step so maybe it's related to the order or seperation of steps in the readme.

**Comment by Hadis-Fard** [comment]
@koennys I installed PHP 7.0, odbc, and apache on clean machine as it is stated on README. When I installed  apache using apt-get, mpm_event is disabled and mpm_prefork is enabled, below is the snippet of installation log:
      `Module mpm_event disabled.`
      `Enabling module mpm_prefork.`
      `apache2_switch_mpm Switch to prefork`

and by running the extra steps you mentioned I got these messages:
sudo a2dismod mpm_event
`Module mpm_event already disabled`

sudo a2enmod mpm_prefork
`Considering conflict mpm_event for mpm_prefork:`
`Considering conflict mpm_worker for mpm_prefork:`
`Module mpm_prefork already enabled`
