### ISSUE TITLE
PHP Startup: Unable to load dynamic library

### ISSUE THREAD

**Issue by bgillet** [Microsoft/msphpsql#255]
Hi all,

I installed :

- PHP 7.1 64 bits NTS on Windows 10 x64
- MSSQL Server 2016 Express x64
- Microsoft ODBC Driver 13.1
- Microsoft PHP Driver 4.0 (php_pdo_sqlsrv_7_nts_x64.dll)

I added extension into php.ini (extension=php_pdo_sqlsrv_7_nts_x64.dll).

After a full restart of the computer, I get the error message indicated into the post title.

`PHP Startup: Unable to load dynamic library 'D:\APPS\PHP\ext\php_pdo_sqlsrv_7_nts_x64.dll' - La procédure spécifiée est introuvable.`

Is there an issue ? Did I forget something ? I have no other information in php error log to say !

**Comment by v-kigos** [comment]
See issue #200

**Comment by meet-bhagdev** [comment]
@bgillet the binaries you are using are for PHP 7, can you try using the PHP 7.1 binaries? The latest release should have them: https://github.com/Microsoft/msphpsql/releases/tag/4.1.5-Windows

**Comment by bgillet** [comment]
Great, it works !!!

May I suggest correcting Microsoft PHP SQL Driver download page ?

In System Requirements section, it is indicating that driver 4.0 is working for PHP 7.0 and above versions. Obviously, this is not true.

![image](https://cloud.githubusercontent.com/assets/3019854/22325931/ea5070a0-e3b0-11e6-96f0-acbde45bdf98.png)
