### ISSUE TITLE
Driver in cygwin enviroment

### ISSUE THREAD

**Issue by RenatasDidysis** [Microsoft/msphpsql#258]
Hello,

how can I get, or compile driver in Cygwin environment

**Comment by v-dareck** [comment]
Hi @RenatasDidysis what is the scenario for using Cygwin? 
Can you just use Windows or Linux directly?

**Comment by RenatasDidysis** [comment]
Hi, i can’t. Because i have Linux based application that is not so easy to migrate...

Can you propose any solution? Because I forced now to use PHP 5 (because PHP 7 drop ms sql driver suport)

**Comment by v-dareck** [comment]
Hi @RenatasDidysis, have you tried the MSSQL php driver on Windows with PHP 7? The latest release is here: https://github.com/Microsoft/msphpsql/releases/tag/4.1.5-Windows

**Comment by ulvii** [comment]
Hi @RenatasDidysis ,

Any update on this?

**Comment by RenatasDidysis** [comment]
Hi, 
I still wait for cygwin driver- because cant use neither Windows or Linux driver. 

And still using old php 5.6 version with ms sql support on cygwin)

**Comment by meet-bhagdev** [comment]
@RenatasDidysis Where did you download the driver for PHP 5.6? Can you shed some light on how your cygwin environment is setup.

**Comment by RenatasDidysis** [comment]
I use thease functions http://php.net/manual/en/book.mssql.php

I use old cygwin setup (Newest cygwin drop php 5.6 support, only 7 aviable -without ms sql support)

**Comment by McBane87** [comment]
I nearly know nothing about C and C++ programming. Most things I know from searches on the internet and script languages, which I know better, so please don't blame me for stupid code :D
But maybe this can help?

https://github.com/McBane87/php-sqlsrv-cygport
(You don't need to do the hole cygport things. The patches themselves should be enough)

**Comment by David-Engel** [comment]
We have no plans to add support for cygwin in our current roadmap. Closing this issue.
