### ISSUE TITLE
compile on debian on phpfarm

### ISSUE THREAD

**Issue by RenatasDidysis** [Microsoft/msphpsql#259]
Hello,
i use phpfarm   - how can I compile (not instal via apt-get)  this extension- need some instructions.

**Comment by v-dareck** [comment]
Hi @RenatasDidysis,

Debian currently isn't supported and we don't have instructions currently. You can try the instructions here: https://github.com/Microsoft/msphpsql/blob/PHP-7.0-Linux/LinuxTutorial.md
If you want to build from PHP and the msphpsql driver from source the section "**Compiling and installing Microsoft PHP drivers for SQL Server from source:**" explains how. Those instruction should work on debian though they maybe out of date. The PHP driver requires the Microsoft ODBC Driver for SQL Server on Linux.

**Comment by RenatasDidysis** [comment]
Thanks it works perfectly. Please add this tutorial to readme. (Debian is real server OS)
