### ISSUE TITLE
PDO statement returns bool(false) when using temporary tables

### ISSUE THREAD

**Issue by v-kigos** [Microsoft/msphpsql#260]
PDO_SQLSRV fails to successfully execute CREATE / SELECT statements 
when using temporary tables, see repro script. This behaviour 
is cross-platform (Win/Linux) on PHP7.0 and 7.1.

SQLSRV driver does not have this issue and returns: 
resource(7) of type (SQL Server Statement)

Repro script:

```
// Connect
$conn = new PDO("sqlsrv:server=$serverName", $username, $password);

// Create a temporary table
$sql = "CREATE TABLE #T1 (code VARCHAR(12))";
$stmt = $conn->query($sql);

// Insert data fails, and returns bool(false)
$sql = "INSERT INTO #T1 VALUES ('ONE')";
$stmt = $conn->query($sql);
var_dump($stmt);
```

Expected output:
resource(7) of type (SQL Server Statement)
string(11) "ONE"

Actual output:
bool(false)

**Comment by yitam** [comment]
The main difference is that PDO invokes query() by first preparing the statement then execute it, whereas in sqlsrv we execute the query directly by SQLExecDirect().

As explained in this [article](https://technet.microsoft.com/en-us/library/ms175528(v=sql.105).aspx):
> Prepared statements cannot be used to create temporary objects on SQL Server. Prepared statements cannot reference system stored procedures that create temporary objects, such as temporary tables. These procedures must be executed directly.
