### ISSUE TITLE
Add SQL2016 Always Encrypt Column support

### ISSUE THREAD

**Issue by RomuAdq** [Microsoft/msphpsql#263]
Hello,

When adding option : column encryption setting=enabled in SQL DSN, the error  

> SQLSTATE[IMSSP]: An invalid keyword 'column encryption setting' was specified in the DSN string
pops up.

When will be this feature supported by MSSQL PDO ?

Regards,

**Comment by meet-bhagdev** [comment]
@RomuAdq We are looking into this. Don't have an accurate timeline yet, but will keep you posted.

**Comment by RomuAdq** [comment]
Thank you for the update !

De : Meet Bhagdev [mailto:notifications@github.com]
Envoyé : lundi, 30 janvier 2017 08:47
À : Microsoft/msphpsql <msphpsql@noreply.github.com>
Cc : Romuald Smirne <rsmirne@adequasys.com>; Mention <mention@noreply.github.com>
Objet : Re: [Microsoft/msphpsql] Add SQL2016 Always Encrypt Column support (#263)


@RomuAdq<https://github.com/RomuAdq> We are looking into this. Don't have an accurate timeline yet, but will keep you posted.

**Comment by floriangrousset** [comment]
@meet-bhagdev - Any update on when it will be supported?

**Comment by meet-bhagdev** [comment]
@floriangrousset: we are looking into doing this in the coming months. We will give you a crisper timeline once we do some more investigation 👍

**Comment by mph2labs** [comment]
any news on this one?

**Comment by alexeycr** [comment]
Really need the support for this feature.. Any ETA?

**Comment by meet-bhagdev** [comment]
@alexeycr @mph2labs @floriangrousset @RomuAdq We are looking into this actively. Can you share with us what scenarios/use cases would you like to use with Always Encrypted? Are you looking to do simple encryption/decryption of sensitive data on the client side? Some psuedo code examples would help a lot. 

Once we have them, we can start enabling them in one of the next previews 👍

**Comment by mph2labs** [comment]
We got a ms sql server 2016 with some tables which use the column encryption. It is not possible to query or select the data from this table (so we come under your simple decryption scenario)

`function OpenConnection()
{
    try
    {
        $serverName = "servername;
        $connectionOptions = array("Database"=>"dbname",
            "Uid"=>"username", "PWD"=>"passw");
        $conn = sqlsrv_connect($serverName, $connectionOptions);
        if($conn == false)
            die(FormatErrors(sqlsrv_errors()));
    }
    catch(Exception $e)
    {
        echo("Error!");
    }
}


function ReadData()
{
    try
    {
        $conn = OpenConnection();
        $tsql = "SELECT [encryptedColumnName] FROM [dbname].[dbo].[TableNameWithSomeEncryptedColumn]";
        $getProducts = sqlsrv_query($conn, $tsql);
        if ($getProducts == FALSE)
            die(FormatErrors(sqlsrv_errors()));
        $productCount = 0;
        while($row = sqlsrv_fetch_array($getProducts, SQLSRV_FETCH_ASSOC))
        {
            echo($row['encryptedColumnName']);
            echo("<br/>");
            $productCount++;
        }
        sqlsrv_free_stmt($getProducts);
        sqlsrv_close($conn);
    }
    catch(Exception $e)
    {
        echo("Error!");
    }
}

//test the connection
ReadData();`

**Comment by meet-bhagdev** [comment]
awesome! @Hadis-Fard and I will see how much time will the simple encryption decryption scenarios will take. For your SELECT queries, do you plan on using parametrized queries?

**Comment by mph2labs** [comment]
not planning to use parametrised queries as this is a back end script but I am sure it will come handy at some point ;-)

**Comment by meet-bhagdev** [comment]
a quick update on this: we will be adding basic AE functionality by July (preview will likely be available earlier)

**Comment by mph2labs** [comment]
great stuff, let us know here when you got something we can test and happy to supply feedback.

**Comment by kenliao55** [comment]
Good day all~  we are currently developing a goverment project with SQL 2016 and php 7, some personal information are using this always encryption function.  Thank for the team doing this. once preview function is released , we are willing to do the testing. thanks a lot~

**Comment by zippy1981** [comment]
I'm chomping at the bit to add a PHP example [to the sample code I use for Always Encrypted talks](https://github.com/sqlcollaborative/AlwaysEncryptedSample/tree/features/phpSampleApp) at meetups and SQL Saturdays.

**Comment by meet-bhagdev** [comment]
@zippy1981 @kenliao55 @mph2labs @RomuAdq @alexeycr @floriangrousset: We are adding functionality for retrieving (SELECT queries on) AE columns/tables very soon (still targeting July preview). 

There are some technical roadblocks for insertions and parameterized queries. We will keep this issue updated 👍

**Comment by kenliao55** [comment]
@meet-bhagdev How does it go?  please let me know if there is a preview. thanks a lot~ good day

**Comment by meet-bhagdev** [comment]
@all we are running into some issues with AE. We have retrieval working. But there are some failing test cases with data types such as varchar max. The failures can result in unrecoverable crashes. We are working aggressively on tracking them down and fixing it. I will keep you guys posted.

**Comment by Hadis-Fard** [comment]
Exciting news @ALL, we have released [5.1.0 preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.1.0-preview) drivers supporting [Always Encrypted](https://github.com/Microsoft/msphpsql/wiki/Features#using-always-encrypted-with-the-php-driver-510-preview-for-sql-server)! To use Always Encrypted you should install [MS ODBC 17 preview ](https://github.com/Microsoft/msphpsql/wiki/Install-and-configuration#odbc-17-linux-installation). You can ODBC 17 binaries from [here ](https://github.com/Microsoft/msphpsql/tree/dev/ODBC%2017%20binaries%20preview).

**Comment by Hadis-Fard** [comment]
@ALL we just released another [preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.1.1-preview) supporting Always Encrypted, would love to hear your feedback :blush:

**Comment by yitam** [comment]
Please check the latest [v5.3.0 release](https://github.com/Microsoft/msphpsql/releases/tag/v5.3.0). 

Should any of you have any other problem or issue with Always Encrypted, please create a new issue.
