### ISSUE TITLE
XML parsing: unable to switch the encoding

### ISSUE THREAD

**Issue by parite** [Microsoft/msphpsql#264]
When inserting into a column declared as an XML type, and your XML has the declaration (at the top), PDO returns a "XML parsing: line 1, character 38, unable to switch the encoding" error.

SQL Version: Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64)
PHP: 7.0.13-0ubuntu0.16.04.1

Using pdo_sqlsrv-4.0.8 from PECL libraries.

DB Structure:
```
CREATE TABLE TestTable
(
  ID INT PRIMARY KEY NOT NULL IDENTITY,
  XMLMessage XML
);
```

PHP:
```
$xml = '<?xml version="1.0" encoding="UTF-8"?>
<ParentXMLTag>
  <ChildTag01>TestValue01</ChildTag01>
  <ChildTag02>TestValue01</ChildTag02>
</ParentXMLTag>';

try {

    $conn = new PDO("sqlsrv:server=tcp:server.corp,1433;Database=SchemaName", "username", "password");
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    $stmt = $conn->prepare("INSERT INTO TestTable (XMLMessage) VALUES (:msg)");
    $stmt->bindValue(':msg', $xml);

    $stmt->execute();

    echo "Success";
}
catch (PDOException $ex) {
    echo "Error: " . $ex->getMessage();
}
```

Results of the above code:
`Error: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]XML parsing: line 1, character 38, unable to switch the encoding`

If you remove the XML declaration, i.e.:

```
$xml = '<ParentXMLTag>
  <ChildTag01>TestValue01</ChildTag01>
  <ChildTag02>TestValue01</ChildTag02>
</ParentXMLTag>';
```

The results are:
`Success`

Am I doing something wrong here?

**Comment by v-kigos** [comment]
Thank you for reporting the issue. I could reproduce it.

This can be a temporary remedy:
```
$stmt = $conn->query("INSERT INTO $tableName (XMLMessage) VALUES ('$xml')");
```

**Comment by v-kigos** [comment]
Actually, XML field is inserted using nvarchar(4000) and thus requires UTF-16 encoding.
This would fix your script:

```
$xml = '<?xml version="1.0" encoding="UTF-16"?>
<ParentXMLTag>
  <ChildTag01>TestValue01</ChildTag01>
  <ChildTag02>TestValue01</ChildTag02>
</ParentXMLTag>';
```

**Comment by parite** [comment]
Thanks @v-kigos, I ended up stripping out the declaration as a temporary fix.

I tried your UTF-16 fix and that seems to do the trick, but that brings up another concern: 

What happens when the XML is more than 4000 characters? Is there a way to declare to PDO which data type to bind the parameter? From what I can see you can use `PDO::PARAM_STR` but this doesn't allow a length (like MAX).

**Comment by v-kigos** [comment]
The same techniques used for other large value types also apply to XML. The driver supports XML that exceeds the length of 4000 characters.

Example:
```
$longSample = str_repeat("a",8500);
$xml1 = '<?xml version="1.0" encoding="utf-16"?>
<ParentXMLTag>
  <ChildTag01>'.$longSample.'</ChildTag01>
</ParentXMLTag>';
```

**Comment by parite** [comment]
Good to know - thank you @v-kigos!
