### ISSUE TITLE
PDOStatement execute error

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#27]
I am using PHP 5.4 (zend 5.6), IIS 7.5, and SQLSRV-PHP driver on my
development machine. I tried inserting some data into SQL2008R2 database using
the new driver but to my surprise every time i run execute(), it inserts the
same record twice. Below is my code:  

$pdo = new PDO("sqlsrv:server=(local);database=devDb;");  
$sql = "insert into tblTest (name,ts) values(:name, :ts)";  
$stmt = $pdo->prepare($sql);  
$args = array(':name'=>'Some Value',':ts'=>microtime(true));  
if( $stmt->execute($args) ){  

```
.....
```

}  

When i run and check the db, it creates 2 records with a difference in the ts
field of some few micro seconds. On my production system which is running
PHP5.3, that is not an issue.  
Could it be a problem in the driver or PHP itself  
## Work Item Details

**Original CodePlex Issue:**    [Issue 22416](http://sqlsrvphp.codeplex.com/workitem/22416)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    May 17, 2012 at 2:33 PM
**Reported by:**    quaspam
**Updated on:** May 21, 2012 at 3:01 PM
**Updated by:** jguerin

**Comment by yitam** [comment]
It's been fixed. Closing this issue.
