### ISSUE TITLE
Windows DLL drivers for PHP 7.0 on PECL

### ISSUE THREAD

**Issue by gmsantos** [Microsoft/msphpsql#275]
First, congratulations for merging Windows and Linux codebases. Really glad to see things going forward so fast 😄 

In [PECL release for version 4.16](https://pecl.php.net/package/pdo_sqlsrv/4.1.6/windows) we only have the compiled DLL for PHP 7.1

Would be nice to include the compiled PHP 7.0 in this release too, or in the future releases.

**Comment by meet-bhagdev** [comment]
@gmsantos thanks :) 👍 Thats a good point, we will look into this.

**Comment by Hadis-Fard** [comment]
@gmsantos We fixed the issue with our PECL repository, you can get the PHP 7.0 and 7.1 from
https://pecl.php.net/package/sqlsrv/4.1.6.1/windows
https://pecl.php.net/package/pdo_sqlsrv/4.1.6.1/windows

**Comment by gmsantos** [comment]
thanks @Hadis-Fard ! 😄
