### ISSUE TITLE
[Linux] Prepared statements changing session scope?

### ISSUE THREAD

**Issue by deeky666** [Microsoft/msphpsql#276]
I have found a weird issue with prepared statements. It affects Linux drivers (both `sqlsrv` and `pdo_sqlsrv`).

The use case is using temporary tables. The following script works (**NOT** using prepared statements):

**sqlsrv**
```php
$connectionInfo = array(
    'UID' => 'sa',
    'PWD' => 'D0ctrine',
);

$conn = sqlsrv_connect('localhost, 1433', $connectionInfo);

$query = "CREATE TABLE #foo (id INT NOT NULL)";
var_dump(sqlsrv_query($conn, $query)); // resource(5) of type (SQL Server Statement)
var_dump(sqlsrv_errors()); // NULL

$query = "DROP TABLE #foo";
var_dump(sqlsrv_query($conn, $query)); // resource(6) of type (SQL Server Statement)
var_dump(sqlsrv_errors()); // NULL
```

**pdo_sqlsrv**
```php
$conn = new PDO('sqlsrv:server=localhost,1433', 'sa', 'D0ctrine');

$query = "CREATE TABLE #foo (id INT NOT NULL)";
var_dump($conn->exec($query)); // int(0)

$query = "DROP TABLE #foo";
var_dump($conn->exec($query)); // int(0)
```

While the following script doesn't (**USING** prepared statements):

**sqlsrv**
```php
$connectionInfo = array(
    'UID' => 'sa',
    'PWD' => 'D0ctrine',
);

$conn = sqlsrv_connect('localhost, 1433', $connectionInfo);

$query = "CREATE TABLE #foo (id INT NOT NULL)";
$stmt = sqlsrv_prepare($conn, $query);
var_dump(sqlsrv_execute($stmt)); // bool(true)
var_dump(sqlsrv_errors()); // NULL

$query = "DROP TABLE #foo";
$stmt = sqlsrv_prepare($conn, $query);
var_dump(sqlsrv_execute($stmt)); // bool(false)
var_dump(sqlsrv_errors());

/*
array(1) {
  [0]=>
  array(6) {
    [0]=>
    string(5) "42S02"
    ["SQLSTATE"]=>
    string(5) "42S02"
    [1]=>
    int(3701)
    ["code"]=>
    int(3701)
    [2]=>
    string(140) "[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot drop the table '#foo', because it does not exist or you do not have permission."
    ["message"]=>
    string(140) "[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot drop the table '#foo', because it does not exist or you do not have permission."
  }
}
*/
```

**pdo_sqlsrv**
```php
$conn = new PDO('sqlsrv:server=localhost,1433', 'sa', 'D0ctrine');

$query = "CREATE TABLE #foo (id INT NOT NULL)";
$stmt = $conn->prepare($query);
var_dump($stmt->execute()); // bool(true)

$query = "DROP TABLE #foo";
$stmt = $conn->prepare($query);
var_dump($stmt->execute()); // bool(false)
var_dump($stmt->errorInfo());

/*
array(3) {
  [0]=>
  string(5) "42S02"
  [1]=>
  int(3701)
  [2]=>
  string(140) "[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot drop the table '#foo', because it does not exist or you do not have permission."
}
*/
```

It seems that using prepared statements somehow changes the session scope (?) so that temporary tables are out of scope?

**Comment by deeky666** [comment]
Btw looks like this is an issue on Windows, too.

**Comment by meet-bhagdev** [comment]
@deeky666 Thanks for the repro. We will look into it :) 👍

**Comment by v-kigos** [comment]
Please check issue #260

**Comment by david-garcia-garcia** [comment]
This is very bad DX.

Any chance the PDO driver can complain with a better  message when using temporary tables in prepared statements?

The workaround is to use ATTR_DIRECT_QUERY on the PDO driver.

Yet, you should NOT use prepared statements at all with the current state of this driver. It is useless.

See https://github.com/Microsoft/msphpsql/issues/60

You are better off using ATTR_DIRECT_QUERY by default until #60 gets fixed.

**Comment by deeky666** [comment]
@meet-bhagdev @v-kigos thanks for the quick response. So do I understand correctly, that this behaviour is not a driver issue but actually intended because the server cannot achieve this? If that is the case, this issue can be closed and I will mark this as known vendor limitation in our repo.

**Comment by v-dareck** [comment]
@deeky666, yes this is the expected behavior:
https://technet.microsoft.com/en-us/library/ms175528(v=sql.105).aspx

**Comment by deeky666** [comment]
Okay closing then. Sorry for the noise and thanks for clearing that up. I patched our library instead to use direct execution for those kind of statements instead of prepared statements.
