### ISSUE TITLE
4.1.6 Windows release is missing PHP DLL driver files

### ISSUE THREAD

**Issue by photodude** [Microsoft/msphpsql#277]
[Release 4.1.5](https://github.com/Microsoft/msphpsql/releases/tag/4.1.5-Windows) has DLLs for PHP 7 and PHP 7.1 but the [4.1.6 Windows/Linux release](https://github.com/Microsoft/msphpsql/releases/tag/v4.1.6) is missing the PHP DLL files for windows

Please add the windows PHP 7 and PHP 7.1 DLLs for the pdo_sqlsrv and sqlsrv drivers to the release

**Comment by photodude** [comment]
/Ping @Hadis-Fard
When can we expect the 4.1.6 Windows drivers to be [posted to the release page](https://github.com/Microsoft/msphpsql/releases/tag/v4.1.6)?

**Comment by meet-bhagdev** [comment]
@photodude You should have it tomorrow :) 👍

**Comment by photodude** [comment]
@meet-bhagdev Thank you. Looking forward to the update.

**Comment by Hadis-Fard** [comment]
@photodude DLLs are now up in our PECL repository, you can download them from:
https://pecl.php.net/package/sqlsrv/4.1.6.1/windows
https://pecl.php.net/package/pdo_sqlsrv/4.1.6.1/windows

**Comment by photodude** [comment]
Thanks, I was hoping for the files to also be included in the release page here, guess I'll change our appveyor code for pulling the dlls.

**Comment by photodude** [comment]
@Hadis-Fard the PECL files are missing the php_pdo_sqlsrv.dll module, they only have the PHP_sqlsrv.dll module

I checked the following files
- http://windows.php.net/downloads/pecl/releases/sqlsrv/4.1.6.1/php_sqlsrv-4.1.6.1-7.1-nts-vc14-x64.zip
- http://windows.php.net/downloads/pecl/releases/sqlsrv/4.1.6.1/php_sqlsrv-4.1.6.1-7.0-nts-vc14-x64.zip

**Comment by photodude** [comment]
Just noticed that the packages are separated unlike what we have for the 4.1.5 release files on the release page.

- https://pecl.php.net/package/sqlsrv/4.1.6.1/windows
- https://pecl.php.net/package/pdo_sqlsrv/4.1.6.1/windows
