### ISSUE TITLE
PDO::lastInsertId() not implemented correctly for sequences

### ISSUE THREAD

**Issue by deeky666** [Microsoft/msphpsql#278]
`\PDO::lastInsertId($name = null)` should return the current value for a given sequence object name. [See the documentation](http://php.net/manual/en/pdo.lastinsertid.php).

Currently this is not working because the PDO implementation is using `SELECT IDENT_CURRENT(%s)` which is not intended for sequences but for tables. [See here](https://github.com/Microsoft/msphpsql/blob/master/source/pdo_sqlsrv/pdo_dbh.cpp#L33).

The current workaround is to extend `\PDO` like [we have done it in Doctrine](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php#L43-L53).

While this is working, it should rather be fixed in the driver itself IMO.

**Comment by meet-bhagdev** [comment]
@deeky666 Your recommendation makes sense. We are still looking into it. If we do change the behavior, we might end up breaking applications that rely on this behavior. Do you think a lot of folks in the community would be using `PDO::lastInsertId($name = null)`  to return the current value of a table?

**Comment by deeky666** [comment]
@meet-bhagdev I do not see why anyone should rely on a behaviour that is not defined. The method is not supposed to accept a table name. It is clearly documented in PHP. If people are really using it for tables, they are misusing the API. I see your objection about BC but IMO keep BC for a bug has nothing to do with BC ;) Does that make sense?

Also I have not come across another PDO implementation that was NOT using this API for sequences.

**Comment by Hadis-Fard** [comment]
This issue is resolved in [5.0.0-preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.0.0-preview) release.
