### ISSUE TITLE
PHP sqlsrv 3.0.1 Driver: sqlsrv_field_metadata returns column name as char*, so unicode column names can't be fetched correctly

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#28]
Customer uses unicode column names:  

CREATE TABLE Greek  
(  
[γεια σας κόσμο] [ nvarchar ](100) NOT NULL,  
[привет мир] [ nvarchar ](100) NOT NULL,  
[こんにちは世界] [ nvarchar ](100) NOT NULL  
);  

calling sqlsrv_field_metadata converts names to ANSI char strings:  

Result 3 Row 2:Array  
(  
[0] => hello world  
[?e?a sa? ??s�?] => hello world  
[1] => hello world  
[?????? ???] => hello world  
[2] => hello world  
[???????] => hello world  
)  

Here are some of the source code changes we would need to make to fix this:  

Core_sqlsrv.h:  

```
sqlsrv_malloc_auto_ptr<SQLCHAR> field_name;
```

…change to:  

```
sqlsrv_malloc_auto_ptr<SQLWCHAR> field_name;
```

core_stmt.cpp:  

```
meta_data->field_name = static_cast<SQLCHAR*>( sqlsrv_malloc( SS_MAXCOLNAMELEN + 1 ));



try {

    core::SQLDescribeCol( stmt, colno + 1, meta_data->field_name.get(), SS_MAXCOLNAMELEN, &field_name_len, 
```

…change to:  

```
meta_data->field_name = static_cast<SQLWCHAR*>( sqlsrv_malloc( SS_MAXCOLNAMELEN + 1 ));



try {

    core::SQLDescribeColW( stmt, colno + 1, meta_data->field_name.get(), SS_MAXCOLNAMELEN, &field_name_len, 
```

stmt.cpp:  

```
    core::sqlsrv_add_assoc_string( *stmt, field_array, FieldMetaData::NAME, 

                                   reinterpret_cast<char*>( core_meta_data->field_name.get() ), 0 TSRMLS_CC );
```

…change to:  

```
    core::sqlsrv_add_assoc_string( *stmt, field_array, FieldMetaData::NAME, 

                                   reinterpret_cast< wchar_t*>( core_meta_data->field_name.get() ), 0 TSRMLS_CC );
```

Pdo_stmt.cpp:  

```
// Set the name 

column_data->name = reinterpret_cast<char*>( core_meta_data->field_name.get());
```

…change to:  

```
column_data->name = reinterpret_cast< wchar_t*>( core_meta_data->field_name.get());
```
## Work Item Details

**Original CodePlex Issue:**    [Issue 22417](http://sqlsrvphp.codeplex.com/workitem/22417)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Sep 25, 2012 at 8:17 PM
**Reported by:**    WRead
**Updated on:** Sep 25, 2012 at 8:17 PM
**Updated by:** WRead
#### Plaintext Attachments

[CodePlex Issue #22417 Plain Text Attachments](https://gist.github.com/9b4f04ed23dd81644600)

**Comment by yitam** [comment]
Already fixed in [4.0.8 release](https://github.com/Microsoft/msphpsql/tree/4.0.8-Linux). Closing this issue.
