### ISSUE TITLE
Ubuntu 16.04 Install Issue?

### ISSUE THREAD

**Issue by BarryCarlyon** [Microsoft/msphpsql#287]
Following the setup for Ubuntu 16.04

```
me@box:~$ sudo apt-get install unixodbc-dev-utf16
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 unixodbc-dev-utf16 : Depends: unixodbc-utf16 (= 2.3.1-2) but it is not going to be installed
                      Depends: odbcinst1debian2-utf16 (= 2.3.1-2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

Installing unixodbc-utf16 wipes out mssql-tools

And mssql-tools didn't seem to provide sqlcmd either…

**Comment by BarryCarlyon** [comment]
(Have now found sqlcmd at `/opt/mssql-tools/bin/sqlcmd` it's just not in $PATH

**Comment by darthtaco** [comment]
Same issue here on Ubuntu 16.04 Vagrant box (Laravel Homestead)

**Comment by meet-bhagdev** [comment]
@BarryCarlyon @darthtaco Did you have a previous version of msodbcsql/mssql-tools installed?

**Comment by BarryCarlyon** [comment]
Negative. Brand spanking new server fresh outta the box from Dell last Friday.

As sorta noted I did do a `sudo apt-get install unixodbc-utf16` without much thought then later when restacking after taking unixodbc-utf16 and readding mssql-tools spotted the issue which I then reported.

So never a different version of mssql-tools but the same one.

**Comment by meet-bhagdev** [comment]
Got it. To confirm, here are the steps you followed? 

```
sudo su
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
exit
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install msodbcsql unixodbc-dev gcc g++ build-essential
sudo pecl install sqlsrv pdo_sqlsrv
sudo echo "extension= pdo_sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
sudo echo "extension= sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
```

**Comment by BarryCarlyon** [comment]
I followed https://github.com/Microsoft/msphpsql#install-linux for Ubuntu 16.04.

Which states:

```
sudo su 
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
exit
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install msodbcsql mssql-tools 
sudo apt-get install unixodbc-dev-utf16
```

So no `unixodbc-dev` has not been installed.

**Comment by meet-bhagdev** [comment]
@BarryCarlyon We recently made some changes. We no longer depend on the utf16 package (instead depend on the custom unixodbc packages).  New install instructions (Also updated on README.md)

```
sudo su
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
exit
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install msodbcsql unixodbc-dev gcc g++ build-essential
sudo pecl install sqlsrv pdo_sqlsrv
sudo echo "extension= pdo_sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
sudo echo "extension= sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
```

Optional Instructions:
```
sudo ACCEPT_EULA=Y apt-get install mssql-tools
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
```

Give this a shot and let us know if they work.

**Comment by BarryCarlyon** [comment]
Looks good now.

`unixodbc-dev` installed without issue

The optional mssql-tools is still not in a normal bin path location but optional module is optional module.

A reinstall of the pecl modules didn't fix #288 so the missing dep

**Comment by meet-bhagdev** [comment]
Still looking into #288

**Comment by cmosguy** [comment]
Hey @meet-bhagdev, can you please update the PDF in the download file for Linux_4.0_Install_Instructions.pdf?  I stumbled upon this issue when trying to resolve the error on your outdated package.

Many thanks!

**Comment by meet-bhagdev** [comment]
@cmosguy sure! What issue did you run into?

**Comment by washcycle** [comment]
When you download a legacy version MSSQL 13 the instructions still note (optionally) unixodbc-dev-utf16

https://www.microsoft.com/en-us/download/details.aspx?id=50420

```
sudo su
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssqlrelease.list
exit
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install msodbcsql=13.0.1.0-1 mssql-tools
sudo apt-get install unixodbc-dev-utf16 #this step is optional but recommended*
```
