### ISSUE TITLE
Problem with sqlsrv_next_result/lastinsertid after insert on table with trigger

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#29]
Hi,  

i have a table with an insert trigger defined. I made an insert on this table
and want to get the inserted id. So i made this:  
$sql = 'INSERT INTO "content" ("parent", "name", "content", "created_by",
"changed_by", "create_date", "change_date") VALUES (?, ?, ?, ?, ?, ?, ?)
SELECT SCOPE_IDENTITY() as Current_Identity';  
$params = array(1, 'TTTTTTTTTTTTT', 'TTTTTTTTTTTTT', 0, 0, '20121128
20:01:57', '20121128 20:01:57');  

$stmt = sqlsrv_query( $conn, $sql, $params);  

To get the Current_Identity i need to make two sqlsrv_next_result. If i delete
the trigger it works with only one sqlsrv_next_result.  
This sounds like a bug for me.  

Attached is an example script.  

I used php 5.4 with sqlsrv 3.0.1  

regards,  
Frank  
## Work Item Details

**Original CodePlex Issue:**    [Issue 22418](http://sqlsrvphp.codeplex.com/workitem/22418)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Nov 30, 2012 at 8:57 AM
**Reported by:**    lordlamer
**Updated on:** Dec 6, 2012 at 7:45 AM
**Updated by:** lordlamer
#### Plaintext Attachments

[CodePlex Issue #22418 Plain Text Attachments](https://gist.github.com/bd189ad8ac04f5a59717)

**Comment by yitam** [comment]
Based on the comment in the [given link](https://cloud.githubusercontent.com/assets/21340756/21733442/4a8597be-d413-11e6-8b8b-0e441a8a326b.png) it is not a bug, see below:

"It isn't a bug.

Your query has 2 results, an INSERT and a SELECT statement.
Your INSERT statement has a trigger - without NOCOUNT it generates a separate result, as written in the manual.
Therefore without NOCOUNT in your trigger you have 3 results: INSERT + TRIGGER + SELECT.
With NOCOUNT in your trigger you have 2 results: INSERT + SELECT.

It's normal.
Rob

Friday, December 07, 2012 4:00 PM
"
