### ISSUE TITLE
curl: (7) Failed connect to packages.microsoft.com:443; connect refused

### ISSUE THREAD

**Issue by xw43230855** [Microsoft/msphpsql#294]
curl https://packages.microsoft.com/config/rhel/7/mssql-server.repo > /etc/yum.repos.d/mssql-server.repo
get   curl: (7) Failed connect to packages.microsoft.com:443; connect refused

**Comment by meet-bhagdev** [comment]
@xw43230855 I just tried the above mentioned curl command on a fresh machine and it worked for me. Is the port 443 open in the outbound TCP port list?
