### ISSUE TITLE
Cannot backup a database and retrieve multiple results in one statement

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#30]
In our application, we need to be able to backup a database from PHP and also
retrieve data from SELECTs in the same statement. Actually, we run all this
code in a Stored Procedure in SQL Server 2008 but we were able to reproduce
the same exact problem with a simple query. Our application is made to work in
UTF-8 and display html using this encoding. What happens here is that PHP is
crashing in this particular case, which is very bad. We found out that if we
remove 'CharacterSet' => 'UTF-8', the issue is gone, the database gets backed
up and data is returned (but I guess utf-8 strings are messed up if any) and
we think it has something to do with UTF-8 encoding of error messages, as
reported in a Stackoverflow question here (which I also commented) : [
http://stackoverflow.com/questions/9621858/sqlsrv-php-driver-and-utf-8
-encoding-issue-with-error-messages
](http://stackoverflow.com/questions/9621858/sqlsrv-php-driver-and-utf-8
-encoding-issue-with-error-messages)  

Here is the source code to reproduce the error :  

<?php  
sqlsrv_configure('WarningsReturnAsErrors', 0);  

```
$result = array();

$connInfo = array(
    "Database"=>"myDB", 
    "UID"=>"sa", // using sa to demonstrate it's not a permission issue
    "PWD"=>"saPassword",
    'APP' => 'MyApp',
    'LoginTimeout' => 5,
    'MultipleActiveResultSets' => true,
    'ReturnDatesAsStrings' => true,
    'CharacterSet' => 'UTF-8'
);

$conn = sqlsrv_connect('myserverhost', $connInfo);

$query = "BACKUP DATABASE [SomeDB] 
            TO DISK = 'C:\\Backup\\test_backup.bak'
            WITH
            NOFORMAT, 
            INIT, 
            NAME = 'super backup', 
            NOREWIND, 
            NOUNLOAD, 
            SKIP;
            SELECT 1;
            SELECT 2;";

$stmt = sqlsrv_prepare($conn, $query);

sqlsrv_execute( $stmt );

// Fetch first result set
while($row = sqlsrv_fetch_array( $stmt, SQLSRV_FETCH_ASSOC)) {
    $result[] = $row;
}

// Fetch all next result sets
while($rs = sqlsrv_next_result($stmt)) {
    $result[] = sqlsrv_fetch_array( $stmt, SQLSRV_FETCH_ASSOC);
}

sqlsrv_free_stmt($stmt);
sqlsrv_close($conn);
```

?>  

If more details are needed I can provide them.  

Hope the issue gets resolved soon  
## Work Item Details

**Original CodePlex Issue:**    [Issue 22419](http://sqlsrvphp.codeplex.com/workitem/22419)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Dec 10, 2012 at 5:56 PM
**Reported by:**    MaxiWheat
**Updated on:** Dec 11, 2012 at 2:29 PM
**Updated by:** MaxiWheat

**Comment by Vanessa45** [comment]
I am currently looking at options to backup my server. Currently I have two physical servers and a small business, so cost is an issue. I need to backup these to some cloud software in a small budget. I was thinking of Ahsay software for backup. Would anybody have a similar setup or opinions on this?Leaving a link below just check:http://www.ahsay.com/jsp/en/home/index.jsp?pageContentKey=ahsay_products_overview

**Comment by yitam** [comment]
Already fixed. Closing this issue.
