### ISSUE TITLE
[ODBC Driver 13] Error if sql query has a criteria's length larger than columns' max length

### ISSUE THREAD

**Issue by Frondor** [Microsoft/msphpsql#307]
I've explained everything in detail in the [forums](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/fe35978a-e291-47d6-9568-fdd0a1976840), and this [SO question](http://stackoverflow.com/questions/42464609). (wasn't aware of this repo)

Looks like prepared statements, or the parameter binding has some problems I can't understand.
After several hours of trial and error I finally found that if execute queries with parameters which length is larger than the column's schema (`varchar(10)` in this case), the following error appears

>SQLSTATE[HY010]: Function sequence error: 0 [Microsoft][ODBC Driver Manager] Error en la secuencia de >funci�n (SQLExecute[0] at ext\pdo_odbc\odbc_stmt.c:260) (SQL: select top 1 1 [exists] from [inventory] > >where [Name] = elevenchars)

## Reproduce the error (prepared statement/param binding)
Where `Name` is `varchar(10)`
```
$serverName = '111.11.111.111,1433';
$database = '';
$uid = '';
$pwd = '';

$pdo = new PDO(
    "odbc:Driver={ODBC Driver 13 for SQL Server};Server={$serverName};Database={$database}",
    $uid,
    $pwd,
    array(
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
    )
);
$sql = 'select * from [inventory] where [Name] = ?';
$sth = $pdo->prepare($sql);
$sth->execute(['someStringLongerThanColumnsSchema']);

$result = $sth->fetchAll(PDO::FETCH_OBJ);
```

`$sth->execute(['someStringLongerThanColumnsSchema']);` won't work
`$sth->execute(['applejuice']);` works

## Reproduce for success (no bindings)
Where `Name` is `varchar(10)`
```
$serverName = '111.11.111.111,1433';
$database = '';
$uid = '';
$pwd = '';

$pdo = new PDO(
    "odbc:Driver={ODBC Driver 13 for SQL Server};Server={$serverName};Database={$database}",
    $uid,
    $pwd,
    array(
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
    )
);
$sql = "select * from [inventory] where [Name] = 'someStringLongerThanColumnsSchema'";
$sth = $pdo->prepare($sql); // or simply  $pdo->query($sql)->fetchAll(PDO::FETCH_OBJ);
$sth->execute();

$result = $sth->fetchAll(PDO::FETCH_OBJ);
```

### Dev machine

1. Windows 7 Ultimate - sp 1 - x86
2. PHP 7.0

### Server specs

1. Windows Server 2012 R2 Standard @ NT x64
2. Microsoft SQL Server Express Edition (64-bit) v11.0.2100 RTM

**Comment by yitam** [comment]
@Frondor thanks for your detailed report but regrettably I can't reproduce on my side. I followed your lemonjuice examples in the forum as well. What version are you using? Please check by doing something like:
```print_r($conn->getAttribute( PDO::ATTR_CLIENT_VERSION ));```

**Comment by Frondor** [comment]
@yitam my pleasure.

```
PDO {#209 ▼
  inTransaction: false
  attributes: {▼
    CASE: NATURAL
    ERRMODE: EXCEPTION
    PERSISTENT: false
    DRIVER_NAME: "odbc"
    ORACLE_NULLS: NATURAL
    CLIENT_VERSION: "ODBC-Win32" // == $conn->getAttribute( PDO::ATTR_CLIENT_VERSION )
    STATEMENT_CLASS: array:1 [▼
      0 => "PDOStatement"
    ]
    DEFAULT_FETCH_MODE: BOTH
  }
}
```

Be sure your `where` clause is looking for a value which length is larger than the one you specified in the schema, at the moment of creating that specific column.

I'm pretty sure you got it perfectly, but trying to be as much clear as I can.
On a database like
    DBname:
        tableName: [
            columnOne: varchar(10) 
            columnTwo: varchar(20)
        ]

Considering we only have one entry with `columnOne = lemonjuice, columnTwo = null`
And we are making use of **prepared statements** (seems like a direct `$pdo->query` would work)

This query would work and return the entry: `SELECT * FROM tableName WHERE columnOne = ?` with param `lemonjuice`
This one should also work and return nothing `SELECT * FROM tableName WHERE columnOne = ?` with param `applejuice`
This one is failing `SELECT * FROM tableName WHERE columnOne = ?` with param `applejuice123`

Please, tell me how can I provide more info if needed. Because I have no idea how to debug this kind of db issues. I got direct access to the SQL Server, probably I can extract a log or something.

**Comment by yitam** [comment]
Thanks @Frondor for your prompt reply. It's much appreciated. Yes, I did try to bind the parameter with 'strawberryjuice' (as described in your repro in the forum):
1. an empty object is returned when using ```fetchAll(PDO::FETCH_OBJ)``` 
2. false is returned when using ```fetch(PDO::FETCH_ASSOC)```

Please check the version of our PDO driver by following these steps:
```
    $conn = new PDO("sqlsrv:Server=$server;Database=$database", $uid, $pwd);
    print_r($conn->getAttribute( PDO::ATTR_CLIENT_VERSION ));  
```

You should see something like below:
```
Array
(
    [DriverDllName] => msodbcsql13.dll
    [DriverODBCVer] => 03.80
    [DriverVer] => 13.00.0702
    [ExtensionVer] => 4.1.6.0
)
```

**Comment by Frondor** [comment]
@yitam that wouldn't work, since I'm only using `pdo_odbc` extension with `ODBC Driver 13` for my app to connect to that specific database. Because the webserver is running under CloudLinux's CentOS 6 and `pdo_sqlsrv` can't be installed there. So my development machine, which runs windows 7 runs without `pdo_sqlsrv`... It works without it tho, this is the only problem I'm having actually.

**Comment by yitam** [comment]
Regrettably @Frondor pdo_odbc is not maintained by us. I should have noticed that right in the beginning. My oversight. Please feel free to ask us any questions concerning pdo_sqlsrv however. We'll be happy to help.

**Comment by Frondor** [comment]
Now this is really embarrassing :laughing: 

Ok, this should be closed then. 
But have you any idea what other solution can I try? As far as I know, there's only 1 odbc extension for PHP(7), and since `pdo_sqlsrv` doesn't support CentOS 6...

Thanks for your time, and sorry.
