### ISSUE TITLE
Empty string set to output parameter on stored procedure returns null instead.

### ISSUE THREAD

**Issue by leehicks** [Microsoft/msphpsql#308]
Referencing #182 which mostly solved the problem, but can't be reopened for this...

I no longer get the garbage output, but I am seeing that "$out" is set to null after the closeCursor() call, instead of "" (which the stored proc is actually returning in this case). All other tested values seem to return fine. I think "" should be the proper response.

**Comment by yitam** [comment]
Thanks @leehicks for confirming that the original problem is gone. We will get back to you on this. Please stay tuned.

**Comment by yitam** [comment]
Hi @leehicks 
Please confirm if this issue has been resolved with our latest release. Thank you.

**Comment by leehicks** [comment]
Resolved, thank you.
