### ISSUE TITLE
Cannot use transactions if there are any open recordsets

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#31]
It seems that SQL Server does not allow more than one recordset to be opened
at the same time. So any code doing the something like this will fail:  
- open recordset 
- open recordset  

To solve that limitation the "Multiple Active Result Sets" mode (MARS) was
created and the combination above started to work.  

But the MARS mode has some limitations about what can and what cannot be done.
One of these is that we cannot use transactions if there are any open
recordsets. That means that any code doing the following will fail:  
- open recordset 
- start transaction  

Is there any way to get around this?  
## Work Item Details

**Original CodePlex Issue:**    [Issue 22420](http://sqlsrvphp.codeplex.com/workitem/22420)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jun 7, 2013 at 11:09 AM
**Reported by:**    luisdev
**Updated on:** Jun 7, 2013 at 11:09 AM
**Updated by:** luisdev

**Comment by yitam** [comment]
This is by design. See related issue #167
