### ISSUE TITLE
Update PHP in Azure Apps

### ISSUE THREAD

**Issue by david-garcia-garcia** [microsoft/msphpsql#312]
I've got several people complaining that the pdo_sqlsrv version that comes out-of-the box in Azure Apps is very outdated.

Any chance you can ping the people in Azure Apps to update pdo_sqlsrv in the default PHP environment?

Thanks!

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia is this with the Drupal + Azure App Services platform or PHP + Azure App Services platform?

**Comment by david-garcia-garcia** [comment]
Does that make any difference? Looks like the default PHP runtime for Azure Apps is using sqlserver_pdo 4.0.6

Users can override both  the runtime and the extensions, but it just seems odd to have such an outdated version of the extension in the default runtime.

**Comment by trevonmckay** [comment]
@meet-bhagdev For me I'm using the PHP + Azure App Services

**Comment by meet-bhagdev** [comment]
@trevonmckay @david-garcia-garcia: We are working on this. There should be an update on this soon. 👍

**Comment by yitam** [comment]
Closing this issue. The user can install the desired PHP 7.* as shown in this [QuickStart](https://docs.microsoft.com/azure/app-service/app-service-web-get-started-php)
