### ISSUE TITLE
Connection failed to sqlsrv : SQLSTATE[HYT00]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired

### ISSUE THREAD

**Issue by larryu** [Microsoft/msphpsql#323]
I use Lavavel 5.4 on CentOS7.2 with Php7.1.
I installed # yum --enablerepo=remi-test install php71-php-sqlsrv.
Server name, user name and password are all OK.
I can access the SQL server when I deploy my app on windows, however I cannot connect to sqlserver when I deploy the app on CentOS.
Any idea and suggestions?
Thanks.

**Comment by Hadis-Fard** [comment]
Can you connect to sql server using `sqlcmd`? please follow the install instructions (https://github.com/Microsoft/msphpsql/tree/dev#install-unix), install pre-requisites and then test the connectivity with `sqlcmd`.

**Comment by larryu** [comment]
I have not installed sqlcmd on my linux server. Do I have to install mssql-tools on CentOS?

**Comment by larryu** [comment]
BTW, I used the  Remi's Repository to install the php7.1 and php-sqlsrv by following the instruction below.

Download the latest remi-release rpm from
http://rpms.famillecollet.com/enterprise/7/remi/x86_64/
Install remi-release rpm:
# rpm -Uvh remi-release*rpm
Install php71-php-sqlsrv rpm package:
# yum --enablerepo=remi install php71-php-sqlsrv

**Comment by larryu** [comment]
I found another issue which maybe associated with this one.
https://github.com/Microsoft/msphpsql/issues/298
Seems that maybe it is the SElinux thing. I will try to see whether it works.

**Comment by meet-bhagdev** [comment]
@larryu : Were you able to connect using sqlcmd?

**Comment by larryu** [comment]
No luck with https://github.com/Microsoft/msphpsql/issues/298.

**Comment by larryu** [comment]
@meet-bhagdev I got the following error.

Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login failed for user 'test'..

**Comment by larryu** [comment]
@meet-bhagdev New information. I reinstalled the sqlcmd based on your step. Then I can connect to the SQLServer via sqlcmd. But still cannot connect to SQL Server via Laravel 5.4.


PDOException in Connector.php line 68:
SQLSTATE[HYT00]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired

**Comment by meet-bhagdev** [comment]
Are sqlcmd and Laravel both on the same machine? The Login timeout expired error seems be a network error.

**Comment by larryu** [comment]
@meet-bhagdev Yes. You are right. Seems to be a network error. I reinstalled all the driver again.  Then tried to use php artisan tinker to connect to the db, that works. Then tried to use web page to connect to the db, no lucks. Then following https://github.com/Microsoft/msphpsql/issues/298, it works.
Thanks All.

**Comment by chgalvez** [comment]
Same problem here, using Laravel 5.4. Solved using IP address instead of names in database connection strings, on config/database.php.

**Comment by afreeland** [comment]
Thanks @chgalvez I changed from
  
`
sqlcmd -S localhost,1433 -U SA -P {pass}
`
  
to
  
`
sqlcmd -S 127.0.0.1,1433 -U SA -P {pass}
`
  
and everything connected perfect =)


Was having this issue with OSX running docker image for [SQL Server on Linux](https://hub.docker.com/r/microsoft/mssql-server-linux/)

**Comment by chgalvez** [comment]
Happy to help!
