### ISSUE TITLE
php 7.1 drivers compatibility with Windows 10 Home edition

### ISSUE THREAD

**Issue by PiTechnik** [Microsoft/msphpsql#327]
I have installed the msphpsql 7.1 drivers in two W10 Professional computers and they are connected to the sql server with no problem.
Installed in W10 Home edition there is no error message but I cannot get connected to the sql server.
Has anybody tried the drivers with with W10 Home?

**Comment by v-kaywon** [comment]
With phpinfo(), do you see SQLSRV or PDO_SQLSRV in the list of loaded modules?

**Comment by PiTechnik** [comment]
I see SQLSRV! .... Finally I installed for a second time the ODBC drivers and the problem was solved!
