### ISSUE TITLE
Ubuntu[16.04.2 64bits] PHP[7.0.15] timeout on connect SQL Server Windows Instance

### ISSUE THREAD

**Issue by Rafabin** [Microsoft/msphpsql#340]
My Ubuntu Server (192.168.10.1)
16.04.2 (64 Bits)
-Microsoft SQL Server vNext (CTP1.4) - 14.0.405.198 (X64)
-default instance instaled [guide](https://www.microsoft.com/en-us/sql-server/developer-get-started/php-ubuntu)
-db LEGACY

My Windows (192.168.0.50)
-Microsoft SQL Server 2014 Express 2014.120.2269.0
-Instance 192.168.0.50\LEGACY
-db LEGACY
-Management Studio 2016
-Firewall Off
-No Antivirus

Issue.
-The php7.0 (ubuntu) connects to the local instance (ubuntu) but does not connect to the remote instance (windows)
-The management studio (windows) successfully connects to the ubuntu and windows instance

Error.
**(Ubuntu)**-> sqlcmd -S 192.168.0.50\LEGACY  -U sa -P xxxxxxxx -Q "USE LEGACY;"

Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2AF9.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections.

**(Ubuntu)**-> sqlcmd -S localhost  -U sa -P xxxxxxxx -Q "USE LEGACY;"
OK Connected!

**(Ubuntu) - PHP**
-localhost sql server instance 'Connected'!
-windows sql server instance Timeout!     =/
[0] => HYT00
            [SQLSTATE] => HYT00
            [1] => 0
            [code] => 0
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired

[0] => 08001
            [SQLSTATE] => 08001
            [1] => -1
            [code] => -1
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]MAX_PROVS: Error Locating Server/Instance Specified [xFFFFFFFF]. 
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]MAX_PROVS: Error Locating Server/Instance Specified [xFFFFFFFF]. 

```
$serverName = "localhost";
$connectionOptions = array(
                "Database" => "LEGACY",
                "UID" => "sa",
                "PWD" => "xxxxxxxx"
);
            //Establishes the connection
            $conn = sqlsrv_connect($serverName, $connectionOptions);

            if ($conn == FALSE)
                die(print_r(sqlsrv_errors()));
            else
                echo 'Connected!';
```

![sem titulo](https://cloud.githubusercontent.com/assets/6231044/24341053/eec8e556-1284-11e7-8a19-0c42a9e99711.png)

**Comment by v-kaywon** [comment]
To connect to a named instance, you need to provide the port number. Please see [here](https://technet.microsoft.com/en-us/library/hh568455.aspx).

Other users also experienced this Login timeout expired issue due to port number, firewall, or odbc config. Please see #190 for other possible solutions.

**Comment by meet-bhagdev** [comment]
@Rafabin: Does @v-kaywon's recommendation help?

**Comment by meet-bhagdev** [comment]
@Rafabin Closing due to in-activity. Feel free to re-open if you still need help 👍
