### ISSUE TITLE
Binary data not returned when column data or column bound by name

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#35]
Hi,  

When using the PDO php driver (v3) with the adventureworks sample db and
either you add the following code to the sample (pdo_photo.php):  

1)  

$stmt->execute(array(&$_GET['productId']));  

/ _ NEW CODE _ /  

$data = array();  
$count = $stmt->columnCount();  
for ( $i = 0; $i < $count; $i++ )  
{  
$field_data_array = $stmt->getColumnMeta($i);  
$data[$field_data->Name] = $field_data_array;  
}  

/ _ END NEW CODE _ /  

$stmt->bindColumn(1, $image, PDO::PARAM_LOB, 0, PDO::SQLSRV_ENCODING_BINARY);  

2)  

$stmt->execute(array(&$_GET['productId']));  

/ _ CHANGE column index to name, strange column indexes are 1 based _ /  

$stmt->bindColumn(1, "LargePhoto", PDO::PARAM_LOB, 0,
PDO::SQLSRV_ENCODING_BINARY);  

Then the binary data is mangled and the photo is not displayed.  

Yours,  

Charles Durrant  
Thomson Reuters  
## Work Item Details

**Original CodePlex Issue:**    [Issue 22424](http://sqlsrvphp.codeplex.com/workitem/22424)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Nov 19, 2013 at 2:47 PM
**Reported by:**    charliedurrant
**Updated on:** Nov 19, 2013 at 2:48 PM
**Updated by:** charliedurrant

**Comment by yitam** [comment]
I was able to reproduce the problem using the following script:
    
    $conn = new PDO( "sqlsrv:server=$server ; Database = $dbName", $uid, $pwd);
    $stmt = $conn->prepare("SELECT LargePhoto FROM [Production].[ProductPhoto] WHERE ProductPhotoID = ?"); 
    $param = 70;
    $stmt->execute(array($param));  
    $stmt->bindColumn(1, $image, PDO::PARAM_LOB, 0, PDO::SQLSRV_ENCODING_BINARY);  
    //$stmt->bindColumn('LargePhoto', $image, PDO::PARAM_LOB, 0, PDO::SQLSRV_ENCODING_BINARY);  	// doing this the binary data is messed up and can't be displayed
    $stmt->fetch(PDO::FETCH_BOUND);  
    echo $image;
    $stmt = null;
    $conn = null;

**Comment by meet-bhagdev** [comment]
@charles-durrant-tr does this repro make sense to you?
