### ISSUE TITLE
Error on Drivers SQLSRV and PDO_SQLSRV

### ISSUE THREAD

**Issue by gersonmollo** [Microsoft/msphpsql#352]
Can you connect to SQL Server via sqlcmd?
R: Yes 
Environment details: e.g. PHP version, thread safe (TS) or non-thread safe (NTS)?
R: PHP 7.0.15-0, Ubuntu 0.16.04.2, Non-thread safe (NTS)
Which driver: SQLSRV or PDO_SQLSRV?
R: SQLSRV and PDO_SQLSRV

Testing table
Create table sys_testeLinux (
test Varchar (50)
)

SQLSRV Driver Error:
When make a SELECT using a PROCEDURE to execute it being the data fixed in the PROCEDURE, the 'pointer' does not seem to be able to identify the size of the sentence and ends up not returning all the content for display. Example:

PROGRAMMING:
![programacao driver sqlsrv](https://cloud.githubusercontent.com/assets/21044233/24551160/dc6dc5ae-15f7-11e7-9f2d-7778f9f8b0bf.PNG)
PROCEDURE:
![capturar2](https://cloud.githubusercontent.com/assets/21044233/24551327/6aff9ec8-15f8-11e7-8f8c-83595466dd2b.PNG)
RESULT:
![capturar](https://cloud.githubusercontent.com/assets/21044233/24551447/d8d83b6c-15f8-11e7-9ae1-231650f256c7.PNG)

When place spaces in the phrase that is fixed in the PROCEDURE, the content comes partially right.

PROCEDURE:
![capturar4](https://cloud.githubusercontent.com/assets/21044233/24551588/652ddab8-15f9-11e7-9871-3f2c8d91c1db.PNG)
RESULT:
![capturar3](https://cloud.githubusercontent.com/assets/21044233/24551636/942bd464-15f9-11e7-97c5-5505b1652393.PNG)

But are still wrong with what's being returned.
The error does not happen if the Procedure is a Select in a given data of a given table. Example:

Table used:
![capturar5](https://cloud.githubusercontent.com/assets/21044233/24551704/d4d2c004-15f9-11e7-8cf9-e9fd1ac37cc0.PNG)
PROCEDURE:
![capturar6](https://cloud.githubusercontent.com/assets/21044233/24551720/eb7528ce-15f9-11e7-875c-6524bf290642.PNG)
RESULT:
![capturar7](https://cloud.githubusercontent.com/assets/21044233/24551727/f63a0ac2-15f9-11e7-8f87-c4908c0e4fa0.PNG)

Notice that are returning the contents of the database correctly. The same error does not occur with the PDO_SQLSRV driver.

PDO_SQLSRV Drive Error:
When I try to do an INSERT, UPDATE or DELETE on the table, it ends up giving the PROCEDURE error, but the data is saved in the database normally.

Error Occurring:
![erro dando insert pdo](https://cloud.githubusercontent.com/assets/21044233/24551862/a6493c94-15fa-11e7-8362-334eadf49017.PNG)

The way I found to resolve this error was by putting the command '$ stmt->nextRowset (); ', but it is not correct to sort this way, because if I select a Select in a table, it ends up giving another error.

Function:
![funcoes driver pdo erro](https://cloud.githubusercontent.com/assets/21044233/24551910/dbf4d6fa-15fa-11e7-8d55-3304959ddf60.PNG)

In the case of the SQLSRV driver, I can perform INSERT, UPDATE and DELETE normally without having to put this command in the function.
I would like to know if this error is a driver bug when the server is running Linux or if it is some error in the way I am executing the commands.

**Comment by ulvii** [comment]
hi @gersonmollo ,

What version of the drivers are you using? You can do:
```
php --ri sqlsrv
php --ri pdo_sqlsrv
```

**Comment by gersonmollo** [comment]
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240
pdo_sqlsrv.client_buffer_max_kb_size => 10240 => 10240

2017-03-31 14:45 GMT-03:00 ulvii <notifications@github.com>:

**Comment by gersonmollo** [comment]
Sorry,

sqlsrv

sqlsrv support => enabled
ExtensionVer => 4.0.8.0

Directive => Local Value => Master Value
sqlsrv.WarningsReturnAsErrors => On => On
sqlsrv.LogSeverity => 0 => 0
sqlsrv.LogSubsystems => 0 => 0
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240

------------------------------------------------------------------------------------------

pdo_sqlsrv

pdo_sqlsrv support => enabled
ExtensionVer => 4.0.8.0

Directive => Local Value => Master Value
pdo_sqlsrv.log_severity => 0 => 0
pdo_sqlsrv.client_buffer_max_kb_size => 10240 => 10240

2017-03-31 15:32 GMT-03:00 Gerson Mollo <gersonmollo3@gmail.com>:

**Comment by david-puglielli** [comment]
Hi @gersonmollo, the latest version is 4.1.7, found [here](https://github.com/Microsoft/msphpsql/releases/tag/v4.1.7-preview). A number of bugs have been fixed since 4.0.8, please upgrade your drivers and let us know if the error persists.

**Comment by david-puglielli** [comment]
You can also try the PECL install, which will give you the latest version:

`sudo pecl install sqlsrv`
`sudo pecl install pdo_sqlsrv`

**Comment by gersonmollo** [comment]
Problem is still happening

sqlsrv support => enabled
ExtensionVer => 4.1.7-preview

Directive => Local Value => Master Value
sqlsrv.WarningsReturnAsErrors => On => On
sqlsrv.LogSeverity => 0 => 0
sqlsrv.LogSubsystems => 0 => 0
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240

pdo_sqlsrv

pdo_sqlsrv support => enabled
ExtensionVer => 4.1.7-preview

Directive => Local Value => Master Value
pdo_sqlsrv.log_severity => 0 => 0
pdo_sqlsrv.client_buffer_max_kb_size => 10240 => 10240

**Comment by gersonmollo** [comment]
![img_05042017_173342_0](https://cloud.githubusercontent.com/assets/21044233/24726135/abd48b60-1a27-11e7-81bf-d769e71f3d00.png)

SQLSrv:

![img_05042017_173835_0](https://cloud.githubusercontent.com/assets/21044233/24726163/bf7ffa28-1a27-11e7-9695-dbc75845e3f2.png)

PDO:

![img_05042017_174318_0](https://cloud.githubusercontent.com/assets/21044233/24726170/ca562cec-1a27-11e7-8c05-de98c7bb5306.png)

**Comment by gersonmollo** [comment]
SQL:
![img_05042017_175932_0](https://cloud.githubusercontent.com/assets/21044233/24726718/b6ffd150-1a29-11e7-8932-e5a42d49a5e3.png)

SQLSrv:
![img_05042017_173835_0](https://cloud.githubusercontent.com/assets/21044233/24726677/9890410a-1a29-11e7-8db7-e27fbd1afec4.png)

PDO:
![img_05042017_174318_0](https://cloud.githubusercontent.com/assets/21044233/24726684/9ad8c6c6-1a29-11e7-9900-863765cdb550.png)

**Comment by gersonmollo** [comment]
![img_05042017_181105_0](https://cloud.githubusercontent.com/assets/21044233/24727604/fbace2d6-1a2c-11e7-8358-5fe6affa5714.png)
![img_05042017_181816_0](https://cloud.githubusercontent.com/assets/21044233/24727613/01638ad6-1a2d-11e7-8340-94e91f812392.png)
![img_05042017_182209_0](https://cloud.githubusercontent.com/assets/21044233/24727616/03646bc0-1a2d-11e7-847f-529dcce9263d.png)

**Comment by gersonmollo** [comment]
![img_05042017_183556_0](https://cloud.githubusercontent.com/assets/21044233/24728075/d8bd3526-1a2e-11e7-8e4c-222cfe295385.png)

**Comment by alessandro-amelio** [comment]
I've got the same problem as you

**Comment by david-puglielli** [comment]
We are having trouble reproducing this issue. Could you provide a full, self-contained PHP script that reproduces this error? In particular we need to know what connection options you are using and any user-defined functions.

**Comment by gersonmollo** [comment]
<?php


$output = shell_exec('php --ri sqlsrv');
echo "<pre>$output</pre>";

echo "<br>";


$output = shell_exec('php --ri pdo_sqlsrv');
echo "<pre>$output</pre>";


echo "<br>";

echo "<br>";




echo "Content-type: text/html; charset=CP1252<br><br>";


echo "Encoding do .php: Windows 1252<br><br>";





header('Content-type: text/html; charset=CP1252');
//header('Content-Type: text/html; charset=UTF-8');


error_reporting(E_ALL|E_STRICT);
ini_set("display_errors", 1);
//ini_set('default_charset', "");
//ini_set('zend.multibyte', '1');
//ini_set('zend.script_encoding', 'UTF-8');


echo "ECHO PHP: יייייeeeeייייי</br>";

echo "ECHO PHP: יייייeeeeייייי</br>";

echo "ECHO PHP: יייייeeeeייייי</br>";




echo "<pre>";
//var_dump(ini_get('default_charset'));

//var_dump(ini_get('zend.script_encoding'));

//var_dump(ini_get('zend.multibyte'));

echo "</pre>";



echo __DIR__."<br><br>";




$serverName = "localhost";
$connectionOptions = array(
    "Database" => "teste",
    "Uid" => "teste ",
    "PWD" => "teste",    
    'CharacterSet' => SQLSRV_ENC_CHAR,    
);

//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if($conn)
    echo "Connected!";



//mb_http_output( "iso-8859-1" );



//Read Query
$tsql= "EXEC dbo.vo_ListaAplicacao_sp '4', '10051265', '99999999', '30', 'J', '1', '0', '0', '0', '0'";

//$tsql= "EXEC dbo.teste_linux ";

$getResults= sqlsrv_query($conn, $tsql);
echo "<br>$tsql<br>";

//echo ("Reading data from table" . PHP_EOL);
if ($getResults == FALSE)
    die(FormatErrors(sqlsrv_errors()));
while ($row = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC)) {
    echo "<pre>";    
    
    //var_dump($row);

    var_dump(mb_detect_encoding($row['submenu']));    
    var_dump('utf8_decode: '.utf8_decode($row['submenu']));
    var_dump($row['submenu']);
    echo "</pre>";
}


sqlsrv_close($conn);

**Comment by gersonmollo** [comment]
<?php


$output = shell_exec('php --ri sqlsrv');
echo "<pre>$output</pre>";

echo "<br>";


$output = shell_exec('php --ri pdo_sqlsrv');
echo "<pre>$output</pre>";


echo "<br>";

echo "<br>";




echo "Content-type: text/html; charset=CP1252<br><br>";


echo "Encoding do .php: Windows 1252<br><br>";





header('Content-type: text/html; charset=CP1252');
//header('Content-Type: text/html; charset=UTF-8');


error_reporting(E_ALL|E_STRICT);
ini_set("display_errors", 1);
//ini_set('default_charset', "");
//ini_set('zend.multibyte', '1');
//ini_set('zend.script_encoding', 'UTF-8');


echo "ECHO PHP: יייייeeeeייייי</br>";

echo "ECHO PHP: יייייeeeeייייי</br>";

echo "ECHO PHP: יייייeeeeייייי</br>";




echo "<pre>";
//var_dump(ini_get('default_charset'));

//var_dump(ini_get('zend.script_encoding'));

//var_dump(ini_get('zend.multibyte'));

echo "</pre>";



echo __DIR__."<br><br>";




$serverName = "localhost";
$connectionOptions = array(
    "Database" => "teste",
    "Uid" => "teste ",
    "PWD" => "teste",    
    'CharacterSet' => SQLSRV_ENC_CHAR,    
);

//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if($conn)
    echo "Connected!";



//mb_http_output( "iso-8859-1" );



//Read Query
$tsql= "EXEC dbo.vo_ListaAplicacao_sp '4', '10051265', '99999999', '30', 'J', '1', '0', '0', '0', '0'";

//$tsql= "EXEC dbo.teste_linux ";

$getResults= sqlsrv_query($conn, $tsql);
echo "<br>$tsql<br>";

//echo ("Reading data from table" . PHP_EOL);
if ($getResults == FALSE)
    die(FormatErrors(sqlsrv_errors()));
while ($row = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC)) {
    echo "<pre>";    
    
    //var_dump($row);

    var_dump(mb_detect_encoding($row['submenu']));    
    var_dump('utf8_decode: '.utf8_decode($row['submenu']));
    var_dump($row['submenu']);
    echo "</pre>";
}


sqlsrv_close($conn);

**Comment by gersonmollo** [comment]
<?php



$output = shell_exec('php --ri sqlsrv');

echo "<pre>$output</pre>";
echo "<br>";


$output = shell_exec('php --ri pdo_sqlsrv');

echo "<pre>$output</pre>";
echo "<br>";
echo "<br>";


error_reporting(E_ALL|E_STRICT);
ini_set("display_errors", 1);

$serverName = "localhost";
$connectionOptions = array(
    "Database" => "teste",
    "UID" => "teste",
    "PWD" => "teste",
);

/*
-- Collation Default: SQL_Latin1_General_CP1_CI_AS

CREATE proc teste_linux

as
set nocount on
    select teste, 'AUTO ATIVAÇÃO' as teste2, teste+' AUTO ATIVAÇÃO' as teste3 from dbo.sys_testelinux
set nocount off
-- exec teste_linux

*/


$sql= "EXEC dbo.teste_linux";

echo "<h1>SQLSRV</h1>";
//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if($conn)
    echo "Connected!";

$getResults = sqlsrv_query($conn, $sql);

if ($getResults == FALSE) die(FormatErrors(sqlsrv_errors()));

echo "<br>";
var_dump($getResults);
echo "<br>";

$results_rows = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC);

echo "<br>";
var_dump($results_rows);
echo "<br>";

while ($row = $results_rows) {
    echo "<pre>";
    var_dump($row);
    echo "</pre>";
}
sqlsrv_close($conn);


echo "<h1>PDO</h1>";
try {            
            $pdo = new PDO("sqlsrv:Server=".$serverName.";Database=".$connectionOptions['Database'], $connectionOptions['UID'], $connectionOptions['PWD']);
    } catch (PDOException $e) {
            echo "Erro de Conexão " . $e->getMessage() . "\n";
            exit;
    }
      $query = $pdo->prepare($sql);
      $query->execute();
        
        
        while ($row = $query->fetch()) {
            echo "<pre>";
            var_dump($row);
            echo "</pre>";
        }
    
 
      unset($pdo); 
      unset($query);

**Comment by gersonmollo** [comment]
<?php



$output = shell_exec('php --ri sqlsrv');

/*echo "<pre>$output</pre>";
echo "<br>";*/


$output = shell_exec('php --ri pdo_sqlsrv');

/*echo "<pre>$output</pre>";
echo "<br>";
echo "<br>";*/


error_reporting(E_ALL|E_STRICT);
ini_set("display_errors", 1);

$serverName = "localhost";
$connectionOptions = array(
    "Database" => "teste",
    "UID" => "teste",
    "PWD" => "teste",
);

/*
-- Collation Default: SQL_Latin1_General_CP1_CI_AS

CREATE proc teste_linux

as
set nocount on
    select teste, 'AUTO ATIVAÇÃO' as teste2, teste+' AUTO ATIVAÇÃO' as teste3 from dbo.sys_testelinux
set nocount off
-- exec teste_linux

*/


$sql= "EXEC dbo.teste_linux";

/*echo "<h1>SQLSRV</h1>";*/
//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if($conn)
/*    echo "Connected!";*/

$getResults = sqlsrv_query($conn, $sql);

if ($getResults == FALSE) die(FormatErrors(sqlsrv_errors()));

/*echo "<br>";
var_dump($getResults);
echo "<br>";*/

$results_rows = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC);

/*echo "<br>";
var_dump($results_rows);
echo "<br>";*/

while ($row = $results_rows) {
/*    echo "<pre>";
    var_dump($row);
    echo "</pre>";*/
}
sqlsrv_close($conn);


/*echo "<h1>PDO</h1>";*/
try {            
            $pdo = new PDO("sqlsrv:Server=".$serverName.";Database=".$connectionOptions['Database'], $connectionOptions['UID'], $connectionOptions['PWD']);
    } catch (PDOException $e) {
            /*echo "Erro de Conexão " . $e->getMessage() . "\n";
            exit;*/
    }
      $query = $pdo->prepare($sql);
      $query->execute();
        
        
        while ($row = $query->fetch()) {
        /*    echo "<pre>";
            var_dump($row);
            echo "</pre>";*/
        }
    
 
      unset($pdo); 
      unset($query);

**Comment by gersonmollo** [comment]
<?php

$output = shell_exec('php --ri sqlsrv');

$output = shell_exec('php --ri pdo_sqlsrv');

error_reporting(E_ALL|E_STRICT);
ini_set("display_errors", 1);

$serverName = "localhost";
$connectionOptions = array(
    "Database" => "teste",
    "UID" => "teste",
    "PWD" => "teste",
);

/*
-- Collation Default: SQL_Latin1_General_CP1_CI_AS

CREATE proc teste_linux

as
set nocount on
    select teste, 'AUTO ATIVAÇÃO' as teste2, teste+' AUTO ATIVAÇÃO' as teste3 from dbo.sys_testelinux
set nocount off
-- exec teste_linux

*/


$sql= "EXEC dbo.teste_linux";

/*echo "<h1>SQLSRV</h1>";*/
//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if($conn)
/*    "Connected!";*/

$getResults = sqlsrv_query($conn, $sql);

if ($getResults == FALSE) die(FormatErrors(sqlsrv_errors()));

$results_rows = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC);


while ($row = $results_rows) {
    var_dump($row);
}
sqlsrv_close($conn);


/*echo "<h1>PDO</h1>";*/
try {            
            $pdo = new PDO("sqlsrv:Server=".$serverName.";Database=".$connectionOptions['Database'], $connectionOptions['UID'], $connectionOptions['PWD']);
    } catch (PDOException $e) {
            exit;
    }
      $query = $pdo->prepare($sql);
      $query->execute();
        
        
        while ($row = $query->fetch()) {
            var_dump($row);
        }
    
 
      unset($pdo); 
      unset($query);

**Comment by gersonmollo** [comment]
$output = shell_exec('php --ri sqlsrv');

echo "<pre>$output</pre>";
echo "<br>";


$output = shell_exec('php --ri pdo_sqlsrv');

echo "<pre>$output</pre>";
echo "<br>";
echo "<br>";


error_reporting(E_ALL|E_STRICT);
ini_set("display_errors", 1);

$serverName = "localhost";
$connectionOptions = array(
    "Database" => "teste",
    "UID" => "teste",
    "PWD" => "teste",
);

/*
-- Collation Default: SQL_Latin1_General_CP1_CI_AS

CREATE proc teste_linux

as
set nocount on
    select teste, 'AUTO ATIVAÇÃO' as teste2, teste+' AUTO ATIVAÇÃO' as teste3 from dbo.sys_testelinux
set nocount off
-- exec teste_linux

*/


$sql= "EXEC dbo.teste_linux";

echo "<h1>SQLSRV</h1>";
//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if($conn)
    echo "Connected!";

$getResults = sqlsrv_query($conn, $sql);

if ($getResults == FALSE) die(FormatErrors(sqlsrv_errors()));

echo "<br>";
var_dump($getResults);
echo "<br>";

$results_rows = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC);

echo "<br>";
var_dump($results_rows);
echo "<br>";

while ($row = $results_rows) {
    echo "<pre>";
    var_dump($row);
    echo "</pre>";
}
sqlsrv_close($conn);


echo "<h1>PDO</h1>";
try {            
            $pdo = new PDO("sqlsrv:Server=".$serverName.";Database=".$connectionOptions['Database'], $connectionOptions['UID'], $connectionOptions['PWD']);
    } catch (PDOException $e) {
            echo "Erro de Conexão " . $e->getMessage() . "\n";
            exit;
    }
      $query = $pdo->prepare($sql);
      $query->execute();
        
        
        while ($row = $query->fetch()) {
            echo "<pre>";
            var_dump($row);
            echo "</pre>";
        }
    
 
      unset($pdo); 
      unset($query);

**Comment by gersonmollo** [comment]
$output = shell_exec('php --ri sqlsrv');

echo "<pre>$output</pre>";
echo "<br>";


$output = shell_exec('php --ri pdo_sqlsrv');

echo "<pre>$output</pre>";
echo "<br>";
echo "<br>";


error_reporting(E_ALL|E_STRICT);
ini_set("display_errors", 1);

$serverName = "localhost";
$connectionOptions = array(
    "Database" => "teste",
    "UID" => "teste",
    "PWD" => "teste",
);

/*
-- Collation Default: SQL_Latin1_General_CP1_CI_AS

CREATE proc teste_linux

as
set nocount on
    select teste, 'AUTO ATIVAÇÃO' as teste2, teste+' AUTO ATIVAÇÃO' as teste3 from dbo.sys_testelinux
set nocount off
-- exec teste_linux

*/


$sql= "EXEC dbo.teste_linux";

echo "<h1>SQLSRV</h1>";
//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if($conn)
    echo "Connected!";

$getResults = sqlsrv_query($conn, $sql);

if ($getResults == FALSE) die(FormatErrors(sqlsrv_errors()));

echo "<br>";
var_dump($getResults);
echo "<br>";

$results_rows = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC);

echo "<br>";
var_dump($results_rows);
echo "<br>";

while ($row = $results_rows) {
    echo "<pre>";
    var_dump($row);
    echo "</pre>";
}
sqlsrv_close($conn);


echo "<h1>PDO</h1>";
try {            
            $pdo = new PDO("sqlsrv:Server=".$serverName.";Database=".$connectionOptions['Database'], $connectionOptions['UID'], $connectionOptions['PWD']);
    } catch (PDOException $e) {
            echo "Erro de Conexão " . $e->getMessage() . "\n";
            exit;
    }
      $query = $pdo->prepare($sql);
      $query->execute();
        
        
        while ($row = $query->fetch()) {
            echo "<pre>";
            var_dump($row);
            echo "</pre>";
        }
    
 
      unset($pdo); 
      unset($query);

**Comment by gersonmollo** [comment]
$output = shell_exec('php --ri sqlsrv');

$output = shell_exec('php --ri pdo_sqlsrv');

error_reporting(E_ALL|E_STRICT);
ini_set("display_errors", 1);

$serverName = "localhost";
$connectionOptions = array(
    "Database" => "teste",
    "UID" => "teste",
    "PWD" => "teste",
);

/*
-- Collation Default: SQL_Latin1_General_CP1_CI_AS

CREATE proc teste_linux

as
set nocount on
    select teste, 'AUTO ATIVAÇÃO' as teste2, teste+' AUTO ATIVAÇÃO' as teste3 from dbo.sys_testelinux
set nocount off
-- exec teste_linux

*/


$sql= "EXEC dbo.teste_linux";

SQLSRV
//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if($conn)
    echo "Connected!";

$getResults = sqlsrv_query($conn, $sql);

if ($getResults == FALSE) die(FormatErrors(sqlsrv_errors()));

var_dump($getResults);

$results_rows = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC);

var_dump($results_rows);

while ($row = $results_rows) {
    var_dump($row);
}
sqlsrv_close($conn);


PDO
try {            
            $pdo = new PDO("sqlsrv:Server=".$serverName.";Database=".$connectionOptions['Database'], $connectionOptions['UID'], $connectionOptions['PWD']);
    } catch (PDOException $e) {
            "Erro de Conexão " . $e->getMessage() . "\n";
            exit;
    }
      $query = $pdo->prepare($sql);
      $query->execute();
        
        
        while ($row = $query->fetch()) {
            var_dump($row);
        }
    
 
      unset($pdo); 
      unset($query);

**Comment by meet-bhagdev** [comment]
Thanks @gersonmollo, we will look into this 👍

**Comment by david-puglielli** [comment]
@gersonmollo, could you set the encoding to UTF-8 in the connection string (add 'CharacterSet'=>'UTF-8' to your $connectionOptions array) and tell us what you get?

**Comment by gersonmollo** [comment]
Thank you, it worked :)

**Comment by ulvii** [comment]
That's great :) Feel free to re-open the issue if you still have questions.
