### ISSUE TITLE
Constantly get error 08S01 (Error code 0x2714)

### ISSUE THREAD

**Issue by rodrigopedra** [Microsoft/msphpsql#365]
Hi,

When running long queries (that take longer than 30s) I am constantly getting the following error:

`08S01 - SQLSTATE[08S01]: [Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2714`

I am running Ubuntu 16.04.2 LTS, php 7.1 (fpm) an tried with the following driver versions:

- 4.0.8 (stable)
- 4.1.7 (preview)
- 4.1.8 (preview)

I also tried running the query with and without the PDO arttributes below, according to the ones available in this link: https://docs.microsoft.com/en-us/sql/connect/php/pdo-setattribute

- `PDO::SQLSRV_ATTR_QUERY_TIMEOUT` (increased to 600, I know the default is no timeout)
- `PDO::SQLSRV_ATTR_CLIENT_BUFFER_MAX_KB_SIZE` (increased to 40MB)

The query is a simple `Insert...Select` with about 400-500K rows as follow:

```
INSERT INTO PORTAL.dbo.SKIP_ORIGEM_TELEFONE_ENRIQUECIMENTO (
       [IdCliente]
      ,[Identificador]
      ,[CPF]
      ,[Id]
      ,[DDD]
      ,[Telefone]
      ,[DataCriacao])
SELECT [IdCliente]
      ,[Identificador]
      ,[CPF]
      ,[Id]
      ,COALESCE([DDD],0)
      ,COALESCE([Telefone],0)
      ,CONVERT(SMALLDATETIME, [DataCriacao], 102) AS [DataCriacao]
  FROM PORTAL.dbo.SKIP_ORIGEM_TELEFONE_ENRIQUECIMENTO_959 WITH(NOLOCK)
```

The SQL Version used is shown below (`IP` and `username` are hidden):

```
sqlcmd -S <ip-address> -U <username>
1> select @@version;
2> go

----------------------------------------------------------------------------------------------
Microsoft SQL Server 2014 (SP2-GDR) (KB3194714) - 12.0.5203.0 (X64)
        Sep 23 2016 18:13:56
        Copyright (c) Microsoft Corporation
        Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)


(1 rows affected)
```

Thanks in advance for any help.

EDIT:

Running the above query directly through `sqlcmd` works fine.

**Comment by ulvii** [comment]
Hi @rodrigopedra,
I was not able to reproduce the issue with `$conn->query()` and **php-cli.**
To help us reproduce, could you provide more details?
1. PHP script that executes the query.
2. Table column data types - `CREATE TABLE` query.
3. Which WebServer are you using? (Apache, Nginx, ...)

**Comment by rodrigopedra** [comment]
Hi,

Never mind. After further investigation the query was being executed through a queued job using beanstalked and the job was timing out.  After forcing a longer timeout it worked.

Sorry for any inconveniences.

**Comment by Gr33nLight** [comment]
hey @rodrigopedra hope I'm not bothering you, but I'm facing the same error on a laravel application. This application connectes to a SQL server. To fix the issue do I have to check on the SQL server for a timeout setting, or on the client system where laravel is running? 
Thanks

**Comment by rodrigopedra** [comment]
Hi @Gr33nLight , I increased the timeout in the Laravel Job and it fixed the issue I was having.

Depending of the Laravel version you are using you just have to add a `protected $timeout = 180;` to the job that connects to SQL Server that it will override the default queue timeout.

180 seconds worked for me, but you can try a different value.

**Comment by Gr33nLight** [comment]
Hey @rodrigopedra thanks for that suggestion. Howere your solution seems to not work in my case. This is because I'm not using a Job class, but a class that extends Facade.
 Inside this class, in the getInstance method, I create a connection with PDO method of PHP and the sqlsrv driver in the connection string.
And that error is relative to where I call the execute() on the query after calling the prepare(). The weird thing is that this happens randomly and not on a fixed query.

for example

$link = new PDO('sqlsrv:Server=' . $result->end_server . ',1433;Database=' . $result->end_database,$result->user,$result->password)
$child_result = $link->prepare($sql);
if ($child_result->execute()) {
.....
}

The prepare and execute is under a foreach loop so its executed multiple times

**Comment by Gr33nLight** [comment]
Hey @rodrigopedra fixed the issue there was an issue on the server sql because it was getting database tables from an access file so it wasn't a normal MSSQL connection

**Comment by rodrigopedra** [comment]
Hi @Gr33nLight , you could try to increase the timeout in the connection, and if your php server runs on windows enabel the connection pooling. Connection pooling does not work weel in linux with  unixODBC < 2.3.6 (as per release notes).

````php
// in your config/database.php


    'connections' => [
        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'appname'  => 'webapp', // useful to identify your app in Sql Server Processes
            'pooling'  => false, // enable if in windows
            'port'     => 1433,
            'options'  => [
                PDO::SQLSRV_ATTR_QUERY_TIMEOUT => 300, // timeout in seconds
                PDO::ATTR_PERSISTENT => true, // try to enable this value, but the timeout should suffice
            ],
        ],
],


````
