### ISSUE TITLE
MERGE statement with OUTPUT does not return data

### ISSUE THREAD

**Issue by radekhulan** [Microsoft/msphpsql#366]
In sama case, MERGE statement with OUTPUT clause will not return data in PHP SQLSRV driver for SQL statements that work well in other environments.

- Driver Version: 4.1.8.9607
- OS Version and Distro: Windows 10, SQL SRV 2016

Steps to Reproduce:

1. run SQL is SSMS, will return "1" as result
2. run it in PHP, will not return anything

--------------------

`<?php

$db = new PDO("sqlsrv:server=localhost; Database=dbname");

$q = $db->query("DROP TABLE IF EXISTS dbo.tmp;
CREATE TABLE dbo.tmp (uid INT IDENTITY(1,1), cislo INT, datum DATETIME);

DECLARE @result TABLE (cislo INT);
MERGE dbo.tmp as target USING (SELECT 1 as cislo) as source
ON target.cislo = source.cislo
WHEN NOT MATCHED THEN
	INSERT (cislo,datum) VALUES (source.cislo,GETUTCDATE())
WHEN MATCHED THEN
	UPDATE SET datum = GETUTCDATE()
OUTPUT inserted.uid INTO @result;

SELECT * FROM @result;");

// this should return [cislo:1], but will return nothing
echo "MERGE result\n";
$data = $q->fetch(PDO::FETCH_ASSOC);
print_r($data);

// this will return identity column (1)
echo "\n\nIDENTITY\n";
print_r($db->lastInsertId());

?>`

**Comment by meet-bhagdev** [comment]
@radekhulan Thanks for the detailed repro and info 👍  We will look into this

**Comment by radekhulan** [comment]
This is result in SSMS:
http://mywebdesign.cz/tmp/result_ssms.PNG

In PHP, the result is empty.

**Comment by ulvii** [comment]
Hi @radekhulan ,
Your query puts the result into `@result`. You need to call `$q->nextRowset();` before `$data = $q->fetch(PDO::FETCH_ASSOC);` to advance to the next result set. More information here: https://docs.microsoft.com/en-us/sql/connect/php/pdostatement-nextrowset

Please let me know if it resolves the issue.

**Comment by radekhulan** [comment]
Of course, it works.

Thank you a lot! :-)
