### ISSUE TITLE
Cannot install on macOS (10.12.4)

### ISSUE THREAD

**Issue by mreuter** [Microsoft/msphpsql#368]
When trying to do the install on macOS as described in the docs, I get the following error messages when installing the drivers:

Cannot install pecl/pdo_sqlsrv on darwin operating system, can only install on linux
No valid packages found
install failed

Cannot install pecl/sqlsrv on darwin operating system, can only install on linux
No valid packages found
install failed

**Comment by meet-bhagdev** [comment]
@mreuter Can you try specifying a version?
pecl install pdo_sqlsrv-4.1.8preview
pecl install sqlsrv-4.1.8preview

**Comment by mreuter** [comment]
That worked. Thank you!
