### ISSUE TITLE
no reference to secure connections in documentation

### ISSUE THREAD

**Issue by beechit** [Microsoft/msphpsql#369]
Hi,
I read the documentation but i can't  find a reference how this package works with a secure connection to mssql (ssl).

is this supported and does this package need to validate the certificates when connection, or is it just connection to a secure port.

**Comment by ulvii** [comment]
Hi,

You can read about connection options here: https://docs.microsoft.com/en-us/sql/connect/php/connection-options

The keyword you are looking for is `Encrypt`. When this flag is set to true, SQL Server uses SSL encryption for all data sent between the client and server if the server has a certificate installed. 

Below are the example connection strings:

**SQLSRV:** 

`$conn = sqlsrv_connect(  "server",  array("UID" => "myusername", "PWD" => "mypassword", "Database"=>"database", "Encrypt"=>true )`

**PDO_SQLSRV:**

`$conn = new PDO( "sqlsrv:Server=server;Database=database;Encrypt=true;", "myusername", "mypassword" );`
 
Please let me know, if you need any further clarifications.

**Comment by meet-bhagdev** [comment]
@beechit Let us know if this works. Closing the issue for now. Feel free to re-open it if you still need help.
