### ISSUE TITLE
"An invalid PHP type for parameter 2 was specified." caused by changing SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_BINARY)

### ISSUE THREAD

**Issue by johanneskonst** [Microsoft/msphpsql#372]
So, i'm a bit at a loss...

I've got a big application based on ZF1 that's using SQLSRV as backend, and when trying to store binary data i got the "An invalid PHP type for parameter 2 was specified" error, which is in the SQLSRV_PHPTYPE_ bit. Upon investigating more i dicovered that the _value_ of SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_BINARY) changes depending on when or where it is being called, which seems quite odd since i expect it to be constant. The main question(s) i have now is where do i solve this bug? Is it something that's faulty in the extension, or is it expected behaviour, should it be solved in my app or in ZF1/ZF2? The weird thing is when stripping down all fluff i do get a working bit of code but anything else just fails with the invalid type error...

- Driver versions 4.1.6/4.1.7-preview/4.1.8-preview
- Windows 8/10/Server 2k12/Server 2k16
- SQL is remote, can connect with sqlcmd/php/other tools
- PHP 7.0 x86/7.1 x86/7.0 x64/7.1 x61, all NTS MSVC14
- Table schema in in the file below

**Comment by johanneskonst** [comment]
[sqlsrv-test.php.txt](https://github.com/Microsoft/msphpsql/files/954588/sqlsrv-test.php.txt)

**Comment by yitam** [comment]
hi @johanneskonst I'm not sure I understand the problem. 

Note that SQLSRV_ENC_BINARY is a constant (the string "binary") but not SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_BINARY). Running your script in 64-bit shows 516 and in 32-bit it's a big negative number.

Yet, putting SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_BINARY) aside, I ran the script you provided and didn't get the "invalid PHP type for parameter 2" error. The values are successfully stored in the database table. 

Perhaps you can tell us when exactly you get this error? When fetching data?

**Comment by johanneskonst** [comment]
Hello @yitam 

the script provided is only to show the different results i get when var_dump'ing the `SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_BINARY)` bit.

I know `SQLSRV_PHPTYPE_STRING` is not a constant but a function, yet when var_dump'ing it a few times in a row (like in the provided script) i expect to get the same result each time, which i _don't_ get.

I not only get 516 (like you said, because we run x64) but also 67109380, 234881540 and 1895825924. And **that** (I think) is the underlying problem for my "invalid PHP type" error.

When you ran it, did it always print 516 for you? If so, could you tell me your setup (platform, phpversion, extensionversion, etc?)

I can provide a working example but that would require me to upload some 30+ megabytes of PHP code and a 12MB installation manual which (i think) is not only overkill but would also deflect from the core 'problem' ;-)

Regards,

**Comment by yitam** [comment]
hi @johanneskonst yes I do get the same big negative number whenever I run in 32 bit and 516 in 64 bit... 

I'm running Windows 10 Enterprise and using sqlsrv version is 4.1.8 preview, I've tested on SQL Server 2016 and 2014, PHP 7.0 (32 bit) NTS and PHP 7.1 (64 bit) NTS

Let's put this aside for now and focus on the error that you encountered. So you said it occurs during insert? Is it consistent or intermittent? 

I tested with your script and have inserted ten rows straight without any problem. In fact, I ran the test again and again today, no sweat. Do you have other input data that we can test?

**Comment by akrabat** [comment]
I'm seeing this same problem.

**Comment by yitam** [comment]
hi @akrabat it will help us if you can provide a repro script / steps to reproduce the problem. Also, please clarify what problem that you're seeing. I suppose you meant you saw the "An invalid PHP type for parameter 2 was specified" error?

**Comment by akrabat** [comment]
Yes. I'm seeing `An invalid PHP type for parameter 6 was specified`.

I'm still confirming, but I'm pretty sure that this is because ZF1's code converts the `$params` array to references.

https://github.com/zendframework/zf1/blob/master/library/Zend/Db/Statement/Sqlsrv.php#L190-L199

**Comment by akrabat** [comment]
Yes - referenced parameters cause the problem. Test code:

```php
<?php

echo '<pre>';

$db = sqlsrv_connect("WIN202.windsor.local\WINDSORSQL", [
    'UID' => "Online_Test",
    'PWD' => "Cromwell2012",
    'CharacterSet' => 'UTF-8',
    'Database' => 'Shoot_DEV',
    'ReturnDatesAsStrings' => true,
    'MultipleActiveResultSets' => true
]);


$sql = "UPDATE files set file_contents = ? WHERE id = 2";

$blob = file_get_contents(__DIR__ . '/test.pdf');
$params = [
    [
        $blob,
        SQLSRV_PARAM_IN,
        SQLSRV_PHPTYPE_STREAM(SQLSRV_ENC_BINARY),
        SQLSRV_SQLTYPE_VARBINARY('max'),
    ]
];

$convertToReferences = $_GET['refs'] ?? true;
if ((bool)$convertToReferences) {
    echo "Using referenced parameters\n";
    // make all params passed by reference
    $params_ = array();
    $temp    = array();
    $i       = 1;
    foreach ($params as $param) {
        $temp[$i]  = $param;
        $params_[] = &$temp[$i];
        $i++;
    }
    $params = $params_;
}

$statement = sqlsrv_query($db, $sql, $params);

if (!$statement) {
    echo "ERROR: " . PHP_EOL;
    var_dump(sqlsrv_errors());
    exit;
}

echo "SUCCESS"  . PHP_EOL;
```

Output when using converting to referenced parameters:

```
Using referenced parameters
ERROR: 
array(1) {
  [0]=>
  array(6) {
    [0]=>
    string(5) "IMSSP"
    ["SQLSTATE"]=>
    string(5) "IMSSP"
    [1]=>
    int(-16)
    ["code"]=>
    int(-16)
    [2]=>
    string(50) "An invalid PHP type for parameter 0 was specified."
    ["message"]=>
    string(50) "An invalid PHP type for parameter 0 was specified."
  }
}
```

**Comment by yitam** [comment]
Thanks @akrabat for your prompt responses. We will do some investigation and get back to you. Thanks.

**Comment by akrabat** [comment]
FWiW, The `sqlsrv` extension is version `4.0.8429.1` according to phpinfo.

**Comment by Hadis-Fard** [comment]
@akrabat what is the type of `files` column in that you are updating and the content of the test.pdf? 
note  that you don't need to mark parameters by reference for _input_ parameters, that's only the case for output or inout parameters where you need to get the value back, and in that case you just need to pass the array by reference and not the elements of the array.

**Comment by Hadis-Fard** [comment]
@akrabat a side note, we have had several [releases ](https://github.com/Microsoft/msphpsql/releases) since  4.0.* release with many bug fixes and cool features, you can see the list of fixes & features in the [changelog](https://github.com/Microsoft/msphpsql/blob/dev/CHANGELOG.md), I'd recommend to update to the latest release.

**Comment by akrabat** [comment]
@Hadis-Fard:

* The `file_contents` column is defined as `varbinary(MAX)`.
* test.pdf attached

[test.pdf](https://github.com/Microsoft/msphpsql/files/1001747/test.pdf)

**Comment by akrabat** [comment]
@Hadis-Fard In terms of releases, updates are applied by the client's IT department which used this URL: https://www.microsoft.com/en-us/download/details.aspx?id=20098

Is there a better URL to use that's on a microsoft.com domain that they should be using to get updates?

**Comment by akrabat** [comment]
> note that you don't need to mark parameters by reference for input parameters, that's only the case for output or inout parameters where you need to get the value back, and in that case you just need to pass the array by reference and not the elements of the array.

This [code](https://github.com/zendframework/zf1/blob/master/library/Zend/Db/Statement/Sqlsrv.php#L190-L199) was last touched over 5 years ago, so I'm not totally surprised that it needs updating :)  It's part of framework that's EOL though, so currently working out how to update it safely

**Comment by akrabat** [comment]
Suggested update to my test case:

Change:
```php
if ((bool)$convertToReferences) {
    echo "Using referenced parameters\n";
    // make all params passed by reference
    $params_ = array();
    $temp    = array();
    $i       = 1;
    foreach ($params as $param) {
        $temp[$i]  = $param;
        $params_[] = &$temp[$i];
        $i++;
    }
    $params = $params_;
}
``` 

to

```php
if ((bool)$convertToReferences) {
    echo "Using referenced parameters\n";
    // make all OUT or INOUT params passed by reference
    $params_ = array();
    $temp    = array();
    $i       = 1;
    foreach ($params as $param) {
        $temp[$i]  = $param;
        if (is_array($param) && in_array($param[1], [SQLSRV_PARAM_OUT, SQLSRV_PARAM_INOUT])) {
            $params_[] = &$temp[$i];
        } else {
            $params_[] = $temp[$i];
        }

        $i++;
    }
    $params = $params_;
}
```

i.e. only make the OUT or INOUT parameters references in the array. However I'm unsure if even this  is needed given @Hadis-Fard's comment above.

**Comment by yitam** [comment]
Hi @akrabat 

The following should work for your scenario:

```
$sql = "UPDATE files set file_contents = ? WHERE id = 2";

$blob = file_get_contents(__DIR__ . '/test.pdf');
$params = [
    [
        $blob,
        SQLSRV_PARAM_IN,
        SQLSRV_PHPTYPE_STREAM(SQLSRV_ENC_BINARY),
        SQLSRV_SQLTYPE_VARBINARY('max'),
    ]
];

$statement = sqlsrv_query($db, $sql, $params);

if (!$statement) {
    echo "ERROR: " . PHP_EOL;
    var_dump(sqlsrv_errors());
    exit;
}

echo "SUCCESS"  . PHP_EOL;
```

For your information, there are some more examples in Microsoft [docs](https://docs.microsoft.com/en-us/sql/connect/php/how-to-perform-parameterized-queries).

> Is there a better URL to use that's on a microsoft.com domain that they should be using to get updates?

Please feel free to check our [releases ](https://github.com/Microsoft/msphpsql/releases) here on GitHub or you can download the Dlls on [PECL](https://pecl.php.net/package/sqlsrv)

Hope this helps :)

**Comment by akrabat** [comment]
Thanks @yitam What would the code look like if `file-contents` was an INOUT parameter?

**Comment by Hadis-Fard** [comment]
@akrabat the update you have applied in 
>Suggested update to my test case:

should work

**Comment by yitam** [comment]
Hi @akrabat , something like this

```
$params = [
    [
        &$blob,
        SQLSRV_PARAM_INOUT,
        SQLSRV_PHPTYPE_STREAM(SQLSRV_ENC_BINARY),
        SQLSRV_SQLTYPE_VARBINARY('max'),
    ]
];
```

Please also take a look at these examples on MS Docs:

[Retrieve Output Parameters](https://docs.microsoft.com/en-us/sql/connect/php/how-to-retrieve-output-parameters-using-the-sqlsrv-driver)
[Retrieve I/O Parameters](https://docs.microsoft.com/en-us/sql/connect/php/how-to-retrieve-input-and-output-parameters-using-the-sqlsrv-driver)

**Comment by akrabat** [comment]
Thanks for your help

**Comment by Hadis-Fard** [comment]
@johanneskonst Do you still have issue with `SQLSRV_PHPTYPE_STRING`?

**Comment by akrabat** [comment]
For what it's worth, this is my write up of how handler to handle this problem with Zend Framework 1: https://akrabat.com/inserting-binary-data-into-sql-server-with-zf1-php-7/

**Comment by yitam** [comment]
Glad to know that it's working for you @akrabat. If you encounter any problem, please create a new issue as we have digressed from the original problem @johanneskonst raised.

@johanneskonst please let us know if you still have problem.

**Comment by yitam** [comment]
@johanneskonst we are going to close this due to inactivity. Please feel free to reopen this or create a new issue.
