### ISSUE TITLE
sqlsrv output param shows garbage when the variable is initialized to a different type

### ISSUE THREAD

**Issue by yitam** [Microsoft/msphpsql#378]
Tested in Windows, 32bit and 64bit, both NTS. 
First, create a simple stored procedure like this
```
create proc test_out @p1 integer, @p2 integer, @p3 integer output
as
begin
	select @p3 = @p1 + @p2
	print @p3
end
go
```

Then, in the script, set warnings return as errors then initialize the output param to a non-integer as shown below:

```
sqlsrv_configure( 'WarningsReturnAsErrors', true );

$v1 = 1;
$v2 = 2;
$v3 = 'str';

$stmt = sqlsrv_query( $conn, "{call test_out( ?, ?, ? )}", array( $v1, $v2, array( &$v3, SQLSRV_PARAM_OUT )));
 
echo "Output: $v3\n";
```

The output is ```Output: 3``` followed by lots of garbage.

To fix this issue, simply do the following:
```sqlsrv_configure( 'WarningsReturnAsErrors', false );```

Then we will get ```Output: 3```, as expected.

**Comment by Hadis-Fard** [comment]
Fixed in in PR #381
