### ISSUE TITLE
PHP process crash

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#39]
We experience PHP process crash and believe that the reason is SQL Server
driver. The driver is used for Drupal 7 installation and the only way to
reproduce it is to issue massive parallel requests while Drupal is clearing
its cache. We were trying to explore the problem as deep as possible with
xebug tracing to get the last PHP function call before the crash and to get
native functions backtrace with Debug Diagnostics Tool as described on the [
PHP documentation ](https://bugs.php.net/bugs-generating-backtrace-win32.php)
. Results are the following:  
- Each xdebug trace of the crashed request ends with PDOStatement->execute() called for the insert query. 
- Native crash analysis reports about "the assembly instruction at php5!_efree+6a in C:\PHP\php5.dll from The PHP Group has caused an access violation exception (0xC0000005) when trying to read from memory location 0x00000000 on thread 0".  

I'm attaching user dump analysis results produced by Debug Diagnostics Tool.
Stack trace looks not resolved probably because of missing debug pack files
for the SQL Server driver. If someone could help me to properly resolve the
stack trace it would be really great.  

If you need more details, please feel free to ask.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 22428](http://sqlsrvphp.codeplex.com/workitem/22428)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Apr 2 at 9:31 AM
**Reported by:**    DmitriyTrt
**Updated on:** Apr 2 at 9:32 AM
**Updated by:** DmitriyTrt
#### Binary Attachments

[php-cgi__PID__181280__Date__04_02_2014__Time_01_00_47AM__868__Second_Chance_Exception_C0000005_CrashHangAnalysis (1).mht](http://sqlsrvphp.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=sqlsrvphp&WorkItemId=22428&FileAttachmentId=821872)
[php-cgi__PID__234608__Date__04_02_2014__Time_03_53_52PM__739__Second_Chance_Exception_C0000005_CrashHangAnalysis.mht](http://sqlsrvphp.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=sqlsrvphp&WorkItemId=22428&FileAttachmentId=821873)

**Comment by meet-bhagdev** [comment]
@DmitriyTrt, do you still have this issue? If so can you help provide us out with a repro script? We are not able to repro the following:

- Native crash analysis reports about "the assembly instruction at php5!_efree+6a in C:\PHP\php5.dll from The PHP Group has caused an access violation exception (0xC0000005) when trying to read from memory location 0x00000000 on thread 0".

**Comment by DmitriyTrt** [comment]
We don't experience this crash anymore, I believe it disappeared after some SQL Server driver update.
