### ISSUE TITLE
The drivers are not working.

### ISSUE THREAD

**Issue by mohammadjouhari** [Microsoft/msphpsql#404]
Hi,

I hvae used the both dll. The drivers are not working in PHP 7. When the full version will be released ?

**Comment by meet-bhagdev** [comment]
@mohammadjouhari What error are you running into?

**Comment by mohammadjouhari** [comment]
Thnaks I mannaged to get it working, I downloaded the pdo_sqlsrv_7.0 from another source.

**Comment by Hadis-Fard** [comment]
Glad to hear you got it fixed, I recommend to get the latest drivers from [releases page](https://github.com/Microsoft/msphpsql/releases), or [PDO_SQLSRV  PECL page](https://pecl.php.net/package/pdo_sqlsrv/4.2.0preview/windows), and if you faced the issues again please check the php.ini file and make sure the extension name and dll name match.
