### ISSUE TITLE
[question] Is it possible to get tag 3.2 working for PHP 5.6 (in Debian)?

### ISSUE THREAD

**Issue by boywijnmaalen** [Microsoft/msphpsql#405]
Hi,

I would like to get sqlsrv/pdo_sqlsrv working on PHP 5.6. 
I got unixODBC 2.3.1 and ODBC Driver 13 in place so far (maybe I need 11 for this to work anyway, not sure). 

I had a close look at [tag v3.2.0.0](https://github.com/Microsoft/msphpsql/archive/v3.2.0.0.tar.gz) because I wanted to compile it manually (as pecl doesn't have a build for 3.2). Turns out it is windows only (judging from the config.w32 file rather than the .m4 file). 

I'm gonna reach now but would it be 'as easy' as rewriting the .w32 config file to .m4 format? If not (which I'm guessing) what would be my best alternative?

My issue is that I want my software to be the same across PHP 5.6/7.0/7.1 (in de mssql context I mean). By default I'm working on PHP7 so I'm using the [sqlsrv functions](http://nl1.php.net/manual/en/book.sqlsrv.php), in PHP 5.6 however that gives me not much joy.

My main goal is to get sqlsrv/pdo_sqlsrv working on PHP 5.6 (on debian). If tag v3.2.0.0 is not the way to go, correct me!

All feedback/suggestions/tips are welcome!

Thanks!

**Comment by meet-bhagdev** [comment]
@boywijnmaalen The PHP Drivers for Linux are compatible with PHP 7 and above. We did not have enough interest from developers on this repository for supporting the older version of PHP. I am closing this as won't fix. If we have more interest for this, I am more than happy to make this happen 👍
