### ISSUE TITLE
Where to find non-prerelease versions for PHP 7.0 or 7.1?

### ISSUE THREAD

**Issue by akrabat** [Microsoft/msphpsql#409]
Looking at https://github.com/Microsoft/msphpsql/releases, they are all marked pre-release. Where do I find a production ready versions for PHP 7.0 and PHP 7.1 for Windows?

**Comment by v-kaywon** [comment]
Hi @akrabat , https://github.com/Microsoft/msphpsql/releases/tag/v4.0-RTW is the lastest RTW release for Windows with PHP 7.0 support. 5.0-RTW driver is anticipated to be released in late July or early August, which supports both PHP 7.0 and 7.1. Furthermore, all of our pre-release versions have been tested in our test lab thus feel free to use them as well.

**Comment by akrabat** [comment]
Thanks.
