### ISSUE TITLE
SQL Server supports a maximum of 2100 parameters

### ISSUE THREAD

**Issue by rodineijf** [Microsoft/msphpsql#410]
I have a centos server running php 7.1.5 and pdo_sqlsrv 4.0.8.0.
I'm trying to insert 1000 rows at the same time and getting this error: 
Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters

I'm also have an ubuntu 16.04 machine with php 7.0.15 and pdo_sqlsrv 4.0.5.0, executing the same script and got no errors.

**Comment by v-kaywon** [comment]
Hi @rodineijf , are you binding a lot of parameters to your statement? (as explained in the error, SQL Server only supported 2100 parameters). If you are binding a lot of parameters, you can try to use emulate_prepare option (https://github.com/Microsoft/msphpsql/wiki/Features#emulate-prepare-in-pdo_sqlsrv-driver), which does the binding in the client side instead of using SQL Server.

**Comment by v-kaywon** [comment]
@rodineijf , could you provide us with more information? How many parameters are you binding? What is the table schema? Which version of SQL server are you using? It would be best if you can provide us a repro script. :)

**Comment by Hadis-Fard** [comment]
@rodineijf We have had several bug fixes since 4.0.8 release, could you try your script with our latest [release](https://github.com/Microsoft/msphpsql/releases)?

**Comment by rodineijf** [comment]
`[Mon May 29 15:47:41.183963 2017] [php7:notice] [pid 10551] [client 201.21.41.254:51381] Slim Application Error:\nType: Illuminate\\Database\\QueryException\nCode: IMSSP\nMessage: SQLSTATE[IMSSP]: Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters. (SQL: insert into [controleTrafego] ([data], [dataSincronizacao], [idtrecho], [idveiculo], [sentido], [timestamp], [uuid]) values (2017-05-26 14:21:47.000, 2017-05-29 15:47:40.000, 1, 1, 2, 1495819307069, 6a3c161a3e8e29a1), (2017-05-26 14:21:47.000, 2017-05-29 15:47:40.000, 1, 1, 2, 1495819307069, 6a3c161a3e8e29a1) >>>>>  *** 1000**`.

I tried with the lastest release and the same error occurs. Seems like a real restriction of sqlserver,  i only open this issue because in php 7.0 this same query works.

**Comment by kAlvaro** [comment]
As the error message suggests, it's just some hard-coded limit, maybe arbitrary:

https://github.com/Microsoft/msphpsql/blob/v4.2.0-preview/source/shared/core_sqlsrv.h#L172

     const int SQL_SERVER_MAX_PARAMS = 2100;

https://github.com/Microsoft/msphpsql/blob/v4.2.0-preview/source/sqlsrv/util.cpp#L318

    // new error for 2.0, used here since 1.1 didn't have a -52
    {
        SQLSRV_ERROR_MAX_PARAMS_EXCEEDED, 
        { IMSSP, (SQLCHAR*) "Tried to bind parameter number %1!d!.  SQL Server supports a maximum of 2100 parameters.", -52, true }
    },

https://github.com/Microsoft/msphpsql/blob/v4.2.0-preview/source/pdo_sqlsrv/pdo_util.cpp#L183

    {
        SQLSRV_ERROR_MAX_PARAMS_EXCEEDED,
        { IMSSP, (SQLCHAR*) "Tried to bind parameter number %1!d!.  SQL Server supports a maximum of 2100 parameters.", -29, true }
    },

**Comment by rodineijf** [comment]
Thanks, i will adapt my script.

**Comment by natsu90** [comment]
@rodineijf I kinda have similar problem like you when I do bulk insert in Laravel. The solution I used is you have to chunk your array of data to not exceed 2100, e.g seems you have 7 fields to insert, so you need to chunk your array of data to insert to 300 at most at one time.

**Comment by rajeev-axl** [comment]
I am getting the same error while importing configuration in Drupal 8. Is there any workaround for Drupal 8?

**Comment by yitam** [comment]
@rajeev-axl if you need help from us please provide more details and repro steps / scripts etc.
