### ISSUE TITLE
Dont return any value PHP 7.1 MSSQL

### ISSUE THREAD

**Issue by nunesti** [Microsoft/msphpsql#411]
Hi!
I install in Plesk sqlsrv and pdo_sql (plesk-php71-dev and unixodbc-dev). My phpinfo is OK!
phpinfo load this:

sqlsrv support enabled
ExtensionVer 4.0.8.0
Directive Local Value Master Value
sqlsrv.ClientBufferMaxKBSize 10240 10240
sqlsrv.LogSeverity 0 0
sqlsrv.LogSubsystems 0 0
sqlsrv.WarningsReturnAsErrors On On
pdo_sqlsrv

pdo_sqlsrv support enabled
ExtensionVer 4.0.8.0
Directive Local Value Master Value
pdo_sqlsrv.client_buffer_max_kb_size 10240 10240
pdo_sqlsrv.log_severity 0 0

Try connect with mssql and dont retun any data from SQL Server
Example: PHP with query select, working in PHP 5.4 and this line echo "Count $numRegistros";
Show just "Count" PHP 5.4 "Count 7874"
Try with PDO, and "could not find driver!"

This module is OK for PHP 7.1, have any patch or update to fix this problem?

Thanks

**Comment by Hadis-Fard** [comment]
@nunesti 4.0.8 built with PHP 7.0. Since then we have had several releases with PHP 7.1 support, could you try our [latest release](https://github.com/Microsoft/msphpsql/releases)?

**Comment by meet-bhagdev** [comment]
@nunesti Are you using PECL or the binaries from GitHub?

**Comment by Hadis-Fard** [comment]
@nunesti [SQLSRV GA release](https://github.com/Microsoft/msphpsql/releases/tag/v4.3.0) supports both 7.0 and 7.1, also starting from v5.0.0 preview we're supporting PHP 7.2 as well
