### ISSUE TITLE
PDO_SQLSRV Debian jessie

### ISSUE THREAD

**Issue by netopvh** [Microsoft/msphpsql#425]
How to install driver in debian jessie?

**Comment by ulvii** [comment]
Hi @netopvh ,

You can use PECL to install the drivers.

```
sudo pecl install sqlsrv-4.2.0preview
sudo pecl install pdo_sqlsrv-4.2.0preview
```
You can also download the binaries [here  ](https://github.com/Microsoft/msphpsql/releases/tag/v4.2.0-preview).

**Comment by netopvh** [comment]
thanks

**Comment by ulvii** [comment]
Feel free to re-open the issue if you still have questions.
