### ISSUE TITLE
pdo_sqlsrv segfault on strings with some characters

### ISSUE THREAD

**Issue by brettmc** [Microsoft/msphpsql#427]
I have come across some data in our database (generated by casting a timestamp to a varchar) which is able to reliable segfault the `pdo_sqlsrv` driver (but the `sqlsrv` driver is able to handle it).
I've played around a bit, and this is the simplest code I can come up with that demonstrates the problem:

```php
<?php
$pdo = new PDO('sqlsrv:Server=xxx', 'username', 'password');
$sql = "select 'aa', cast(char(0x8f) as varchar)";
$query = $pdo->query($sql);
$r = $query->fetch(PDO::FETCH_ASSOC);
var_dump($r);
```

What seems to be important to trigger the segfault is the position of 0x8f compared to the length of the prior column. For example:
```
'a', 0x8f -> ok
'aa', 0x8f -> segfault
'aa', 'b'+0x8f' -> ok
'aaa', 'b'+0x8f -> segfault
```

I have found a few characters that do this: 0x81, 0x8d, 0x8f, 0x90, 0x9d
I've tested this on centos 7 (php 7.1.5 from remi repo).

Sql Server version info:
```
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 
	Oct 28 2016 18:17:30 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor)
```

**Comment by ulvii** [comment]
Hi @brettmc,

Thank you for the repro script. Which version of the driver ( `php --ri pdo_sqlsrv` ) are you using? I was unable to reproduce segmentation fault with the latest PDO_SQLSRV. 

Please try the script with the latest version and let me know if the issue still persists. 

`sudo pecl install pdo_sqlsrv-4.2.0preview`

You can also download the binaries [here](https://github.com/Microsoft/msphpsql/releases/tag/v4.2.0-preview) .

**Comment by brettmc** [comment]
Hi @ulvii ,
I have been able to replicate with `pdo_sqlsrv-4.2.0preview` running in docker. I hope that the following docker commands will illustrate:
centos image:
```
FROM centos:7

RUN yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi-php71 && \
    yum install -y \
    php \
    php-cli \
    php-common \
    php-devel \
    php-mbstring \
    php-pdo \
    php-pear \
    msodbcsql-libs \
    mssqlodbc \
    unixODBC \
    unixODBC-devel && \
    yum groupinstall -y "Development Tools" && \
    yum clean all

RUN pecl install pdo_sqlsrv-4.2.0preview && \
    echo "extension=pdo_sqlsrv.so" >> /etc/php.d/30-pdo_sqlsrv.ini
```
build php image:
```bash
docker build . -t myphp
```

run sql server:
```bash
docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Abcd123$" --name sqlsrv -d microsoft/sqlsrv
```
`test.php`:
```php
<?php
$pdo = new PDO('sqlsrv:Server=sqlsrv', 'sa', 'Abcd123$');
$sql = "select 'aa', cast(char(0x8f) as varchar)";
$query = $pdo->query($sql);
$r = $query->fetch(PDO::FETCH_ASSOC);
var_dump($r);
```

```
docker run -it --link sqlsrv -v $(pwd):/tmp/php myphp bash
[root@66736303e5bf tmp]# php --ri pdo_sqlsrv

pdo_sqlsrv

pdo_sqlsrv support => enabled
ExtensionVer => 4.2.0-preview

Directive => Local Value => Master Value
pdo_sqlsrv.log_severity => 0 => 0
pdo_sqlsrv.client_buffer_max_kb_size => 10240 => 10240
[root@66736303e5bf tmp]# php /tmp/php/test.php 
Segmentation fault (core dumped)
```

**Comment by brettmc** [comment]
Hello,
I think I have worked out the problem. I was installing package `mssqlodbc` via remi repo (`msodbcsql-13.0.0.0-2.el7.remi.x86_64`)
I switched over to `msodbcsql` (`msodbcsql-13.1.8.0-1.x86_64`) and it works as expected, so I guess the issue was fixed between these versions. Thankyou for your assistance!

**Comment by remicollet** [comment]
@ulvii I will be nice to be able to install recent msodbc 13.1.8.0, but I can't find the tarball anywhere

Installation script still refer to 13.0.0.0:
https://github.com/Microsoft/msphpsql/blob/PHP-7.0-Linux/ODBC%20install%20scripts/installodbc_redhat.sh

**Comment by remicollet** [comment]
Idem from https://msdn.microsoft.com/fr-fr/library/hh568454(v=sql.110).aspx

**Comment by ulvii** [comment]
@brettmc, glad you could solve the issue.
@remicollet please see #433. Also not that, PHP-7.0-Linux branch has been archived and we are no longer updating it. For latest source code and instructions use [dev ](https://github.com/Microsoft/msphpsql/tree/dev) branch. You can also use [master ](https://github.com/Microsoft/msphpsql)branch which gets updated after every release.
