### ISSUE TITLE
Can't connect to MSsql using pdo::construct 

### ISSUE THREAD

**Issue by daniel94104** [Microsoft/msphpsql#428]
OS: ubuntu 16.04
PHP: 7.1
installed all drivers needed accoding to [this](https://github.com/meet-bhagdev/phptekdemo/blob/master/proposedreadme.md#step-1-install--php-unless-already-installed)

Error message: 

''
SQLSTATE: HYT00
Code: 0
Message: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
SQLSTATE: 08001
Code: 10057
Message: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2749
SQLSTATE: 08001
Code: 10057
Message: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.''

Code here
> try {
    $conn = new PDO ("sqlsrv:Server=host.com\instance; Database = DBName",NULL,NULL);
    $conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
 } catch( PDOException $e ){
    die(print_r( $e->getMessage()));}

Since I am using Windows NT authentication, I leaved username and password blank. 

Really need HELP!! 

Thanks!!!

**Comment by daniel94104** [comment]
https://blogs.msdn.microsoft.com/brian_swan/2010/02/10/sql-server-driver-for-php-understanding-windows-authentication/

Solution here.

**Comment by ulvii** [comment]
Hi @daniel94104 ,

Were you able to connect to SQL Server?

**Comment by daniel94104** [comment]
I found out that the NT authentication is not compatible in Ubuntu. So, I created a new SQL account taking sql server authentication. Then, worked.

**Comment by ulvii** [comment]
Great. You can also try to use Kerberos Authentication on Linux. Details [here](https://technet.microsoft.com/en-us/library/cc280745(v=sql.105).aspx). 

I am closing the issue. Feel free to re-open it or create a new one if you have any other questions.

**Comment by daniel94104** [comment]
So,  sqlsrv_query worked with sql server authentication. However, I am trying to use pdo:sqlsrv using the sql server authentication to connect to sql server with failure. I have no idea why this happened. 

     try {
       $conn = new PDO ("sqlsrv:Server=host:port; Database = dbname","user","password");
       $conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

     } catch( PDOException $e ){
       die(print_r( $e->getMessage()));
     }

**Comment by benyanke** [comment]
Are you using a Linux server, or Windows Server, daniel94104? I'm trying to set up Kerberos on my Linux appserver (which is not on the domain), and finding it quite difficult.

Is there any other options, or is SQL authentication the best way in this situation?
