### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by billschaller** [Microsoft/msphpsql#43]
Now that MS has released a SQL Server native driver for Linux, when can we expect to see the sqlsrv driver supported on Linux as well?

**Comment by Lfsantos** [comment]
We are working on that.  I cannot comment on dates right now, but this is one of our top priorities now.

I’ll keep you posted.

Thanks

**Comment by zeroedin-bill** [comment]
Thanks, @Lfsantos, I appreciate your action on this and PHP 5.5 support.

**Comment by deancsmith** [comment]
+1

**Comment by felixkiss** [comment]
+1

**Comment by rwitchell** [comment]
+1 to this also. Our enterprise is heavily invested in Microsoft, however we need better support with our Linux servers.

**Comment by IndiAsh** [comment]
+1 linux support would be great

**Comment by CreditSense** [comment]
+1

**Comment by igorvarga** [comment]
+1

**Comment by kuniteru** [comment]
+1

**Comment by shenol** [comment]
8

**Comment by tegansnyder** [comment]
:+1:

**Comment by skynet** [comment]
+1

**Comment by pete01** [comment]
:+1:

**Comment by stmeyer** [comment]
Are there any news about the Linux support?

**Comment by meet-bhagdev** [comment]
Hello @stmeyer  - hope you are doing well :)
The PHP linux driver is already planned. We are working on it and will let you know once it is completed. Unfortunately I can not comment on the dates.
Hope this helps!
Best,
Meet

**Comment by zeroedin-bill** [comment]
@meet-bhagdev So does this mean you're about to release?

**Comment by meet-bhagdev** [comment]
Apologies for that. As Luiz said earlier we are working on it. I will reopen the issue and keep you posted.

Thanks

**Comment by zeroedin-bill** [comment]
@meet-bhagdev Haha :)

Happy new year!

**Comment by craigcarnell** [comment]
@meet-bhagdev Any updates on this?

**Comment by meet-bhagdev** [comment]
@craigcarnell : No updates as of now. We have done some initial discovery work and will start porting the driver from Windows to Linux in the coming months.

**Comment by craigcarnell** [comment]
@meet-bhagdev Looking forward to it.

Unfortunately in PHP 7 they have removed mssql* functions and also pdo_dblib seems broken at returning parameters from stored procedures (see this bug: https://bugs.php.net/bug.php?id=50555)

So at the moment I cannot do anything with PHP 7 and MSSQL, which is a big problem for me!

**Comment by jleckie** [comment]
Maybe this will help, apparently MS loves linux after all..
http://blogs.microsoft.com/blog/2016/03/07/announcing-sql-server-on-linux/

**Comment by skynet** [comment]
Haa haa

**Comment by craigcarnell** [comment]
Is it April's fools already?

**Comment by djsipe** [comment]
Hi @meet-bhagdev,

I see in the release notes for [v4.0.2](https://github.com/Azure/msphpsql/releases/tag/v4.0.2) that a PDO driver is expected "in the coming weeks".  Do you know if that will include Linux or will that just be Windows at first?

**Comment by ethanhann** [comment]
How usable will the Linux driver be with Azure Data Warehouse?

**Comment by sdh100shaun** [comment]
Any update on release date?

**Comment by meet-bhagdev** [comment]
@sdh100shaun 
We have started work on the Linux port and working through some unknowns. We will have an approximate timeline to share in a couple of weeks once we iron out the unknowns.

@ethanhann 
The Linux driver will certainly support Azure SQL DW.

Thanks,
Meet

**Comment by rachitpops** [comment]
Hi @meet-bhagdev I want to say I am very happy with how you and team are fixing the bugs reported, doing multiple releases and sending surveys. My team is grateful for that. We have migrated our apps to PHP7 and so far it looks great and I commend you for that. Please keep it up. :)
We as part of our Q3-Q4 plans we are looking to move some of our PHP apps to Linux and really need this Linux driver. I am eagerly waiting for the Linux driver and am more than happy to test it out and provide initial feedback.

**Comment by jonnywang** [comment]
+1

**Comment by meet-bhagdev** [comment]
@all we are targeting an early preview with basic functionality for Linux in the next 4-6 weeks. We will continue to receive feedback and shoot for 3 week releases to keep the feedback loop in motion.

Thanks,
Meet

**Comment by rogeriolino** [comment]
Hi @meet-bhagdev, any news?

**Comment by meet-bhagdev** [comment]
@rogeriolino We shipped some early bits last week and will have another update on Friday. Check it out :) https://github.com/Azure/msphpsql/tree/PHP-7.0-Linux

**Comment by rogeriolino** [comment]
@meet-bhagdev Thanks!

**Comment by meet-bhagdev** [comment]
Hi all, please check out our early preview release for Linux here: https://github.com/Azure/msphpsql/releases/tag/v4.0.1-Linux

There are several limitations and we are working through them. In the meanwhile, let us know if you have any feedback and we will improve on it incrementally. 

Can you also take this survey to help us understand how PHP developers install it on Linux: https://www.surveymonkey.com/r/6BBW8QM

Thanks,
Meet

**Comment by meet-bhagdev** [comment]
Hi team, we are getting ready to do a product release for the PHP Linux Driver for SQL Server. As we do that, we would like to know how do you install/download the driver on Linux: PECL vs Binaries on GitHub. 
<br>Please take this survey: https://www.surveymonkey.com/r/XCCKPQG and let us know what you think.

**Comment by craigcarnell** [comment]
No binaries! Open source or nothing thanks.

**Comment by regevbr** [comment]
+1
