### ISSUE TITLE
Where to find sources tarball for msodbc 13.1.x

### ISSUE THREAD

**Issue by remicollet** [Microsoft/msphpsql#433]
Related to #427 

See  https://msdn.microsoft.com/fr-fr/library/hh568454(v=sql.110).aspx

See https://github.com/Microsoft/msphpsql/blob/PHP-7.0-Linux/ODBC%20install%20scripts/installodbc_redhat.sh#L56

So only 13.0.0.0 can be found, it will be nice to have more recent version (13.1.8.0 ?)

**Comment by ulvii** [comment]
Hi @remicollet ,

Looks like the french version of the page is out of date. Thank you for reporting this, we will make sure the page is updated with the latest instructions. In the meantime, you can use https://msdn.microsoft.com/en-us/library/hh568454(v=sql.110).aspx.

**Comment by remicollet** [comment]
Thanks for your answer.

The problem for me is that this page only offers links to package (RPM) repositories, while I'm searching for the tarball which was available for 13.0.0.0

The tarball allow me to build my own RPM
- for other distro => Fedora
- used to build the PHP extension (in my buildroot)

Notice : I run all my tests using a Microsoft SQL Server on RHEL-7, but run PHP scripts from Fedora.

I will probably have to review my build system... only for this ext....

**Comment by remicollet** [comment]
About the documentation, I also notice installation instruction (which refer to my repository) are mostly ok on this github repo

```
yum-config-manager --enable remi-php70
yum update
yum install php php-pdo php-xml php-pear php-devel re2c gcc-c++ gcc
```

Well, as my repo have this extension, simpler to not install the devel stuff, and simply add **php-sqlsrv** to the package list ;)

More on https://docs.microsoft.com/fr-fr/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server there is confusing instruction
=> https://www.microsoft.com/en-us/sql-server/developer-get-started/php/rhel/

`yum install php70-php httpd php-cli php-common php-devel php-fpm php-mbstring php-mcrypt php-pear`

There are 2 PHP stacks in my repo

* php70-php-* in "remi-safe" enable by default, for parallel installation beside default PHP version (Software Collections)
* php-* in "remi-php70" (which have to be enabled) for base installation (replace default PHP version)

Both stacks have the sqlsrv package: php-sqlsrv and php70-php-sqlsrv (or php71-phpsqlsrv)

**Comment by ulvii** [comment]
Hi @remicollet ,

Thank you for the suggestions. Correct me if I am wrong, we can either execute the following commands to replace the defaults:
```
yum-config-manager --enable remi-php70
yum update
yum install php php-pdo php-xml php-pear php-devel 
```
OR use php70 from remi-safe:
```
yum update
yum install php70-php php70-php-pdo php70-php-xml php70-php-pear php70-php-devel 
```
In the latter case, would I execute php as `php70 -v`?

**Comment by meet-bhagdev** [comment]
@remicollet i just saw your comment about the tar ball. We do not have the tar for the driver right now. Our build machine produce packages for RHEL 7, 6, SLES 11, SLES 12, Ubuntu 15, 16 and 17. Were you able to make any of the RHEL ones work on Fedora?

**Comment by remicollet** [comment]
@ulvii right

**Comment by remicollet** [comment]
@ulvii notice that you can also use official package from RH on RHSCL (channel for RHEL users) or centos-scl (repository for CentOS users)

In this case, package prefix is "rh-php70"

Best (aka official) way to enable a Software Collections if to use the command

```
scl enable rh-php70 bash
php -v
```

**Comment by remicollet** [comment]
@meet-bhagdev indeed RHEL-7 packages works on Fedora (24 to 26), but this can change in the future...

BTW, I review my builders configuration to pull msodbcsql from Microsoft repository
(used for sqlsrv 4.3.0RC1 build)

**Comment by ulvii** [comment]
Thank you @remicollet. We will make sure the instructions are updated.

**Comment by David-Engel** [comment]
Hi @remicollet 

The original French MSDN page you linked to now redirects to the new English version on docs.microsoft.com which should be up-to-date. The localization team has prioritized localizing content and unfortunately that particular page is low on their list. Hopefully the English version is sufficient for the time being.

Regards,
David

**Comment by yitam** [comment]
Closing issue.
