### ISSUE TITLE
How to compile driver for Linux?

### ISSUE THREAD

**Issue by MartinKoeditz** [Microsoft/msphpsql#437]
Hi,

how can I compile the sqlsrv driver for other Linux distros, such as OpenSuse? Is there a tutorial for that task?
Will there a precompiled version?

Regards
Martin

**Comment by ulvii** [comment]
Hi @MartinKoeditz ,

SQLSRV is a PHP wrapper of SQL Server’s ODBC implementation ( MSODBCSQL ). To be able to use the driver, you will need to make sure that MSODBCSQL is installed. See [this](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server) page for the instructions to install MSODBCSQL using package manager as well as offline installation. 

Here are a few things to try once MSODBCSQL is installed. 

1. Try downloading and installing the package using PECL: `sudo pecl install sqlsrv-4.2.0preview` for the latest version.

2. OR you can download the driver source and try `phpize `locally.
```
wget https://github.com/Microsoft/msphpsql/archive/dev.tar.gz
tar -xf dev.tar.gz
cd msphpsql-dev/source/sqlsrv
cp -r ../shared/ .
phpize
./configure
make
```
3. Alternatively, you can try to compile the driver with PHP source. 
```
wget https://github.com/Microsoft/msphpsql/archive/dev.tar.gz
tar -xf dev.tar.gz
wget http://ca1.php.net/get/php-7.0.20.tar.gz/from/this/mirror -O php-7.0.20.tar.gz
tar -xf php-7.0.20.tar.gz
cp -r msphpsql-dev/source/sqlsrv/ php-7.0.20/ext/
cp -r msphpsql-dev/source/shared/ php-7.0.20/ext/sqlsrv/
cd php-7.0.20/
./buildconf --force
./configure --enable-sqlsrv=shared  --with-odbcver=0x0380
make
```
 We currently build and test binaries for Ubuntu 15, Ubuntu 16, RHEL7, so none of the instructions above has been tested on other Linux distributions.  Let me know how it goes or if you have questions.

**Comment by sirio3mil** [comment]
[Here](http://scriptinside.blogspot.com.es/2017/04/compilando-php-fpm-en-centos-7.html) you have one tutorial (in Spanish) for CentOS 7.

**Comment by meet-bhagdev** [comment]
@MartinKoeditz We don't support OpenSUSE officially.
@sirio3mil We have tutorials or CentOS/RHEL but not in English. What are you specifically looking for in the tutorial?

**Comment by Hadis-Fard** [comment]
#451
