### ISSUE TITLE
Can't install SQLSRV on Raspian. Error

### ISSUE THREAD

**Issue by ukypayne** [Microsoft/msphpsql#441]
I'm having a problem executing `sudo pecl install sqlsrv-4.0.8`. It runs and gets to the MAKE portion of the install, and then eventually gives me "make: *** [conn.lo] Error 1 "

It shows me 7 different issues, the first being 

'/tmp/pear/temp/sqlsrv/shared/intsafe.h:58:29: error: conflicting declaration 'typedef windowsULong_t DWORD'
 typedef windowsULong_t      DWORD;
                             ^'

The carrot is shown under the first D in the last "DWORD;".

Any thoughts?? Complete code below.

https://pastebin.com/FLp8vG4Y

**Comment by ulvii** [comment]
Hi @ukypayne ,

We currently build and test the drivers for Ubuntu 15, Ubuntu 16, RHEL7, Debian8. You can try to install the latest version `sudo pecl install sqlsrv-4.2.0preview`. See #437 for instructions to compile the source manually.

**Comment by meet-bhagdev** [comment]
@ukypayne What OS are you using?

**Comment by ukypayne** [comment]
Any suggestion of how I could get it to work? Will you ever support Raspian since it is Debian based?

**Comment by ulvii** [comment]
@ukypayne have you tried the instructions above? You can also download the Debian8 binaries from [releases ](https://github.com/Microsoft/msphpsql/releases) page and see if they work on Raspbian.
