### ISSUE TITLE
Can't connect to ip\instance from Linux/Ubuntu 16.04, working with ip,dynamic port

### ISSUE THREAD

**Issue by edoc-dokopp** [Microsoft/msphpsql#442]
I can't connect to a MSSQL Server via IP\instanceName.
It's working with ip and the dynamic port, but that's just a workaround not a solution for us.

Is this by design or what can I do?

System: `Ubuntu 16.04.2 LTS`
sqlcmd: `Version 13.1.0007.0 Linux`

Not working:
`root@ubuntu:~# sqlcmd -S 10.0.0.10\\TEST -U ... -P ...`

Gives the following error:

> Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
> Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : MAX_PROVS: Error Locating Server/Instance Specified [xFFFFFFFF]. .
> Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

Working:
`root@ubuntu:~# sqlcmd -S 10.0.0.10\\TEST,50123 -U ... -P ...`
`root@ubuntu:~# sqlcmd -S 10.0.0.10,50123 -U ... -P ...`

Thanks for your help.

**Comment by ulvii** [comment]
Hi @edoc-dokopp ,

Yes, it is by design. You need to provide port number to connect to a named instance. See this [page](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns). Related issues: #340, #190, #175

**Comment by hktalent** [comment]
in my kali linux
```
# sqlcmd  -S 92.18.1.125\\LTEST,1443 -U SA -P 123456
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection because an error was encountered during handshakes before login. Common causes include client attempting to connect to an unsupported version of SQL Server, server too busy to accept new connections or a resource limitation (memory or maximum allowed connections) on the server..
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection due to prelogin failure.
```

**Comment by grubshka** [comment]
I've also an error on some databases, but not all.
If I don't provide an instance name I go to the default instance.
If I provide an instance name, I get a timeout.
If I provide an instance name AND a port, I go to the default insance

```
importerp@ipssxrifc100:/opt/ACE/elivie-import-erps$ sqlcmd -S SRVSQL\INSTANCEB -U sa -P 123456
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : MAX_PROVS: Error Locating Server/Instance Specified [xFFFFFFFF]. .
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
```

**Comment by yitam** [comment]
Hi @grubshka 

Based on the error message you go `Error Locating Server/Instance Specified`, maybe this [support page](https://support.microsoft.com/en-us/help/944390/fix-error-message-when-you-connect-to-a-named-instance-of-sql-server-o) will help.

Also, I'm quoting one of the comments above:
> Yes, it is by design. You need to provide port number to connect to a named instance. See this page. Related issues: #340, #190, #175

**Comment by grubshka** [comment]
@yitam Thanks for your answer.
I finally got the database administrator, that told me the instance I was trying to connect is on another port...
