### ISSUE TITLE
sqlsrv param GETDATE()

### ISSUE THREAD

**Issue by genyslt** [Microsoft/msphpsql#445]
Hello,

## Issue

PHP Code:

```
$sql = "INSERT INTO myTable (field,field1,datetimefield) VALUES(?,?,?)";
$value = array('sring1', 'string2', 'GETDATE()');

$stmt = sqlsrv_query($conn,$sql,$params);
```

The result is error:
Conversion failed when converting character string to smalldatetime data type

## Question

**Why GETDATE() function is not working?**

If i pass to param any function - this is also not works?

## System info

**PHP version:** 7.1.5
**Linux version:** Ubuntu 16.04.2 LTS
**sqlsrv_client_info:**
[DriverName] => libmsodbcsql-13.1.so.8.0
[DriverODBCVer] => 03.52
[DriverVer] => 13.01.0008
[ExtensionVer] => 4.0.8.0
**sqlsrv_server_info:**
[SQLServerVersion] => 12.00.2000

## Connection params

"CharacterSet" => 'UTF-8',
"ReturnDatesAsStrings" => true,
"MultipleActiveResultSets" => 0

**Comment by sirio3mil** [comment]
You can't use SQL Servers functions as params, embedded it on SQL

$sql = "INSERT INTO myTable (field,field1,datetimefield) VALUES(?,?,GETDATE())";
$value = array('sring1', 'string2');

$stmt = sqlsrv_query($conn,$sql,$params);

**Comment by ulvii** [comment]
Hi @genyslt,

You cannot bind SQL Server functions as a query parameter. Does @sirio3mil's suggestion help?

**Comment by meet-bhagdev** [comment]
@genyslt closing this issue as it is not possible
