### ISSUE TITLE
Standard 'This extension requires the Microsoft ODBC Driver 11 for SQL Server', but unsolvable

### ISSUE THREAD

**Issue by GHExplorer** [Microsoft/msphpsql#446]
I had the 11 Driver installed for the past year, but recently installed the 13 Driver.

Now, php 5.6 keeps returning the standard driver 11 error.

I've confirmed that both 11 and 13 are installed, in the ODBC Administrator, and also re-installed driver 11.

And, I've got

[PHP_SQLSRV_56_NTS]
extension=php_sqlsrv_56_nts.dll
extension=php_pdo_sqlsrv_56_nts.dll

in the php.ini file, along with the actual files in the ext folder.

But I keep receiving the error.  Will I need to uninstall 13?  I'm using it for non-Php purposes.

**Comment by ulvii** [comment]
Hi @GHExplorer,

ODBC 13 should not really affect your PHP5 applications, because connection string is hard-coded to use ODBC 11. You can check the source code [here](https://github.com/Microsoft/msphpsql/blob/PHP5/pdo_sqlsrv/core_conn.cpp#L45).

Note that, we do not maintain PHP5 drivers anymore. Is there any reason why you are not using PHP7+?

**Comment by ulvii** [comment]
I just tried PDO_SQLSRV with PHP5 on a VM which has both ODBC11 and ODBC13 installed and was able to connect. 

```
php -v

PHP 5.6.28 (cli) (built: Nov  9 2016 06:40:27)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

`ODBC 11 version: 12.2`
`ODBC 13 version: 13.1`

**Comment by GHExplorer** [comment]
I use PHP 7 for personal projects.  But our agency, is using 5.5 and 5.6, and they're not ready to upgrade, yet.  I've been able to test and run most of their code in PHP 7, but some of the code doesn't work there, and it's in some of our legacy libraries.

**Comment by ulvii** [comment]
Hi @GHExplorer ,

Were you able to solve the issue?

**Comment by GHExplorer** [comment]
Not yet.  I was off yesterday, and will play with it, during today.

**Comment by GHExplorer** [comment]
Same error.  It was originally non-thread safe.  But for the heck of it, I moved to thread safe, replacing the nts files with nt in the extensions folder and confirmed with phpinfo.  

No go.

**Comment by GHExplorer** [comment]
After reinstalling VS 2012 runtime, and a reboot, I checked both the odbc administrator and the registry.  ODBC Driver 11 for SQL Server is no longer in the list.  Driver 13 is still there.

I tried re-installing #11, and it ran successfully.  But it still doesn't show up, in the odbc administrator, nor the registry.

This is the problem, obviously.  At some point, driver 11 was removed, and can't be reinstalled.  I'm going to try uninstalling driver 13, even though some of my User DSNs depend on it, and then re-re-install driver 11.

**Comment by GHExplorer** [comment]
Ok, got it.  I don't know at what point the 11 drivers were uninstalled - I've been using them for a while.

But when trying to reinstall them, the components were unchecked, and therefore the reinstall wasn't even attempting to put them back.

Everything's good now, thanks.

**Comment by Hadis-Fard** [comment]
@GHExplorer glad to hear that! I'll close the issue then
