### ISSUE TITLE
SQL_GUID is only defined if ODBCVER >= 0x0350, PHP 5.6 support

### ISSUE THREAD

**Issue by Jan-E** [Microsoft/msphpsql#45]
After this commit php_sqlsrv.dll and php_pdo_sqlsrv.dll did not compile anymore
https://github.com/php/php-src/commit/9bf95d82911dc7028c624494e9ac914f615f66ed#commitcomment-10090036
(PHP 5.6.7RC1 and PHP 5.5.23RC1).

The reason: SQL_GUID is only defined if ODBCVER >= 0x0350. The fix is here:
https://github.com/Jan-E/msphpsql/commit/9628db1bd944ea9cc7bf3d5e55cce127ec24a1b5

This patch is part of a pull request that also fixes the build for PHP 5.6 and x64:
https://github.com/Azure/msphpsql/pull/44

**Comment by yitam** [comment]
@Jan-E closing this issue, as the related #44 was closed in 2015.

**Comment by Jan-E** [comment]
Fine with me. I did not even remember opening this issue...
