### ISSUE TITLE
sqlsrv_query return false when execute msdb.dbo.sp_send_dbmail

### ISSUE THREAD

**Issue by thReality** [Microsoft/msphpsql#462]
sqlsrv_query return false when execute msdb.dbo.sp_send_dbmail and sqlsrv_errors() contains this

SQLSTATE: 01000
code: 0
message: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Mail (Id: 3049) queued.

sqlsrv,windows,64bit

**Comment by ulvii** [comment]
Hi @thReality ,

#266 could be related to this, please try the solution mentioned in the issue. 

Have you tried to call `sp_send_dbmail ` from SSMS( SQL Server Management Studio )?

**Comment by thReality** [comment]
Honestly I call the proc that call sp send mail but the result is the same.ssms return same msg as sqlsrv error,Mail queued. (no result set)

**Comment by ulvii** [comment]
Hi @thReality ,

This is not a SQLSRV related issue, your Mail Server is not properly set up. 

This [page](https://blogs.msdn.microsoft.com/suhde/2009/07/12/how-to-configure-sql-server-database-mail-to-send-email-using-your-windows-live-mail-account-or-your-gmail-account/) explains how you can setup SQL Server Database Mail to send emails using Windows Live or Gmail account. The instructions should be similar if you are using an SMTP Server.

The following pages could be helpful to troubleshoot the issue. 
https://technet.microsoft.com/en-us/library/ms190630(v=sql.105).aspx
https://technet.microsoft.com/en-us/library/ms189959(v=sql.105).aspx
https://msdn.microsoft.com/en-us/library/ms191278(v=sql.105).aspx


Note that, **SQL Server Express** does not support Database Mail, you can instead try CLR Intergration. See this [page](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/cd59b9cc-21ea-4130-afd1-791124031ada/can-sql-server-express-send-emails?forum=sqlexpress) for possible solutions.

**Comment by thReality** [comment]
???? I believe code 0 mean it was success isn't it and they do send the mail.

**Comment by ulvii** [comment]
@thReality ,

`SQLSTATE: 01000` does not really mean success, it is used for general warning and informative messages. See this [page](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/appendix-a-odbc-error-codes). I would suggest to use SSMS to get SQL Server Database Mail working first.

**Comment by meet-bhagdev** [comment]
@thReality it seems like you did not setup DB Mail correctly. Closing as it is not a PHP issue. If you have more questions on how to setup DB Mail and get it working via SSMS or PHP send me an email at meetb@microsoft.com
