### ISSUE TITLE
PDO_SQLSRV_56_NTS not working even after installing ODBC11

### ISSUE THREAD

**Issue by barohatoum** [Microsoft/msphpsql#47]
Hello,

I have installed PHP 5.6.7 NTS x86 with SQLSRV3.2 and ODBC11 on Windows Web Server 2008 R2 x64 with SQL Server 2008 R2 x64.

When accessing website, it says "This extensions require ODBC 11 x86". Since I'm on a x64 architecture, I can't install the ODBC 11 x86.

Any solutions to this problem.

Thank you

**Comment by meet-bhagdev** [comment]
Hi barohatoum,
We just published a blog on this. http://blogs.msdn.com/b/sqlphp/archive/2015/05/11/getting-started-with-php-and-microsoft-sql-server.aspx

The blog talks about how we can connect to the Microsoft SQL Server/SQL Azure by using this driver on a 64 bit machine.

If you download the 64bit ODBC driver that would also include the 32bit ODBC driver. Let me know if you are able to get your configuration to work using the blog mentioned above. If not I can try to help you further.

**Comment by itguy614** [comment]
I am having this same issue.  Error states:

```
Unable to load dynamic library 'ext\pdo_php_sqlsrv_56_nts.dll' - %1 is not a valid Win32 application
```

I have SQL Server 2014 console and client components installed locally.

**Comment by meet-bhagdev** [comment]
Hi @itguy614 which ODBC binary did you download? There are two - one for x86 and the other for x64.

**Comment by meet-bhagdev** [comment]
@itguy614 : Do you still need assistance?

**Comment by yitam** [comment]
@itguy614 we are going to close this issue. Please feel free to reopen if you need assistance.
