### ISSUE TITLE
Add support for DateTimeImmutable objects

### ISSUE THREAD

**Issue by kajstrom** [Microsoft/msphpsql#475]
Using DateTime objects currently work as parameters for date and time fields. Using DateTimeImmutable objects as parameters for date and time fields results in error code -16 and an error message "An invalid PHP type for parameter X was specified.".

In many cases using DateTimeImmutables is preferable to DateTime and this results in extra work as the DateTimeImmutable must be converted to a DateTime object or a string for use as a parameter with the SQL Server drivers.

It'd be great to have direct support for DateTimeImmutables in the SQL Server PHP Driver.

**Comment by yitam** [comment]
Hi @kajstrom 
It would be nice if you can show us a common use case or a simple repro script in which DateTimeImmutables is preferred over DateTime. Thank you.

**Comment by kajstrom** [comment]
Hi @yitam 

Using DateTimeImmutabless is preferable for example when objects hold a time object and offers it's clients access to it.  An example with DateTime, where using DateTime causes an issue with encapsulation and usage of DateTimeImmutable would prevent it:

```php
class MyClass {
  private $time;

  public function __construct()
  {
    $this->time =new \DateTime();
  }

  public function getTime()
  {
    return $this->time;
  }
}

$myObject = new MyClass();
$time = $myObject->getTime();

//This also modifies the DateTime attribute $time held by $myObject
$time->setTime(11,00,15);
```

Using DateTimeImmutable would prevent the issue above as DateTimeImmutable does not mutate the original object, but returns a new modified instance.

When I am using DateTimeImmutables  I currently have to convert those to either DateTime objects or strings when I am saving the values to SQL Server. Adding support for DateTimeImmutables in the SQL Server PHP drivers would remove the need for conversion before saving.

**Comment by Hadis-Fard** [comment]
@kajstrom Thanks for suggestion, we have looked into this request and at this moment it's not included in our plans.
