### ISSUE TITLE
SQL Server : TCP Provider: Error code 0x2AFA

### ISSUE THREAD

**Issue by Nilavu89** [Microsoft/msphpsql#476]
I'm new to Linux I have a Open Suse Leap 42.2 and when I installed mssql after the config part and installing the command line tools 
I started with "sqlcmd -S localhost -U SA -P password"

Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2AFA.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

It gave me this error !! please help!!

**Comment by meet-bhagdev** [comment]
Is your SQL Server running locally on Open Suse Leap?

**Comment by Nilavu89** [comment]
@meet-bhagdev Yes it is! checked it with the command "sudo systemctl status mssql-server" it was running!

**Comment by meet-bhagdev** [comment]
did you run mssql-conf after installing?

**Comment by Nilavu89** [comment]
Yes, it has 7 options I selected Evaluation version 180 days first one and set a password!!

**Comment by meet-bhagdev** [comment]
What port are you running SQL Server on?

**Comment by jeffbeagley** [comment]
I am also receiving this same error via a Docker Container running Ubuntu 16.04, PHP 7, and my MSSQL server is remotely hosted elsewhere. However it is inconsistent with me, sometimes timeout, other times the query works fine. Within the Docker Container, pinging the sql server results in a steady 50ms latency.

**Comment by yitam** [comment]
Basically this error message means you can't connect to the sql server. Probably your network connection is unstable (especially you said this problem is inconsistent)?
Next time when you fail to connect from php, I suggest you try with tools like `sqlcmd` or `isql`.

**Comment by jeffbeagley** [comment]
I'm able to ping the server from the container, and my instance of Apache/PHP are able to connect.. but I fixed the inconsistency by connecting utilizing the IP instead of the name. Have not tried sqlcmd with the IP yet.

**Comment by yitam** [comment]
Any update @jeffbeagley ? Otherwise, we will close this issue due to inactivity. Thank you.

**Comment by jeffbeagley** [comment]
No, I've not been able to thoroughly test by switching back to using the hostname. Referencing our SQL server via IP has seemed to solve any issues.. hard to say though if thats an internal DNS issue or not.

**Comment by yitam** [comment]
Sounds good, @jeffbeagley . I'll close this issue for now, and in case you run into similar or other problems, please feel free to create a new issue, referencing this one. Thank you.

**Comment by phabri** [comment]
Or we can use '127.0.0.1' instead of 'localhost' in the pod.
