### ISSUE TITLE
error on osx 

### ISSUE THREAD

**Issue by botaxs28** [Microsoft/msphpsql#478]
i get error like this
dyld: lazy symbol binding failed: Symbol not found: _iconv_open
  Referenced from: /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so
  Expected in: flat namespace
[core:notice] [pid 23472] AH00052: child pid 23479 exit signal Abort trap (6)

**Comment by Hadis-Fard** [comment]
@botaxs28 what is the version of the pdo_drivers that you are using?

**Comment by meet-bhagdev** [comment]
@botaxs28 If you can more info about your PATH, setup and version of PHP it will help as well 👍

**Comment by botaxs28** [comment]
@Hadis-Fard i'm using 4.3.0
@meet-bhagdev , like this
botaxs28s-MacBook-Pro:~ botaxs28$ php -version
PHP 7.1.1 (cli) (built: Jan 20 2017 07:19:55) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
botaxs28s-MacBook-Pro:~ botaxs28$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by yitam** [comment]
Hi @botaxs28, this is not related to our drivers. 

The library that contains iconv_open should be in libiconv.dylib. You can see if you have multiple versions of that? Try `ls -l libiconv*` in your `/usr/lib`

For your information, someone else has a similar issue in [stackoverflow](https://stackoverflow.com/questions/15678546/git-dyld-lazy-symbol-binding-failed-symbol-not-found-iconv-open).

Please check your `$DYLD_LIBARY_PATH` and make sure `/usr/lib` is there. If not, do this:
`export DYLD_LIBRARY_PATH=/usr/lib/:$DYLD_LIBRARY_PATH`

**Comment by botaxs28** [comment]
Sorry this my mistake.
this error, because xampp always load they own libiconv.
i has comment all script from /Applications/XAMPP/xamppfiles/bin/envvars,
now, this library can work perfect.

**Comment by yitam** [comment]
Hi @botaxs28 , thanks for the update! Glad to hear that your issue has been resolved. I'm now closing this issue. Have a good day!

**Comment by awaistariq** [comment]
Hi @yitam, I am having sort of same issue in accessing MSSQL from Php (Xampp on MacOS HighSierra) ls -l libiconv* gives me 
```
lrwxr-xr-x  1 root  wheel       16 Oct 10 09:01 libiconv.2.4.0.dylib -> libiconv.2.dylib
-r-xr-xr-x  1 root  wheel  2104288 Oct  3 08:51 libiconv.2.dylib
lrwxr-xr-x  1 root  wheel       20 Oct 10 09:01 libiconv.dylib -> libiconv.2.4.0.dylib
```
Can you help me?

**Comment by yitam** [comment]
Hi @awaistariq 

Did you try the suggestion above and/or check the similar problem in [stackoverflow](https://stackoverflow.com/questions/15678546/git-dyld-lazy-symbol-binding-failed-symbol-not-found-iconv-open)?

**Comment by awaistariq** [comment]
Yes, I have tried, but it didn't work.
