### ISSUE TITLE
Guide update request for RedHat SELinux Apache Enforcing mode allow

### ISSUE THREAD

**Issue by kviktorman** [Microsoft/msphpsql#494]
Hi,

thank you for the solution and the description about the environment set up, its really great!

I have had some difficulties only with the RHEL installation guide. You already know the solution, but it takes time to find it. 

I followed the instruction here on this URL (https://www.microsoft.com/en-us/sql-server/developer-get-started/php/rhel/) from the "Step 2.1 Install the PHP Driver for SQL Server" I really missed this one line command.

_sudo setsebool -P httpd_can_network_connect_db 1_

This line you have it here : https://github.com/Microsoft/msphpsql/blob/dev/README.md
In the "Step 5: Restart Apache to load the new php.ini file" , but it is hard to discover it there as well. 

**Changes which I would like to ask:**

- Here on github in the install instructions it would be really helpful to move in the step 5 section that line before the  "Mac OS X" header, because the RedHat header do not have the sign that it has that one line extra comment. For me it was really confusing that it was after the Mac section, because its RedHat related.

- On the microsoft url it would be great to have that one line added to the 2.1 section or somewhere near to it. 
 
**For me the behavior was the following:**

I developed a PHP - MSSQL solution on Ubuntu and when I tried to deploy it on CentOS it was not connecting to the server. I was able to connect via SQLCMD to the MSSQL server, query returned the expected result. Unfortunately when I tried to do the same through PHP it failed every time with this error: 

[unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired Error: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x271D Error: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. 

Now since executed that command its working fine. So this is more like a please update the guide  request.

Thanks again its really great work,
Vik

**Comment by kviktorman** [comment]
Ohh, I forget to mention that for RHEL I think one of the install package name is mistyped on the microsoft website ( https://www.microsoft.com/en-us/sql-server/developer-get-started/php/rhel/). "php-mycrypt"  was not a valid package name for me in "Step 1.2 Install PHP and other required packages"  I think its called the same way as the Ubuntu version "php-mcrypt".

Also here on github maybe it would be advised to change the service restart to 
- for RHEL:
systemctl restart httpd
- for Ubuntu:
systemctl restart apache2

**Comment by Hadis-Fard** [comment]
@kviktorman Thanks points taken! we sent a PR with your suggestions

**Comment by kviktorman** [comment]
Thanks, I see the changes here on Github. On the linked MS webpage its still the same. Do I need to report that in a different way or it will be updated soon and I shall close this issue?

**Comment by Hadis-Fard** [comment]
We'll take care of that one here too :wink: @meet-bhagdev can you update 'Get started pages similar to #500 and @kviktorman suggestions.

**Comment by yitam** [comment]
Closing this issue @kviktorman as the MS [Get started page](https://www.microsoft.com/en-us/sql-server/developer-get-started/php/rhel/) has been updated. Thank you for your contributions.
