### ISSUE TITLE
PDO Connexion to localdb generate Login timeout expired exception

### ISSUE THREAD

**Issue by Ducatel** [Microsoft/msphpsql#495]
Hi,
I'm trying to use open a localdb database thought PDO in a docker container.

With a sample like 
```php

<?php
try{
    $conn = new PDO('sqlsrv:server=(local)\\v11.0;AttachDBFileName=project_data.mdf;Database=mydb', '', '');
    $query = "select count(*) from table";
    $stmt = $conn->query($query);
    var_dump($stmt->fetchAll(PDO::FETCH_ASSOC));
} catch(PDOException $ex) {
  var_dump($ex);
}
```

This generate an exception
```
[unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
```

My container is build with this dockerfile

````Dockerfile
FROM php:7.1-apache

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates zlib1g-dev && \
    update-ca-certificates && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y unixodbc unixodbc-dev libgss3 odbcinst msodbcsql locales && \
    apt-get clean && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen && \
    pecl install sqlsrv pdo_sqlsrv && \
    docker-php-ext-enable sqlsrv pdo_sqlsrv && \
    docker-php-ext-install zip && \
    a2enmod rewrite && \
    a2enmod headers && \
    a2enmod ssl
````

So I did a stupid things ?
Thanks

**Comment by Hadis-Fard** [comment]
@Ducatel How are you running the script and where's the script located?

**Comment by Ducatel** [comment]
Hi @Hadis-Fard 
I execute the script directly in the docker container directly with the php interpreter
```
root@29c8a4b546f6:/var/www/html# php test.php
```

**Comment by Hadis-Fard** [comment]
@Ducatel I'm trying to repro this issue. let's do a little experiment, can you run the same script in your machine outside of Docker? Also do you get the same error if you give the server name of your local server  and supply username and password?

**Comment by Ducatel** [comment]
I have tried to do that on Windows7.1X64 and I have this error
```
"SQLSTATE[08001]: [Microsoft][ODBC Driver 13 for SQL Server]SQL Server Network Interfaces: "
```

But I have somethings to clarify.
When I do 
```php
new PDO('sqlsrv:server=(local)\\v11.0;AttachDBFileName=project_data.mdf;Database=mydb', '', '');
```
This line start the "localdb server" ?
In need to do something before trying to connect with PDO ?

**Comment by Hadis-Fard** [comment]
@Ducatel can you send the complete error you are receiving? is that `Error locating server`? can you try `sqlcmd -S <YourServerName> -U <YourUserName>-P <YourPassword>` and send me the result?

Also can you try
`$conn = new PDO('sqlsrv:server=(local)', '<YourUserName>', '<YourPassword>');`

**Comment by Ducatel** [comment]
@Hadis-Fard I didn't have any username or password.

On my windows host:
```
C:\Users\me>sqllocaldb create "MyInstance"
Instance de base de données locale « MyInstance » créée avec la version 12.0.2000.8.
C:\Users\me>sqllocaldb start "MyInstance"
Instance de base de données locale « MyInstance » démarrée.
C:\Users\me>sqlcmd -S (localdb)\MyInstance
1> select @@version
2> go

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
--------------------------------------------------
Microsoft SQL Server 2014 - 12.0.2000.8 (X64)
        Feb 20 2014 20:04:26
        Copyright (c) Microsoft Corporation
        Express Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)
```

And if I execute the following php code, it's working
```
$conn = new PDO('sqlsrv:server=(localdb)\MyInstance');
$query = "select @@version";
$stmt = $conn->query($query);
var_dump($stmt->fetchAll(PDO::FETCH_ASSOC));
```

It's also working if I did
```
$conn = new PDO('sqlsrv:server=(localdb)\MyInstance;AttachDBFileName=C:\Users\me\data.mdf;Database=test_data');
```

I understand now that `new PDO` didn't start any localdb instance.
So How I can start the localdb instance inside the docker container ?
Because, the `sqllocaldb` executable isn't present

**Comment by Ducatel** [comment]
According to the other issue, it isn't possible make what I want in a container.
Thanks @Hadis-Fard for your help ;)
