### ISSUE TITLE
Memory limit of KB exceeded for buffered query

### ISSUE THREAD

**Issue by jansor** [Microsoft/msphpsql#499]
Hi, 
Maybe this is not really an issue rather a question.

On regular time we need to pull big data sets out of the db. But then we run against  "Memory limit of 40960 KB exceeded for buffered query"

What is the better way to solve this? I could just increase the size of the memory limit. But are their any other tricks, so i can avoid that. for example take out in sections.

Also keeping in mind performance wise.

Thans

**Comment by Hadis-Fard** [comment]
Which driver are using PDO_SQLSRV or SQLSRV? Would be great if you can post a repo of the scenario you have in mind.

**Comment by jansor** [comment]
At this moment i am using SQLSRV with the query option of SQLSRV_CURSOR_CLIENT_BUFFERED
I have two general scenarios at this moment, one is to export the data via a client portal site to excel. 
Other one is to display the result set on screen depending on search criteria, essential one big HTML table.

**Comment by Hadis-Fard** [comment]
@jansor with SQLSRV_CURSOR_CLIENT_BUFFERED you must increase the buffer size, the other option is to stream data, please see https://docs.microsoft.com/en-us/sql/connect/php/retrieving-data-as-a-stream-using-the-sqlsrv-driver and https://docs.microsoft.com/en-us/sql/connect/php/sqlsrv-send-stream-data

**Comment by Hadis-Fard** [comment]
@jansor do you need any further assistance?
