### ISSUE TITLE
Coonection Failed in Ubuntu 16.04 :(

### ISSUE THREAD

**Issue by harrypotter0** [Microsoft/msphpsql#506]
Here is what I tried :::
sqlcmd -S 192.168.225.147 -U SA -P 'kanika@123' -Q "USE LEGACY"
Here is the error ::
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
Please suggest something . Thanks in advance :)

**Comment by david-puglielli** [comment]
Hi @harrypotter0, how often does this happen? Are you sure the server is online (try pinging it)?

**Comment by david-puglielli** [comment]
Hi @harrypotter0, you could try running 
`strace -tt sqlcmd -S 192.168.225.147 -U SA -P 'kanika@123' -Q "USE LEGACY"`. 
Examine the timestamps and see if there is a backwards jump right when it tries to connect. We suspect a bug in the ODBC driver related to time measurement is responsible for some connection failures; see #468 for more info.

**Comment by harrypotter0** [comment]
Fixed it finally on 26th Aug :) 
Thanks for the help .

**Comment by david-puglielli** [comment]
Glad we could help. Closing this issue, please reopen if the problem arises again.

**Comment by ankushreddy** [comment]
@harrypotter0  Hi I am facing a similar issue could You please let me know what is fix that you applied.

Thanks,
Ankush Reddy.
