### ISSUE TITLE
Reporting file not found when driver exists

### ISSUE THREAD

**Issue by cjorge** [Microsoft/msphpsql#508]
PHP fires an error on Mac OS:

SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib '/usr/local/lib/libodbcinst.2.dylib' : file not found

The file exists and is in the right place... Running otool -l I check all dependencies exist and are correct.

No idea what can ben happening. Any help?

**Comment by cjorge** [comment]
the driver is obviously /usr/local/lib/libmsodbcsql.13.dylib

**Comment by Hadis-Fard** [comment]
related to Microsoft/homebrew-mssql-release#1
