### ISSUE TITLE
Unable to handle SQL_VARIANT types

### ISSUE THREAD

**Issue by david-garcia-garcia** [Microsoft/msphpsql#51]
The PDO driver is chocking on SQL_VARIANT types, but this can contain themselves simple types such as char, intenger, etc...

Steps to reproduce:
1. Create an UDF:

CREATE FUNCTION [dbo].[GREATEST](@op1 sql_variant, @op2 sql_variant) RETURNS sql_variant AS
BEGIN
  DECLARE @result sql_variant
  SET @result = CASE WHEN @op1 >= @op2 THEN @op1 ELSE @op2 END
  RETURN @result
END
GO
1. Run this query through the PDO

SELECT dbo.GREATEST(5, 6)
1. Theses are the errors you get:

Without Buffered Queries:

SQLSTATE[IMSSP]: Invalid type.

With Buffered Queries:

Fatal error: Unknown type in sqlsrv_buffered_query::sqlsrv_buffered_query

I can manage to get it to work if I use PDO::PARAM_INT on the column before the fetch, but there is no way that I can infer this informatino from the PDO metadata (getColumnMeta) that is reporting:

sql_srv_type = sql_variant
native_type = string

Possible solutions.....
1. At least let me retrieve the data as a string by default, instead of Fatal crashing.

**Comment by stevebauman** [comment]
This is still an issue today. Is there a fix in the works?

**Comment by Hadis-Fard** [comment]
@stevebauman PHP drivers rely on ODBC to handle SQL data types, and SQL_VARIANT is not supported in ODBC. We're looking into David's suggestion to see if SQL variants can be handled with string inferred type.

**Comment by stevebauman** [comment]
@Hadis-Fard Awesome! Thanks for the reply :).

**Comment by Hadis-Fard** [comment]
@stevebauman @david-garcia-garcia we added support for sql variants in [4.2.0-preview] (https://github.com/Microsoft/msphpsql/releases/tag/v4.2.0-preview), you can get the driver from our PECL repositiry or GitHub releases page. Note that sqlvariant for output parameters is not supported.
