### ISSUE TITLE
"CharacterSet" => SQLSRV_ENC_CHAR on Linux

### ISSUE THREAD

**Issue by gruyoman** [Microsoft/msphpsql#515]
In the Windows server "CharacterSet" => SQLSRV_ENC_CHAR is the default setting. 
In Linux SQLSRV_ENC_CHAR exists or not? Even when I set it, it uses UTF-8.

Thanks

**Comment by Hadis-Fard** [comment]
@gruyoman SQLSRV_ENC_CHAR in linux only works with ASCII characters, and you should set the character set to utf-8 for non-ASCII characters. please see https://github.com/Microsoft/msphpsql#limitations

**Comment by Hadis-Fard** [comment]
@gruyoman is there anything else that we can help you in?

**Comment by gruyoman** [comment]
I've seen that in linux SQLSRV_ENC_CHAR behaves exactly like UTF-8. That means that SQLSRV_ENC_CHAR actually doesn't exist. The problem is that there isn't compatibility between windows and linux web application with SQLSRV_ENC_CHAR.
However I have one question: to use unicode chars i have to use N' prefix for nchar, nvarchar and ntext value. Is there any possibility to set something in php or apache to skip N' prefix because we have multidatabase application.
Thank you

**Comment by lilgreenbird** [comment]
hi @gruyoman, that is not possible and as @Hadis-Fard mentioned above it's a limitation in the Linux driver. I have created a feature request for this we will look into supporting this in future releases.

**Comment by gruyoman** [comment]
Ok, thank you
