### ISSUE TITLE
Trying to connect Drupal SQLSRV driver  to Drupal 8.3.7 and Red hat linux

### ISSUE THREAD

**Issue by Jcook894** [Microsoft/msphpsql#551]
I am currently trying to set up Drupal 8.3.7 on Red hat 7.4 and connect it to MS SQL database, I have gotten as far as installing the Microsoft OBDC driver for php and the sqlsrv driver for Drupal. The only documentation it has is in the readme and says "Drop the driver Folder into the root of your Drupal installation." But I've tried and the option for SQL server in the drupal installation screen is not there(like this [image](http://www.drupalonwindows.com/sites/default/files/ckfinder_files/1/images/Blogs/2016/103/install2.png)), They say the driver is compatible with linux but seems like it lacking a lot of documentation for it. Is there any steps I am missing in this process? Has anyone been able to connect or have experience drupal 8 on red hat to MS SQL database?

**Update** :    So I put the sqlsrv directory in the modules directory in Drupal, I set up a test database with mariadb just to get past the initial install screen for Drupal and then I navigated to extend tab and see 
![drupal_image](https://user-images.githubusercontent.com/17104934/30826335-449a90ce-a204-11e7-9806-c7a78f9c9810.png)

But I cannot enable it. Is this a step in the right direction?

**Comment by Hadis-Fard** [comment]
This is related to Drupal configuration. @david-garcia-garcia could you please help in this issue?

**Comment by meet-bhagdev** [comment]
@Jcook894 Where did you get the Linux binaries from? Can you point me to the doc where the steps for Drupal + SQL Server is documented?

**Comment by Jcook894** [comment]
@meet-bhagdev It says it in the readme on the Drupal SQLSRV driver, Here is a screenshot:
![virtualbox_rhel_05_10_2017_09_51_44](https://user-images.githubusercontent.com/17104934/31230873-4bf239ce-a9b3-11e7-8962-2f4431da81ef.png)

I followed the documentation for MSSQL php driver on here for RHEL and I downloaded the Drupal SQLSRV driver version 8.x-1.0-rc4 from [here](https://www.drupal.org/project/sqlsrv)

**Comment by yitam** [comment]
hi @Jcook894 just checking if you still need help with configuration. I'd suggest you check with Drupal as well. Thanks.

**Comment by yitam** [comment]
First I'd like to see if sqlsrv driver is correctly set up in your env, so please provide the outputs for the following:
1. `php -v`
2. `php --ini`
3. `php --ri sqlsrv`

Also, I've assumed you have followed the [instructions](https://github.com/Microsoft/msphpsql) for Red Hat, and have you tried running the sample app? Does that work for you?

**Comment by Jcook894** [comment]
Here are the outputs for those commands:

php -v = 
PHP 7.0.23 (cli)


php --ini = 
Configuration File (php.ini) Path: /etc
Loaded Configuration File:         /etc/php.ini
Scan for additional .ini files in: /etc/php.d
Additional .ini files parsed:      /etc/php.d/20-bz2.ini,
/etc/php.d/20-calendar.ini,
/etc/php.d/20-ctype.ini,
/etc/php.d/20-curl.ini,
/etc/php.d/20-dom.ini,
/etc/php.d/20-exif.ini,
/etc/php.d/20-fileinfo.ini,
/etc/php.d/20-ftp.ini,
/etc/php.d/20-gd.ini,
/etc/php.d/20-gettext.ini,
/etc/php.d/20-iconv.ini,
/etc/php.d/20-json.ini,
/etc/php.d/20-mysqlnd.ini,
/etc/php.d/20-pdo.ini,
/etc/php.d/20-phar.ini,
/etc/php.d/20-posix.ini,
/etc/php.d/20-shmop.ini,
/etc/php.d/20-simplexml.ini,
/etc/php.d/20-sockets.ini,
/etc/php.d/20-sqlite3.ini,
/etc/php.d/20-sysvmsg.ini,
/etc/php.d/20-sysvsem.ini,
/etc/php.d/20-sysvshm.ini,
/etc/php.d/20-tokenizer.ini,
/etc/php.d/20-xml.ini,
/etc/php.d/20-xmlwriter.ini,
/etc/php.d/20-xsl.ini,
/etc/php.d/30-mysqli.ini,
/etc/php.d/30-pdo_mysql.ini,
/etc/php.d/30-pdo_sqlite.ini,
/etc/php.d/30-wddx.ini,
/etc/php.d/30-xmlreader.ini,
/etc/php.d/pdo_sqlsrv.ini,
/etc/php.d/sqlsrv.ini


php --ri sqlsrv =
sqlsrv

sqlsrv support => enabled
ExtensionVer => 4.3.0

Directive => Local Value => Master Value
sqlsrv.WarningsReturnAsErrors => On => On
sqlsrv.LogSeverity => 0 => 0
sqlsrv.LogSubsystems => 0 => 0
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240

& yes I followed the instructions for Redhat, I've also ran the sample app and that works. It's just not connecting to my new Drupal installation.

**Comment by yitam** [comment]
Thanks for providing all the info as per my request, @Jcook894, but regrettably Drupal installation/configuration is not in scope of our support.

**Comment by Jcook894** [comment]
Ahh okay @yitam, Thanks anyways!

**Comment by yitam** [comment]
Closing since this is beyond the scope of support
