### ISSUE TITLE
How to store encrypted data in mssql database

### ISSUE THREAD

**Issue by alsong** [Microsoft/msphpsql#559]
`<?php

class SecurityClass  
{
    
    public function my_simple_crypt( $string, $action = 'e',$algo ) {
        // you may change these values to your own
        $secret_key = 'my_simple_secret_key';
        $secret_iv = 'my_simple_secret_iv';
     
        $output = false;
        $encrypt_method = "AES-256-CBC";
        $key = hash( $algo, $secret_key );
        $iv = substr( hash( $algo, $secret_iv ), 0, 16 );
     
        if( $action == 'e' ) {
            $output = base64_encode( openssl_encrypt( $string, $encrypt_method, $key, 0, $iv ) );
        }
        else if( $action == 'd' ){
            $output = openssl_decrypt( base64_decode( $string ), $encrypt_method, $key, 0, $iv );
        }
     
        return $output;
    }

}

?>`

**The code above is what i am using to encrypt and decrypt**
Then the code below is me applying it without a database

`<?php
 require_once(dirname(__FILE__).'/Secure.php');
$mainpass = "ALSONGWEWEWEWEWE";
//MD5 encryption

$options = [
    'cost' => 12,
];

$mSecure = new SecurityClass();

	
$encrypted = $mSecure->my_simple_crypt( $mainpass, 'e','sha512' );

$decrypted = $mSecure->my_simple_crypt($encrypted, 'd','sha512' );

echo "encrypted $encrypted<br/>";
echo "decrypted $decrypted<br/>";

 
?>`

**This is the output**

![capture1](https://user-images.githubusercontent.com/19310511/31040253-e13726f6-a57c-11e7-8d70-e0f2f6a319d1.PNG)

**Now when i put this encrypted data in a database, then retrieve it from the database and decrypt it. It doesnt decrypt. I saved the data in datatype nvarchar(max)**

I need some help on how to store encrypted data and it remains functioning after i have retrieved it from the database

**Comment by v-kaywon** [comment]
@alsong , I couldn't reproduce the problem you are facing with the [latest PDO_SQSRV driver](https://github.com/Microsoft/msphpsql/releases/tag/v5.1.0-preview) with PHP 7.1. The following code is how I used the PDO_SQLSRV driver to store the encrypted data, retrieve it, and decrypt using your SecurityClass:

```
<?php
class SecurityClass
{
    public function my_simple_crypt( $string, $action = 'e',$algo ) 
    {
        // you may change these values to your own
        $secret_key = 'my_simple_secret_key';
        $secret_iv = 'my_simple_secret_iv';
     
        $output = false;
        $encrypt_method = "AES-256-CBC";
        $key = hash( $algo, $secret_key );
        $iv = substr( hash( $algo, $secret_iv ), 0, 16 );
     
        if( $action == 'e' ) {
            $output = base64_encode( openssl_encrypt( $string, $encrypt_method, $key, 0, $iv ) );
        }
        else if( $action == 'd' ){
            $output = openssl_decrypt( base64_decode( $string ), $encrypt_method, $key, 0, $iv );
        }
     
        return $output;
    }
}

$mainpass = "ALSONGWEWEWEWEWE";
//MD5 encryption

$options = [
'cost' => 12,
];

$mSecure = new SecurityClass();

$encrypted = $mSecure->my_simple_crypt( $mainpass, 'e','sha512' );

$decrypted = $mSecure->my_simple_crypt($encrypted, 'd','sha512' );

echo "encrypted $encrypted
";
echo "decrypted $decrypted
";

// Store $encrypted into a nvarchar(max) column
require_once("MsSetup.inc");
$conn = new PDO("sqlsrv:Server=$server;database=$databaseName;", $uid, $pwd);

$tbname = "test559";
$conn->exec("CREATE TABLE $tbname (c1 nvarchar(max))");

$conn->exec("INSERT INTO $tbname VALUES ('$encrypted')");

// Retrieved stored encrypted value
$stmt = $conn->query("SELECT c1 FROM $tbname");
$encryptedAfterStore = $stmt->fetchColumn();

// Decrypt encrypted value retrieved from the database
$decryptedAfterStore = $mSecure->my_simple_crypt($encryptedAfterStore, 'd','sha512');
echo "encrypted after store: $encryptedAfterStore\n";
echo "decrypted after store: $decryptedAfterStore\n";

// Cleanup
$conn->exec("DROP TABLE $tbname");
unset($stmt);
unset($conn);
?>

```

The output I get is:
```
encrypted clZQMEdKUTNPUzcyZUMzVllNQzlGUU1yWGxvanpQeVM4Rm5aMldZZUVUOD0=
decrypted ALSONGWEWEWEWEWE
encrypted after store: clZQMEdKUTNPUzcyZUMzVllNQzlGUU1yWGxvanpQeVM4Rm5aMldZZUVUOD0=
decrypted after store: ALSONGWEWEWEWEWE
```

As you can we, the decrypted values I get before storing into the database and after are the same. Please try the code above and see if it works for you. Thanks.

**Comment by alsong** [comment]
@v-kaywon , thanks man for the help
