### ISSUE TITLE
typo "LoginTimggeout"?

### ISSUE THREAD

**Issue by makotokato** [Microsoft/msphpsql#56]
See https://github.com/Azure/msphpsql/blob/master/sqlsrv/core_sqlsrv.h#L1013 for definition of  LoginTimeout.

const char LoginTimeout[] = "LoginTimggeout";

Is typo of LoginTimeout?

**Comment by meet-bhagdev** [comment]
Thanks for the question. This has been reported to the engineering team and they are looking at it.
Best,
Meet Bhagdev
Program Manager, Microsoft
