### ISSUE TITLE
Can't open lib  ODBC Driver 13 for SQL Server

### ISSUE THREAD

**Issue by bpodlisetskyi** [Microsoft/msphpsql#561]
I have a problem
`Illuminate\Database\QueryException with message 'SQLSTATE[01000]: [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found`

macOS, php 7.1

**Comment by david-puglielli** [comment]
Hi @bpodlisetskyi, it seems like the ODBC driver is not installed. Have you followed the installation instructions for macOS in the [Readme](https://github.com/Microsoft/msphpsql/blob/dev/README.md)? [Step 2](https://github.com/Microsoft/msphpsql/blob/dev/README.md#step-2-install-prerequisites) describes how to install the ODBC driver under the **macOS** sub-header.

**Comment by bpodlisetskyi** [comment]
Yes, I did all steps
