### ISSUE TITLE
Use sqlsrv_query on encrypted varchar max fields results in function sequence error

### ISSUE THREAD

**Issue by yitam** [microsoft/msphpsql#569]
1. Create a table with an encrypted varchar max column and then insert one row
2. Fetch data by using sqlsrv_query() and then sqlsrv_get_field()
3. Failed with Function sequence error

The problem disappears if using sqlsrv_prepare() in step 2 above.

**Comment by Hadis-Fard** [comment]
Would you please add a repro script?

**Comment by yitam** [comment]
Repro steps:

1. Create a table as follows:
```
CREATE TABLE aTest ( [c1] varchar(max) COLLATE Latin1_General_BIN2 ENCRYPTED WITH (ENCRYPTION_TYPE = deterministic, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256', COLUMN_ENCRYPTION_KEY = AEColumnKey) )
```
2. Then insert some large string into this column
```
$value = "some very large string";
$stmt = sqlsrv_prepare($conn, "INSERT INTO aTest (c1) VALUES (?)", array($value));
sqlsrv_execute($stmt);
```
3. Data has been successfully inserted, so fetch data as follows:
```
$stmt = sqlsrv_query($conn, "SELECT * FROM aTest ");
sqlsrv_fetch($stmt);
$fieldVal = sqlsrv_get_field($stmt, 0, SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_CHAR));
```
4. sqlsrv_get_field() returns `false` so print sqlsrv_errors()

**Comment by Hadis-Fard** [comment]
if it is going to be a limitation, there should be an informative error preventing the calls to ODBC

**Comment by david-puglielli** [comment]
Seems to work if the table is not empty. If the table is empty, I get an error saying `A row must be retrieved with sqlsrv_fetch before retrieving data with sqlsrv_get_field.`, which might be confusing since sqlsrv_fetch *is* called before sqlsrv_get_field, it's just that there is no row to fetch. We might want to clarify the error.

**Comment by yitam** [comment]
@david-puglielli upon more investigation, the error message is not entirely wrong. Based on [sqlsrv_fetch](https://docs.microsoft.com/sql/connect/php/sqlsrv-fetch?view=sql-server-2017), `If there are no more results in the result set, null is returned.`

In the script, the user should have checked the returned value of sqlsrv_fetch() before calling  [sqlsrv_get_field](https://docs.microsoft.com/sql/connect/php/sqlsrv-get-field?view=sql-server-2017).

Thus, the error message indicates *no row* has been retrieved with sqlsrv_fetch yet, not that sqlsrv_fetch is not called.

**Comment by yitam** [comment]
In order to give a clearer message by checking if the table is empty first requires additional calls to the server, which does not justify the cost. Closing this issue as the original problem was already fixed.
