### ISSUE TITLE
error "The active result for the query contains no fields" after PDOStatement->nextRowset()

### ISSUE THREAD

**Issue by epoxa** [Microsoft/msphpsql#591]
I need to fetch results from a dynamic query returning potentially multiple result sets.
Because of dynamic nature of the request I do not know how many result sets will be returned from server.
To handle this I used the code:
`                do {
                    if ($result->columnCount()) {
                        $data = $result->fetchAll(PDO::FETCH_NUM);
                    } else {
                        $data = [];
                    }
                } while ($result->nextRowset());
`
After upgrading to the latest pdo_sqlsrv version I get the error mentioned in the issue title.
I've checked this out: https://github.com/Microsoft/msphpsql/issues/507 but I do not want to suppress all errors with PDO::ERRMODE_SILENT
Is any possibility to determine next rowset is present before calling nextRowset()? Or how can I handle the issue other way?
Thanks.

**Comment by yitam** [comment]
Hi @epoxa 

This is related to #581, which we are currently investigating. We will keep you posted.

**Comment by epoxa** [comment]
Ah really! Thanks a lot
