### ISSUE TITLE
Documentation Link Anchors Incorrect

### ISSUE THREAD

**Issue by v-chojas** [Microsoft/msphpsql#593]
## Driver version or file name
Haven't installed it (yet)

## SQL Server version
2016

## Client operating system
CentOS68

## PHP version
Haven't installed it (yet)

## Microsoft ODBC Driver version
Haven't installed it (yet)

## Table schema
Haven't created any (yet)

## Problem description
Go to https://github.com/Microsoft/msphpsql/wiki/Install-and-configuration and click on the links in the Contents.

## Expected behavior and actual behavior
Expected: The browser should scroll to the appropriate section.

Actual: Nothing happens.

## Repro code
The anchors in the links are incorrect. For example, "End to End Installation instructions" links to https://github.com/Microsoft/msphpsql/wiki/Install-and-configuration#EndToEnd but the actual anchor is named "#end-to-end-installation-instructions", as can be seen from the source:
```
<a id="user-content-end-to-end-installation-instructions" class="anchor" href="#end-to-end-installation-instructions" 
```

**Comment by yitam** [comment]
Hi @v-chojas we used the links provided on the page. For example, hover to the left of each section title until you see the chain symbol. Then you will see the url

**Comment by v-chojas** [comment]
Yes, those URLs show the correct anchors, but your links in the Contents don't.

For example, you have the link in the contents to anchor "EndToEnd":
```
<li><a href="#EndToEnd">End to End Installation instructions</a></li>
```
...but the actual section header's anchor is titled "end-to-end-installation-instructions":
```
<a id="user-content-end-to-end-installation-instructions" class="anchor" href="#end-to-end-installation-instructions" ...> ... </a>End to End Installation instructions</h2>
```
Thus, you should change either of the hrefs to match.

**Comment by yitam** [comment]
This is Markdown, and the anchors are created like the examples in [here](https://gist.github.com/asabaylus/3071099)
I've tested in more than one web browser and the links work perfectly. I could even open new links using the anchors. There is no need to make any change. Closing this issue.

**Comment by v-chojas** [comment]
The links are incorrect, it appears to be using raw HTML and thus conflicting with the autogenerated anchors. Please see https://github.com/Microsoft/msphpsql/wiki/Install-and-configuration/_edit

**Comment by yitam** [comment]
There are no conflicts. Tested with IE, Edge, Chrome, Safari, and Firefox.
