### ISSUE TITLE
PDO_SQLSRV Mac OS issue

### ISSUE THREAD

**Issue by joao-s-neves** [Microsoft/msphpsql#602]
Hi guys, I need some help installing PDO SQL Server drivers for Mac OS X.
Followed this (https://github.com/Microsoft/msphpsql/tree/dev#install-unix) tutorial and everything went well. Except for the fact that the PDO drivers don't show up in phpinfo(); despite the command "php -m | grep sqlsrv" showing me the drivers.
Also, phpinfo() is showing me the path to a php.ini that's completely empty, and when I do php --ini it points me out to a php.ini that has zero extensions on it.
Can someone help me out?

Using php7.1

**Comment by yitam** [comment]
Hi @joao-s-neves, are you saying that you see pdo_sqlsrv when you did `php -m | grep sqlsrv` and yet you can's find pdo_sqlsrv in phpinfo()?
Did you do PECL install? 
Which version of macOS are you using?

What's the output of `php --ri pdo_sqlsrv`?
What's the output of `php --ini`?

**Comment by joao-s-neves** [comment]
Nevermind, just solved it. Had various php.ini and apache was not pointing to the correct one
