### ISSUE TITLE
5.1.2preview missing on PECL ?

### ISSUE THREAD

**Issue by remicollet** [Microsoft/msphpsql#604]
Hi,

I noticed 5.1.2preview have been tagged here but missing on 

* https://pecl.php.net/package/sqlsrv
* https://pecl.php.net/package/pdo_sqlsrv

**Comment by yitam** [comment]
Yes we will upload them today. Please stay tuned.

**Comment by yitam** [comment]
@remicollet just so you know, we have uploaded the packages. Closing this issue now.
