### ISSUE TITLE
Batch query with mixture of direct query and parameterized query returns Invalid Descriptor Index error in a Column Encryption Enabled connection

### ISSUE THREAD

**Issue by v-kaywon** [Microsoft/msphpsql#607]
## Driver version or file name
 5.1.2
 
 ## SQL Server version
SQL Server 2016
 
 ## Client operating system
Windows 10
 
 ## PHP version
7.1.11
 
 ## Microsoft ODBC Driver version
17
 
 ## Table schema
(id int, class int, value char(32))
the table schema isn't really relevant
 
 ## Problem description
 When preparing a batched query with a mixture of direct query and parameterized query (specifically, direct query *before* parameterized query), an **Invalid Descriptor Index** is thrown.
 
 ## Expected behavior and actual behavior
No exception should be thrown
 
 ## Repro code
```
try {
    $conn = new PDO("sqlsrv:server = $server; Database = $databaseName; ColumnEncryption=Enabled;", $uid, $pwd);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    $tableName = "pdo_test_table";
    $conn->exec("IF OBJECT_ID('$tableName', 'U') IS NOT NULL DROP TABLE $tableName");
    $conn->exec("CREATE TABLE pdo_test_table ([id] int ENCRYPTED WITH (ENCRYPTION_TYPE = deterministic, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256', COLUMN_ENCRYPTION_KEY = AEColumnKey) ,
	                                          [class] int ENCRYPTED WITH (ENCRYPTION_TYPE = deterministic, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256', COLUMN_ENCRYPTION_KEY = AEColumnKey) ,
	                                          [value] char(32) COLLATE Latin1_General_BIN2 ENCRYPTED WITH (ENCRYPTION_TYPE = deterministic, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256', COLUMN_ENCRYPTION_KEY = AEColumnKey))");

    // prepare and execute batch query
    $directQuery = "SELECT 1";
    $parameterizedQuery = "INSERT INTO $tableName VALUES(?, ?, ?)";
    $stmt = $conn->prepare("$directQuery; $parameterizedQuery");
    $id = 1;
    $class = 4;
    $value = '2011';
    $stmt->bindParam(1, $id);
    $stmt->bindParam(2, $class);
    $stmt->bindParam(3, $value);
    $stmt->execute();

    $conn->exec("DROP TABLE $tableName");
    unset($stmt);
    unset($conn);
} catch (Exception $e) {
    echo $e->getMessage();
}
?>

**Comment by yitam** [comment]
The [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-api/sqldescribeparam) clearly indicates that `When processing a batch of Transact-SQL statements, the driver also does not support calling SQLDescribeParam for parameter markers in statements after the first statement in the batch.`

**Comment by yitam** [comment]
Updated our Wiki section on [binding parameters in AE](https://github.com/Microsoft/msphpsql/wiki/Features#aebindparam).
