### ISSUE TITLE
MSSQL physloc is garbage on php retrieval

### ISSUE THREAD

**Issue by mrduckelsDev** [Microsoft/msphpsql#611]
+## Driver version or file name
 + /usr/lib/php/20160303/pdo_sqlsrv.so
 + /usr/lib/php/20160303/sqlsrv.so
 
 +## SQL Server version
 + SQL SERVER 2012 Express Edition
 + Microsoft SQL Server Management Studio						11.0.2100.60
 + Microsoft Data Access Components (MDAC)						6.3.9600.17415
 + Microsoft MSXML						3.0 6.0 
 + Microsoft Internet Explorer						9.11.9600.18838
 + Microsoft .NET Framework						4.0.30319.42000
 + Operating System						6.3.9600
 
 +## Client operating system
 +Linux Ubuntu 16.04
 
 +## PHP version
 +PHP 7.1.11-1
 
 +## Problem description
 +The MSSQL physloc hex number is returned as garbage. It worked well on PHP 7.0 (with another MSSQL driver).
 
 +## Expected behavior and actual behavior
 +We should receive a string with the hex value in it, in stead it is a string with garbage. Switching back to PHP 7.0 (with the other, non-MS, MSSQL driver) fixes the problem.
 
 +## Repro code (PHP pseudo code just for the idea!)
```
$physLocQuery = 'select %%physloc%% AS physloc from tableX';
$physLocQuery->run();
print_r($physLocQuery->physloc);

```

**Comment by david-puglielli** [comment]
Hi @mrduckelsDev, retrieving binary hex data in the sqlsrv driver is done by returning a php string type, as the following snippet shows:
```
$stmt = sqlsrv_query($conn, "select %%physloc%% AS physloc from tblA");
if(sqlsrv_fetch($stmt))
{
    $field = sqlsrv_get_field($stmt, 0, SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_CHAR));
    print_r($field);
}
```
The default is to return binary data as a PHP stream using SQLSRV_PHPTYPE_STREAM(), which is useful for images (for example) but will produce garbage on the command line. To get the hex value of a binary stream, you must set the optional third argument in sqlsrv_get_field to return a SQLSRV_PHPTYPE_STRING. More information on default data types [here](https://docs.microsoft.com/en-us/sql/connect/php/default-php-data-types); note that all binary types default to using streams.

**Comment by david-puglielli** [comment]
@mrduckelsDev do you still have questions? I will close this issue now, please reopen if you have any.

**Comment by mrduckelsDev** [comment]
Hi no thanks please close it, I will try a solution if it doesnt work I'll post it here. Thanks again.
