### ISSUE TITLE
README pointer to Debian 9/stretch prod.list not available

### ISSUE THREAD

**Issue by pniederlag** [Microsoft/msphpsql#641]
The README in section "Step 2: Install Prerequisites" for debian 9 contains a link to  https://packages.microsoft.com/config/debian/9/prod.list which is not available.

If there are no packages/support for debian 9/stretch yet please indicate that properly, thx.

**Comment by yitam** [comment]
For Debian 9 it requires [ODBC 17 preview](https://github.com/Microsoft/msphpsql/wiki/Install-and-configuration#debian-8-and-9)
We will modify README accordingly. Please let us know if this helps.

**Comment by lilgreenbird** [comment]
hi @pniederlag you can find the Debian 9 preview binaries [here](https://github.com/Microsoft/msphpsql/tree/master/ODBC%2017%20binaries%20preview/Debian%209)

**Comment by yitam** [comment]
Closing this issue. Please feel free to reopen.
