### ISSUE TITLE
SQL CONNECTION ERROR: [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found

### ISSUE THREAD

**Issue by dccsp92** [Microsoft/msphpsql#647]
I ran the following on a Ubuntu Linux 17.10 machine to do the install as per the instructions:
  739  sudo bash -c "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -"
  740  sudo bash -c "curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list"
  741  sudo apt-get update
  742  yes | sudo ACCEPT_EULA=Y apt-get install -y msodbcsql mssql-tools
  743  yes | sudo apt-get purge -y mssql-tools msodbcsql 
  744  dpkg -i /home/websites/msodbcsql_17.0.0.5-1_amd64.deb 
  745  dpkg -i /home/websites/mssql-tools_17.0.0.5-1_amd64.deb 
  746  ln -sfnv /opt/mssql-tools/bin/* /usr/bin
  747  echo $PATH
  748  pear config-set php_ini `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` system
  749  pecl install sqlsrv
  750  pecl install pdo_sqlsrv

I reloaded apache but when I try to run a script that works on other machines I am getting the error SQL CONNECTION ERROR: [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found

Why would it be looking for Driver 13 when 17 is the only thing that was ever installed?

**Comment by dccsp92** [comment]
Found the issue, if you are downloading the packages manually from https://github.com/Microsoft/msphpsql/tree/master/ODBC%2017%20binaries%20preview/Ubuntu%2017
You have to run 
sudo pecl install sqlsrv-5.2.0RC1
sudo pecl install pdo_sqlsrv-5.2.0RC1
instead of just pecl install sqlsrv and pecl install pdo_sqlsrv

**Comment by yitam** [comment]
Hi @dccsp92 looks like you've downloaded the previous release (stable) versions of sqlsrv/pdo_sqlsrv from pecl. In order to try ODBC 17 preview, you'll need the preview versions of sqlsrv/pdo_sqlsrv as well. First, ```pecl uninstall sqlsrv``` and ```pecl uninstall pdo_sqlsrv``` then install the drivers as follows:
```
pecl install sqlsrv-5.2.0RC1
pecl install pdo_sqlsrv-5.2.0RC1
```

If you prefer not to try the previews, then please wait for the upcoming release.

**Comment by yitam** [comment]
Ha @dccsp92 glad that you've figured it out yourself 👍
