### ISSUE TITLE
/private/tmp/pear/temp/sqlsrv/shared/xplat.h:30:10: fatal error: 'sql.h' file not found

### ISSUE THREAD

**Issue by zrubinrattet** [Microsoft/msphpsql#651]
+## Driver version or file name
 +Please tell us what the PHP driver version or file name is.
 +5.2.0-RC
 +## SQL Server version
 +Please tell us what the SQL Server version is.
 +4.1.7
 +## Client operating system
 +Please tell us what oprating system the client program is running on.
 + macOS 10.12.6 (16G1114)
 +## PHP version
 +Please tell us which version of PHP you are running.
 + 7.1.12
 +## Microsoft ODBC Driver version
 +Please tell us which version of the Microsoft ODBC Driver you are using.
 + 13.1.9.0
 +## Table schema
 +Please tell us the table schema
 + N/A
 +## Problem description
 +Please share more details with us.
 + running `sudo pecl install sqlsrv` returns error: /private/tmp/pear/temp/sqlsrv/shared/xplat.h:30:10: fatal error: 'sql.h' file not found
 +## Expected behavior and actual behavior
 +Please tell us what should happen and what happened instead
 + No error and make to finish properly
 +## Repro code
 +Please share repro code with us, or tell us how to reproduce the issue.
 follow your instructions for php 7.1 and on macOS

**Comment by yitam** [comment]
hi @zrubinrattet , did you install this in a clean env or you have installed previous versions of PHP / sqlsrv drivers?

**Comment by zrubinrattet** [comment]
i'm not sure if i did a clean install and i had 5.6 installed previously. when i do php -v it says i'm running 7.1.12

**Comment by yitam** [comment]
Please try `pecl version`. What's the output?
Also, did you install the drivers by following these steps?
```
chmod -R ug+w /usr/local/opt/php71/lib/php
pear config-set php_ini /usr/local/etc/php/7.1/php.ini system

pecl install sqlsrv-5.2.0RC1
pecl install pdo_sqlsrv-5.2.0RC1
```

**Comment by zrubinrattet** [comment]
output from pecl version:

PEAR Version: 1.10.5
PHP Version: 7.1.12
Zend Engine Version: 3.1.0
Running on: Darwin Rheas-Computer.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

I haven't tried installing those specific versions yet but I get the same error:

/private/tmp/pear/temp/pdo_sqlsrv/shared/xplat.h:30:10: fatal error: 'sql.h' file not found

**Comment by yitam** [comment]
But you said you had our drivers with version 5.2.0-RC?
If you don't specify the versions pecl will install the previous stable version, which is v4.3.0. 
When the system can't find 'sql.h' there are different reasons. Have you tried to find it?

`find / -name sql.h`

Please also check a related issue #373 and see if you get any idea there.

**Comment by zrubinrattet** [comment]
my miscommunication.
here's the result from running `find / -name sql.h`
/usr/local/Cellar/unixodbc/2.3.4/include/sql.h

I have checked that issue and got nowhere.

**Comment by zrubinrattet** [comment]
i've been trying to run pecl install sqlsrv and i keep getting that error. i've followed the steps in the readme having never done them before. im on macos 10.12.6 (16G1114). hopefully that is clearer. thanks

**Comment by yitam** [comment]
Hi @zrubinrattet, 

First, can you find sql.h in `/usr/local/include/sql.h`?

If yes, what's your env path? Type `echo $PATH`

If /usr/local/bin is not in path, please type `export PATH="/usr/local/bin:${PATH}"`

**Comment by zrubinrattet** [comment]
Hi @yitam 

I looked in `/usr/local/include/` and i did not find a file named sql.h what should i do now? thanks!

**Comment by yitam** [comment]
Did you check your $PATH as I mentioned above?

**Comment by zrubinrattet** [comment]
Here is the result from `echo $PATH`: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/git

**Comment by yitam** [comment]
Looks like brew did not symlink, please type `brew doctor`. Do you see any warnings?

**Comment by zrubinrattet** [comment]
Yes here's the dump from `brew doctor`: 

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/android-ifaddrs.h
  /usr/local/include/node/ares.h
  /usr/local/include/node/ares_build.h
  /usr/local/include/node/ares_rules.h
  /usr/local/include/node/ares_version.h
  /usr/local/include/node/libplatform/libplatform.h
  /usr/local/include/node/nameser.h
  /usr/local/include/node/node.h
  /usr/local/include/node/node_buffer.h
  /usr/local/include/node/node_object_wrap.h
  /usr/local/include/node/node_version.h
  /usr/local/include/node/openssl/aes.h
  /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
  /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
  /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux32-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
  /usr/local/include/node/openssl/asn1.h
  /usr/local/include/node/openssl/asn1_mac.h
  /usr/local/include/node/openssl/asn1t.h
  /usr/local/include/node/openssl/bio.h
  /usr/local/include/node/openssl/blowfish.h
  /usr/local/include/node/openssl/bn.h
  /usr/local/include/node/openssl/buffer.h
  /usr/local/include/node/openssl/camellia.h
  /usr/local/include/node/openssl/cast.h
  /usr/local/include/node/openssl/cmac.h
  /usr/local/include/node/openssl/cms.h
  /usr/local/include/node/openssl/comp.h
  /usr/local/include/node/openssl/conf.h
  /usr/local/include/node/openssl/conf_api.h
  /usr/local/include/node/openssl/crypto.h
  /usr/local/include/node/openssl/des.h
  /usr/local/include/node/openssl/des_old.h
  /usr/local/include/node/openssl/dh.h
  /usr/local/include/node/openssl/dsa.h
  /usr/local/include/node/openssl/dso.h
  /usr/local/include/node/openssl/dtls1.h
  /usr/local/include/node/openssl/e_os2.h
  /usr/local/include/node/openssl/ebcdic.h
  /usr/local/include/node/openssl/ec.h
  /usr/local/include/node/openssl/ecdh.h
  /usr/local/include/node/openssl/ecdsa.h
  /usr/local/include/node/openssl/engine.h
  /usr/local/include/node/openssl/err.h
  /usr/local/include/node/openssl/evp.h
  /usr/local/include/node/openssl/hmac.h
  /usr/local/include/node/openssl/idea.h
  /usr/local/include/node/openssl/krb5_asn.h
  /usr/local/include/node/openssl/kssl.h
  /usr/local/include/node/openssl/lhash.h
  /usr/local/include/node/openssl/md4.h
  /usr/local/include/node/openssl/md5.h
  /usr/local/include/node/openssl/mdc2.h
  /usr/local/include/node/openssl/modes.h
  /usr/local/include/node/openssl/obj_mac.h
  /usr/local/include/node/openssl/objects.h
  /usr/local/include/node/openssl/ocsp.h
  /usr/local/include/node/openssl/opensslconf.h
  /usr/local/include/node/openssl/opensslv.h
  /usr/local/include/node/openssl/ossl_typ.h
  /usr/local/include/node/openssl/pem.h
  /usr/local/include/node/openssl/pem2.h
  /usr/local/include/node/openssl/pkcs12.h
  /usr/local/include/node/openssl/pkcs7.h
  /usr/local/include/node/openssl/pqueue.h
  /usr/local/include/node/openssl/rand.h
  /usr/local/include/node/openssl/rc2.h
  /usr/local/include/node/openssl/rc4.h
  /usr/local/include/node/openssl/ripemd.h
  /usr/local/include/node/openssl/rsa.h
  /usr/local/include/node/openssl/safestack.h
  /usr/local/include/node/openssl/seed.h
  /usr/local/include/node/openssl/sha.h
  /usr/local/include/node/openssl/srp.h
  /usr/local/include/node/openssl/srtp.h
  /usr/local/include/node/openssl/ssl.h
  /usr/local/include/node/openssl/ssl2.h
  /usr/local/include/node/openssl/ssl23.h
  /usr/local/include/node/openssl/ssl3.h
  /usr/local/include/node/openssl/stack.h
  /usr/local/include/node/openssl/symhacks.h
  /usr/local/include/node/openssl/tls1.h
  /usr/local/include/node/openssl/ts.h
  /usr/local/include/node/openssl/txt_db.h
  /usr/local/include/node/openssl/ui.h
  /usr/local/include/node/openssl/ui_compat.h
  /usr/local/include/node/openssl/whrlpool.h
  /usr/local/include/node/openssl/x509.h
  /usr/local/include/node/openssl/x509_vfy.h
  /usr/local/include/node/openssl/x509v3.h
  /usr/local/include/node/pthread-barrier.h
  /usr/local/include/node/pthread-fixes.h
  /usr/local/include/node/stdint-msvc2008.h
  /usr/local/include/node/tree.h
  /usr/local/include/node/uv-aix.h
  /usr/local/include/node/uv-bsd.h
  /usr/local/include/node/uv-darwin.h
  /usr/local/include/node/uv-errno.h
  /usr/local/include/node/uv-linux.h
  /usr/local/include/node/uv-sunos.h
  /usr/local/include/node/uv-threadpool.h
  /usr/local/include/node/uv-unix.h
  /usr/local/include/node/uv-version.h
  /usr/local/include/node/uv-win.h
  /usr/local/include/node/uv.h
  /usr/local/include/node/v8-debug.h
  /usr/local/include/node/v8-experimental.h
  /usr/local/include/node/v8-platform.h
  /usr/local/include/node/v8-profiler.h
  /usr/local/include/node/v8-testing.h
  /usr/local/include/node/v8-util.h
  /usr/local/include/node/v8-version.h
  /usr/local/include/node/v8.h
  /usr/local/include/node/v8config.h
  /usr/local/include/node/zconf.h
  /usr/local/include/node/zlib.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  c-ares
  jemalloc
  libev
  libevent
  libidn2
  libpng
  pcre
  unixodbc
Error: Formulae found in multiple taps: 
       * microsoft/msodbcsql/msodbcsql
       * microsoft/mssql-release/msodbcsql

Please use the fully-qualified name e.g. microsoft/msodbcsql/msodbcsql to refer the formula.

**Comment by yitam** [comment]
Please follow these steps, @zrubinrattet :
1. brew untap microsoft/msodbcsql
2. brew search msodbcsql (for this step you should now see only microsoft/mssql-release)
3. brew link unixodbc

**Comment by zrubinrattet** [comment]
Output from those commands: 

$ brew untap microsoft/msodbcsql
Untapping microsoft/msodbcsql... (36 files, 35.2KB)
Untapped 4 formulae
$ brew search msodbcsql 
==> Searching local taps...
microsoft/mssql-release/msodbcsql ✔                          microsoft/mssql-release/msodbcsql@13.1.7.0
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...
$ brew link unixodbc
Linking /usr/local/Cellar/unixodbc/2.3.4... 
Error: Could not symlink share/man/man5/odbc.ini.5
/usr/local/share/man/man5 is not writable.

**Comment by yitam** [comment]
Then in this case this is something to do with homebrew. This [issue](https://stackoverflow.com/questions/26647412/homebrew-could-not-symlink-usr-local-bin-is-not-writable) might be helpful to you, or you may want to try [Homebrew FAQ](https://docs.brew.sh/FAQ.html)

**Comment by zrubinrattet** [comment]
Ok after running `sudo chown -R `whoami`:admin /usr/local/bin` and `sudo chown -R `whoami`:admin /usr/local/share` i was able to run `brew link unixodbc`. what should i do now?

**Comment by yitam** [comment]
First you can see if sql.h is in `/usr/local/include/ ` 
If exists, perhaps try `pecl install again`?

**Comment by zrubinrattet** [comment]
Yes sql.h is in `/usr/local/include/`

running `pecl install sqlsrv` i get this error now:

-bash: /usr/local/bin/pecl: No such file or directory

**Comment by yitam** [comment]
As suggested above, something must have gone wrong during brew install and/or adding symlinks. You might consider uninstalling PHP first. 

```
brew uninstall --force php71
brew unlink php71
brew cleanup
```

Make sure php is indeed cleaned up before you reinstall by following our instructions. 

Alternatively, our [wiki page](https://github.com/Microsoft/msphpsql/wiki/Install-and-configuration#faq-about-install-and-configuration) might be useful.

**Comment by zrubinrattet** [comment]
I've tried again and when I run `brew install php70 --with-pear --with-httpd24 --with-cgi` I get:

$ brew install php70 --with-pear --with-httpd24 --with-cgi
==> Installing php70 from homebrew/php
==> Downloading https://php.net/get/php-7.0.27.tar.bz2/from/this/mirror
Already downloaded: /Users/rhea/Library/Caches/Homebrew/php70-7.0.27
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.27_19 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/ph
==> make
==> make install
==> /usr/local/Cellar/php70/7.0.27_19/bin/pear config-set php_ini /usr/local/etc/php/7.0/php.ini system
Last 15 lines from /Users/rhea/Library/Logs/Homebrew/php70/04.pear:
2018-01-05 13:57:33 -0500

/usr/local/Cellar/php70/7.0.27_19/bin/pear
config-set
php_ini
/usr/local/etc/php/7.0/php.ini
system


READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
php70-opcache: new testing method for module https://github.com/Homebrew/homebrew-php/pull/3905

**Comment by yitam** [comment]
hi @zrubinrattet I'm confused. I thought you wanted to install PHP 7.1, not 7.0?

**Comment by zrubinrattet** [comment]
sorry found out I need 7.0 from my boss. why am i getting these errors?

**Comment by yitam** [comment]
Please uninstall PHP 7.0 first similar to how you removed 7.1
After that, make sure whatever in /usr/local/etc/php/ has been removed (used to be 7.1 now you might see 7.0)
If not, remove 7.0 / 7.1 from /usr/local/etc/php/

If you still have problems, our [wiki page](https://github.com/Microsoft/msphpsql/wiki/Install-and-configuration#faq-about-install-and-configuration) might be helpful.

**Comment by zrubinrattet** [comment]
I removed all the folders in `/usr/local/etc/php` which were 7.0 and 7.1. I then ran `brew install php70 --with-pear --with-httpd24 --with-cgi` and got the same error as above.

**Comment by yitam** [comment]
Did you try the suggestions in the wiki page as mentioned above?

**Comment by zrubinrattet** [comment]
Finally got the .so files built! Ran through the common issues in the wiki there after all this and that did it. phew. Thanks for all your help!

**Comment by yitam** [comment]
So glad to hear that @zrubinrattet ! 
May I close the issue?

**Comment by zrubinrattet** [comment]
Yes thanks

**Comment by yitam** [comment]
Please feel free to re-open or create a new issue. Have a nice weekend :)

**Comment by raulast** [comment]
Hi, I had the same issue on MAC mini M1, however I was able to solve it in the following way:

`sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install sqlsrv`
`sudo CXXFLAGS="-I/opt/homebrew/opt/unixodbc/include/" LDFLAGS="-L/opt/homebrew/lib/" pecl install pdo_sqlsrv`

"... add the CXXFLAGS & LDFLAGS to point to unixodbc headers files and lib path, this helps to compile the modules with pecl..."

i took the guide from: https://github.com/microsoft/msphpsql/issues/198#issuecomment-326139609

hope it helpful

**Comment by radinsky** [comment]
This will resolve it:

`sudo apt-get install unixodbc-dev`

**Comment by ezlage** [comment]
@radinsky, your suggestion solved my problem on a Debian 11.3 server. Thank you!

**Comment by guilherme8787** [comment]
@radinsky, your suggestion solved my problem on a Docker with Debian 11. Thank you!

**Comment by seba1rx** [comment]
> This will resolve it:
> 
> `sudo apt-get install unixodbc-dev`

Thanks, this worked for me too
