### ISSUE TITLE
Windows server 2003. Error Error code 0x2746

### ISSUE THREAD

**Issue by MatthewPattell** [Microsoft/msphpsql#657]
## Driver version or file name
 latest
 ## SQL Server version
 SQL Server 2008R2 SP3
 ## Client operating system
 ubuntu 16.04
 ## PHP version
 php 7.1
 ## Microsoft ODBC Driver version
 ODBC 13.1
 ## Problem description
 If the server on which the MS SQL is installed is Windows Server 2003, I get an error (launch through  sqlcmd or php):
In php:
[unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2746
In console:
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Client unable to establish connection.

**Comment by v-kaywon** [comment]
@MatthewPattell , which SQL Server version are you using? Please note that starting from [SQL Server 2012](https://www.microsoft.com/en-ca/download/details.aspx?id=29062), Windows Server 2003 is no longer supported. As for the latest stable PHP Drivers version (version 4.3), the oldest SQL Server we support is SQL Server 2008 R2.

**Comment by MatthewPattell** [comment]
@v-kaywon SQL Server 2008R2 SP3

**Comment by v-kaywon** [comment]
@MatthewPattell , unfortunately the PHP Drivers and the ODBC Driver do not support Window Server 2003 because of lack of TLS 1.2 support (see #252).
