### ISSUE TITLE
php 7.1 with Apache on Windows 7 sp1 can't load sql server driver extension

### ISSUE THREAD

**Issue by maxp76** [Microsoft/msphpsql#661]
Hello, I can't load sql server driver in php 7.1. I followed all the instructions on Microsoft and PHP websites, did the procedure many times, but always the same end.
This is what i did:
1) download the drivers from https://www.microsoft.com/en-us/download/details.aspx?id=20098
and extract the files in c:\php7\ext
2) edit php.ini as in the screenshot and edit extension_dir="c:\php7\ext"
3) restart apache

I run SQL SERVER 2012.

Thank you in advance for your help.

![screen shot 2018-01-12 at 19 50 39](https://user-images.githubusercontent.com/35380500/34890572-b86c0054-f7d2-11e7-8fe2-4ef6766ca7d2.png)

**Comment by yitam** [comment]
Hi @maxp76 
First, the drivers you downloaded were old. Should try to get 4.3.0 from [here](https://www.microsoft.com/en-us/download/details.aspx?id=55642)
In fact, we might soon release another stable version.

Besides, if you want to load 7.1 binaries, you should modify php.ini this way:
```
extension=php_pdo_sqlsrv_71_ts.dll
extension=php_sqlsrv_71_ts.dll
```

Looks like you downloaded our PHP 7 binaries and tried to load them PHP 7.1
You have to make sure the PHP versions match.

Hope this helps.

**Comment by maxp76** [comment]
Hi yitam!
I used old drivers 4.0 because at that link system requirements no include Windows 7. Anyway I follow your advice and now works! Thank you very much!

**Comment by yitam** [comment]
Wonderful! Yes we are fixing the download links in our documentation. Our oversight. Glad that now it works for you, @maxp76 
Closing this issue now. Please feel free to reopen or create new ones if necessary.
