### ISSUE TITLE
NULL values and data truncation due to automatic data types conversion

### ISSUE THREAD

**Issue by atlix** [Microsoft/msphpsql#668]
Driver version or file name: php-sqlsrv-5.1.2~preview-1.el7.remi.7.0.x86_64
SQL Server version: Microsoft SQL Server 2016 (SP1-GDR) (KB4019089) - 13.0.4206.0 (X64)
Client operating system: Windows Server 2012 64-bit
PHP version: 7.0
Microsoft ODBC Driver version: 13

We are migrating from FreeTDS to Doctrine PDOSQLSrv or SQLSrv (trying both at the monent) and have encountered the problem with the data truncation of the fields that are not updated.

Our update statements look like

`update tbl set field1 = isnull(?, field1), field2 = isnull(?, field2) where id = ?`
We have investigated that it is caused by the data type conversion. FreeTDS runs the queries as is, so when you pass the NULL value, NULL is used. However PDOSQLSrv and SQLSrv run queries with sp_prepexec stored procedure, so it is not NULL any more, but a NULL-valued variable.

Unfortunately both libraries convert PHP nulls to char(1) (in documentation https://docs.microsoft.com/en-us/sql/connect/php/default-sql-server-data-types it is said to be varchar(1) but still it doesn't help, I can see char(1) in the Profiler), so when the field is not updated and we pass NULL, it truncates the data.

Full code example:
```

use Doctrine\DBAL\DriverManager;

include_once __DIR__ . '/vendor/autoload.php';

$connectionOptions = array_merge(
    ['driverClass' => '\Doctrine\DBAL\Driver\PDOSqlsrv\Driver'],
    ['host' => '127.0.0.1', 'port' => 1433, 'dbname' => 'users', 'user' => '', 'password' => '']
);

try {
    $conn = DriverManager::getConnection($connectionOptions);
} catch (\Exception $e) {
    die($e->getMessage());
}

$userId = 1;
$nick = 'test';

try {
    $result = $conn->executeUpdate(
        'UPDATE users.users SET user_nick = isnull(:nick, user_nick) WHERE user_id = :userId',
        ['nick' => $nick, 'userId' => $userId],
        ['nick' => \PDO::NULL_EMPTY_STRING, 'userId' => \PDO::PARAM_INT]
    );
} catch (\Exception $e) {
    die($e->getMessage());
}
```
So the question is how to pass null correctly?

**Comment by yitam** [comment]
Hi @atlix 

I'm not sure which driver you plan to use, but based on your repro script I believe you wanted to try pdo_sqlsrv, which conforms to the [predefined set of APIs](https://docs.microsoft.com/en-us/sql/connect/php/pdo-sqlsrv-driver-reference) 

In your case, you might want to try using [bindParam](https://docs.microsoft.com/en-us/sql/connect/php/pdostatement-bindparam)

Here is an example for you

```
try {
    $conn = new PDO("sqlsrv:Server=$server; database=$database;", $uid, $pwd);
    // here you might want to check if this table exists first
    $conn->query("CREATE TABLE Users (user_id int, user_nick varchar(50))");
    $stmt = $conn->query("INSERT INTO Users VALUES (1, 'test1')");
    $stmt = $conn->query("INSERT INTO Users VALUES (2, 'test2')");

    $userId = 1;
    $nick = 'test_one';

    // update user 1
    $stmt = $conn->prepare('UPDATE Users SET user_nick = :nick WHERE user_id = :userId');
    $stmt->bindParam(':nick', $nick);
    $stmt->bindParam(':userId', $userId);
    $stmt->execute();
    
    // fetch data to check if the update was actually successful
    $stmt2 = $conn->prepare('SELECT * FROM Users');
    $stmt2->execute();
    while ($row = $stmt2->fetch(PDO::FETCH_ASSOC)) {  
        print_r($row);
    }  
    
    // update user 2
    $userId = 2;
    $nick = null;
    $stmt->execute();

    // fetch data to check if the update was actually successful
    $stmt2->execute();
    while ($row = $stmt2->fetch(PDO::FETCH_ASSOC)) {  
        print_r($row);
    }  

} catch (\Exception $e) {
    die($e->getMessage());
}

```

**Comment by atlix** [comment]
Greetings, @yitam ! Thank you for your answer.
We tested your sample code and there's no data truncation. 
Query like `UPDATE Users SET user_nick = :nick WHERE user_id = :userId` works fine, but when we try to use isnull(), we got bad result (got just first letter). 
Sample:
`UPDATE users.Users SET user_nick = isnull(:nick, user_nick) WHERE user_id = :userId`
We have many queries with insull() function in our projects and hoped that we could use them with the Microsoft pdo_sqlsrv driver, but now it's impossible.
Do you have any idea why isnull corrupting the data?

**Comment by yitam** [comment]
Hello @atlix 

Glad to know that my example works for you!

However, I'm not sure about the usage of isnull(), partly because in php the method is called [is_null()](http://php.net/manual/en/function.is-null.php) but mainly because `is_null()` returns a boolean. Based on your script above it seems that you're setting `user_nick` with a boolean value

Please let me know if I have misunderstood your sample script.

**Comment by atlix** [comment]
i'm about this isnull
https://docs.microsoft.com/en-US/sql/t-sql/functions/isnull-transact-sql
You can see it in my sample query at previous comment.

**Comment by yitam** [comment]
My bad. Yes I see it now. It looks like you want to update `user_nick` with `:nick` but leave it alone if the value of `:nick` is null?

**Comment by atlix** [comment]
Yep, if a value is passed in the parameter, then it will take it. And if passed null, then the current value is taken from the table

**Comment by yitam** [comment]
Yes @atlix we can reproduce the issue of updating the `user_nick` with only the first character when null is passed as a parameter. We will investigate further.

**Comment by atlix** [comment]
hope it's minor bug and you can fix it soon, cause we want to use Microsoft's driver in our new projects.

**Comment by David-Engel** [comment]
Hi @atlix ,

This isn't a bug in the driver. See the ISNULL documentation:
https://docs.microsoft.com/en-us/sql/t-sql/functions/isnull-transact-sql:

> ISNULL ( check_expression , replacement_value )

> Returns the same type as check_expression. **If a literal NULL is provided as check_expression, returns the datatype of the replacement_value.** If a literal NULL is provided as check_expression and no replacement_value is provided, returns an int.

In other words, your SQL worked fine as long as FreeTDS used the literal NULL for the check_expression. But since you are now using variables via the PHP driver, check_expression is no longer the literal NULL and the return value is of the same type as the variable being passed as the check_expression instead of the replacement_value.

You can observe similar behavior in SQL Server simply by running:
`select ISNULL(CAST(null as varchar(1)), 'its just i') as using_isnull, COALESCE(CAST(null as varchar(1)), 'its all there') as using_coalesce`

Which returns:

|using_isnull|using_coalesce|
|-|-|
|i|its all there|

You need to modify your SQL. I think the easiest change for you may simply be to change your ISNULL functions to COALESCE:
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/coalesce-transact-sql

Regards,
David

**Comment by atlix** [comment]
Thank you for detailed explain, COALESCE works fine for us.
