### ISSUE TITLE
Help me for php and sql server connection

### ISSUE THREAD

**Issue by Snayder187** [Microsoft/msphpsql#669]
Hello, I have a problem when I want to connect my xampp (php) with my sql server, I downloaded the latest version of Microsoft Drivers for PHP for SQL Server that comes up to 7.1 and in Xampp I have version 7.2 (capable that's the problem) and SQLSRV43. This is my code:

<? php
$ serverName = "localhost";
$ connectionInfo = array ("Database" => "SIGVENTAS", "UID" => "DESIGN", "PWD" => "", "CharacterSet" => "UTF-8");
$ con = sqlsrv_connect ($ serverName, $ connectionInfo);
 
  if ($ con) {
  echo "successful connection!";
  } else {
  echo "connection failure";
  }
?>

But I get error in line 4 bone with the connection. What can be wrong?

**Comment by lilgreenbird** [comment]
hi @Snayder187, I can't tell what "line 4 bone"? your code doesn't seem to be formatted correctly.

Also, if your xampp is PHP 7.2 then you need to use the 7.2 binaries and not 7.1.

**Comment by lilgreenbird** [comment]
hi @Snayder187, are you still having issues with this? Please let us know otherwise we will close this issue due to inactivity. Thanks..
