### ISSUE TITLE
Restructuring Setup Docs

### ISSUE THREAD

**Issue by benyanke** [Microsoft/msphpsql#672]
Would you be open to a PR restructuring the config to read more inline? Currently, there's lots of scrolling and cherry picking of code segments to get the bash commands required.

Currently the visual flow is such, causing the reader to have to lots of visual jumps, and is very prone to error.

```
-- section 1
[skip]
[skip]
[read]
[skip]

-- section 2
[skip]
[skip]
[read]
[skip]

-- section 3
[skip]
[skip]
[read]
[skip]
```

I would propose it would be easier to use with a format like:

```
-- section 1
[read]
[read]
[read]

-- section 2
[skip]
[skip]
[skip]

-- section 3
[skip]
[skip]
[skip]

-- section 4
[skip]
[skip]
[skip]
```

This could even be implemented as different files for each distribution. I would be willing to assist in reformatting this, but don't want to do the work if it's going to get rejected.

**Comment by yitam** [comment]
@benyanke did you mean the instructions on our README? If so, we are in the process of updating the [docs](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac) 

In this case, README will only provide the link to this page. We welcome suggestions, so please let us know how we can improve further.

**Comment by benyanke** [comment]
Yes, I am discussing the README. 

Also, I'd strongly suggest keeping the setup instructions, at least a copy of them, somewhere in the repo. It makes life much easier, as well as keeps them with the code if the MS page ever goes away or changes, and keeps it versioned along with the code it's supporting.

**Comment by yitam** [comment]
Good point, @benyanke. We will move the installation instructions in README to a separate MD file instead so that it's version-controlled with each release, stable or preview. Please wait until this is done for the upcoming release, and we welcome any feedback / suggestions afterwards.

**Comment by benyanke** [comment]
Absolutely, thanks!

**Comment by yitam** [comment]
FYI, we are closing this issue @benyanke 
The documentation has been updated.
