### ISSUE TITLE
Unable to connect on debian 9 php7

### ISSUE THREAD

**Issue by Lehnerr** [Microsoft/msphpsql#686]
+## Driver version or file name
 +Please tell us what the PHP driver version or file name is.
Microsoft ODBC Driver 17
 +
 +## SQL Server version
 +Please tell us what the SQL Server version is.
Microsoft SQL Server 2014 - 12.0.2269.0 (X64) Jun 10 2015 03:35:45 Copyright (c) Microsoft Corporation Enterprise Edition (64-bit) on Windows NT 6.3 (Build 9600: ) (Hypervisor) 
 +
 +## Client operating system
 +Please tell us what oprating system the client program is running on.
debian 9
 +
 +## PHP version
 +Please tell us which version of PHP you are running.
7.0
 +
 +## Microsoft ODBC Driver version
 +Please tell us which version of the Microsoft ODBC Driver you are using.
 +
Microsoft ODBC Driver 17
 +## Table schema
 +Please tell us the table schema
 +
 +## Problem description
 +Please share more details with us.
 +
I've done all installationsteps wich are metioned in the  README.md  for Debian 9.
The i created the mentioned Sample app https://github.com/Microsoft/msphpsql#step-6-create-your-sample-app .
I entered my db-settings in this file and get following in Browser:
Error information:
SQLSTATE: IMSSP
Code: -14
Message: An invalid parameter was passed to sqlsrv_query.

In apache Log i found:
PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, boolean given in /var/www/html/mstest.php on line 13

I've done all Stuff on Ubunto16.04 which works fine.
Think there is a problem witht the Driver on Debian 9

 +## Expected behavior and actual behavior
 +Please tell us what should happen and what happened instead
 +
 +## Repro code
 +Please share repro code with us, or tell us how to reproduce the issue.
https://github.com/Microsoft/msphpsql#step-6-create-your-sample-app .

**Comment by david-puglielli** [comment]
@Lehnerr Which version of the sqlsrv driver are you using? Run `php --ri sqlsrv` to find out. I suspect you are running the last stable release, which does not support ODBC 17. You can upgrade to the latest preview by running `pecl install sqlsrv-5.2.0RC1`.

**Comment by Lehnerr** [comment]
That helps.
Thx.
