### ISSUE TITLE
How to have less verbose response from $exception->getMesssage()

### ISSUE THREAD

**Issue by funkflute** [Microsoft/msphpsql#687]
## Driver version or file name
php_pdo_sqlsrv_56_ts.dll
  
## SQL Server version
2014

## Client operating system
Windows 2012R2

## PHP version
5.6.32

## Microsoft ODBC Driver version
Microsoft Drivers for PHP for SQL Server Version 3.2

## Problem description

I moved from the old PHP SQLSRV to this, but the SQL error exception message returned from $e->getMessage() contain error codes and a file/line number, which is extraneous... Is there anyway to return them the way they did before, example:

Old SQLSRV driver returned this when calling $e->getMessage() when an SQL exception was triggered:

Invalid Marketing Vehicle (58) + Typical Offer (18)

New PDO/ODBC driver setup returns:

SQLSTATE[42000]: Syntax error or access violation: 50000 [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid Marketing Vehicle (58) + Typical Offer (152) (SQLExecute[50000] at ext\pdo_odbc\odbc_stmt.c:254)

 ## Expected behavior and actual behavior
SQL codes should only be retrieved from $e->getCode()

## Repro code
```
try {
	$pdo = new PDO('odbc:Server={XXXXX};Driver={ODBC Driver 13 for SQL Server};Database=XXXXX', 'XXXXX', 'XXXXX');
	$pdo->query("EXEC someStoredProcedure'); // throws SQLException
} catch(Exception $e) {
	echo $e->getMesssage(); // this is where error message is overly verbose
}
```

**Comment by david-puglielli** [comment]
@funkflute It appears you are using the pdo_odbc driver, which we are not responsible for and do not support. The pdo_sqlsrv driver simply returns an error message saying `SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Could not find stored procedure 'someStoredProcedure'.` We are happy to answer any question you may have about the sqlsrv or pdo_sqlsrv drivers however. To use the pdo_sqlsrv driver, replace `odbc:` at the beginning of your connection string with `sqlsrv:`.

**Comment by funkflute** [comment]
Okay, if I change it to use sqlsrv:
```
try {
	$pdo = new PDO('odbc:Server={XXXXX};Driver={ODBC Driver 13 for SQL Server};Database=XXXXX', 'XXXXX', 'XXXXX');
	$pdo->query("EXEC someStoredProcedure"); // throws SQLException
} catch(Exception $e) {
	echo $e->getMesssage(); // this is where error message is overly verbose
	exit;
}
```
is there any way to just return the error or SQL exception, without the "SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]" in front? Or should I just make a regex to remove it.

**Comment by david-puglielli** [comment]
Unfortunately there's no way to easily remove the extra stuff in the error message, so you'll need to parse the string yourself. [This issue](https://github.com/Microsoft/msphpsql/issues/414) goes into more detail about error codes and the fifth comment includes a regex you can use to get just the error message.

**Comment by funkflute** [comment]
Thanks.
