### ISSUE TITLE
Error while accessing MSSQL from Xampp on macOS High Sierra 

### ISSUE THREAD

**Issue by awaistariq** [Microsoft/msphpsql#693]
I am having sort of the same issue in accessing MSSQL from Php (Xampp on MacOS HighSierra) 
`ls -l libiconv* `
gives me

_> 
> lrwxr-xr-x  1 root  wheel       16 Oct 10 09:01 libiconv.2.4.0.dylib -> libiconv.2.dylib
> -r-xr-xr-x  1 root  wheel  2104288 Oct  3 08:51 libiconv.2.dylib
> lrwxr-xr-x  1 root  wheel       20 Oct 10 09:01 libiconv.dylib -> libiconv.2.4.0.dylib
>_ 

In error log I get this:

> dyld: lazy symbol binding failed: Symbol not found: _iconv_open
> Referenced from: /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so
> Expected in: flat namespace
> 

Can you help me?

**Comment by awaistariq** [comment]
I have two php versions as I have installed xampp. In terminal I get different version of php and in localhost phpinfo I get different. I believe mssql drivers installation using homebrew doesn't link it with xampp php instance. I don't know, this is my guess so far.

**Comment by yitam** [comment]
Yes @awaistariq, your guess might be valid. Do you see sqlsrv or pdo_sqlsrv in phpinfo?

You should see something like the followings (looks like you're using sqlsrv, so you should see at least `sqlsrv`):

```
sqlsrv support => enabled
ExtensionVer => 5.2.0+10619
...
pdo_sqlsrv support => enabled
ExtensionVer => 5.2.0+10619
```

Related to #478

**Comment by awaistariq** [comment]
Following is what I have.

![screen shot 2018-02-21 at 8 32 02 am](https://user-images.githubusercontent.com/3714825/36464618-dd748d98-16e1-11e8-98dd-a34b0087daff.png)
![screen shot 2018-02-21 at 8 32 29 am](https://user-images.githubusercontent.com/3714825/36464619-ddacdb76-16e1-11e8-8f2b-73f8c03c216b.png)

**Comment by yitam** [comment]
Hi @awaistariq, when you said you found differences in phpinfo, I should have asked you to compare these lines as well (running php in a terminal vs. localhost):

Configuration File (php.ini) Path 
Loaded Configuration File

**Comment by awaistariq** [comment]
In that case, this is the output from php -i :

> sqlsrv
> 
> sqlsrv support => enabled
> ExtensionVer => 4.3.0
> 

> 
> pdo_sqlsrv
> 
> pdo_sqlsrv support => enabled
> ExtensionVer => 4.3.0

**Comment by awaistariq** [comment]
I removed Xampp and Php came with it, but still it is not working. I have sqlsrv and pdo_sqlsrv extensions enabled in` php -i` Does https://github.com/Microsoft/homebrew-mssql-release/issues/12 has anything to do with my environment?

**Comment by yitam** [comment]
You're using version 4.3.0 so ODBC 13.1 should work, so the answer is 'no, not really related'. 
I'm not asking the output of `php -i` but the output of `php --ini`
Thank you for your patience.

**Comment by awaistariq** [comment]
php --ini is:
> Configuration File (php.ini) Path: /usr/local/etc/php/7.1
> Loaded Configuration File:         /usr/local/etc/php/7.1/php.ini
> Scan for additional .ini files in: /usr/local/etc/php/7.1/conf.d
> Additional .ini files parsed:      /usr/local/etc/php/7.1/conf.d/ext-xdebug.ini

**Comment by yitam** [comment]
Please bear with me as I tried to understand what's causing the problem. You started by installing PHP 7.1 via brew and pecl install our drivers, correct? 
Can you quickly try `brew info php71`

When you installed PHP and/or our drivers, did you already have xampp then?

**Comment by awaistariq** [comment]
Thank you for your help as well. Below is the what you asked:

> 
> homebrew/php/php71: stable 7.1.14 (bottled), HEAD
> PHP Version 7.1
> https://php.net
> Conflicts with:
>   php53 (because different php versions install the same binaries.)
>   php54 (because different php versions install the same binaries.)
>   php55 (because different php versions install the same binaries.)
>   php56 (because different php versions install the same binaries.)
>   php70 (because different php versions install the same binaries.)
>   php72 (because different php versions install the same binaries.)
> /usr/local/Cellar/php71/7.1.11_22 (349 files, 39.4MB)
>   Poured from bottle on 2017-11-05 at 14:39:30
> /usr/local/Cellar/php71/7.1.12_23 (349 files, 39.3MB)
>   Poured from bottle on 2017-12-03 at 13:09:07
> /usr/local/Cellar/php71/7.1.14_25 (512 files, 41.9MB) *
>   Poured from bottle on 2018-02-20 at 09:55:40
> From: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php71.rb
> ==> Dependencies
> Required: freetype ✔, gettext ✔, icu4c ✔, jpeg ✔, libpng ✔, libxml2 ✔, unixodbc ✔, readline ✔, openssl ✔
> Optional: enchant ✘, gmp ✘, webp ✘, postgresql ✘, httpd ✘
> ==> Options
> --with-cgi
> 	Enable building of the CGI executable (implies --without-fpm)
> --with-debug
> 	Compile with debugging symbols
> --with-embed
> 	Compile with embed support (built as a static library)
> --with-enchant
> 	Build with enchant support
> --with-gmp
> 	Build with gmp support
> --with-homebrew-curl
> 	Include Curl support via Homebrew
> --with-homebrew-libressl
> 	Include LibreSSL instead of OpenSSL via Homebrew
> --with-homebrew-libxml2
> 	Include Libxml2 support via Homebrew
> --with-homebrew-libxslt
> 	Include LibXSLT support via Homebrew
> --with-httpd
> 	Enable building of shared Apache Handler module
> --with-imap
> 	Include IMAP extension
> --with-libmysql
> 	Include (old-style) libmysql support instead of mysqlnd
> --with-mssql
> 	Include MSSQL-DB support
> --with-pdo-oci
> 	Include Oracle databases (requries ORACLE_HOME be set)
> --with-pear
> 	Build with PEAR
> --with-phpdbg
> 	Enable building of the phpdbg SAPI executable
> --with-postgresql
> 	Build with postgresql support
> --with-thread-safety
> 	Build with thread safety
> --with-webp
> 	Build with webp support
> --without-bz2
> 	Build without bz2 support
> --without-fpm
> 	Disable building of the fpm SAPI executable
> --without-ldap
> 	Build without LDAP support
> --without-legacy-mysql
> 	Do not include the deprecated mysql_ functions
> --without-mysql
> 	Remove MySQL/MariaDB support
> --without-pcntl
> 	Build without Process Control support
> --without-unixodbc
> 	Build without unixODBC support
> --HEAD
> 	Install HEAD version
> ==> Caveats
> The php.ini file can be found in:
>     /usr/local/etc/php/7.1/php.ini
> 
> ✩✩✩✩ Extensions ✩✩✩✩
> 
> If you are having issues with custom extension compiling, ensure that you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:
> 
>       PATH="/usr/local/bin:$PATH"
> 
> PHP71 Extensions will always be compiled against this PHP. Please install them using --without-homebrew-php to enable compiling against system PHP.
> 
> ✩✩✩✩ PHP CLI ✩✩✩✩
> 
> If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc, ~/.zshrc, ~/.profile or your shell's equivalent configuration file:
>   export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
> 
> ✩✩✩✩ FPM ✩✩✩✩
> 
> To launch php-fpm on startup:
>     mkdir -p ~/Library/LaunchAgents
>     cp /usr/local/opt/php71/homebrew.mxcl.php71.plist ~/Library/LaunchAgents/
>     launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php71.plist
> 
> The control script is located at /usr/local/opt/php71/sbin/php71-fpm
> 
> OS X 10.8 and newer come with php-fpm pre-installed, to ensure you are using the brew version you need to make sure /usr/local/sbin is before /usr/sbin in your PATH:
> 
>   PATH="/usr/local/sbin:$PATH"
> 
> You may also need to edit the plist to use the correct "UserName".
> 
> Please note that the plist was called 'homebrew-php.josegonzalez.php71.plist' in old versions of this formula.
> 
> With the release of macOS Sierra the Apache module is now not built by default. If you want to build it on your system you have to install php with the --with-httpd option. See  brew options php71 for more details.
> 
> By 31st March 2018 we will deprecate and archive the PHP tap.
> Some of the formulae will be migrated to homebrew-core.
> 
> For more details, see https://github.com/Homebrew/homebrew-php/issues/4721
> 
> To have launchd start homebrew/php/php71 now and restart at login:
>   brew services start homebrew/php/php71

**Comment by yitam** [comment]
Hi @awaistariq, the first thing I noticed is that you have quite many php versions installed (you see conflicts?). I think you should unlink them. This [page ](https://iandouglas.com/blog/howto-managing-multiple-versions-of-php-on-mac-os-x/) might be able to help.

**Comment by yitam** [comment]
Besides, you have multiple 7.1.* versions. You might need to uninstall or `brew upgrade --cleanup php71` . Alternatively, try `brew doctor` and see if it helps you diagnose the problem.

The [homebrew-php](https://github.com/Homebrew/homebrew-php) might also be helpful.

**Comment by awaistariq** [comment]
Finally, this nightmare came to an end. Your suggestions helped alot. Following is what I did:

1. Uninstalled Xampp and perhaps php came with it.
2. Installed Fresh Php from[ this ](https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions) with `--with-pear option`.
3. Follow above tutorial till Apache PHP Setup - Part 2.
4. Then follow instructions from Php [Mac OS](https://www.microsoft.com/en-us/sql-server/developer-get-started/php/mac/).
