### ISSUE TITLE
Issue with primary key on 5.2.0RC1

### ISSUE THREAD

**Issue by Pindzia** [Microsoft/msphpsql#694]
+## Driver version or file name
 +Please tell us what the PHP driver version or file name is.
 +sqlsrv and pdo_sqlsrv 5.2.0RC1
 +## SQL Server version
 +Please tell us what the SQL Server version is.
 +SQL Server 11
 +## Client operating system
 +Please tell us what oprating system the client program is running on.
 +Ubuntu16.04
 +## PHP version
 +Please tell us which version of PHP you are running.
 +Version => 7.0.27-1
 +## Microsoft ODBC Driver version
 +Please tell us which version of the Microsoft ODBC Driver you are using.
 +msodbcsql_13.1.9.2-1
 +## Table schema
 +Please tell us the table schema
 +
 +## Problem description
 +Please share more details with us.
 +Im using driver with Yii to manage connection between php and sqlsrv
 and after i move driver from 4.3.0 to 5.2.0RC1
Saving model drops Primary key during inserting new record to table
 +## Expected behavior and actual behavior
 +Please tell us what should happen and what happened instead
Normally as i used to in 4.3.0 that after saving new model I've had access to primary key
after upgrading to new versions of drivers i don t have access to PK
 +
 +## Repro code
 +Please share repro code with us, or tell us how to reproduce the issue.
if($model->save)
{
    $id = $model->id;// it s empty here but it shouldn't
}

**Comment by yitam** [comment]
Hello @Pindzia 

We do not support Yii, so we need more details about how to reproduce your problem. Do you use both sqlsrv and pdo_sqlsrv? 

Which methods did you use to save $model? What's your table schema?

**Comment by Pindzia** [comment]
I have made some reasearch about this how could it be connected with the PDO.
($model->save()) -> invoke method insert()
https://github.com/yiisoft/yii/blob/1.1.19/framework/db/ar/CActiveRecord.php#L1073
there is a builder which trying to return last id by using connection to database with PDO here:
https://github.com/yiisoft/yii/blob/1.1.19/framework/db/CDbConnection.php#L561
and finally pdo is created like this:
https://github.com/yiisoft/yii/blob/1.1.19/framework/db/CDbConnection.php#L430
i couldn t go deeper into PDO implementation so it seems you should've know now if there is any kind of bug because instead of returning null it gives me an empty string on ID(PK) of currently saved model
I use both sqlsrv and pdo_sqlsrv and default 'dbo' table schema.

**Comment by yitam** [comment]
Hi @Pindzia 

This is due to the changes in our API [lastinsertid](https://github.com/Microsoft/msphpsql/wiki/Features#lastinsertid) to conform to the expected behavior outlined in [PDO::lastinsertid](http://php.net/manual/en/pdo.lastinsertid.php).

This also explains why we changed our driver versions from v4.* to v5.*

Please contact the support of Yii to inform them of this breaking change in our drivers. Thank you.

**Comment by Pindzia** [comment]
Thank you for help then.
I'm very grateful
