### ISSUE TITLE
Cannot connect to MSSQL on local network - Centos / php72 / mssql2017

### ISSUE THREAD

**Issue by Carpesimia** [Microsoft/msphpsql#703]
+## Driver version or file name
 +Please tell us what the PHP driver version or file name is.
 pdo_sqlsrv, sqlsrv
 +## SQL Server version
 +Please tell us what the SQL Server version is.
 Sql Server Express 2017
 +## Client operating system
 +Please tell us what oprating system the client program is running on.
 Centos 7
 +## PHP version
 +Please tell us which version of PHP you are running.
 php 7.2
 +## Microsoft ODBC Driver version
 +Please tell us which version of the Microsoft ODBC Driver you are using.
 extension = sqlsrv.so
 extension = pdo_sqlsrv.so
 +## Table schema
 +Please tell us the table schema
 +
 +## Problem description
 +Please share more details with us.
 Cannot connect.  Can't connect via code, can't connect via sqlcmd.  I can connect fine from SQL Server Management Console, though.

SQLCMD:
[root@rfmdev tmp]# sqlcmd -S 192.168.151.40 -U myuser -P 'mypass'
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

My Code:
```
<?php
    $serverName = "192.168.151.40";
    $connectionOptions = array(
        "Database" => "mydb",
        "Uid" => "myuser",
        "PWD" => "mypass"
    );
    //Establishes the connection
    $conn = sqlsrv_connect($serverName, $connectionOptions);
    if($conn) {
        echo "Connected!";
    }
    else {
        die( print_r( sqlsrv_errors(), true));
    }
?>
```

output:

```
Array
(
    [0] => Array
        (
            [0] => HYT00
            [SQLSTATE] => HYT00
            [1] => 0
            [code] => 0
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
        )

    [1] => Array
        (
            [0] => 08001
            [SQLSTATE] => 08001
            [1] => 10057
            [code] => 10057
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2749
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2749
        )

    [2] => Array
        (
            [0] => 08001
            [SQLSTATE] => 08001
            [1] => 10057
            [code] => 10057
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.
        )

)
```

 +
 +## Expected behavior and actual behavior
 +Please tell us what should happen and what happened instead
 Expected:  To connect.
 Actual:  Did not connect.

 +## Repro code
 +Please share repro code with us, or tell us how to reproduce the issue.

This is a CLEAN Centos that was just installed.  Installed the REMI php-72, and then sqlsrv.  

# php -m|grep sqlsrv
pdo_sqlsrv
sqlsrv

Any help?

**Comment by Carpesimia** [comment]
Wow, the code was chopped.  Lets try again...

`
<?php
    $serverName = "192.168.151.40";
    $connectionOptions = array(
        "Database" => "mydb",
        "Uid" => "myuser",
        "PWD" => "mypass"
    );
    //Establishes the connection
    $conn = sqlsrv_connect($serverName, $connectionOptions);
    if($conn) {
        echo "Connected!";
    }
    else {
        die( print_r( sqlsrv_errors(), true));
    }
?>
`

and the output:
`
Array
(
    [0] => Array
        (
            [0] => HYT00
            [SQLSTATE] => HYT00
            [1] => 0
            [code] => 0
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
        )

    [1] => Array
        (
            [0] => 08001
            [SQLSTATE] => 08001
            [1] => 10057
            [code] => 10057
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2749
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2749
        )

    [2] => Array
        (
            [0] => 08001
            [SQLSTATE] => 08001
            [1] => 10057
            [code] => 10057
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.
        )

)
`

**Comment by Carpesimia** [comment]
Trying code again:

`PHPBEGINMARKER (keeps getting eaten)
    $serverName = "192.168.151.40";
    $connectionOptions = array(
        "Database" => "rfm",
        "Uid" => "php",
        "PWD" => "a19!.irsa"
    );
    //Establishes the connection
    $conn = sqlsrv_connect($serverName, $connectionOptions);
    if($conn) {
        echo "Connected!";
    }
    else {
        die( print_r( sqlsrv_errors(), true));
    }
?>`

**Comment by Carpesimia** [comment]
```
<?php
    $serverName = "192.168.151.40";
    $connectionOptions = array(
        "Database" => "mydb",
        "Uid" => "myuser",
        "PWD" => "mypass"
    );
    //Establishes the connection
    $conn = sqlsrv_connect($serverName, $connectionOptions);
    if($conn) {
        echo "Connected!";
    }
    else {
        die( print_r( sqlsrv_errors(), true));
    }
?>```

**Comment by Carpesimia** [comment]
Output of program:
```Array
(
    [0] => Array
        (
            [0] => HYT00
            [SQLSTATE] => HYT00
            [1] => 0
            [code] => 0
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired
        )

    [1] => Array
        (
            [0] => 08001
            [SQLSTATE] => 08001
            [1] => 10057
            [code] => 10057
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2749
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2749
        )

    [2] => Array
        (
            [0] => 08001
            [SQLSTATE] => 08001
            [1] => 10057
            [code] => 10057
            [2] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.
            [message] => [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.
        )

)```

**Comment by yitam** [comment]
Hi @Carpesimia 
Since you can't even connect via SQLCMD, and its error message was `A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..` 

Can you please make sure that works first?

**Comment by Carpesimia** [comment]
Hi,

So yeah, it's definitely set up to allow remote connections, because I can connect remotely with the SQL Server Management Console, which did not work until I enabled the remote connection.

As far as the name, I have tried:
SERVER17/SQLEXPRESS
192.168.151.40/SQLEXPRESS
SERVER17
192.168.151.40

As the name of the server.  The above names are correct, and the ones used when connecting with SSMC.  I have even added SERVER17 to the /etc/hosts file.

Is there a log generated anywhere for sqlcmd?  Is there a way to get more verbose output?  I'd love to get it working, because that would prove connectivity and let me focus on the app.

**Comment by yitam** [comment]
Are you using named instance? If so, you might want to check this related issue #470

**Comment by Carpesimia** [comment]
So, I've been following through with some troubleshooting and it turns out that my SQL Server is not listening on port 1433.  It is listening on 50076.

That being said, I added the port to both sqlcmd and to the test program and they both work.  go figure.

Thanks for all your assistance.
