### ISSUE TITLE
AE - Cannot insert double with precision and scale (38, 38)

### ISSUE THREAD

**Issue by lilgreenbird** [Microsoft/msphpsql#706]
When inserting a double (even for small double such as 0.1) into a column of type decimal(38, 38), the data inserted is 0. 
Note that the data has to be inserted as double (i.e., no casting from double to string, no use of PDO::PARAM_STR when binding parameter)

for example, do something like this
$res = $stmt->bindParam(2, $val, PDO::PARAM_INT);

otherwise, the double value will be automatically casted to a string

New test covering this scenario: pdo_ae_insert_pdoparam_decimal_precision.phpt

**Comment by yitam** [comment]
Tested with [ODBC 17.1](https://blogs.msdn.microsoft.com/sqlnativeclient/2018/04/03/odbc-driver-17-1-for-sql-server-released/) and verified that this had been fixed.
