### ISSUE TITLE
What will be the process to install SQL Drivers on a Linux machine without internet activity?

### ISSUE THREAD

**Issue by awaistariq** [Microsoft/msphpsql#713]
I have a production environment under DMZ. As per company policy servers are not allowed to have direct internet connectivity. Can you guide how can I install SQL drivers? I have php and apache installed.

**Comment by yitam** [comment]
Hello @awaistariq, note that we focus on helping users with issues re PHP drivers for SQL Servers. That being said, there are a handful of articles in Microsoft Docs to help you get started. I just picked two that might be relevant to you:

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-installation-wizard-setup

Hope this helps.

**Comment by awaistariq** [comment]
Thank you for your reply. 
After digging deep, I managed to install drivers for RedHat. The process I followed is to download all required pkg's by downloading them (in my case in another machine with --downloadonly flag as I don't have direct internet connectivity for my prod servers) and then install them as offline.
