### ISSUE TITLE
Extension version not reported

### ISSUE THREAD

**Issue by david-garcia-garcia** [Microsoft/msphpsql#72]
This must be the only extension in the world that is not reporting it's release verision in phpinfo().

![mssqlpdo](https://cloud.githubusercontent.com/assets/9599352/12176848/44e720a8-b51e-11e5-8133-abe268875a62.png)

A real pain when trying to find out what version of the PDO driver is being run... yes you can use custom code to retrieve that, but taking a look at phpinfo() is the standard for quick diagnosing the current deployment.

**Comment by ulvii** [comment]
Fixed!
