### ISSUE TITLE
Unable to load dynamic library '/usr/lib/php/20160303/sqlsrv.so'

### ISSUE THREAD

**Issue by ergonomicus** [Microsoft/msphpsql#729]
I have tried all of the suggested fixes in Issues, still getting
`Unable to load dynamic library '/usr/lib/php/20160303/sqlsrv.so'`
and
`Unable to load dynamic library '/usr/lib/php/20160303/pdo_sqlsrv.so'`
when I try to list modules (php -m)...

I've followed the official instructions trying to get this thing running on Ubuntu 16.04 with Nginx  and php 7.1, but without luck.

This is frustrating me for two days now, any help is appreciated.

**Comment by david-puglielli** [comment]
Hi @ergonomicus Are you using prebuilt binaries or building the drivers using PECL?

**Comment by ergonomicus** [comment]
Hey @david-puglielli thanks for replying.

I've followed the instructions on main page, so I guess I was building drivers using PECL (whatever that means :). None of the combinations worked for me, .so files were always in wrong folder, or there wasn't any... I have tried three versions of php and numerous building scripts from various issues from this repo, and gave up at the end. Well, after two days of hell :).

I've purged everything and installed Apache2 instead of Nginx, followed the instructions again. This time there was no errors, but modules were not loaded (neither phpinfo nor cli). I found that .so files were still missing, so I downloaded binaries for Ubuntu 16.04 and php 7.1, put them in some command (echo -e something...) that I found on the internet, and manually added extension lines in php.ini.

Test script works now, I have no idea how, but if I was forced to do it again, I would probably spend that time migrating data to MySql.

I just hope that I won't have any issues when I build my app relying on it.

**Comment by david-puglielli** [comment]
You need to put the .so files in the PHP extension directory, which is listed in the output of phpinfo(). However the extension directory for Apache may be different from the one using PHP from the command line (and I assume the extension directory may be different for Nginx as well). Importantly, the location of php.ini may also be different. So my advice is to check the output of phpinfo() in a browser to find out where the extensions need to go and which php.ini file it is loading, then copy the extensions that directory (if they're not already there) and add the extension lines to php.ini.

**Comment by ergonomicus** [comment]
Thanks @david-puglielli I guess that was what I did at the end, it's working now...

Though, why don't you just put those two files available to download from the main page, and write the instructions where to put them?

Anyway, closing this now, thanks for your time!
