### ISSUE TITLE
Will Ubuntu 18.04 LTS Bionic Beaver be supported?

### ISSUE THREAD

**Issue by fasterforward** [Microsoft/msphpsql#749]
Are there plans to support Ubuntu 18.04 LTS Bionic Beaver? Any ETA?

**Comment by David-Engel** [comment]
@fasterforward There is a slight chance that it will be in the next stable release, which is targeted for July. Unfortunately we are time and resource constrained and it is at the bottom of our priority list for the July release. Most likely it will be in the one after that, which is targeted for January 2019.

Regards,
David

**Comment by kaliberx** [comment]
July, really? This is ridiculous.

**Comment by David-Engel** [comment]
@kaliberx Thanks for the feedback. I'd like to point out that:
1. Ubuntu 18.04 (production/RTM) has not even released yet (it's scheduled for April 26). A July support date would mean we prioritized this into a two month window for completing any code and test infrastructure changes required for production support (on top of other work being done).
2. The PHP drivers have a dependency on ODBC drivers which themselves have to support 18.04 first.

**Comment by david-puglielli** [comment]
That does seem to be an issue with msodbcsql, which underscores the fact that we can't support 18.04 until the underlying ODBC driver supports it. The ODBC driver devs will be made aware of this error, @savvidevs, thanks for pointing it out.

**Comment by david-puglielli** [comment]
For more information about the libcurl issue in Ubuntu 18.04, see the corresponding [discussion on Launchpad](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294).

**Comment by Catscrash** [comment]
until this is fixed on the odbc-side, you can install the libcurl4 from here https://launchpad.net/~xapienz/+archive/ubuntu/curl34 which will provide a libcurl3 as well and make it possible to install everything

**Comment by thsmrtone1** [comment]
Please make this a higher priority. There are MANY libraries that require libcurl4 on 18.04 and it is becoming harder and harder to delay use of them. Support for the newest LTS version should be high priority.

@Catscrash can you elaborate on this any more?

**Comment by yitam** [comment]
Hi @thsmrtone1 and @Catscrash , rest assured that ODBC driver has this libcurl issue fixed and will be ready in July, as @David-Engel has mentioned above. Please stay tuned for their [blog announcement](https://blogs.msdn.microsoft.com/sqlnativeclient/).

**Comment by yitam** [comment]
Please check the latest [v5.3.0 release](https://github.com/Microsoft/msphpsql/releases/tag/v5.3.0) 

Should any of you have any other problem or issue with Ubuntu 18.04, which requires the latest [ODBC 17.2](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017), please create a new issue.
