### ISSUE TITLE
Memory Leak PHP7 - Early Technical Preview 

### ISSUE THREAD

**Issue by srd2010** [Microsoft/msphpsql#75]
Hi. we've tried the Early Technical Preview for PHP7.
Let me first say, that the driver works as expected and runs much faster than the older drivers (at least on our system),

We've observed a memory leak of about 8-9 kb per Request (simple select query, repeated n-times).
The Result is free'd after output, all variables are unset.

Running the same code with odbc drivers does not show increase in memory usage.

---

**Memory Usage: 12.71 kb (Connection only)**

GOT pulldata Event!
Send Data to client!
**Memory Usage: 43.86 kb (first query)**

GOT pulldata Event!
Send Data to client!
**Memory Usage: 51.98 kb (second query)**

GOT pulldata Event!
Send Data to client!
Memory Usage: 60.09 kb

GOT pulldata Event!
Send Data to client!
Memory Usage: 68.21 kb

GOT pulldata Event!
Send Data to client!
Memory Usage: 76.4 kb

GOT pulldata Event!
Send Data to client!
Memory Usage: 84.41 kb

GOT pulldata Event!
Send Data to client!
Memory Usage: 92.43 kb

GOT pulldata Event!
Send Data to client!
Memory Usage: 100.45 kb

**Comment by meet-bhagdev** [comment]
@srd2010 : Thanks for reporting this. Is there a generic repro script that you can share with us?

**Comment by srd2010** [comment]
@meet-bhagdev : sure.. i'll throw somthing together..

**Comment by srd2010** [comment]
@meet-bhagdev : 

I've put the script on Gist:
https://gist.github.com/srd2010/758502ef6aabcbbd4374

All you have to do is add your Database Details in the top section of the script.
The script is run in powershell.

Building the script we've observed that the memoryleak is in direct connection to the size of the Resultset. The larger the Resultset, the larger the memory leak.

Compare this to odbc driver by switching mode to odbc (also in the top section of the script).

Hope this helps.

Greets,
Frank

**Comment by meet-bhagdev** [comment]
Frank, the repro script is great. Thank you :) Can you also share your schema?

**Comment by nickmccally** [comment]
We are also experiencing a memory leak using the php_sqlrv_4.0.4_x86 driver

**Comment by meet-bhagdev** [comment]
@nickmccally We are trying hard to identify these leaks. Can you share which apis and data types are you using that is causing the memory leak? A repro script and your schema definition will certainly help too!

**Comment by srd2010** [comment]
@meet-bhagdev :
after clearing from our customer, we could provide you a demo schema definition with some sample data to test. How can we get this to you without it beiing public ?

**Comment by meet-bhagdev** [comment]
Send me an email at meetb@microsoft.com :)

**Comment by srd2010** [comment]
@meet-bhagdev email is on it's way.. hope it helps.

**Comment by meet-bhagdev** [comment]
@srd2010 Check out our latest [release](https://github.com/Azure/msphpsql/releases/tag/v4.0-RC). We have tried to fix memory leaks based on your schema. While we don't have 100% success, we were able to iron out majority of the leaks.

**Comment by srd2010** [comment]
@meet-bhagdev :+1: looking a whole lot better! Thanks! Keep up the good work.

**Comment by meet-bhagdev** [comment]
@srd2010 I am glad to hear :) Are there any other memory leak issues you would like to share with us?

**Comment by david-garcia-garcia** [comment]
With the last 4.0.5 x64 NTS release:

![image](https://cloud.githubusercontent.com/assets/9599352/16175920/3df7bff2-35ff-11e6-95f2-8f4cf2477928.png)

PHP processes for this application are always in the 10 to 20 Mb range. I understand 8GB means something is leaking.

The underlying codebase is too complex and big to isolate with ease. Will a process dump help you find out where the leak might be originating?

**Comment by meet-bhagdev** [comment]
Definitely! Process dump would help. A sample schema would help as well. Is this something you see only with the 4.0.5 binaries?

**Comment by david-garcia-garcia** [comment]
Nevermind, the issue was on my side (infinite recursion due to wrong setup when switching to PHP 7). 

Still, something is wrong here the PHP process should fatal upon reaching the memory limit defined in php.ini.

**Comment by srd2010** [comment]
@meet-bhagdev 
We still observe some memory leaks, especially when selecting large amount of data.
Better than before but still leaking.

let me know if you need any more info on that.

**Comment by meet-bhagdev** [comment]
@srd2010 Is the schema and repro identical to what you sent us earlier? How much data in terms of # of rows and amount of data(in MB/GB) are we talking about here?

**Comment by srd2010** [comment]
@meet-bhagdev:
I'll send you a sample query.

We're talking about around 12.000 Rows.

We're jumping from 19.27 kb to 90.07 kb memory usage after query.

**Comment by meet-bhagdev** [comment]
Closing as the memory management issues are fixed in the latest releases. @srd2010 feel free to re-open these if you are still seeing the issues.
