### ISSUE TITLE
Module not loading under Windows Server 2012 R2 Version 6.3 (Build 9600)

### ISSUE THREAD

**Issue by tecfu** [Microsoft/msphpsql#754]
Issue
---

I attempted  ["Loading the Microsoft Drivers for PHP for SQL Server"](https://docs.microsoft.com/en-us/sql/connect/php/loading-the-php-sql-driver?view=sql-server-2017) and followed the instructions verbatim. 

However, the output of my php.ini file does not show the drivers are loaded. 

![screenshot - 04202018 - 06 17 05 pm](https://user-images.githubusercontent.com/7478359/39078985-3259216c-44c7-11e8-9955-4e8985465c62.png)

Looking in the comments of the tutorials mentioned above, it seems this has been the same experience others have had.  **Please advise.** 

## Driver version or file name
extension=php_sqlsrv_72_nts_x64.dll  
extension=php_pdo_sqlsrv_72_nts_x64.dll

## SQL Server version
Microsoft SQL Server 2014

## Client operating system
Windows Server 2012 R2 Version 6.3 (Build 9600)

## PHP version
7.2.2

## Microsoft ODBC Driver version
ODBC Driver 11 for SQL Server 2014.120.2000.08

**Comment by tecfu** [comment]
**Thanks for getting back to me on this.** 

### Answers to your questions:

> How did you download PHP 7.2, @tecfu ?

Web Platform Installer 5.0

> Also, can you run php --ini in command prompt?

Yes. The paths given in PowerShell match those output by the phpinfo() function.

> What's the Loaded Configuration File? Is the path as expected?

Yes. The loaded configuration file was discovered via phpinfo().

> Where did you copy the php drivers?

The php drivers were copied to the extensions directory found in phpinfo():

```
extension_dir | C:\Program Files\iis express\PHP\v7.2\ext\
```

### Update

I followed the tutorial previously referenced verbatim. In my case, that resulted in the following steps:

 1. Downloaded from [https://www.microsoft.com/en-us/download/details.aspx?id=56729](https://www.microsoft.com/en-us/download/details.aspx?id=56729).

2. Ran the executable via RDP and installed into the extension directory given by my php.ini, in this case:
```
C:\Program Files\iis express\PHP\v7.2\ext\
```

3. Added the following lines to my php.ini:

```
extension=php_sqlsrv_72_nts_x64.dll
extension=php_pdo_sqlsrv_72_nts_x64.dll
```

4. Restarted IIS. 

5. Checked phpinfo() to see if the drivers were loaded and found no change. 

### Solution

1. Instead of following the tutorial, I used the **Web Platform Installer 5.0*** to install the drivers. 

### Request

Please update the tutorial at  ["Loading the Microsoft Drivers for PHP for SQL Server"](https://docs.microsoft.com/en-us/sql/connect/php/loading-the-php-sql-driver?view=sql-server-2017) to suggest installation via Web Platform Installer rather than the currently stated method. That method does not work.

**Comment by yitam** [comment]
Without more inputs from you, it's difficult for us to figure out what went wrong in your setup. Note that `The driver file must match the PHP version, architecture, and threadedness of your PHP environment.` 

If you download via the Web Platform Installer it basically follows the steps in the aforementioned documentation and also configures php / iis, etc. for the user. Besides, it downloads the right PHP version that matches the drivers you have selected.
