### ISSUE TITLE
PDO::ATTR_SERVER_VERSION not supported by driver

### ISSUE THREAD

**Issue by jeff1985** [microsoft/msphpsql#756]
## Driver version
ODBC v17 (libmsodbcsql-17.1.so.0.1) and php_sqlsrv 5.2.0

 ## SQL Server version
Azure SQL Database

 ## Client operating system
Ubuntu 16.04

 ## PHP version
php 7.1.16

 ## Table schema
not relevant here, error is happening without relevance to any table 

 ## Problem description
When using PDO with php_sqlsrv and connection pooling enabled and the latest odbcv17 driver, the attribute PDO::ATTR_SERVER_VERSION 
is not always available. This attribute is defined here https://docs.microsoft.com/en-us/sql/connect/php/pdo-getattribute?view=sql-server-2017
and there are no documented limitations.

In our tests the attribute is available on the first call after server restart. Following calls to the same URL
 will raise an exception: `SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute`

 ## Affected software
 The doctrine library uses the information provided by this call when connecting to a MSSQL database. 
 Because of this error we are not able to use connection pooling in our doctrine based php application.
 
 The error however also happens with a pure PDO code.
 
 ## Example log
    
    2018-04-23 12:46:22.276177 version=12.00.0300
    2018-04-23 12:46:24.588640 Exception: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute
    2018-04-23 12:47:23.881217 version=12.00.0300
    2018-04-23 12:47:24.889867 Exception: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute
    2018-04-23 12:47:26.546435 Exception: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute
    2018-04-23 12:47:27.965711 Exception: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute
    2018-04-23 12:47:29.331294 Exception: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute
    2018-04-23 12:47:30.874883 Exception: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute
    2018-04-23 12:47:43.370788 version=12.00.0300
    2018-04-23 12:47:45.725874 Exception: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute

 ## Expected behavior and actual behavior
The expected behaviour is:
the PDO::ATTR_SERVER_VERSION is always available to application

The actual behaviour is:
the PDO::ATTR_SERVER_VERSION is available to application on the first call, but then produces exceptions

## Logs
All relevant logs are available here:
https://gist.github.com/jeff1985/439267b7e4463c0e107b0d00de75e9dc
Note: I removed db credentials from logs and code.

**Comment by jeff1985** [comment]
I’ve upgraded unixODBC per your recommendation with the following commands:

    export CPPFLAGS="-DSIZEOF_LONG_INT=8"
    apt-get -y install gcc-5 g++-5
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++     /usr/bin/g++-5
    cd ~
    echo "Configuring the unixODBC 2.3.6 Driver Manager"
    wget ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.6.tar.gz
    tar -xzf unixODBC-2.3.6.tar.gz
    cd unixODBC-2.3.6/
    ./configure --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc --disable-gui --disable-drivers --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE 1> odbc_con.log 2> make_err.log

    echo "Building and Installing the unixODBC 2.3.6 Driver Manager"
    make
    make install
    echo "####### build ready ###### "

odbcinst reports the desired version

    root@0a02cc3bface:/usr/lib/x86_64-linux-gnu# /usr/bin/odbc_config --version 2.3.6
    root@0a02cc3bface:/usr/lib/x86_64-linux-gnu# odbcinst -j
    unixODBC 2.3.6
    DRIVERS............: /etc/odbcinst.ini
    SYSTEM DATA SOURCES: /etc/odbc.ini
    FILE DATA SOURCES..: /etc/ODBCDataSources
    USER DATA SOURCES..: /root/.odbc.ini
    SQLULEN Size.......: 8
    SQLLEN Size........: 8
    SQLSETPOSIROW Size.: 8

However I still have the same error as specified in the bug description.

**Comment by yitam** [comment]
hi @jeff1985, I'm sorry to say that you haven't completely overwritten the existing unixODBC with the correct one. Ubuntu by default does not install in /usr/lib64

Please do the following:
1. Remove all `libodbc.*.so.*` and `libodbcinst.*.so.*` in your system
2. Then install 2.3.6 in /usr/local/lib

**Comment by jeff1985** [comment]
Hi @yitam ,

I'm not very familiar with compiling packages from sources. I adjusted my commands per your recommendation:


    # clean existing
    rm -f /usr/lib/x86_64-linux-gnu/libodbcinst.so*
    rm -f /usr/lib/x86_64-linux-gnu/libodbc.so*

    # try to upgrade unixodbc-dev
    export CPPFLAGS="-DSIZEOF_LONG_INT=8"
    apt-get -y install gcc-5 g++-5
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
    cd ~
    echo "Configuring the unixODBC 2.3.6 Driver Manager"
    wget ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.6.tar.gz
    tar -xzf unixODBC-2.3.6.tar.gz
    cd unixODBC-2.3.6/
    ./configure --prefix=/usr --libdir=/usr/local/lib --sysconfdir=/etc --disable-gui --disable-drivers --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE 1> odbc_con.log 2> make_err.log

    echo "Building and Installing the unixODBC 2.3.6 Driver Manager"
    make
    make install
    echo "####### build ready ###### "
 
1. Can you please verify that the parameters are as needed by your driver? 
2. The so-files were installed under /usr/lib/x86_64-linux-gnu/ but you recommend  /usr/local/lib as lib folder. Why and does that break something?
3. `--prefix=/usr --libdir=/usr/local/lib --sysconfdir=/etc --disable-gui --disable-drivers --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE` are those parameters correct?

**Comment by v-chojas** [comment]
`/usr/local/lib` has priority over `/usr/lib/x86_64-linux-gnu` on Ubuntu. The package manager usually uses `/usr/lib/x86_64-linux-gnu`, while `/usr/local/lib` is a more "traditional" location for user-installed libraries. Unless you have other software that depends on the _bugs_ in older (>=2.3.1) unixODBC which were fixed in later versions, that shouldn't break anything.

With the above in mind, `--prefix=/usr/local` would be a better place for the binaries (odbcinst, isql, etc.)

**Comment by jeff1985** [comment]
Hi @v-chojas ,

thanks for the explanation regarding the /usr/local/lib

Can you also verify the remaining parameters as I got them from some of the bug-tickets here in your repo, but not sure about the meaning. I also was not able to find any official instructions from msphpsql and dont want to break other things by setting wrong parameters.

Here is a list of parameters in question:
1. --prefix=/usr 
2. --libdir=/usr/local/lib **already confirmed to be a good choice**
3. --sysconfdir=/etc 
4. --disable-gui 
5. --disable-drivers
6. --enable-iconv 
7. --with-iconv-char-enc=UTF8 
8. --with-iconv-ucode-enc=UTF16LE

**Comment by v-chojas** [comment]
The other options should be OK.

**Comment by jeff1985** [comment]
Hi @v-chojas ,

thanks for clarifying. I can confirm that the bug reported here is fixed by compiling unixODBC 2.3.6 and installing from source. 

Please add this requirement to the docs under https://docs.microsoft.com/en-us/sql/connect/php/connection-pooling-microsoft-drivers-for-php-for-sql-server?view=sql-server-2017 

Also you should add it under requirements here: https://github.com/Microsoft/msphpsql 
and here https://www.microsoft.com/en-us/sql-server/developer-get-started/php/ubuntu/

Note that there are currently no packages available for unixODBC 2.3.6 on ubuntu or debian which means that you will have people running into this issue again and again so it is a good idea to provide documentation for people to be able to run your driver.

**Comment by yitam** [comment]
Hi @jeff1985 , glad to hear that you have successfully upgraded to unixODBC 2.3.6! Yes, I agree about the lack of documentation in this regard.

Do you have any update re issue #755 ?

**Comment by yitam** [comment]
Closing this issue, @jeff1985 , as you have confirmed that the problem no longer exists with unixODBC 2.3.6
