### ISSUE TITLE
xenial does not have a release file

### ISSUE THREAD

**Issue by bkraul** [Microsoft/msphpsql#763]
When attempting to run a routine update with ```apg update```, the following error is encountered:

```
Err:7 https://packages.microsoft.com/ubuntu/16.04/prod xenial Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/ubuntu/16.04/prod xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

What is going on? Have the release package files been moved? I checked on a browser and they are indeed gone.

## Environment:
* MSSQL Tools version: ```mssql-tools/xenial 17.1.0.1-1 amd64```
* ODBC Driver Version: ```msodbcsql17/xenial 17.1.0.1-1 amd64```
* PHP Extension Version: 5.2.0-RC1
* SQL Server version: SQL Server 2012
* Operating system: Ubuntu Server 16.04.4 LTS
* PHP version: 7.0

## Expected behavior and actual behavior
apt should check for available updates. Instead it errors out with the message above.

**Comment by david-puglielli** [comment]
Have you followed the instructions [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#ubuntu-1404-1604-and-1710)?

**Comment by bkraul** [comment]
@david-puglielli Of course, everything has been installed per the instructions. There have been no issues with updating until now, it is like the release were pulled or moved (without notice, which is not uncommon, based on a couple of previous issues).

**Comment by David-Engel** [comment]
@bkraul Apparently there was an issue with the packages repository and the repo admins are working on restoring impacted paths. Hopefully they will have everything back in order soon.

**Comment by bkraul** [comment]
The repository release file appears to be back, and update check works as usual.

**Comment by superBatbrat** [comment]
I'm still getting the same error when I run an apt update on this repository (/ubuntu/16.04/prod xenial Release), and also on (https://packages.microsoft.com/repos/vscode stable Release. I've tried running an apt clean before doing an update, but I still have issues. I'd appreciate directions on resolving this.

**Comment by david-puglielli** [comment]
@superBatbrat The repos seem to be working. Have you followed the instructions [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#ubuntu-1404-1604-and-1710)?

**Comment by kiejstutb** [comment]
I have the same issue on ubuntu 16.04. I followed the instructions, did following:
sudo su 
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
#Ubuntu 16.04
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
exit
sudo apt-get update

I am receiving:
W: The repository 'https://packages.microsoft.com/ubuntu/16.04/prod xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages  Received HTTP code 403 from proxy after CONNECT
E: Some index files failed to download. They have been ignored, or old ones used instead.

Checked the structure of directories in https://packages.microsoft.com/ubuntu and found nothing unusual in 16.04...

**Comment by GlennVL91** [comment]
I am getting the same error here when trying to install. Followed the instructions but no succes so far. Ubuntu 16 here.

**Comment by yitam** [comment]
@GlennVL91 I assume you followed [the latest instructions](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu17)?
