### ISSUE TITLE
Bring Azure Key Vault keystore provider support for non-Windows systems to use AlwaysEncrypted

### ISSUE THREAD

**Issue by therosco** [Microsoft/msphpsql#767]
## Driver version
libmsodbcsql-17.1.so.0.1
DriverODBCVer: 03.52
ExtensionVer: 5.2.0

 ## Client operating system
Debian/Any Linux

 ## PHP version
7.1.x

 ## Problem description
Azure Key Vault keystore provider is currently not supported.

 ## Expected behavior and actual behavior
Azure Key Vault keystore provider is supported.

 ## Repro code
`ColumnEncryption` is among supported options for `new PDO(...)`

**Comment by david-puglielli** [comment]
@therosco Azure Key Vault support is planned for our next stable release (expected this summer), so please stay tuned!

**Comment by david-puglielli** [comment]
@therosco The latest preview release (available [here](https://github.com/Microsoft/msphpsql/releases)) contains support for Azure Key Vault. You can find documentation on the [wiki](https://github.com/Microsoft/msphpsql/wiki/Features#akv). Please try it out and let us know if you run into any issues.

**Comment by yitam** [comment]
HI @therosco, please check the latest [v5.3.0 release](https://github.com/Microsoft/msphpsql/releases/tag/v5.3.0). 

Should you have any other problem or issue with Always Encrypted and/or Azure Key Vault, please create a new issue.
