### ISSUE TITLE
Error. Cannot connect to database: SQLSTATE[HYT00]

### ISSUE THREAD

**Issue by michelelaferla** [microsoft/msphpsql#778]
**Driver version or file name**
pdo_sqlsrv 5.2.0
 
**SQL Server version**
SQL Server 2017
 
**Client operating system**
Linux

**PHP version**
PHP Version 7.0.30

**Microsoft ODBC Driver version**
17

**Problem description**
When trying to connect to my database using the code below, I get the following error: 

> Error. Cannot connect to database: SQLSTATE[HYT00]: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired

I have installed all the necessary drivers including their most updated versions as can be seen here:

ODBC version 0x0380
PDO_ODBC
PDO_sqlsrv version 5.2.0
sqlsrv version 5.2.0
 
**Expected behavior and actual behavior**
I am expecting my code to connect to the database successfully. Instead I get the mentioned error. 

**Repro code**
```
<?php

class DB_Connect {
    private $db;

    function construct() {
    }

public function connect() {
        require_once 'String.php';

        try {
              $this->db = new PDO('sqlsrv:Server=server,port; Database=database_name', 'username', 'password');
            return $this->db;
        } catch (PDOException $e) {
            return "Error. Cannot connect to database: " . $e->getMessage();
        }
    }
?>
```

**Comment by mlaferla** [comment]
Yes I have checked the FAQ and gone through the posts. However what I see different from the other posts is that the issue is not intermittent. It is always happening. Can you please check it out?

**Comment by yitam** [comment]
Hi @mlaferla, 

Are you using named instance? If so, please check this [page](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-2017) or #442. 

Also, please tell me:
 
1. What are the output of running sqlcmd using the same credentials? 
2. How did you install our drivers, using pecl as shown in our [documentation](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017)? 
3. Which linux platform?

**Comment by mlaferla** [comment]
For the time being I don't have access to run sqlcmd on the server from where I am calling the database, however when running sqlcmd from my local PC, I am able to connect successfully.

drivers are the latest (5.4.0) and were installed using pecl.

Linux Platform is Redhat 7

**Comment by mlaferla** [comment]
Hi @yitam. I found that the issue was a firewall one which was prohibiting the server from connecting to the database. 

We reinstalled the drivers using pecl, as per your documentation and opened access for the server to access the database. 

It works now :)

Thanks for your help.

**Comment by yitam** [comment]
Glad to hear that @mlaferla 
Thank you for getting back to us.
