### ISSUE TITLE
It is not possible to connect to remote server or php or via sqlcmd

### ISSUE THREAD

**Issue by zan182** [microsoft/msphpsql#790]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:
 +## PHP Driver version or file name
 +sqlsrv support => enabled
   ExtensionVer => 5.2.0
+pdo_sqlsrv support => enabled
  ExtensionVer => 5.2.0

 +## SQL Server version
 +Microsoft SQL Server 2017 (RTM-CU7) (KB4229789) - 14.0.3026.27 (X64) 
+Enterprise Edition (64-bit)

 +## Client operating system
 +Linux (CentOS Linux 7 (Core)

 +## PHP version
 +PHP 7.0.30 (cli) (built: Apr 24 2018 21:28:23) ( NTS )

 +## Microsoft ODBC Driver version
 +17
 +## Table schema
 +Remote server 10.1.2.1
 +## Problem description
 +I need your help, I need to connect to a remote server via sqlcmd, locally if I can connect to my database, but I get the following message connecting to the external server

via sqlcmd:
[root@localhost ~]# sqlcmd -S 10.1.2.1,1434 -U userx
Password:
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x102.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

via web:
Error information:
SQLSTATE: HYT00
Code: 0
Message: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired
SQLSTATE: 08001
Code: 258
Message: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x102
SQLSTATE: 08001
Code: 258
Message: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.

+File PHP
/* $serverName = "10.1.2.1,1433";
$connectionOptions = array(
    "Database" => "tnl",
    "Uid" => "ingx",
    "PWD" => "75349x"
);

//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if( $conn === false ) {
    die( FormatErrors( sqlsrv_errors()));
}

//Select Query
$tsql= "SELECT @@Version as SQL_VERSION";

//Executes the query
$getResults= sqlsrv_query($conn, $tsql);

//Error handling
if ($getResults == FALSE)
    die(FormatErrors(sqlsrv_errors()));

echo '<h1> Results : </h1>'

while ($row = sqlsrv_fetch_array($getResults, SQLSRV_FETCH_ASSOC)) {
    echo ($row['SQL_VERSION']);
    echo ("<br/>");
}

sqlsrv_free_stmt($getResults);

function FormatErrors( $errors )
{ /* Display errors. */
    echo "Error information: <br/>";
    foreach ( $errors as $error )
    {   echo "SQLSTATE: ".$error['SQLSTATE']."<br/>";
        echo "Code: ".$error['code']."<br/>";
        echo "Message: ".$error['message']."<br/>";
    }
}
?>

***to the local database if it is possible to connect***
 +## Expected behavior and actual behavior
 +I need to connect to a database on an external server for queries

Currently I can only connect to the local database
 +## Repro code or steps to reproduce
firs step [here](https://www.microsoft.com/en-us/sql-server/developer-get-started/php/rhel/) 
Then look [here] (https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-red-hat-7)
Then look [here] (https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#redhat-enterprise-server-6-and-7)

It is worth mentioning that already probe with the two ports 1433 and 1434

Thanks

**Comment by david-puglielli** [comment]
@zan182 There are many possible causes, and the problem may be on your end or it may be with the remote server. Please see the thread for issue #576 for some possible solutions. If you still cannot connect, let us know what you tried. Thanks!

**Comment by zan182** [comment]
hello!, thanks for the prompt response, the problem is not found on the remote server because from Windows it is possible to access this server, they gave me the task of making it work with the CentOs 7 and this is where the connection could not be made, neither using php nor from the sqlcmd line

checking the link that you send me checking the odbc I realize that I have 13 and 17, do you think that is the conflict ?, you will have the command to eliminate the driver 13, I thank you

[root@localhost ~]# odbcinst -q -d
[PostgreSQL]
[MySQL]
[ODBC Driver 17 for SQL Server]
[ODBC Driver 13 for SQL Server]

**Comment by zan182** [comment]
I have added these two commands
 
+firewall-cmd --add-port = 1433 / tcp --permanent
+firewall-cmd --reload 

this is the result in console

[root@localhost ~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp7s0
  sources: 
  services: ssh dhcpv6-client
  ports: 1433/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:

**Comment by david-puglielli** [comment]
Firewall looks fine. Are you able to connect to the server using `isql`?

**Comment by david-puglielli** [comment]
@zan182 Do you have any updates? Please let us know - if there is no further activity on this issue, we will close it in a few days.

**Comment by david-puglielli** [comment]
Closing issue. Feel free to reopen if needed.
