### ISSUE TITLE
slsrv_errors - Non English characters converted to '?'

### ISSUE THREAD

**Issue by meet-bhagdev** [Microsoft/msphpsql#80]
Trying to use driver php_sqlsrv_7_ts.dll instead of php_sqlsrv_53_ts_vc9. Code page 1251. All is working good except one thing - function sqlsrv_errors, returning error, produced by SQL server, converts all non-english letters to '?'. Is it possible to correct this somehow? Not sure is this a problem of sqlsrv driver or ODBC driver 11 (Which replaces SQL Server Native Client 10.0, as I understand)...

**Comment by meet-bhagdev** [comment]
@Nick74k The ‘?’ occurs when the driver cannot translate a character from one encoding into another.  In this case, the target encoding is CP1252 (which is the default ACP / Windows locale) and it seems likely that the characters you refer to cannot be represented by CP1252 (to give you an idea, [these] (https://en.wikipedia.org/wiki/Windows-1252) are the supported characters).  If the characters you are expecting should be able to be translated, can you give us an example of the expected error message?
 
And for more details on how the driver works, the best resource is our MSDN documentation. According to our [Constants](https://msdn.microsoft.com/en-us/library/cc296183(v=sql.105).aspx) page:
 
| Contant      | Description           | 
| ------------- |:-------------:| -----:|
| SQLSRV_ENC_CHAR      | Data is returned in 8-bit characters as specified in the code page of the Windows locale that is set on the system. Any multi-byte characters or characters that do not map into this code page are substituted with a single byte question mark (?) character. This is the default encoding. | 

This means that you could try to change the active code page to match the desired code page, or use UTF8 as was suggested.  You can find more details on how to use UTF8 [here](https://msdn.microsoft.com/en-us/library/cc626307(v=sql.105).aspx).

Does this help? Feel free to let us know if you have follow up questions.

Cheers,
Meet

**Comment by Nick74k** [comment]
**meet-bhagdev** well, any character from the last four rows of this [table](https://en.wikipedia.org/wiki/Windows-1251). Meet, THE ONLY function which cannot work now with cp1251 in SQLSRV_ENC_CHAR mode is **sqlsrv_errors**. All other functions work perfect. I can fetch data with 1251 symbols, I can execute SQL with cp1251 symbols and the only problem - getting error message, written with cp1251. E.g. message, passed from trigger with RAISERROR ('Русский текст', 16, 1) would be replaced with '??????? ?????'.

**Comment by yitam** [comment]
@Nick74k this issue is no longer reproducible with the latest sqlsrv in Windows. 
If on the other hand this problem still exists on your side, please provide a repro script if possible.

**Comment by meet-bhagdev** [comment]
@Nick74k Closing the issue for now as we can't repro it. Feel free to reopen if you still need help :)
