### ISSUE TITLE
segfault libssl.so after curl upgrade

### ISSUE THREAD

**Issue by wdarins** [Microsoft/msphpsql#800]
After CURL upgrade and switch SSL from NSS/3.34 to OpenSSL/1.1.1 cannot connect anymore to MSSQL server via php-pdo it throws me a sementation fault in dmesg:
[  +4.610141] php-cgi[12185]: segfault at 3f0 ip 00007ff722cdfe8b sp 00007ffc39326190 error 4 in libssl.so.1.0.2k[7ff722cb7000+67000]

Old version of curl:
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.34 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets 

New version:
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.1.1 zlib/1.2.7
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

 +## PHP Driver version or file name
 +5.2.0
 +## Client operating system
CPU Model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
CPU Details: 10 Core (3492 MHz)
Distro Name: CentOS Linux release 7.4.1708 (Core)
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Platform: x86_64
 +## PHP version
PHP 7.1.9 (cli) (built: Jun 20 2018 10:51:55) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by david-puglielli** [comment]
@wdarins How did you upgrade curl? With yum, or by manual install?

**Comment by david-puglielli** [comment]
@wdarins Any updates on this? If not, we will close it in a few days.

**Comment by david-puglielli** [comment]
Closing the issue. Please reopen if you still have the issue.
