### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by brainfoolong** [Microsoft/msphpsql#804]
I am here just to ask for some information about 7.3 timeline. As always, i am an early tester for every new PHP release and we still require SQL support on windows :)

**Comment by david-puglielli** [comment]
@brainfoolong Support for PHP 7.3 is in the pipeline but no timeline has been set yet. Please stay tuned.

**Comment by brainfoolong** [comment]
Thank you for your answer.

**Comment by Jan-E** [comment]
The ZVAL_INTERNAL_DTOR raised an error in PHP 7.3.0 alpha 4.
https://github.com/Microsoft/msphpsql/blob/master/source/pdo_sqlsrv/pdo_dbh.cpp#L555
or in the dev branch
https://github.com/Microsoft/msphpsql/blob/dev/source/pdo_sqlsrv/pdo_dbh.cpp#L549
```
ext\pdo_sqlsrv\pdo_dbh.cpp(549): error C2065: 'ZVAL_INTERNAL_DTOR': undeclared identifier
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\`
```
zval_internal_dtor(zvalue) is defined in
https://github.com/php/php-src/blob/master/Zend/zend_variables.h#L94

Probably the ZVAL_INTERNAL_DTOR must be changed into ZVAL_PTR_DTOR or ZVAL_INTERNAL_PTR_DTOR
https://github.com/php/php-src/blob/master/Zend/zend_variables.h#L111

**Comment by Jan-E** [comment]
BTW In PHP 7.2 ZVAL_INTERNAL_DTOR still existed:
https://github.com/php/php-src/blob/PHP-7.2/Zend/zend_variables.h#L113

**Comment by Jan-E** [comment]
ZVAL_INTERNAL_DTOR was removed in this commit:
https://github.com/php/php-src/commit/7eb045d31a108323e3878947419cde94e2ba8645#diff-93200b0a055c7319402b4e44c8ee8cd4

And became public in PHP 7.3.0 alpha 4. @cmb69 Undocumented as well?

**Comment by yitam** [comment]
> ZVAL_INTERNAL_DTOR was removed in this commit:
> php/php-src@7eb045d#diff-93200b0a055c7319402b4e44c8ee8cd4
> And became public in PHP 7.3.0 alpha 4. @cmb69 Undocumented as well?
 
Thanks @Jan-E for the reference about the macro ZVAL_INTERNAL_DTOR being removed in php 7.3 alpha, and it looks like the change is not documented in the change log.

```
     core::sqlsrv_zend_hash_init( *g_pdo_henv_cp, pdo_conn_options_ht, 10 /* # of buckets */, 
                                 ZVAL_INTERNAL_DTOR, 0 /*persistent*/ TSRMLS_CC );
```

However, replacing ZVAL_INTERNAL_DTOR with ZVAL_INTERNAL_PTR_DTOR resulted in segfaults 

But, replacing ZVAL_INTERNAL_DTOR with ZVAL_PTR_DTOR seems to rid of the segfault issues

**Comment by cmb69** [comment]
> […] the macro ZVAL_INTERNAL_DTOR being removed in php 7.3 alpha, and it looks like the change is not documented in the change log.

See <http://news.php.net/php.cvs/102609>, Apparently, `ZVAL_INTERNAL_DTOR` was not supposed to be used, in the first place.

**Comment by yitam** [comment]
I see. Thanks @cmb69 
It would be nice to find official documentation to know which macros/functions to replace the obsolete ones. For sure replacing ZVAL_INTERNAL_DTOR with ZVAL_INTERNAL_PTR_DTOR resulted in segfaults

**Comment by cmb69** [comment]
> It would be nice to find official documentation to know which macros/functions to replace the obsolete ones. For sure replacing ZVAL_INTERNAL_DTOR with ZVAL_INTERNAL_PTR_DTOR resulted in segfaults

@dstogov Thoughts?

**Comment by yitam** [comment]
Sounds good, thanks @dstogov and @cmb69

**Comment by david-puglielli** [comment]
@brainfoolong PHP 7.3 support is coming in our next preview release - date of availability is TBA, so please stay tuned!

**Comment by yitam** [comment]
Closing this issue as we support PHP 7.3 starting with [5.4.0-preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.4.0-preview) release.
