### ISSUE TITLE
ear

### ISSUE THREAD

**Issue by Venaseph** [Microsoft/msphpsql#812]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 +
 +## SQL Server version
 +
 +## Client operating system
 +
 +## PHP version
 +
 +## Microsoft ODBC Driver version
 +
 +## Table schema
 +
 +## Problem description
 +
 +## Expected behavior and actual behavior
 +
 +## Repro code or steps to reproduce

**Comment by david-puglielli** [comment]
@Venaseph is there an issue?
