### ISSUE TITLE
I want this driver for php5.6. Will it work? 

### ISSUE THREAD

**Issue by mhgill** [Microsoft/msphpsql#819]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 +None
 +## SQL Server version
 +2012
 +## Client operating system
 +Ubuntu
 +## PHP version
 +5.6
 +## Microsoft ODBC Driver version
 +2017
 +## Table schema
 +
 +## Problem description
 +I am trying to connect to a sql server 2012 with this library, but it says it only supports php7 (I have php5.6). I am trying to install using this command: 
sudo pecl install sqlsrv
output: 
pecl/sqlsrv requires PHP (version >= 7.0.0), installed version is 5.6.36-1+ubuntu14.04.1+deb.sury.org+1
No valid packages found
install failed

 +## Expected behavior and actual behavior
 + IS there any command like: "sudo pecl install sqlsrv_for_php_5.6" ?
 +## Repro code or steps to reproduce

**Comment by yitam** [comment]
Hi @mhgill we only support PHP 7+ in Linux. Please consider upgrading PHP.

**Comment by yitam** [comment]
Closing this issue, @mhgill , as we do not support PHP 5* in Linux. Please feel free to create a new issue for any question concerning PHP 7+.
