### ISSUE TITLE
SQLSRV 64bit module crash

### ISSUE THREAD

**Issue by meet-bhagdev** [Microsoft/msphpsql#82]
I am getting a crash in the 64 Bit module. I am using Apache 2.4, Windows 10 & PHP 7.0.4. I am using the same code base that we have in production.

Faulting application name: httpd.exe, version: 2.4.18.0, time stamp: 0x5667fd57
Faulting module name: php7ts.dll, version: 7.0.4.0, time stamp: 0x56d77347
Exception code: 0xc0000005
Fault offset: 0x000000000001ae0d
Faulting process id: 0x2bac
Faulting application start time: 0x01d18e418a22bd23
Faulting application path: D:\Program Files\Apache24\bin\httpd.exe
Faulting module path: D:\PHP\php7ts.dll
Report Id: 3248c3ef-3559-4c3c-9d4a-5401be16a7f3
Faulting package full name:

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: httpd.exe
P2: 2.4.18.0
P3: 5667fd57
P4: php7ts.dll
P5: 7.0.4.0
P6: 56d77347
P7: c0000005
P8: 000000000001ae0d
P9: 
P10:

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_httpd.exe_9860e3bfaaecee75f074070b0e41e269273_75fa684f_2325d7cc

Analysis symbol: 
Rechecking for solution: 0
Report Id: 00008176-be42-4321-a08f-913da275e65d
Report Status: 4100
Hashed bucket:

The crash file contents:
Version=1
EventType=APPCRASH
EventTime=131042285770735908
ReportType=2
Consent=1
ReportIdentifier=fb8fc7f0-fa36-11e5-8d96-40e2303c248a
IntegratorReportIdentifier=652b032e-8ad7-4ae2-9eb0-64b1fdcfe282
NsAppName=httpd.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=httpd.exe
Sig[1].Name=Application Version
Sig[1].Value=2.4.18.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5667fd57
Sig[3].Name=Fault Module Name
Sig[3].Value=php7ts.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=7.0.4.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=56d77347
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000000000001ae0d
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10586.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=b1f0
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=b1f07c44f790817cf33b8c06b56ffd1b
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=915b
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=915b46e626583658430a12e9fb5af458
UI[2]=D:\Program Files\Apache24\bin\httpd.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=Apache HTTP Server stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=D:\Program Files\Apache24\bin\httpd.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\system32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\system32\KERNELBASE.dll
LoadedModule[4]=D:\Program Files\Apache24\bin\libhttpd.dll
LoadedModule[5]=C:\WINDOWS\system32\WS2_32.dll
LoadedModule[6]=C:\WINDOWS\system32\sechost.dll
LoadedModule[7]=C:\WINDOWS\system32\RPCRT4.dll
LoadedModule[8]=C:\WINDOWS\system32\ADVAPI32.dll
LoadedModule[9]=C:\WINDOWS\system32\msvcrt.dll
LoadedModule[10]=D:\Program Files\Apache24\bin\libaprutil-1.dll
LoadedModule[11]=D:\Program Files\Apache24\bin\libapr-1.dll
LoadedModule[12]=C:\WINDOWS\system32\SHELL32.dll
LoadedModule[13]=C:\WINDOWS\system32\cfgmgr32.dll
LoadedModule[14]=C:\WINDOWS\system32\windows.storage.dll
LoadedModule[15]=C:\WINDOWS\system32\combase.dll
LoadedModule[16]=C:\WINDOWS\system32\bcryptPrimitives.dll
LoadedModule[17]=C:\WINDOWS\system32\shlwapi.dll
LoadedModule[18]=C:\WINDOWS\system32\GDI32.dll
LoadedModule[19]=C:\WINDOWS\system32\USER32.dll
LoadedModule[20]=C:\WINDOWS\system32\kernel.appcore.dll
LoadedModule[21]=C:\WINDOWS\system32\shcore.dll
LoadedModule[22]=C:\WINDOWS\system32\powrprof.dll
LoadedModule[23]=C:\WINDOWS\system32\profapi.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
LoadedModule[25]=C:\WINDOWS\SYSTEM32\ucrtbase.dll
LoadedModule[26]=D:\Program Files\Apache24\bin\pcre.dll
LoadedModule[27]=D:\Program Files\Apache24\bin\libapriconv-1.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\MSWSOCK.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
LoadedModule[30]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[31]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[32]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[33]=D:\Program Files\Apache24\modules\mod_deflate.so
LoadedModule[34]=D:\Program Files\Apache24\bin\zlib1.dll
LoadedModule[35]=D:\Program Files\Apache24\modules\mod_mime.so
LoadedModule[36]=D:\Program Files\Apache24\modules\mod_rewrite.so
LoadedModule[37]=D:\Program Files\Apache24\modules\mod_expires.so
LoadedModule[38]=D:\Program Files\Apache24\modules\mod_headers.so
LoadedModule[39]=D:\Program Files\Apache24\modules\mod_cache.so
LoadedModule[40]=D:\Program Files\Apache24\modules\mod_socache_dbm.so
LoadedModule[41]=D:\Program Files\Apache24\modules\mod_access_compat.so
LoadedModule[42]=D:\Program Files\Apache24\modules\mod_actions.so
LoadedModule[43]=D:\Program Files\Apache24\modules\mod_alias.so
LoadedModule[44]=D:\Program Files\Apache24\modules\mod_allowmethods.so
LoadedModule[45]=D:\Program Files\Apache24\modules\mod_asis.so
LoadedModule[46]=D:\Program Files\Apache24\modules\mod_auth_basic.so
LoadedModule[47]=D:\Program Files\Apache24\modules\mod_authn_core.so
LoadedModule[48]=D:\Program Files\Apache24\modules\mod_authz_core.so
LoadedModule[49]=D:\Program Files\Apache24\modules\mod_autoindex.so
LoadedModule[50]=D:\Program Files\Apache24\modules\mod_dir.so
LoadedModule[51]=D:\Program Files\Apache24\modules\mod_env.so
LoadedModule[52]=D:\Program Files\Apache24\modules\mod_include.so
LoadedModule[53]=D:\Program Files\Apache24\modules\mod_isapi.so
LoadedModule[54]=D:\Program Files\Apache24\modules\mod_log_config.so
LoadedModule[55]=D:\Program Files\Apache24\modules\mod_negotiation.so
LoadedModule[56]=D:\Program Files\Apache24\modules\mod_setenvif.so
LoadedModule[57]=D:\PHP\php7apache2_4.dll
LoadedModule[58]=D:\PHP\php7ts.dll
LoadedModule[59]=C:\WINDOWS\system32\ole32.dll
LoadedModule[60]=C:\WINDOWS\system32\PSAPI.DLL
LoadedModule[61]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[62]=C:\WINDOWS\system32\NSI.dll
LoadedModule[63]=D:\PHP\ext\php_bz2.dll
LoadedModule[64]=D:\PHP\ext\php_curl.dll
LoadedModule[65]=C:\WINDOWS\system32\WLDAP32.dll
LoadedModule[66]=C:\WINDOWS\system32\Normaliz.dll
LoadedModule[67]=D:\Program Files\Apache24\bin\LIBEAY32.dll
LoadedModule[68]=D:\PHP\libssh2.dll
LoadedModule[69]=D:\Program Files\Apache24\bin\SSLEAY32.dll
LoadedModule[70]=D:\PHP\ext\php_fileinfo.dll
LoadedModule[71]=D:\PHP\ext\php_gd2.dll
LoadedModule[72]=D:\PHP\ext\php_gettext.dll
LoadedModule[73]=D:\PHP\ext\php_gmp.dll
LoadedModule[74]=D:\PHP\ext\php_intl.dll
LoadedModule[75]=D:\PHP\icuuc56.dll
LoadedModule[76]=D:\PHP\icuin56.dll
LoadedModule[77]=D:\PHP\icuio56.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\MSVCP140.dll
LoadedModule[79]=D:\PHP\icudt56.dll
LoadedModule[80]=D:\PHP\ext\php_imap.dll
LoadedModule[81]=C:\WINDOWS\system32\CRYPT32.dll
LoadedModule[82]=C:\WINDOWS\system32\MSASN1.dll
LoadedModule[83]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[84]=C:\WINDOWS\SYSTEM32\Secur32.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[86]=C:\WINDOWS\SYSTEM32\SSPICLI.DLL
LoadedModule[87]=D:\PHP\ext\php_mbstring.dll
LoadedModule[88]=D:\PHP\ext\php_exif.dll
LoadedModule[89]=D:\PHP\ext\php_openssl.dll
LoadedModule[90]=D:\PHP\ext\php_pdo_odbc.dll
LoadedModule[91]=C:\WINDOWS\SYSTEM32\ODBC32.dll
LoadedModule[92]=C:\WINDOWS\SYSTEM32\DPAPI.dll
LoadedModule[93]=D:\PHP\ext\php_sockets.dll
LoadedModule[94]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[95]=D:\PHP\ext\php_tidy.dll
LoadedModule[96]=D:\PHP\ext\php_sqlsrv_7_ts.dll
LoadedModule[97]=C:\WINDOWS\system32\msodbcsql11.dll
LoadedModule[98]=C:\WINDOWS\system32\OLEAUT32.dll
LoadedModule[99]=C:\WINDOWS\system32\NETAPI32.dll
LoadedModule[100]=C:\WINDOWS\system32\COMDLG32.dll
LoadedModule[101]=C:\WINDOWS\system32\FirewallAPI.dll
LoadedModule[102]=C:\WINDOWS\system32\VERSION.dll
LoadedModule[103]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.10586.0_none_396e892957c7fb25\COMCTL32.dll
LoadedModule[104]=C:\WINDOWS\system32\MSVCR100.dll
LoadedModule[105]=C:\WINDOWS\system32\DAVHLPR.DLL
LoadedModule[106]=C:\WINDOWS\system32\fwbase.dll
LoadedModule[107]=C:\WINDOWS\SYSTEM32\MTXDM.DLL
LoadedModule[108]=C:\WINDOWS\system32\clbcatq.dll
LoadedModule[109]=C:\Windows\System32\comsvcs.dll
LoadedModule[110]=C:\WINDOWS\system32\1033\msodbcsqlr11.rll
LoadedModule[111]=C:\WINDOWS\system32\CLUSAPI.DLL
LoadedModule[112]=C:\WINDOWS\SYSTEM32\ncrypt.dll
LoadedModule[113]=C:\WINDOWS\SYSTEM32\NTASN1.dll
LoadedModule[114]=C:\WINDOWS\system32\RESUTILS.DLL
LoadedModule[115]=C:\WINDOWS\system32\security.dll
LoadedModule[116]=C:\WINDOWS\system32\schannel.DLL
LoadedModule[117]=C:\Program Files\Microsoft SQL Server\90\Shared\instapi.dll
LoadedModule[118]=C:\WINDOWS\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9193_none_88e4514b2faac6c7\MSVCR80.dll
LoadedModule[119]=C:\WINDOWS\SYSTEM32\mskeyprotect.dll
LoadedModule[120]=C:\WINDOWS\system32\ncryptsslp.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Apache HTTP Server
AppPath=D:\Program Files\Apache24\bin\httpd.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=5DB4A09869DD73F016080CF76D0925EA

**Comment by meet-bhagdev** [comment]
@DigitalSolo Do you have a repro script we can use to repro and investigate this crash?

**Comment by DigitalSolo** [comment]
I don't really because it's an integrated framework that I wrote myself. I have tried to pull pieces of it out to reproduce the crash and I cannot thus far. I'll do the best I can to isolate this issue.


Sent from Outlook Mobile






On Mon, Apr 4, 2016 at 2:07 PM -0700, "Meet Bhagdev" <notifications@github.com> wrote:












@DigitalSolo Do you have a repro script we can use to repro and investigate this crash?

**Comment by meet-bhagdev** [comment]
:+1:

**Comment by DigitalSolo** [comment]
I have to assume because no one else is reporting an issue it must be something wrong with my SQLSRV class.  I am just covered up at the moment.  The only hint I get is in the Apache error.log file where the PHP process crashes and restarts (255).

**Comment by DigitalSolo** [comment]
I had to revert my test box back to 32 Bit everything because I have a big project to finish up by Q2 so this will probably sit idle for some time; sorry in advance.

**Comment by meet-bhagdev** [comment]
Understood. Keep us posted. We will investigate this right away once you have something that can better help us understand this crash.

**Comment by oys0629** [comment]
@meet-bhagdev 
hi!
i'm developing web site.
Windows10, apache2.4, php7.0.9, mssql 2008

i have problem like that

Faulting application name: httpd.exe, version: 2.4.23.0, time stamp: 0x5776399f
Faulting module name: php_sqlsrv_7_ts.dll, version: 4.0.8629.2, time stamp: 0x57745572
Exception code: 0xc0000005
Fault offset: 0x0000000000037e83
Faulting process id: 0x1378
Faulting application start time: 0x01d1eeb15ee7292d
Faulting application path: C:\Apache24\bin\httpd.exe
Faulting module path: c:\php7\ext\php_sqlsrv_7_ts.dll
Report Id: 135e5ca9-f1b3-4d45-9229-a72622abc34b
Faulting package full name: 
Faulting package-relative application ID: 

i think that this error is same as above that.

do you resolve this error??

**Comment by meet-bhagdev** [comment]
@oys0629 CAn you share a repro script/schema that we can use to emulate this in our lab? Feel free to email me at meetb@microsoft.com

**Comment by vovech** [comment]
Hi People, i have similar issue using SQLServer with PDO:

PHP Versions: 7.0.12.0 (i've tried with others)
SQL Server 2008R2
[PHP_SQLSRV_7_TS_X86]
extension=php_sqlsrv_7_ts_x86.dll

Here is my script:

```
error_reporting(E_ALL);
ini_set("display_errors", 1);
$pdo = new PDO("sqlsrv:Server={XXXX}; Database = {XXXX}", "XXXX", "XXXX", [PDO::ATTR_ERRMODE => PDO::ERRMODE_WARNING]);
/*
        Store Procedure:
	ALTER PROCEDURE [dbo].testSP 
	AS
	BEGIN
		-- DECLARE @returnValue INT
		SELECT 'SIMPLY TEST WITH SELECT' AS resultado
		return -1
	END
*/

$stmt = $pdo->prepare("EXEC testSP");
$stmt->execute();

do {
    $results[] = $stmt->fetchAll();
} while ($stmt->nextRowset());   

print_r($results);
```

This works perfectly if you are execute in command line: 
**php-cgi.exe test.php**

By using navigator:
**www.mysite.com/test.php**

**IIS Server Throwing 500** error without any specific error, and event_log shows:

`Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: php-cgi.exe
P2: 7.0.12.0
P3: 57ffcd8f
P4: php7ts.dll
P5: 7.0.12.0
P6: 57ffd3c2
P7: c0000005
P8: 00006e8c
P9: 
P10: 

Attached files:
C:\Windows\Temp\WER1044.tmp.appcompat.txt
C:\Windows\Temp\WER1064.tmp.WERInternalMetadata.xml
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_php-cgi.exe_1aec6c868dca22ed10abf8bc4a683b26443662f_476a3a53_cab_53201073\memory.hdmp
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_php-cgi.exe_1aec6c868dca22ed10abf8bc4a683b26443662f_476a3a53_cab_53201073\triagedump.dmp
WERGenerationLog.txt
`

Another Error:

`Faulting application name: php-cgi.exe, version: 7.0.12.0, time stamp: 0x57ffcd8f
Faulting module name: php7ts.dll, version: 7.0.12.0, time stamp: 0x57ffd3c2
Exception code: 0xc0000005
Fault offset: 0x00006e8c
Faulting process id: 0xc48
Faulting application start time: 0x01d2444406f7cf03
Faulting application path: C:\Program Files (x86)\PHP\v5.7\php-cgi.exe
Faulting module path: C:\Program Files (x86)\PHP\v5.7\php7ts.dll
Report Id: 44b046b9-b037-11e6-80e0-00155d3bf438
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by vovech** [comment]
I've tried to reproduce error using XAMPP last versión with php7 and Windows 10. 

Here is a little bit different error. With script i've posted works, with a biggest Store Procedure it crash again with: ERR_CONNECTION_RESET error and windows log show:

_Nombre de la aplicación con errores: httpd.exe, versión: 2.4.23.0, marca de tiempo: 0x577631b1
Nombre del módulo con errores: php7ts.dll, versión: 7.0.13.0, marca de tiempo: 0x58224f14
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x00006e9c
Identificador del proceso con errores: 0xa94
Hora de inicio de la aplicación con errores: 0x01d2445048af3f7e
Ruta de acceso de la aplicación con errores: C:\xampp7\apache\bin\httpd.exe
Ruta de acceso del módulo con errores: C:\xampp7\php\php7ts.dll
Identificador del informe: 8380d68c-d983-4a04-9527-191215a2eea8
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores: _

**Comment by vovech** [comment]
As this issue been closed i opened  a new one:

https://github.com/Microsoft/msphpsql/issues/186
