### ISSUE TITLE
Docker: cannot start mssql windows container after copying files into volume

### ISSUE THREAD

**Issue by MehdiAbed** [Microsoft/msphpsql#824]
##After creating a docker image as follow: 
`PS> docker run -d -p 1433:1433 --name sql1 -v sql1data:C:/sqldata -e sa_password=MyPass123 -e ACCEPT_EULA=Y microsoft/mssql-server-windows-developer`

##I stopped my container and copied a backupfile into my volume:
`PS> docker cp .\DataBase.bak sql1:C:\data`

##After that I can no longer start my container, the error message is as follows:
```
Error response from daemon: container 5fe22f4ac151d7fc42541b9ad2142206c67b43579ec6814209287dbd786287dc encountered an error during Start: failure in a Windows system call: Le système de calcul s’est fermé de façon inattendue. (0xc0370106)
Error: failed to start containers: sql1
```

I can start and stop any other container, the problem occurs only after copying the file into the volume.
I'm using windows containers 
my docker version is 18.06.0-ce-win72 (19098)

the only workaround i found is to not copy any files into my container volume.

Ay ideas ?

**Comment by yitam** [comment]
I'm afraid this is not the right page to post an issue about [mssql-server-windows-developer](https://hub.docker.com/r/microsoft/mssql-server-windows-developer/).

**Comment by MehdiAbed** [comment]
Right, I'm moving the issue under Microsoft/mssq-docker. 
Thank you
