### ISSUE TITLE
Unable to load dynamic library

### ISSUE THREAD

**Issue by Alcatros** [Microsoft/msphpsql#830]
Error message: PHP Startup: Unable to load dynamic library 'php_sqlsrv_72_nts.so' (tried: /usr/lib/php/20170718/php_sqlsrv_72_nts.so (libodbc.so.2: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/php_sqlsrv_72_nts.so.so (/usr/lib/php/20170718/php_sqlsrv_72_nts.so.so: cannot open shared object file: No such file or directory))

 +## PHP Driver version or file name
 +
PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.7-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies

 +## SQL Server version
 + Just client based issue used the sharedobject from Ubuntu18-7.2.tar on the repo, tried to load php_sqlsrv_72_ts.so and php_sqlsrv_72_nts.so, both seem not to be loadable.
 +## Client operating system
 + Ubuntu 18.04
 +## PHP version
 + 7.2
 +## Microsoft ODBC Driver version
 + libodbc2.so
 +## Table schema
 +
 +## Problem description
 + I try to load the mssql driver for a php application on a docker container.

root@a4ff3b5c264d:/var/www/html# ll /usr/lib/php/20170718/php_sqlsrv_72_nts.so
-rwxrwxrwx 1 root root 350208 Jul 31 22:27 /usr/lib/php/20170718/php_sqlsrv_72_nts.so*

I have given for the tests purpose full access rights and it cant find the driver for some reason.

 +## Expected behavior and actual behavior
 + Expected: Should load the driver and work as expected. Actual: refuses to load the driver
 +## Repro code or steps to reproduce
Run any application which requires a mssql connect.

**Comment by david-puglielli** [comment]
The error message indicates that libodbc is missing. This library is provided by unixodbc. Have you installed unixodbc and the MS ODBC driver? Full instructions for installing them are provided [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017). Full instructions for installing the PHP drivers are provided [here](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017).

**Comment by Alcatros** [comment]
Thanks David-pugglielli i will give it a shot and write back here

**Comment by Alcatros** [comment]
@david-puglielli  thanks it worked. Is it possible to add the msodbc library plain? My docker image increased +300 mb after following the install guide for ubuntu 18.04?

**Comment by GeoffreyDijkstra** [comment]
@Alcatros You don't need all that :smile: See the copied parts from my docker file (note I used PHP 7.3, but also works for 7.1 and 7.2, this also removes the need for php-dev package):

```Dockerfile
FROM ubuntu:bionic
ENV ACCEPT_EULA=Y

RUN apt-get update; apt-get install -y unixodbc php7.3-odbc
RUN mkdir /tmp/sqlsrv
RUN wget https://packages.microsoft.com/ubuntu/18.10/prod/pool/main/m/msodbcsql17/msodbcsql17_17.4.2.1-1_amd64.deb -qO /tmp/sqlsrv/msodbcsql17.deb
RUN dpkg -i /tmp/sqlsrv/msodbcsql17.deb
RUN wget https://github.com/microsoft/msphpsql/releases/download/v5.6.1/Ubuntu18-7.3.tar -qO /tmp/sqlsrv/sqlsrv.tar
RUN tar -C /tmp/sqlsrv -xvf /tmp/sqlsrv/sqlsrv.tar --strip-components 1
RUN cp /tmp/sqlsrv/*sqlsrv_73_nts*.so `php -i | grep -e '^extension_dir' | sed -rn 's/.*=> (.*).*$/\1/p'`
RUN rm -rf /tmp/sqlsrv
```
