### ISSUE TITLE
PDO::SQLSRV_ATTR_QUERY_TIMEOUT not work.

### ISSUE THREAD

**Issue by hzw-the-programmer** [Microsoft/msphpsql#838]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 +5.2.0
 +## SQL Server version
 +2012
 +## Client operating system
 +ubuntu 16.04
 +## PHP version
 +7.0
 +## Microsoft ODBC Driver version
 +17
 +## Table schema
 +
 +## Problem description
 +PDO::SQLSRV_ATTR_QUERY_TIMEOUT not work.
 +## Expected behavior and actual behavior
 +$db->query() should return after 1 second but 270 seconds
 +## Repro code or steps to reproduce
 +$dbh = new PDO(..., [PDO::SQLSRV_ATTR_QUERY_TIMEOUT => 1]); // success
 +sleep(10); // while it sleep, I disable the network interface
 +$dh->query() // this will block about 270 second

**Comment by yitam** [comment]
@hzw-the-programmer I can't seem to reproduce this. How long did you disable the network interface for? Before the sleep was over or longer?

Also, please give this a try:

```
$t0 = microtime(true);
$stmt = $conn->query("WAITFOR DELAY '00:00:10'; $your_query");
var_dump($conn->errorInfo());
$t1 = microtime(true);
echo "Time elapsed: " . ($t1 - $t0) . " sec\n";
```

I tried the above by disabling the network for less than 10 seconds, and I got this

```
array(3) {
  [0]=>
  string(5) "HYT00"
  [1]=>
  int(0)
  [2]=>
  string(63) "[Microsoft][ODBC Driver 17 for SQL Server]Query timeout expired"
}
Time elapsed: 13.885461091995 sec
```

**Comment by hzw-the-programmer** [comment]
Thanks. I tried, but not work. 
I disabled the network interface (ifconfig enp0s3 down) before the execution of the query until it throws exception.
I want to simulate this: after connection success, do some query, then network broke, query again.
and at this query, I want to get error or exception quick not block for a long time.
Here is my code and comment:
`
<?php
$server = '10.0.37.248'; //$argv[1];
$user = 'sa'; //$argv[2];
$passwd = '123456'; //$argv[3];

$dsn = "sqlsrv:Server=$server;Database=test;LoginTimeout=5";

$dbh = new PDO($dsn, $user, $passwd, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::SQLSRV_ATTR_QUERY_TIMEOUT => 2 // this does not work as I expected.
]);

echo "before sleep\n"; // after this display, I disable the network interface: ifconfig enp0s3 down.
sleep(10);
echo "after sleep\n"; // when this display, network interface is already down.

$start = microtime(true);
try {
    echo "before query\n"; // this will display.
    $dbh->query("WAITFOR DELAY '00:00:10'; SELECT 1"); // it blocks here for about 242 seconds.
} catch (PDOException $e) {
    print_r($e->errorInfo); // this will run after about 242 seconds, not as I expected 1 second.
}
echo "cost: " . (microtime(true) - $start) . PHP_EOL;
`
Here is the output:
`
before sleep
after sleep
before query
Array
(
    [0] => HYT00
    [1] => 0
    [2] => [Microsoft][ODBC Driver 17 for SQL Server]Query timeout expired
)
cost: 242.18173193932
`

**Comment by hzw-the-programmer** [comment]
@yitam Thanks. I tried, but not work. 

I disabled the network interface (ifconfig enp0s3 down) before the execution of the query until it throws exception.

I want to simulate this: after connection success, do some query, then network broke, query again.
and at this query, I want to get error or exception quick not block for a long time.

Here is my code and comment:
```
<?php
$server = '10.0.37.248'; //$argv[1];
$user = 'sa'; //$argv[2];
$passwd = '123456'; //$argv[3];

$dsn = "sqlsrv:Server=$server;Database=test;LoginTimeout=5";

$dbh = new PDO($dsn, $user, $passwd, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::SQLSRV_ATTR_QUERY_TIMEOUT => 2 // this does not work as I expected.
]);

echo "before sleep\n"; // after this display, I disable the network interface: ifconfig enp0s3 down.
sleep(10);
echo "after sleep\n"; // when this display, network interface is already down.

$start = microtime(true);
try {
    echo "before query\n"; // this will display.
    $dbh->query("WAITFOR DELAY '00:00:10'; SELECT 1"); // it blocks here for about 242 seconds.
} catch (PDOException $e) {
    print_r($e->errorInfo); // this will run after about 242 seconds, not as I expected 1 second.
}
echo "cost: " . (microtime(true) - $start) . PHP_EOL;
```
Here is the output:
```
before sleep
after sleep
before query
Array
(
    [0] => HYT00
    [1] => 0
    [2] => [Microsoft][ODBC Driver 17 for SQL Server]Query timeout expired
)
cost: 242.18173193932
```

**Comment by hzw-the-programmer** [comment]
@yitam Sorry, I misunderstand the use of PDO::SQLSRV_ATTR_QUERY_TIMEOUT. 
But why query() blocks when network is broken?
How to prevent this? Is there another configuration for this (detect network errors.)?

**Comment by yitam** [comment]
hello @hzw-the-programmer 

When the network is down, I'm not even sure if communication from the server to the client driver is possible. Also, based on your more detailed script above, when did you re-enable the network interface?

Nonetheless, it should have failed sooner with some error message like broken connection or something like that.

What ODBC driver and unixODBC versions are you using? With ODBC 17.2, the latest PHP drivers (5.3.0) supports [connection resiliency](https://docs.microsoft.com/en-us/sql/connect/php/connection-resiliency?view=sql-server-2017), which attempts to reconnect when the connection is broken.

Are you using connection pooling by any chance?

**Comment by hzw-the-programmer** [comment]
@yitam Thanks. I miss understand the use of PDO::SQLSRV_ATTR_QUERY_TIMEOUT.

**Comment by yitam** [comment]
Ok @hzw-the-programmer 
Let us know if you have other questions. If we don't hear from you we will close this issue. Thanks!

**Comment by yitam** [comment]
Closing this issue @hzw-the-programmer. Please feel free to reopen if you have any other questions.
