### ISSUE TITLE
Can't insert/update a Cyrillic characters to the database.

### ISSUE THREAD

**Issue by endigo** [Microsoft/msphpsql#845]
## PHP Driver version or file name
latest
## SQL Server version
SQL Server 2008 R2
## Client operating system
Ubuntu 18.04 || Mac OS High Sierra
## PHP version
PHP 7.2
## Microsoft ODBC Driver version
unixodbc-dev -- it's latest

 ## Problem description
Can't insert any Cyrillic characters to any table of my database.
They all to changed ??????.

I'm using Laravel 5.6 project. 

// config/database.php
*** php
'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
        ],
***

**Comment by yitam** [comment]
Hi @endigo 

To narrow down the issue, please try without using Laravel, following the example on this [page](https://docs.microsoft.com/en-us/sql/connect/php/how-to-send-and-retrieve-utf-8-data-using-built-in-utf-8-support?view=sql-server-2017), if possible. 

Also, can you give us a sample of your Cyrillic characters for us to test?

**Comment by endigo** [comment]
FIXED: After upgrading laravel 5.5 to 5.7.
