### ISSUE TITLE
Ubuntu 18.04 Installation of MSODBCSQL Driver 17

### ISSUE THREAD

**Issue by plabbett** [Microsoft/msphpsql#847]
## PHP Driver version or file name

5.3

 ## Client operating system

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	        18.04
Codename:	bionic

 ## PHP version
 
7.2

 ## Microsoft ODBC Driver version

Microsoft ODBC Driver 17 for SQL Server

## Problem description

Attempted to follow installation instructions found here: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017

The driver installs fine through PECL and I can load/use it in PHP, but it gives me the following message: 

`SQLSTATE[IMSSP]: This extension requires the Microsoft ODBC Driver for SQL Server to communicate with SQL Server. Access the following URL to download the ODBC Driver for SQL Server for x64: https://go.microsoft.com/fwlink/?LinkId=163712 (SQL: SELECT TOP 1 * FROM tablename)`

## Expected behavior and actual behavior

My expectation was to follow the Ubuntu 18.04 install instructions at the link above and have a working PHP SQLSRV driver. However, it fails trying to install msodbcsql17. 

user@hostname:~$ sudo apt-get install msodbcsql17
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 msodbcsql17 : Depends: unixodbc (>= 2.3.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

user@hostname:~$ sudo apt-get install unixodbc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package unixodbc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  odbcinst1debian2 odbcinst libodbc1

E: Package 'unixodbc' has no installation candidate

user@hostname:~$ sudo apt-get install odbcinst1debian2 odbcinst libodbc1
Reading package lists... Done
Building dependency tree
Reading state information... Done
libodbc1 is already the newest version (2.3.4-1.1ubuntu3).
odbcinst is already the newest version (2.3.4-1.1ubuntu3).
odbcinst1debian2 is already the newest version (2.3.4-1.1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

> odbcinst -j
unixODBC 2.3.4
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/user/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
 

> dpkg-query -L libodbc1
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libodbc.so.2.0.0
/usr/lib/x86_64-linux-gnu/libodbccr.so.2.0.0
/usr/lib/x86_64-linux-gnu/odbc
/usr/lib/x86_64-linux-gnu/odbc/libnn.so
/usr/share
/usr/share/doc
/usr/share/doc/libodbc1
/usr/share/doc/libodbc1/NEWS.Debian.gz
/usr/share/doc/libodbc1/changelog.Debian.gz
/usr/share/doc/libodbc1/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libodbc1
/usr/lib/x86_64-linux-gnu/libodbc.so.1
/usr/lib/x86_64-linux-gnu/libodbc.so.2
/usr/lib/x86_64-linux-gnu/libodbccr.so.1
/usr/lib/x86_64-linux-gnu/libodbccr.so.2

**Comment by plabbett** [comment]
It was a clean install, adding in the ondrej PPA for Ubuntu. My sources.list has the typical sources in it. I will try another clean server and see which PPA breaks it I guess. Thanks, will report back. 

deb http://archive.ubuntu.com/ubuntu bionic main
deb http://archive.ubuntu.com/ubuntu bionic-security main
deb http://archive.ubuntu.com/ubuntu bionic-updates main

**Comment by yitam** [comment]
Oh that explains it. Do not add the ondrej PPA because it comes with [conflicting dependencies](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-ubuntu-1604-1710-and-1804). Please click our notes in the link.

**Comment by plabbett** [comment]
Yeah, I must have have read the first few sentences of that info box without groking the warning about conflict, especially since the Step 1 on that page shows adding in the ondrej PPA. Thanks for pointing it out!

**Comment by benyanke** [comment]
Is there any way to do it while retaining the ondrej repo?

**Comment by yitam** [comment]
@benyanke we do plan to test that out very soon as PHP 7.3 is going to GA in about a week. Meanwhile, [this page](https://ayesh.me/Ubuntu-PHP-7.3) might have answered your questions.

**Comment by benyanke** [comment]
Thanks @yitam - it looks like that link recommends the ondrej repo however. Is there any plans to have the PECL packages work well with the ondrej repo?

**Comment by yitam** [comment]
Yes @benyanke we will verify PECL install with the latest ondrej repo and if compatible, we will update our instructions accordingly. Rest assured this is of high priority.

**Comment by benyanke** [comment]
Excellent. Thank you!

**Comment by benyanke** [comment]
Where can I subscribe / watch to track this?

**Comment by yitam** [comment]
We will update our release page and instructions some time after PHP 7.3 GA so please stay tuned, @benyanke

**Comment by yitam** [comment]
@benyanke 
> Where can I subscribe / watch to track this?

FYI, please follow https://blogs.msdn.microsoft.com/sqlphp/

**Comment by yitam** [comment]
FYI, @benyanke 
[5.5.0-preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.5.0-preview) is published, and we welcome feedback.

**Comment by benyanke** [comment]
Thanks for the notification @yitam . I look forward to now start updating my application to php 7.3.

For the help of anyone else who finds this, github also introduced a great new feature: watching *only* releases.

![image](https://user-images.githubusercontent.com/4274911/49681435-32767680-fa67-11e8-8df9-784c651fb474.png)


I've done this on this repo, and hopefully it's helpful to others as well.

**Comment by funcelotwork** [comment]
Very detailed instructions:

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15
