### ISSUE TITLE
Bug pdo_sqlsrv returns integer as string

### ISSUE THREAD

**Issue by mschop** [Microsoft/msphpsql#859]
The PDO driver (pdo_sqlsrv) returns an integer as a string. I would expect it to return it as a PHP integer instead.
The non PDO driver (sqlsrv) returns integers correctly as an php integer. So this seems like an inconsistent behaviour between the two driver variants.

Environment:
- Windows 10 x64
- Ubuntu 18.04 Sub System
- PHP 7.2
- SQL-Server 2016/4 Developer Edition
- ODBC-Driver-Version: 2.3.4-1.1ubuntu3
- Table Schema: Irrelevant as it is reproducible for default integer.

Here my test code:

```
<?php

$query = "SELECT TOP 1 id from product";

$connectionOptions = array("Database"=>"somedb", "Uid"=>"someuser", "PWD"=>"somepassword", "LoginTimeout" => 10);
$conn = sqlsrv_connect('tcp:localhost\\INSTANCE,1433', $connectionOptions);
$stmt = sqlsrv_query($conn, $query);
echo("\n" . gettype(sqlsrv_fetch_array($stmt)['id']));

$pdoConn = new PDO("sqlsrv:Server=localhost;Database=somedb", "someuser", "somepassword");
$stmt = $pdoConn->query($query);
echo("\n" . gettype($stmt->fetch(\PDO::FETCH_ASSOC)['id']));

echo("\n");
```

The resulting output is:

```
integer
string
```
 
Conclusion: The drivers return db integers differently.
Expected: Both values should have the same type.

Best Regards
mschop

**Comment by yitam** [comment]
Hi @mschop it's not a bug. It's by design to adhere to [PHP PDO standard](http://php.net/manual/en/book.pdo.php). However, we do provide the attribute `PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE` in our [pdo_sqlsrv ](https://docs.microsoft.com/en-us/sql/connect/php/pdo-setattribute?view=sql-server-2017) for fetching integers as numbers.

**Comment by mschop** [comment]
@yitam Thanks. I didn't research on this but as far as I know, other PDO driver do provide numeric types by default (e.g. MySQL). I'm not sure on this but maybe, the you could recheck this. Maybe the standard is not as strict in this point.

Thanks very much for you help. Switched to pdo_sqlsrv now ;-)
