### ISSUE TITLE
Driver fails to load with no errors in php 7.1.22

### ISSUE THREAD

**Issue by joneschrisan** [Microsoft/msphpsql#860]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 + 7.1 
 +## SQL Server version
 + 2018
 +## Client operating system
 + Windows 10
 +## PHP version
 + 7.1.22 64 bit non thread safe
 +## Microsoft ODBC Driver version
 + 17
 +## Table schema
 + n/a
 +## Problem description
 + Module doesn't load and the driver is not available but no errors logged
 +## Expected behavior and actual behavior
 + Module should load and driver should be available or start up error should be logged
 +## Repro code or steps to reproduce
 Installed php 7.1.22 x64 nts
 Installed ODBC 17
 Added driver DLL to ext folder and to php.ini
 run `php -m` from php folder
 run `php -r phpinfo();`
 Driver not loaded

**Comment by david-puglielli** [comment]
@joneschrisan If you have added the driver to php.ini and to the extension folder but no error comes up when running php, I can only surmise that either the extension folder is wrong, or the php.ini is wrong. Please verify that you have the correct php.ini file by running `php --ini` and that you have the correct extension folder by running `php -i | sls extension_dir` (in powershell).

**Comment by david-puglielli** [comment]
@joneschrisan Does this problem still occur? We will close the issue in a few days if we do not hear from you.

**Comment by david-puglielli** [comment]
Closing the issue. Please reopen if the you still have the problem.
