### ISSUE TITLE
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'view_table'

### ISSUE THREAD

**Issue by yusren** [microsoft/msphpsql#876]
My Specs: Ubuntu 16.04, PHP 7.1.23-4, pdo_sqlsrv.so driver for PHP.
I've created a view_table on my Database-Views. I make a view because there are too many join tables. The code, in Windows works normally, but on Ubuntu 16.04 it produces an error message.
```[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'view_table'```
is there anyone here who has faced this problem?

**Comment by david-puglielli** [comment]
@yusren It's quite strange that an existing table cannot be found - the `invalid object name` error is returned by SQL Server itself. What versions of pdo_sqlsrv, ODBC driver and unixODBC are you using? Can you provide a repro script so we can see how the view is created and how you are trying to access it in Ubuntu?

**Comment by yusren** [comment]
I'm following this guide to installing Linux ODBC for Ubuntu 16.04:
[https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#microsoft-odbc-driver-17-for-sql-server](url)
This is my version of odbcinst (2.3.1-4.1), msodbcsql17 (17.2.0.1-1), mssql-tools (17.2.0.2-1)
But I've no idea how to get my sqlsrv.so and pdo_sqlsrv.so version
[https://www.microsoft.com/en-us/sql-server/developer-get-started/php/ubuntu/step/2.html](url)
I followed these instructions yesterday, I think the version is still the same as today.
FYI : I'm trying to run this query from **sqlcmd** ```select top 10 * from view_table_customers```
the query works well!
Thanks in advance.

**Comment by david-puglielli** [comment]
You can get the version of sqlsrv and pdo_sqlsrv by running `php --ri sqlsrv` and `php --ri pdo_sqlsrv`. But it would really help us most if you could provide a repro script for this.

**Comment by david-puglielli** [comment]
I want to clarify: you've got a table called view_table (or v_employee_attendance, or view_table_customers) that results from running a query like the one above (the query with all the joins). You can access this table when running the script above in Windows, but not in Ubuntu. Can you access this table in Ubuntu without using laravel? ie. try something like this:
```
$stmt = sqlsrv_query($conn, "SELECT * FROM v_employee_attendance");
print_r(sqlsrv_errors());
while($res = sqlsrv_fetch_array($stmt))
{
    print_r($res);
}
```

**Comment by yusren** [comment]
I'm trying to delete and re-create v_employee_attendance and now it's working like it should. I think this is an anomaly on Halloween. Big Thanks for your time, Sir.

**Comment by david-puglielli** [comment]
Ok, closing the issue. Feel free to reopen if needed.

**Comment by Hayat21** [comment]
hello There,
can You help me to solve This ERROR, It launch when i am trying to execute a service that consomate data by an API


ERROR [2023-01-24 07:56:51,640] (synch_press, synch:298) ERROR : b'{"message":"ERROR : (\'42S22\', \\"[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name \'IdDocLink\'. (207) (SQLExecDirectW)\\")"}'
Traceback (most recent call last):
  File "/workdir/services/synch_press.py", line 183, in synch
    service = self.service
  File "/workdir/utils/decorators.py", line 112, in wrap_func
    raise e
  File "/workdir/utils/decorators.py", line 110, in wrap_func
    return func_handler(resp)
  File "/workdir/api/articles_api.py", line 49, in func_handler
    raise Exception(message)
Exception: b'{"message":"ERROR : (\'42S22\', \\"[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name \'IdDocLink\'. (207) (SQLExecDirectW)\\")"}'
