### ISSUE TITLE
t -j

### ISSUE THREAD

**Issue by Moorelife** [Microsoft/msphpsql#877]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 +
 +## SQL Server version
 +
 +## Client operating system
 +
 +## PHP version
 +
 +## Microsoft ODBC Driver version
 +
 +## Table schema
 +
 +## Problem description
 +
 +## Expected behavior and actual behavior
 +
 +## Repro code or steps to reproduce

**Comment by david-puglielli** [comment]
@Moorelife Is there an issue here?

**Comment by Moorelife** [comment]
No sorry, i remember having typed something that ended up in the wrong window, but couldn't find it anymore. Sorry if it ended up here...

**Comment by david-puglielli** [comment]
Closing the issue, please reopen if needed.
