### ISSUE TITLE
Error signature on MacOS

### ISSUE THREAD

**Issue by nightwolf93** [Microsoft/msphpsql#884]
Hello,
I have a mac on Mojave and when i try to load the .so file on php 7.1 i have this error :
mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

I didn't found any solutions
Thank you

**Comment by david-puglielli** [comment]
@nightwolf93 Which .so file is it? Can you provide the full error message that you get?

**Comment by nightwolf93** [comment]
Solved, instead of load the .so in the php.ini, i loaded it directly on Apache and it work
