### ISSUE TITLE
Why not bundle ms php sql into php source repository?

### ISSUE THREAD

**Issue by netroby** [Microsoft/msphpsql#89]
Why not bundle ms php sql into php source repository?

github.com/php/php-src

The opensource project php will like everyone's contribute.

**Comment by meet-bhagdev** [comment]
@netroby : Great idea! Definitely open to it. Does the driver need to be cross platform to get integrated into the PHP core?

**Comment by netroby** [comment]
Yes, user may running php on Windows/Linux/Unix, So the driver need more test under different platform.

**Comment by meet-bhagdev** [comment]
Makes sense. Once we complete our port on Linux over the next few weeks followed by Mac at some point in future, we will look into doing this :) I will keep the issue open for tracking.
