### ISSUE TITLE
Analysis Services Driver

### ISSUE THREAD

**Issue by v-mabarw** [Microsoft/msphpsql#9]
Provide an interface to SQL Server Analysis Services.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 16555](http://sqlsrvphp.codeplex.com/workitem/16555)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Feb 26, 2010 at 6:27 AM
**Reported by:**    MitchMcBride
**Updated on:** Mar 8 at 11:04 AM
**Updated by:** miguelajh

**Comment by meet-bhagdev** [comment]
Closing as it is out of scope for now.
