### ISSUE TITLE
macos `pdo_sqlsrv_db_handle_factory: Unknown exception caught`

### ISSUE THREAD

**Issue by peterlupu** [Microsoft/msphpsql#906]
## PHP Driver version or file name
pdo sqlsrv 5.3.0
 ## SQL Server version
 
 ## Client operating system
 mac os Mojave 10.14.1 (18B75)
 ## PHP version
 PHP 7.2.13
 
This issue is very similar to #161 

it worked fine until today when I rebooted my local machine.

The error I'm getting when trying to connect to any MSSQL Database is: `pdo_sqlsrv_db_handle_factory: Unknown exception caught`

I've tried clearing all php installations and configs and reinstalling:
- php 7.2 (homebrew)
- `sudo pecl install pdo_sqlsrv`
- `sudo pecl install sqlsrv`
- `brew install --no-sandbox msodbcsql mssql-tools`

Now i'm getting `pdo_sqlsrv_db_handle_factory: Unknown exception caught`.

Looking at #161, I've added `export LC_ALL=en_US.UTF-8` and `export LANG=en_US.UTF-8` to my .zshrc file. In the console, I can connect successfuly, but running PHP through Apache, I get the above error.

I've tried setting Env Vars from Apache to PHP, using 
```
SetEnv LC_ALL "en_US.UTF-8"
SetEnv LANG "en_US.UTF-8"
```

And it has been set successfully, but I still get the same error.

Any help with this, please?

**Comment by sahil-devzila** [comment]
Thanks for the explanation and i am also caught up in the same issue. how did you add this to php environment ? i was able to add this only to apache environment.
