### ISSUE TITLE
PDO_SQLSRV drivers 5.3 vs 4.3 issues

### ISSUE THREAD

**Issue by fredsky2003** [Microsoft/msphpsql#915]
+## PHP Driver version or file name
 +
version PDO_SQLSRV 5.3
 php_sqlsrv_71_ts.dll
php_pdo_sqlsrv_71_ts.dll

 +## SQL Server version
 + Microsoft SQL Server 2012 - 11.0.2100.60 (X64)   Feb 10 2012 19:39:15   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) 
 +## Client operating system
 + Windows Server 2008 R2 Standard Edition Service Pack 1
 +## PHP version
 + 7.1.15 x64
 +## Microsoft ODBC Driver version
 + 17.2 (latest as today), installed on 2008 R2 machine
 +## Table schema
 + 2 servers : 1) SQL 2012 entreprise x64  2) 2008 R2 + PHP 7.1.15 + PDO_SQLSRV 5.3 + ODBC 13 + ODBC 17
+
 +## Problem description
 + it works "well" when using PDO_SQLSRV 4.3 (old) version, with either ODBC 13 or 17.
+ but as soon as i install the 2 new PHP DLL of PDO_SQLSRV 5.3; i got this : 

ERROR : Connection could not be established.<br />SQLSTATE[IM004]: [Microsoft][ODBC Driver Manager] Driver's SQLAllocHandle on SQL_HANDLE_ENV failed

 +## Expected behavior and actual behavior
 + working with PDO 5.3 version
 +## Repro code or steps to reproduce
 here is my connection code in PHP 

<code>
try
{
    $mssqlCconn = new PDO("sqlsrv:server=".$server.";Database=".$dbname,
        $user,
        $pwd,
            array(
            PDO::SQLSRV_ATTR_QUERY_TIMEOUT  => 30,//"Specify your time here (seconds)",
            PDO::SQLSRV_ATTR_DIRECT_QUERY => true
        )
    );

    $mssqlCconn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); //obligatoire pour chopper TOUTES les cas d'erreurs!
}
catch(Exception $e)
{
    echo "ERROR : Connection could not be established.<br />";
    echo $e->getMessage();
    die( log_to_file( $e->getMessage() ,"logDB_init.txt" ) );
}
</code>

**Comment by fredsky2003** [comment]
ok this is solved by 

> For those who have Driver 17.1.0.1 or below installed, it is recommended that it be uninstalled manually prior to installing the newer version of the Driver

which means that i've to :
- uninstall all versions of ODBC
- reboot the machine
- install only ODBC 17.2


it also solve the issue of SQLCMD not working.

so now : PHP 7.1 x64 + SQLSRV 5.3 + ODBC 17.2 + SQLCMD works perfectly together :)

**Comment by docktermj** [comment]
Related issue: https://github.com/microsoft/mssql-docker/issues/431
