### ISSUE TITLE
complex stored procedure and PDO_SQLSRV

### ISSUE THREAD

**Issue by fredsky2003** [Microsoft/msphpsql#916]
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 +version PDO_SQLSRV 5.3
 +## SQL Server version
 +Microsoft SQL Server 2012 - 11.0.2100.60 (X64) Feb 10 2012 19:39:15 Copyright (c) Microsoft Corporation Enterprise Edition (64-bit) on Windows NT 6.1 (Build 7601: Service Pack 1)
 +## Client operating system
 +Windows Server 2008 R2 Standard Edition Service Pack 1
 +## PHP version
 +7.1.15 x64
 +## Microsoft ODBC Driver version
 + version 13 or 17
 +## Table schema
 +2 servers : 1) SQL 2012 entreprise x64 2) 2008 R2 + IIS + PHP 7.1.15 + PDO_SQLSRV 4.3 + ODBC 13 
+ my desktop , where i display the web page trough IIS is win10 x64
 +## Problem description
 +running an SP with complex code (this code is itself using several others SP) DOES NOT complete and does NOT FAIL, but result is incorrect.
i mean : my code does call and run the SP; but the result in the database is wrong; it's like the SP was not 100% run, stopped at 50%.

running the same SP, with same parameters , via SQLCMD works perfectly (from my desktop or from sqlserver itself); and result is correct in the database.

 +## Expected behavior and actual behavior
 + working, or at least giving error message.
 +## Repro code or steps to reproduce
 here is my PHP code to call the SP

a) connect to DB
<code>
try
{
    $mssqlCconn = new PDO("sqlsrv:server=".$server.";Database=".$dbname,
        $user,
        $pwd,
            array(
            PDO::SQLSRV_ATTR_QUERY_TIMEOUT  => 30,//"Specify your time here (seconds)",
            PDO::SQLSRV_ATTR_DIRECT_QUERY => true
        )
    );

    $mssqlCconn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); //obligatoire pour chopper TOUTES les cas d'erreurs!
}
catch(Exception $e)
{
    echo "ERROR : Connection could not be established.<br />";
    echo $e->getMessage();
    die( log_to_file( $e->getMessage() ,"logDB_init.txt" ) );
}

</code>

b) the part that call the Stored Procedure:

<code>
// i receive the input parameter "id" via GET

try {
        $sql = "exec [dbo].[dupliquer_Fiche]  ".$_GET['id'];
        $mssqlCconn->setAttribute(constant('PDO::SQLSRV_ATTR_DIRECT_QUERY'), true);
        $array = $mssqlCconn->query($sql)->fetchAll(PDO::FETCH_ASSOC);
    }
    catch (PDOException $e) {
        echo 'PDO failed: ' . $e->getMessage();
    }
</code>

**Comment by fredsky2003** [comment]
still not working after proper installation of SQLSRV drivers 5.3 + ODBC 17.2

**Comment by yitam** [comment]
@fredsky2003 glad to know that you resolved the installation problem in #915 

Please provide more details about the failing stored procedure to help us understand what went wrong. Just so you know there was some breaking change between 4.3 and 5.3 as well.

**Comment by fredsky2003** [comment]
![complexsp](https://user-images.githubusercontent.com/28629771/50991523-d928b980-14e2-11e9-9dc2-fe3e389950bb.PNG)

this is a screenshot, that show only about 1/3 of my SP.
this SP call many others SP.
the overall time to complete is <1 sec when running through SQL management studio

**Comment by yitam** [comment]
Thank you for providing more details, @fredsky2003 . However, by showing a snapshot of the complicated stored procedure that invokes other stored procedures doesn't help us with investigation. 

> i mean : my code does call and run the SP; but the result in the database is wrong; it's like the SP was not 100% run, stopped at 50%.

In order to reproduce this problem please provide a much simpler version of a stored procedure that clearly shows us what worked before with 4.3 but not with 5.3. In addition, please indicate the expected output and provide actual output of a single stored procedure.

**Comment by fredsky2003** [comment]
sorry i don't have this.
my SP doesn't work/had never worked with ANY version of PDO_SQLDRV.
my all my others SP, that are much simpler works...
i don't know how to debug it

**Comment by fredsky2003** [comment]
AWESOME!
PDO:exec works like a charm.

so if i understand well, it's ONLY because the first part of my SP use a temp #t table?

can you put the  issue #260 in BOLD AND BIG in the driver download page?
as well as the ABSOLUTE NECESSITY to uninstall any preview ODBC driver, then reboot, then install new one.

i've spend 3 days on those 2 issues.

regards,
fred

**Comment by yitam** [comment]
Ok sounds great, @fredsky2003 
Closing this issue now. Please feel free to reopen if you have question.
