### ISSUE TITLE
Change language at login

### ISSUE THREAD

**Issue by vrobert78** [Microsoft/msphpsql#929]
Hi,

as for the issue #14, we need to change the language during login.

The official ODBC documentation mentions the language attribute: https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-2017

But it is not usable in this driver: https://docs.microsoft.com/en-us/sql/connect/php/connection-options?view=sql-server-2017

In the past with freetds, the option existed. (http://www.freetds.org/userguide/locales.htm)
In /etc/locales.conf:
```
[en_US]
	date format = %b %e %Y %I:%M:%S:%z%p
	language = us_english
	charset = iso_1
```
As a workaround, we use a `sqlsrv_query($this->bdd, 'SET LANGUAGE us_english');` .

Is there any chance that you add the language option ?

Regards,

Vincent

**Comment by gdegoulet** [comment]
it could maybe help you ? PR : https://github.com/Microsoft/msphpsql/pull/930

**Comment by david-puglielli** [comment]
@vrobert78 @gdegoulet Thank yo for your contributions. We will review the PR you provided after the next RTW, which should be in the next few days.

**Comment by david-puglielli** [comment]
PR #930 merged. Closing issue. Please reopen if necessary.
