### ISSUE TITLE
packages.microsoft.com Debian Packages does not verify

### ISSUE THREAD

**Issue by andrewnicols** [Microsoft/msphpsql#938]
Strictly speaking this is not an issue with msphpsql but I couldn't find anywhere appropriate to file this.

It appears that the Packages list on packages.microsoft.com was updated on 25th February, but the InRelease file for it was not (last update 19th Feb).

Files known to be affected:
https://packages.microsoft.com/debian/9/prod/dists/stretch/InRelease
https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/

It also looks like the Release was updated, but not the Release.gpg

This makes it impossible to install safely on Debian.

```
Hit:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease
Get:2 https://packages.microsoft.com/debian/9/prod stretch InRelease [3232 B]
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:5 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages [38.0 kB]
Err:5 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages
  Writing more data than expected (38208 > 37999)
  Hashes of expected file:
   - Filesize:37999 [weak]
   - SHA512:194ded11a350aab88b7fc1c5fee5dd6746a6bd0136ee96ad2290fc9459086daf75fbeda376ab00c0455cbeab6e64fa405f82ef0991b28322f29f30dab2aaaede
   - SHA256:369f15b8a43c29e6adf6db3329576366123c6bb749ee311f5099752de06474ea
   - SHA1:87f67045f0db46ee582998ba1d432b47900f5992 [weak]
   - MD5Sum:38eeded94abf10a911e570233047151b [weak]
  Release file created at: Tue, 19 Feb 2019 18:30:09 +0000
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Hit:6 http://cdn-fastly.deb.debian.org/debian stretch Release
Fetched 3232 B in 0s (6394 B/s)
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Writing more data than expected (38208 > 37999)
```

**Comment by david-puglielli** [comment]
@andrewnicols Yes we are aware of the issues with the repos and they are being fixed. Please stay tuned, it should not be long before they are fixed.

**Comment by andrewnicols** [comment]
Thanks for the prompt response @david-puglielli. Have a great day.

**Comment by david-puglielli** [comment]
The latest ODBC driver should now be in the repos and the problems fixed. Please try again and let us know if there are any issues. Thanks!

**Comment by david-puglielli** [comment]
Closing issue, please reopen if necessary.
