### ISSUE TITLE
Packages haven't been deployed to windows.php.net

### ISSUE THREAD

**Issue by morozov** [Microsoft/msphpsql#955]
The [5.6.0](https://windows.php.net/downloads/pecl/releases/sqlsrv/5.6.0/) directory exists on windows.php.net since February 22 but it's empty:

![image](https://user-images.githubusercontent.com/59683/54406252-9e83fe80-4696-11e9-80b6-f39376c194b5.png)

The fact that https://pecl.php.net/rest/r/sqlsrv/stable.txt points to 5.6.0 [breaks](https://ci.appveyor.com/project/doctrine/dbal/builds/23090110/job/exu86rhatneyhwb7) build automation (e.g. on [doctrine/dbal](https://github.com/doctrine/dbal)).

One of the published [build logs](https://windows.php.net/downloads/pecl/releases/sqlsrv/5.6.0/logs/php_sqlsrv-5.6.0-7.1-nts-vc14-x64-logs.zip) contains:

> C:\php-snap-build\php-src\php71\x64\php-src\configure.js(5499, 13) Microsoft JScript runtime error: 'PHP_PDO_SQLSRV' is undefined

**Comment by yitam** [comment]
Thanks @morozov for bringing this to our attention. We will get back to you on this.

**Comment by david-puglielli** [comment]
This should now be fixed with the latest release, 5.6.1. Please let us know if there are any issues.

**Comment by morozov** [comment]
@david-puglielli thank you. The 5.6.1 builds are available but the 5.6.0 still aren't. Are they expected to be deployed as well?

**Comment by david-puglielli** [comment]
5.6.1 itself is the fix for the deployment failure, so 5.6.0 will not be deployed.

**Comment by david-puglielli** [comment]
Closing this issue. Please reopen if necessary.
