### ISSUE TITLE
Requires the Microsoft ODBC Driver 11 - not supported by Win Srv 2012 R2

### ISSUE THREAD

**Issue by seepu** [Microsoft/msphpsql#96]
Last week I started installation php with mssql support on Win Server 2012 R2.
All versions of Microsoft Driver for PHP for SQL Server need Microsoft ODBC Driver 11 for SQL Server, but this one can't install on WinServ2012, only Microsoft ODBC Driver 13.

https://msdn.microsoft.com/en-us/library/cc296170.aspx
Here we can read:
Versions 3.2 and 3.1 require Microsoft ODBC Driver 11 (or higher) for SQL Server.

Its not true, allways is this error
SQLSTATE: IMSSP
code: -49
message: This extension requires the Microsoft ODBC Driver 11 for SQL Server.

Can You chceck this problem, and recompile all php-mssql drivers (3.xx and 4.xx) for correct works with Microsoft ODBC Driver 13?

**Comment by meet-bhagdev** [comment]
@seepu Our latest [release](https://github.com/Azure/msphpsql/releases/tag/v4.0-RC) works with Microsoft ODBC Driver 13. What error do you get when you use the ODBC Driver 11 on Win Server 2012?

**Comment by seepu** [comment]
Hello,
My last attempt was with the version 4.0.4, tommorow I will try new 4.0.5

I could not install Odbc 11 on Win2012svr R2, and then sqlsrv didn’t work on my server.

**Comment by seepu** [comment]
hello again
now it works, today i checked only simple queries

**Comment by seepu** [comment]
Is any chance to recompile driver 3.2 for work with ODBC Driver 13?

**Comment by meet-bhagdev** [comment]
@seepu We do not have plans for this as of now. We are focusing heavily on Linux. Any reason why you can not update to 4.0.x version for this driver?

**Comment by david-garcia-garcia** [comment]
> Any reason why you can not update to 4.0.x version for this driver?

I might be able to answer this. Lack of extensions such as couchbase, memcache, XHPROF and others + the fact that less people run PHP on windows means more bugs (more headaches and cost) for early adopters.

**Comment by seepu** [comment]
I have a lot of old modules, which need php 5.xx.
Can I recompile it myself? Whether it requires a lot of changes in code?

**Comment by KyleWiering** [comment]
@seepu what odbc issue are you running into? I've successfully run php5.4 and php7 with their respective PDO sql drivers on server 2012 r2.  The only problem we had updating to php7 was a security policy that prevented certain installation locations from being used.  Php 5.4-5.6 have pdo drivers still available for download as well, even though php5.4 is no longer considered secure.

**Comment by seepu** [comment]
in recent months I changed the program code so that it works on php7. Now I test everything on a Windows 2016 Server
