### ISSUE TITLE
Please update blog url in README.md

### ISSUE THREAD

**Issue by Tilogorn** [Microsoft/msphpsql#961]
The referenced blog url https://blogs.msdn.com/b/sqlphp/ redirects to https://blogs.msdn.microsoft.com/sqlphp/ which throws a `410 - Gone`

**Comment by david-puglielli** [comment]
@Tilogorn Both of those links works for me - can you try them again? May have just been a network glitch.

**Comment by Tilogorn** [comment]
Yep, can confirm that they work again. Thanks for your time!
