### ISSUE TITLE
Debian and CP1250 encoding for SQLSRV driver

### ISSUE THREAD

**Issue by pavero01** [microsoft/msphpsql#998]
I have a PHP application which uses CP1250/Windows-1250 encoding + MSSQL database with  Czech_CI_AS collation (all text columns types are VARCHAR).

If I use these setting on Windows platform, it works perfectly.

$connectionInfo = array("UID" => DB_USER, "PWD" => DB_PASSWORD, "Database" => DB_NAME, "CharacterSet" => SQLSRV_ENC_CHAR);

But now I need to install this application on Debian Linux server. If I try to read data from the database (via PHP script, VARCHAR data type) all Czech special chars are displayed incorrectly.

How can I set explicitly CP1250 encoding in SQLSRV driver?

- Debian 9.9
- Linux manadesk2 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
- php 7.3 (7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7)
- msodbcsql17 (17.3.1.1-1)
- pdo_sqlsrv 5.6.1
- sqlsrv      5.6.1

many thanks,

**Comment by yitam** [comment]
hi @pavero01 , we are not experts with Czech chars, but have you configured to use the right locale in your Debian 9? For example, what's the output of `locale`? If it shows utf8, please do the following:

- Check the file `/etc/locale.gen` and look for cs_CZ [ISO-8859-2](http://www.columbia.edu/kermit/latin2.html) (which is [the equivalent of Windows 1250](https://packages.debian.org/sid/python-chardet)). 
- If the line begins with a `#`, run `sed -i 's/# cs_CZ ISO-8859-2/cs_CZ ISO-8859-2/g' /etc/locale.gen` (you need admin rights for this)
- type `locale-gen cs_CZ`

Something like this will show up:
```
Generating locales (this might take a while)...
  cs_CZ.ISO-8859-2... done
  en_US.UTF-8... done
Generation complete. 
```

Now you have several options, depending on your needs or requirements.

You may call the [setlocale()](https://www.w3schools.com/php/func_string_setlocale.asp) function in each php script **before** you make any connection to your database server. 

Alternatively, in a terminal, type
```
export LANG="cs_CZ.ISO-8859-2"
export LANGUAGE="cs_CZ.cs"
export LC_ALL="cs_CZ.ISO-8859-2"
```

Then run a php script. See if you can your Czech chars correctly. This basically affects your current settings in _this_ terminal. It's up to you whether to modify `.bashrc` by appending the above lines at the end, which affects the programs launched from any terminal subsequently.

If you're planning to use Czech locale as the system default, it's another story. Please consult with your system administrator. You might also find this [reference page](https://www.debian.org/doc/manuals/debian-reference/ch08.en.html#_the_locale) useful.

**Comment by pavero01** [comment]
Thanks for your answer. Unfortunately  ISO-8859-2 isn't fully equal with Win-1250 encoding. There are some differences. And win-1250 locale on Linux distributions isn't available.

https://cs.wikipedia.org/wiki/Windows-1250

Is there really no other way how to specify for SQLSRV driver Win-1250 (or some other specific) encoding?

**Comment by yitam** [comment]
Hi @pavero01, our main focus is UNICODE support rather than individual codepage. 

That being said, please launch a Debian terminal and try to set its encoding as follows:

Terminal -> Set Encoding -> Central European -> WINDOWS 1250

Does it help? But this only affects the current terminal. 

Thus, similar to my first reply, try to modify `/etc/locale.gen` by appending `cs_CZ CP1250` at the end. Then `locale-gen cs_CZ` should produce the output below:

```
Generating locales (this might take a while)...
  en_CA.UTF-8... done
  cs_CZ.CP1250... done
Generation complete.
```

Again, you can set `LANG` etc. but this time you should use `cs_CZ.CP1250` instead. Hope this helps.

**Comment by yitam** [comment]
@pavero01 any update? FYI, due to inactivity, we might close this issue soon.

**Comment by pavero01** [comment]
Sorry for longer inactivity. We were quite busy in these days.

We have an admin access on Debian server. So we tried:

```
Generating locales (this might take a while)...
  en_US.UTF-8... done
  cs_CZ.CP1250... done
Generation complete.
```
And set in etc/default/locale  
`LANG=cs_CZ.cp1250` 

We obtained these error:
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LANG = "cs_CZ"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
```
We also tried to set in etc/default/locale  
`LANG=cs_CZ` 

The second case didn't generated any errors. 

But Czech special chars from MSSQL DB were displayed still incorect in PHP script (default charset for PHP CP1250, the script itself was saved in CP1250 encoding).

**Comment by yitam** [comment]
hi @pavero01 

What's the output of the following env variables? Are they cs_CZ.CP1250? Something like this?

LANG="cs_CZ.CP1250"
LANGUAGE="cs_CZ.cs"
LC_ALL="cs_CZ.CP1250"

Have you tried this?
> please launch a Debian terminal and try to set its encoding as follows:
> Terminal -> Set Encoding -> Central European -> WINDOWS 1250

You might not need to call the [setlocale()](https://www.w3schools.com/php/func_string_setlocale.asp) function in a php script before you make any connection to your database server, but the above fails, you might want to give it a try.

**Comment by pavero01** [comment]
`LANG=cs_CZ.CP1250

LANGUAGE=

LC_CTYPE="cs_CZ.CP1250"

LC_NUMERIC="cs_CZ.CP1250"

LC_TIME="cs_CZ.CP1250"

LC_COLLATE="cs_CZ.CP1250"

LC_MONETARY="cs_CZ.CP1250"

LC_MESSAGES="cs_CZ.CP1250"

LC_PAPER="cs_CZ.CP1250"

LC_NAME="cs_CZ.CP1250"

LC_ADDRESS="cs_CZ.CP1250"

LC_TELEPHONE="cs_CZ.CP1250"

LC_MEASUREMENT="cs_CZ.CP1250"

LC_IDENTIFICATION="cs_CZ.CP1250"

LC_ALL=`

Terminal isn't available on the server.

**Comment by pavero01** [comment]
But maybe we have find another solutions:

Debian locale UTF-8
PHP defaul charset UTF-8
All PHP scripts saved with UTF-8 encoding
$connectionInfo = array("UID" => DB_USER, "PWD" => DB_PASSWORD, "Database" => DB_NAME, "CharacterSet" => "UTF-8");

Now, all varchars from DB are displayed correctly on HTML output.

If I send UTF-8 string to the database via PHP script (SQL statement INSERT/UPDATE), the string is saved correctly with CP1250 encoding.

Do you think we can use this solution? Or can we expect any problems?

**Comment by yitam** [comment]
Yes @pavero01 UTF-8 is the way to go. In Debian, where the default is UTF-8, if you want a different ANSI encoding using `"CharacterSet" => SQLSRV_ENC_CHAR` you have to do additional work, like I have mentioned above. 

One thing to check is whether you have to alter your codepage settings at all with this solution. I suspect you might not need to do that now. Also, if your `char` and `varchar` columns all display correct characters, then indeed you might have found the solution.

**Comment by yitam** [comment]
Any update @pavero01 ? If not we will close this issue in a few days.

**Comment by pavero01** [comment]
Yes, I think we can close it now.

We will test the solution described above.

**Comment by yitam** [comment]
Sounds good @pavero01! Please feel free to reopen this if necessary.
